var i=void 0;function m(){return function(){}}function aa(a){return function(){return a}}var p,q,ba=15,ca=24;function da(a){for(var b="",c=0;c<a.length;c++)switch(a.charCodeAt(c)){case 13:b+="<br />";break;case 63368:b+="&#224;";break;case 63374:b+="&#233;";break;default:b+=a.charAt(c)}return b}
function ea(a){a=fa(a);var b=a.v&256,c=a.v&16384,d="dbox",f=!1,e=!1;a.v&32768&&(d="document");a.v&16&&(d="info");a.v&8192&&(d="alert");a.v&4096&&(f=!0);a.v&2048&&(e=!0);a=new ga(d,c,b,f,e,a.left*2,a.top*2,a.right*2-a.left,a.bottom*2-a.top);a.hide();ia(a);return a};function r(a){a[0]=="3"&&a[1]=="/"&&(a=a.substring(2));return ja(a.toLowerCase(),2)}var s=i;
function ja(a,b){s.seek(b*512+2,s.set);var c=t(s),d=u(s);(d&240)!=240&&(d&240)!=224&&fatal("Corrupt directory");s.seek(30,s.o);var f=u(s),e=u(s),g=u(s),h=1,j=0;d=a.indexOf("/");var k="";d>0&&(k=a.substring(d+1),a=a.substring(0,d));for(;j<g;){s.seek(b*512+f*h+4,s.set);d=u(s);if(d!=0){if(v(s,d&15).toLowerCase()==a){if((d&240)==208)return s.seek(16-(d&15),s.o),c=t(s),ja(k,c);s.seek(b*512+f*h+21,s.set);c=t(s);s.seek(2,s.o);f=ka(s)&16777215;k=c;c=f;f="";switch(d&240){case 16:f=la(k,c);break;case 32:f=
ma(k,c);break;case 48:d=k;k=c;c="";for(f=0;k>0;){s.seek(d*512+f,s.set);g=u(s);s.seek(d*512+f+256,s.set);g|=u(s)<<8;e=k;e>131072&&(e=131072);if(g)c+=ma(g,e);else for(g=0;g<e;g++)c+=String.fromCharCode(0);k-=e;f++}f=c}return new w(f)}j++}h++;h==e&&(h=0,b=c,s.seek(b*512+2,s.set),c=t(s))}return!1}function la(a,b){s.seek(a*512,s.set);return v(s,b)}
function ma(a,b){for(var c="",d=0;b>0;){s.seek(a*512+d,s.set);var f=u(s);s.seek(a*512+d+256,s.set);f|=u(s)<<8;var e=b;e>512&&(e=512);if(f)c+=la(f,e);else for(f=0;f<e;f++)c+=String.fromCharCode(0);b-=e;d++}return c};var x,na,oa=!0;function pa(a,b,c){this.width=a>>1;this.height=b*2;this.r=c;this.z=a;this.H=b;this.data=Array(b*c)}
pa.prototype.g=function(a,b,c){if(!(this.width==0||this.height==0)){var d=a.get(0).getContext("2d"),f=0,e=0;b<0&&(f=-b,b=0);c<0&&(e=-c,c=0);var g=this.width,h=this.height;g+b>=a.width()&&(g=a.width()-b);h+c>=a.height()&&(h=a.height()-c);if(!(g==0||h==0)){a=d.getImageData(b,c,g,h);for(var j=e;j<h;j++)for(var k=(j>>1)*this.r,o=(j-e)*a.width*4,l,n=f;n<g;n++)l=this.data[k+(n>>2)],na&&(l=na[l]),(l=(l>>(n&2?0:4)&15)*3)?(a.data[o++]=x[l++],a.data[o++]=x[l++],a.data[o++]=x[l++],a.data[o++]=255):o+=4;d.putImageData(a,
b,c)}}};function qa(a){y.seek(368+a*32,y.set);a=u(y);return v(y,a)}function ra(){y.seek(496,y.set);var a=u(y);return v(y,a)}function fa(a){y.seek(a*10);a={};a.top=t(y);a.left=t(y);a.bottom=t(y);a.right=t(y);a.v=t(y);return a}function sa(){y.seek(1008,y.set);var a=u(y);return da(v(y,a))}var ta=[0,80,208];function ua(a){y.seek(1128+ta[a],y.set);a=u(y);return v(y,a)}var y;function va(a){for(a={m:a,h:0};wa(a););}
function wa(a){var b=!1;if(a.m[a.h]=="."||a.m[a.h+1]==".")return!1;a.m[a.h++]==" "&&(b=!0);a.h++;for(var c="";a.m[a.h]!="\\";)c+=a.m[a.h++];a.h++;for(var d="",f=!0,e=0,g=!1;a.m[a.h]!="\r";)switch(a.m[a.h++]){case "*":d=a.m[a.h++];a.h++;break;case "B":c="<b>"+c+"</b>";break;case "C":a.h++;break;case "D":f=!1;break;case "H":e=a.m.charCodeAt(a.h++)&255;e|=(a.m.charCodeAt(a.h++)&255)<<8;break;case "I":c="<i>"+c+"</i>";break;case "N":break;case "U":break;case "V":g=!0;break;case "X":break;default:fatal("Unknown menu control code")}a.h++;
if(b)return xa(c,e,d,f),g&&xa("-",0,"",!1),!0;z={id:e};z.a=$(document.createElement("div"));c=="@"?z.a.addClass("apple"):z.a.html(c);z.a.data("refCon",z);z.a.mousedown(function(a){if(A)return!1;Aa(a);return!1});z.i=$(document.createElement("table"));z.i.addClass("menu");z.body=$(document.createElement("tbody"));z.i.append(z.body);z.l=[];B.append(z.a);C.push(z);return!0};var D=2,E=24,Ba=20,Ca=4,Da=32,Ea=24,Fa=34,Ga;
function Ha(){var a=Ia(10,36,620,354);a.add(F([240,318,120,22],1,10,["OK"]));a.add(F([10,18,600,146],2,32790,["\u0001J\u0001\0Apple IIGS ^0\r\u0001J\u0001\0Written by:\r\u0001J\u0001\0\u0001S\u0001\0Fred Allen\u0001S\0\0\r\r\u0001J\u0001\0Artwork by:\r^1\r\r\u0001J\u0001\0\u0001S\u0004\0MacVenture Team\u0001S\0\0"]));a.add(F([10,164,300,136],3,32790,["^2"]));a.add(F([310,164,300,136],4,32790,["^3"]));a.add(F([10,294,600,22],5,32790,["\u0001J\u0001\0WebVenture by Sean Kasun"]));a.param([sa(),ua(0),
ua(1),ua(2)]);return a}function Ja(){var a=Ia(80,80,480,200);a.add(F([214,150,50,30],1,10,["OK"]));a.add(F([100,80,280,22],2,24,[0,0,100]));a.add(F([20,30,440,30],3,15,["Sound Volume"]));return a}
function Ka(a){var b=Ia(92,146,456,108);b.add(F([24,68,120,22],1,10,["YES"]));b.add(F([168,68,120,22],2,10,["NO"]));b.add(F([312,68,120,22],3,10,["CANCEL"]));b.add(F([100,10,340,38],4,32790,["Save changes before ^0   "]));switch(a){case 0:b.param(["starting a new game?"]);break;case 1:b.param(["opening another game?"]);break;case 2:b.param(["quitting?"])}return b}
function La(){var a=Ia(50,70,520,228);a.add(F([12,8,298,30],4,22,["Load which game:"]));a.add(F([12,50,298,164],3,23,[]));a.add(F([320,158,190,24],1,10,["Open"]));a.add(F([320,194,190,24],2,10,["Cancel"]));return a}function Ma(){var a=Ia(50,70,540,256);a.add(F([22,50,298,124],4,23,[]));a.add(F([22,182,298,30],5,22,["Save game as:"]));a.add(F([22,200,290,36],3,17,[""]));a.add(F([330,186,200,22],1,10,["Save"]));a.add(F([330,222,200,22],2,10,["Cancel"]));return a};function w(a){this.set=0;this.o=1;this.end=2;this.data=a;this.length=a.length;this.p=this.c=0}function u(a){return a.data.charCodeAt(a.c++)&255}function G(a){var b=(a.data.charCodeAt(a.c++)&255)<<8;b|=a.data.charCodeAt(a.c++)&255;return b}function t(a){var b=a.data.charCodeAt(a.c++)&255;b|=(a.data.charCodeAt(a.c++)&255)<<8;return b}function Na(a){var b=(a.data.charCodeAt(a.c++)&255)<<16;b|=(a.data.charCodeAt(a.c++)&255)<<8;b|=a.data.charCodeAt(a.c++)&255;return b}
function Oa(a){var b=(a.data.charCodeAt(a.c++)&255)<<24;b|=(a.data.charCodeAt(a.c++)&255)<<16;b|=(a.data.charCodeAt(a.c++)&255)<<8;b|=a.data.charCodeAt(a.c++)&255;return b}function ka(a){var b=a.data.charCodeAt(a.c++)&255;b|=(a.data.charCodeAt(a.c++)&255)<<8;b|=(a.data.charCodeAt(a.c++)&255)<<16;b|=(a.data.charCodeAt(a.c++)&255)<<24;return b}
function Pa(a){var b=(a.data.charCodeAt(a.c)&255)<<24;b|=(a.data.charCodeAt(a.c+1)&255)<<16;b|=(a.data.charCodeAt(a.c+2)&255)<<8;b|=a.data.charCodeAt(a.c+3)&255;return b}w.prototype.seek=function(a,b){switch(b){case this.o:a+=this.c;break;case this.end:a+=this.length}this.c=a};function v(a,b){var c=a.c;a.c+=b;return a.data.substring(c,a.c)}w.prototype.e=function(a){var b=Pa(this);b>>>=32-this.p-a;b&=(1<<a)-1;this.p+=a;this.p&16&&(this.p&=15,this.c+=2);return b};function Qa(){if(s!=i){y=r("3/RESOURCE.DAT");q.remove();delete q;var a=qa(6),b=r(a);b.seek(8,b.set);x=[];for(var c=0;c<16;c++)G(b),x.push(G(b)&255),x.push(G(b)&255),x.push(G(b)&255);a=new pa(1280,200,160);for(c=0;c<32E3;c++)a.data[c]=u(b);b=new ga("plainDBox",!1,!1,!1,!1,0,0,640,400);b.hide();ia(b);H=b;H.show();Ra(H.port,0);a.g(H.port,0,0);a=[3,1,2,0,5];for(b=0;b<5;b++){c=b;var d=qa(a[b]);d=r(d);var f={ka:0,Q:!1};d.seek(0,d.set);var e=d.length,g=Oa(d),h=i;if(g&2147483648){g&=2147483647;f.Q=!0;d.seek(g,
d.set);f.F=G(d);e=Array(16);h=Array(16);for(var j=0;j<15;j++)e[j]=G(d);for(j=0;j<16;j++)h[j]=u(d);f.S=Array(f.F);f.R=Array(f.F);var k=0,o=i;for(j=0;j<f.F;j++){if((j&63)==0){d.seek(g+(j>>6)*6+48,d.set);var l=Na(d);o=Na(d);k=l&7;d.seek(g+(l>>3),d.set)}f.S[j]=o;l=Oa(d)>>>16-k&65535;d.seek(-4,d.o);var n;for(n=0;n<16;n++)if(e[n]>l)break;l=h[n];k+=l&15;k&16&&(k&=15,d.seek(2,d.o));l>>=4;n=0;l&&(n=Pa(d),l--,l==0?n=0:n>>>=32-l-k,n&=(1<<l)-1,n|=1<<l,k+=l,k&16&&(k&=15,d.seek(2,d.o)),o+=n);f.R[j]=n}h=g-4}else e-=
4,h=e,f.Y=g,f.F=e/g|0;d.seek(4,d.set);f.data=v(d,h);J[c]=f}a={};y.seek(76,y.set);a.da=t(y);a.ba=t(y);a.ia=t(y);a.ca=t(y);t(y);a.ja=t(y);a.Z=[];for(b=0;b<24;b++)a.Z.push(u(y));a.T=[];for(b=0;b<64;b++)a.T.push(u(y));a.U=[];for(b=0;b<64;b++)a.U.push(t(y));a.V=[];for(b=0;b<64;b++)a.V.push(u(y));K=a.da;Sa=a.ba;Ta=a.ca;Ua=a.T;Va=a.U;Wa=a.V;L=fa(5);L.top*=2;L.left*=2;L.width=L.right*2-L.left;L.height=L.bottom*2-L.top;L.ma=20;L.la=20;L.X=0;Xa=[];Ya=[];Za=[];$a=[];ab=Array(K*2);if(y.length!=1676){a={};y.seek(1676,
y.set);a.length=t(y);a.aa=[];y.seek(1680,y.set);for(b=0;b<a.length;b++)a.aa.push(t(y));a.$=[];y.seek(1868,y.set);for(b=0;b<a.length;b++)a.$.push(u(y));a.ea=[];y.seek(1964,y.set);for(b=0;b<a.length;b++)a.ea.push(u(y))}a=[];y.seek(720,y.set);for(b=0;b<16;b++)a.push(t(y));x=[];for(b=0;b<16;b++)c=a[b]>>4&15,d=a[b]&15,x.push((a[b]>>8&15)*17),x.push(c*17),x.push(d*17);a=[];y.seek(752,y.set);for(b=0;b<256;b++)a.push(u(y));na=a;y.seek(1092,y.set);Ga=t(y);a=[];y.seek(1596,y.set);for(b=0;b<32;b++)a.push(u(y));
a=[];y.seek(1636,y.set);for(b=0;b<32;b++)a.push(u(y));bb=ea(3);bb.n=9;bb.addClass("commands");a=[{name:"3/SHADOWGATE",start:49390,D:-3272},{name:"3/DEJAVU",start:49390,D:-3272},{name:"3/DEJAVUII",start:4014,D:66},{name:"3/UNINVITED",start:49390,D:-3272}];for(b=0;b<a.length;b++)if(c=r(a[b].name)){for(d=0;d<9;d++)c.seek(a[b].start+d*11,c.set),f=t(c)*2,g=t(c)*2,e=t(c)*2-f,h=t(c)*2-g,j=u(c),k=t(c),k=k&15|k&61440,c.seek(a[b].start+115+d*4,c.set),n=t(c),c.seek(n+a[b].D),o=t(c),l=v(c,o*e),c.seek(a[b].start+
151+d*4,c.set),n=t(c),c.seek(n+a[b].D),t(c),n=v(c,o*e),bb.add(F([g,f,h,e],j,k,[o,l,n]));break}cb=ea(0);cb.n=10;M=ea(1);M.n=11;N=$(document.createElement("div"));N.addClass("textEdit");a=M;b=N;c=a.port.width();d=a.port.height();a.port.remove();b.css("top","0px");b.css("left","0px");b.css("width",c+"px");b.css("height",d+"px");a.port=b;a.d.append(b);O=ea(4);O.n=12;O.b={id:0,x:0,y:0,children:[{id:1,top:0,left:0,width:0,height:0}]};db=ea(2);P(db,"Exits");db.n=13;db.addClass("exits");B=$(document.createElement("div"));
B.addClass("menubar");a=[">L File \\H\u0002\0\r LNew\\V*NnH\u0001\u0001\r LOpen...\\*OoH\u0002\u0001\r LSave\\*SsH\u0003\u0001\r LSave As...\\VH\u0004\u0001\r LQuit\\*QqH\u0005\u0001\r.",">L Edit \\H\u0003\0\r LUndo\\DV*ZzH\u00fa\0\r LCut\\D*XxH\u00fb\0\r LCopy\\D*CcH\u00fc\0\r LPaste\\DV*VvH\u00fd\0\r LClear\\DH\u00fe\0\r.",">L Special \\H\u0004\0\r LClean Up\\DH\u0006\u0001\r LMess Up\\DH\u0007\u0001\r."];y.seek(1024);b=v(y,48);va(b);for(b=0;b<a.length;b++)va(a[b]);z=C[0];xa("Adjust Volume...",
2304,"",!0);P(M,"Untitled");if(gameparts.length>1)Q=gameparts[1],a=window.JSON.parse(window.localStorage.getItem(Q).toString()),R=a.O,S=a.P,N.html(a.text),P(M,Q);else{a=r(ra());R=Array(Ta);S=Array(Sa);for(b=0;b<Ta;b++){R[b]=Array(K);for(c=0;c<K;c++)R[b][c]=G(a)}for(b=0;b<Sa;b++)S[b]=G(a)}eb();Q==""&&Ya.push(T(1,0));setTimeout(fb,500)}else setTimeout(Qa,10)}function eb(){for(var a,b,c=0;c<K*2;c++)ab[c]=0;for(c=K-1;c;c--)a=R[0][c],(b=ab[a*2])&&(ab[c*2+1]=b),ab[a*2]=c}
function gb(){for(var a=[],b=0;b<U.length;b++)(U[b].n==10||U[b].n==14)&&a.push(U[b]);for(b in a){var c=a[b];if(c!=i)if(c.n==10)c.b={},P(c,"");else{var d={L:c.port.height(),K:c.port.width()};hb(c,{L:0,K:0});hb(c,d);c.b={};V(c)}}L.X=0;$a=[];Xa=[]}var ab;
function fb(){V(H);delete H;desktop.append(B);bb.show();O.show();var a=O;if(a!=i&&a.b!=i&&(a==O||T(a.b.id,6)==1)){a==cb?ib(a.b.id*2).g(cb.port,0,0):Ra(a.port,Ga);for(var b=0;b<a.b.children.length;b++){var c;var d=a.b.children[b].id;c=a;var f=T(d,1),e=T(d,2),g=T(d,3);if(!g||!T(d,4)){var h=1;g?h=0:Za.indexOf(d)!=-1&&(h=2);g=i;f-=c.b.x;g=e-c.b.y;var j=c.port,k=h;h={top:0,left:0,width:0,height:0};e=i;if(e=ib(d*2))switch(h={top:g,left:f,width:e.width,height:e.height},k){case 1:e.g(j,f,g);break;case 2:if(d=
f,f=g,!(e.width==0||e.height==0)){g=j.get(0).getContext("2d");var o=k=0;d<0&&(k=-d,d=0);f<0&&(o=-f,f=0);var l=e.width,n=e.height;l+d>=j.width()&&(l=j.width()-d);n+f>=j.height()&&(n=j.height()-f);if(!(l==0||n==0)){j=g.getImageData(d,f,l,n);for(var ya=o;ya<n;ya++)for(var Ib=(ya>>1)*e.r,ha=(ya-o)*j.width*4,I,za=k;za<l;za++)I=e.data[Ib+(za>>2)],na&&(I=na[I]),(I=I>>(za&2?0:4)&15)?(I^=15,I*=3,j.data[ha++]=x[I++],j.data[ha++]=x[I++],j.data[ha++]=x[I++],j.data[ha++]=255):ha+=4;g.putImageData(j,d,f)}}}g=h;
g.top+=c.b.y;g.left+=c.b.x;c=g}else c={top:0,left:0,width:0,height:0};a.b.children[b].top=c.top;a.b.children[b].left=c.left;a.b.children[b].width=c.width;a.b.children[b].height=c.height}if(a.n==14&&a.b.ha){b={top:0,left:0,right:0,bottom:0};a.b.ha=!1;for(c=0;c<a.b.children.length;c++)h=a.b.children[c],b.right==b.left||b.bottom==b.top?(b.top=h.top,b.left=h.left,b.bottom=h.top+h.height,b.right=h.left+h.width):(b.top=Math.min(b.top,h.top),b.left=Math.min(b.left,h.left),b.bottom=Math.max(b.bottom,h.top+
h.height),b.right=Math.max(b.right,h.left+h.width));if(b.right==b.left||b.bottom==b.top)b.top=a.b.y,b.left=a.b.x,b.bottom=a.b.y,b.right=a.b.x;else{if(b.left>a.b.x)b.left=a.b.x;if(b.right<a.b.x)b.right=a.b.x;if(b.top>a.b.y)b.top=a.b.y;if(b.bottom<a.b.y)b.bottom=a.b.y}if(a.n==11)a.f.data("min",b.top),a.f.data("max",b.bottom),e=a.port.scrollTop(),b=a.f.data("min"),c=a.f.data("max"),b<c?(h=e-b,e+=a.port.height(),h=h*(a.height-48-E-24)/(c-b)|0,b=e*(a.height-48-E-24)/(c-b)|0,a.f.css("top",h+22+"px"),a.f.css("height",
b-h+"px")):(a.f.css("top","22px"),a.f.css("height",a.height-48-E-24+"px"));else{if(b.left>a.b.x)b.left=a.b.x;if(b.right<a.b.x+a.port.width())b.right=a.b.x+a.port.width();if(b.top>a.b.y)b.top=a.b.y;if(b.bottom<a.b.y+a.port.height())b.bottom=a.b.y+a.port.height();a.A&&(a.j.data("min",b.left),a.j.data("max",b.right));a.B&&(a.f.data("min",b.top),a.f.data("max",b.bottom));a.A&&(b=a.j.data("min"),c=a.j.data("max"),b<c?(e=a.b.x-b,h=a.port.width(),e=e*(a.port.width()-68)/(c-b)|0,b=h*(a.port.width()-68)/(c-
b)|0,b>a.port.width()-68-e&&(b=a.port.width()-68-e),a.j.css("left",e+32+"px"),a.j.css("width",b+"px")):(a.j.css("left","32px"),a.j.css("width",a.port.width()-68+"px")));a.B&&(b=a.f.data("min"),c=a.f.data("max"),b<c?(e=a.b.y-b,h=a.port.height(),e=e*(a.port.height()-48)/(c-b)|0,b=h*(a.port.height()-48)/(c-b)|0,b>a.port.height()-48-e&&(b=a.port.height()-48-e),a.f.css("top",e+22+"px"),a.f.css("height",b+"px")):(a.f.css("top","22px"),a.f.css("height",a.port.height()-48+"px")))}}}db.show();M.show();cb.show();
jb=N.get(0).scrollHeight;N.scrollTop(jb-jb%ba);kb(T(1,0));W=!1;lb()};var W=!1,jb=0,Za,Ya,Xa,$a,H,cb,bb,M,O,db,N,K,Sa,Ta,Wa,Va,Ua,L,R,S,Q="";function X(){}var A=!1;function lb(){fatal("runmain")}function kb(a){var b=1;if(Xa.indexOf(a)==-1){Xa.push(a);var c={a:a};c.parent=T(a,0);c.x=T(a,1);c.y=T(a,2);c.na=T(a,9);c.oa=T(a,10);c.pa=T(a,11);c.ra=T(a,3);c.qa=T(a,4);$a.push({id:7,val:c})}c=Ua[6];b<<=Wa[6];b&=Va[6];R[c][a]=b|R[c][a]&~Va[6];W=!0}
function T(a,b){var c,d=Ua[b];if(d&128){var f=mb(0,a);if(f.length==0)return 0;d&=127;c=(f.charCodeAt(d*2)&255)<<8;c|=f.charCodeAt(d*2+1)&255}else c=R[d][a];c&=Va[b];c>>=Wa[b];c&32768&&(c=-((c^65535)+1));return c}function nb(a){switch(a){case 256:ob();break;case 257:pb();break;case 258:qb();break;case 259:X=m();rb();break;case 260:X=m();sb();break;case 261:tb();break;case 2304:ub();break;default:fatal("Unknown menuitem: "+a.toString(16))}}
function ob(){var a=Ha();A=!0;a.show(function(){V(a);A=!1})}function ub(){var a=Ja(),b=vb();b==null&&(b=50);wb(a.getItem(2),b);A=!0;a.show(function(){var b=a.getItem(2).value,d=new Date;d.setTime(d.getTime()+31536E6);document.cookie="webventure_volume="+escape(b)+"; expires="+d.toGMTString()+"; path=/";V(a);A=!1})}function pb(){if(W){var a=Ka(0);A=!0;a.show(function(b){V(a);switch(b){case 1:X=pb;rb();break;case 2:xb();break;case 3:A=!1}})}else xb()}
function xb(){Q="";for(var a=r(ra()),b=0;b<Ta;b++)for(var c=0;c<K;c++)R[b][c]=G(a);for(b=0;b<Sa;b++)S[b]=G(a);gb();eb();P(M,"Untitled");N.html("");Ya=[T(1,0)];kb(T(1,0));W=!1;lb()}function qb(){if(W){var a=Ka(1);A=!0;a.show(function(b){V(a);switch(b){case 1:X=qb;rb();break;case 2:yb();break;case 3:A=!1}})}else yb()}
function yb(){var a=La();A=!0;for(var b=a.getItem(3),c=i,d=0;d<window.localStorage.length;d++){var f=window.localStorage.key(d);if(f!=null&&window.JSON.parse(window.localStorage.getItem(f).toString()).W==gamename){var e=$(document.createElement("div"));e.addClass("listitem");e.mousedown(aa(!1));e.click(function(a){c&&c.removeClass("active");c=$(a.target);c.addClass("active")});e.dblclick(function(){a.getItem(1).a.click()});e.text(f.toString());b.a.append(e)}}a.show(function(b){switch(b){case 1:if(c==
i)break;Q=c.text();V(a);A=!1;b=window.JSON.parse(window.localStorage.getItem(Q).toString());R=b.O;S=b.P;gb();eb();P(M,Q);N.html(b.text);jb=N.get(0).scrollHeight;N.scrollTop(jb);Ya=[];kb(T(1,0));W=!1;lb();break;case 2:V(a),A=!1}})}function rb(){Q==""?sb():(window.localStorage.setItem(Q,window.JSON.stringify({W:gamename,O:R,P:S,text:N.html()})),P(M,Q),W=!1,X())}
function sb(){var a=Ma();A=!0;var b=a.getItem(3);b.a.focus();b.a.keypress(function(b){if(b.which==13)return a.getItem(1).a.click(),!1;return!0});b=a.getItem(4);for(var c=i,d=0;d<window.localStorage.length;d++){var f=window.localStorage.key(d);if(f!=null&&window.JSON.parse(window.localStorage.getItem(f).toString()).W==gamename){var e=$(document.createElement("div"));e.addClass("listitem");e.mousedown(aa(!1));e.click(function(b){c&&c.removeClass("active");c=$(b.target);c.addClass("active");a.getItem(3).a.val(c.text())});
e.dblclick(function(){a.getItem(1).a.click()});e.text(f.toString());b.a.append(e)}}a.show(function(b){switch(b){case 1:Q=a.getItem(3).a.val();V(a);A=!1;rb();break;case 2:V(a),A=!1,X()}})}function tb(){if(W){var a=Ka(2);A=!0;a.show(function(b){V(a);switch(b){case 1:X=tb;rb();break;case 2:lb();break;case 3:A=!1}})}else lb()}
function vb(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var c=a[b];c.charAt(0)==" ";)c=c.substring(1,c.length);if(c.indexOf("webventure_volume=")==0)return unescape(c.substring(18,c.length))}return null};function ib(a){a=mb(3,a);if(!(a.length<2)){if(a.length==2)return ib((a.charCodeAt(0)&255)<<8|a.charCodeAt(1)&255);var b;a=new w(a);var c=a.e(3),d,f;oa&&a.e(2);f=a.e(1)?a.e(10):a.e(6);if((d=a.e(1)?a.e(10):a.e(6))&&f)switch(b=new pa(d,f,d+15>>3&65534),c){case 0:c=b.z>>4;d=b.z&15;for(var e=0,g=0;g<b.H;g++){for(var h=0;h<c;h++)f=Pa(a),a.seek(2,a.o),f>>>=16-a.p,b.data[e++]=f>>8&255,b.data[e++]=f&255;d&&(f=a.e(d),f<<=16-d,b.data[e++]=f>>8&255,b.data[e++]=f&255)}break;case 1:zb(Ab,Bb,Cb,b,a);break;case 2:zb(Db,
Eb,Fb,b,a);break;case 3:c=Array(17);for(e=0;(d=Gb[e++])!=255;){for(f=a.e(d);(d=Gb[e++])!=255;)c[Gb[e++]]=f%d,f=f/d|0;c[Gb[e++]]=f}c[16]=0;for(f=16;f>0;f--)for(d=f;d<=16;d++)c[d]>=c[f-1]&&c[d]++;for(f=16;f>=0;f--)if(c[f]==16){c[f]=255;break}e=Array(17);g=Array(17);d=a.e(2)+1;for(f=h=0;f<15;f++){if(f)for(;!a.e(1);)d++;g[f]=d;e[f]=h;h+=1<<16-d}for(e[15]=h;h&1<<16-d;)d++;e[16]=h|1<<16-d;g[15]=d;g[16]=d;zb(e,g,c,b,a)}return b}}
function Ra(a,b){for(var c=a.width(),d=a.height(),f=a.get(0).getContext("2d"),e=f.getImageData(0,0,c,d),g=0;g<d;g++)for(var h=g*e.width*4,j=0;j<c;j++){var k=(b>>4*(j&3)&15)*3;e.data[h++]=x[k++];e.data[h++]=x[k++];e.data[h++]=x[k++];e.data[h++]=255}f.putImageData(e,0,0)}
var Ab=[0,8192,16384,20480,24576,28672,32768,36864,40960,45056,49152,53248,55296,57344,59392,61440,63488],Bb=[3,3,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5],Cb=[0,15,3,5,6,7,8,9,10,12,255,1,2,4,11,13,14],Db=[0,16384,32768,49152,51200,53248,55296,57344,59392,61440,62464,62976,63488,64E3,64512,65024,65280],Eb=[2,2,2,5,5,5,5,5,5,6,7,7,7,7,7,8,8],Fb=[255,0,15,1,3,7,14,12,8,6,2,4,9,13,11,10,5],Gb=[8,15,2,255,0,4,255,1,7,9,8,255,3,4,255,4,10,7,10,11,6,255,5,6,6,11,255,7,3,255,9,4,3,14,255,12,2,255,13,1,255,15,255];
function zb(a,b,c,d,f){var e;Y=Z=0;e=d.z&3?f.e(5):f.e(4)<<1;var g=0,h=d.z&15;h&&(h>>=2,g=h&1,h=2-(h>>1));for(var j=0,k=0;k<d.H;k++){for(var o=0;o<d.z>>3;o++){var l=Hb(a,b,c,f)<<4;d.data[j++]=Hb(a,b,c,f)|l}g&&(d.data[j]=Hb(a,b,c,f)<<4);j+=h}if(o=d.z&3){j=d.r-h;var n=0;for(k=h=0;k<d.H;k++)e&1?(n<o&&(l=Hb(a,b,c,f)<<4,h|=l>>>n,n+=4),n-=o,l=h,h<<=o,h&=255):(l=f.e(o),l<<=8-o),g&&(l>>>=4),d.data[j]|=l&255,j+=d.r}if(e&8)for(k=j=0;k<d.H;k++)if(l=0,e&2)for(o=0;o<d.r;o++)d.data[j]^=l,l=d.data[j++];else for(o=
0;o<d.r;o++)h=d.data[j]^l,h^=h>>>4&15,d.data[j++]=h,l=h<<4&255;if(e&4){a=d.r*4;e&2&&(a*=2);j=0;e=a;for(b=0;b<d.H*d.r-a;b++)d.data[e++]^=d.data[j++]}}var Z=0,Y=0;
function Hb(a,b,c,d){if(Z)return Z--,Y=Y<<8&65280|Y>>8,Y&255;var f=Pa(d);f>>>=16-d.p;f&=65535;var e;for(e=0;e<16;e++)if(a[e+1]>f)break;d.p+=b[e];d.p&16&&(d.p&=15,d.seek(2,d.o));a=c[e];if(a==255)return d.e(1)||(Y&=255,Y|=Y<<8),Z=d.e(3),Z<3&&(Z<<=4,Z|=d.e(4),Z<8&&(Z<<=8,Z|=d.e(8))),Z-=2,Y=Y<<8&65280|Y>>8,Y&255;else Y<<=8,Y|=a,Y&=65535;return a};function xa(a,b,c,d){var f={id:b},e=$(document.createElement("tr"));if(a[0]=="-"){var g=$(document.createElement("td"));g.attr("colspan","2");g.addClass("divider");g.append(document.createElement("hr"))}else e.addClass("menuitem"),g=$(document.createElement("td")),g.html(da(a)),e.append(g),g=$(document.createElement("td")),c!=""&&(g.addClass("shortcut"),Jb.push({key:c,id:b}),g.text(c));e.append(g);f.a=e;f.enabled=d;f.enabled||f.a.addClass("disabled");z.body.append(f.a);z.l.push(f)}
function Aa(a){for(var b=$(a.target);b.data("refCon")==i;)b=b.parent();b.addClass("active");var c=b.data("refCon");desktop.append(c.i);a=b.position();c.i.css("top",a.top+ca+"px");c.i.css("left",a.left+"px");var d=-1;$(document).mousemove(function(a){var e=B.offset();if(a.pageX>=e.left&&a.pageY>e.top&&a.pageX<e.left+B.width()&&a.pageY<e.top+B.height())for(var g=0;g<C.length;g++){if(e=C[g].a.offset(),a.pageX>=e.left&&a.pageX<e.left+C[g].a.outerWidth()){c.i.remove();b.removeClass("active");b=C[g].a;
b.addClass("active");c=b.data("refCon");desktop.append(c.i);e=b.position();c.i.css("top",e.top+ca+"px");c.i.css("left",e.left+"px");break}}else if(e=c.i.offset(),a.pageX>=e.left&&a.pageY>=e.top&&a.pageX<e.left+c.i.outerWidth()&&a.pageY<e.top+c.i.outerHeight())for(g=0;g<c.l.length;g++){var h=c.l[g].a;h.hasClass("menuitem")&&c.l[g].enabled&&(e=h.offset(),a.pageY>=e.top&&a.pageY<e.top+h.outerHeight()?(d=g,h.addClass("active")):h.removeClass("active"))}else{for(g=0;g<c.l.length;g++)c.l[g].a.removeClass("active");
d=-1}});$(document).mouseup(function(){$(document).unbind("mousemove");$(document).unbind("mouseup");c.i.remove();b.removeClass("active");d!=-1&&nb(c.l[d].id)})}var B,C=[],Jb=[],z=i;$("body").keydown(function(a){if(a.target.type=="text")return!1;if(!a.altKey)return!1;if(A)return!1;for(var b=0;b<Jb.length;b++)if(Jb[b].key.charCodeAt(0)==a.which)for(var c=Jb[b].id,d=0;d<C.length;d++)for(var f=0;f<C[d].l.length;f++)C[d].l[f].id==c&&C[d].l[f].enabled&&Kb(C[d],c)});
function Kb(a,b){a.a.addClass("active");setTimeout(function(){a.a.removeClass("active");nb(b)},200)};function ga(a,b,c,d,f,e,g,h,j){this.w=[];this.N=c;this.M=b;this.B=d;this.A=f;this.d=$(document.createElement("div"));this.d.addClass(a);if(a=="document"||a=="info")b="<span></span>",this.title=$(document.createElement("div")),this.title.addClass("title"),this.title.mousedown(function(a){A||fatal(a);return!1}),this.M&&(b='<div class="close"></div>'+b),this.N&&(b+='<div class="resize"></div>'),this.title.html(b),this.M&&(b=this.title.children("div.close"),b.mousedown(aa(!1)),b.click(function(a){A||
fatal(a);return!1})),this.N&&(b=this.title.children("div.resize"),b.mousedown(aa(!1)),b.click(function(a){A||fatal(a);return!1})),this.d.append(this.title);this.port=$(document.createElement("canvas"));this.port.mousedown(function(a){A||fatal(a);return!1});this.port.attr("width",h);this.port.attr("height",j);this.d.append(this.port);this.top=g;this.height=j;this.left=e;this.width=h;a=="document"?(this.top-=E+D,this.height+=E,this.left-=D):a=="info"?(this.top-=Ba+D,this.height+=Ba,this.left-=D):a==
"alert"?(this.top-=Ca*2,this.left-=Ca*2,this.width+=Ca,this.height+=Ca):(this.top-=D,this.left-=D);this.B&&(this.width+=Da);this.A&&(this.height+=Ea);this.d.css("top",this.top+"px");this.d.css("left",this.left+"px");this.d.css("width",this.width+"px");this.d.css("height",this.height+"px");desktop.append(this.d);(this.B||this.A)&&Lb(this)}p=ga.prototype;p.show=function(){this.d.show();for(var a=0;a<this.w.length;a++)this.w[a].q!=255&&this.w[a].show()};p.hide=function(){this.d.hide()};
function P(a,b){if(a.title!=i){var c=a.title.children("span");c.html("");if(b=="")c.hide();else{var d=a.d.css("display")=="none";a.d.show();c.css({position:"absolute",visibility:"hidden",display:"block"});var f=a.port.width();a.M&&(f-=30);a.N&&(f-=30);for(var e=0;e<b.length;e++)if(c.append(b.substring(e,e+1)),c.width()>f){c.html(b.substring(0,e-1));break}c.css({position:"",visibility:"",display:""});d&&a.d.hide()}}}p.addClass=function(a){this.d.addClass(a)};p.removeClass=function(a){this.d.removeClass(a)};
p.add=function(a){var b=this.port.position().top,c=parseInt(a.a.css("top"),10);a.a.css("top",c+b+"px");this.d.append(a.a);a.d=this;this.w.push(a);this.d.css("display")!="none"&&a.g()};p.remove=function(a){var b=this.w.indexOf(a);b!=-1&&this.w.splice(b,1);a.a.remove()};p.close=function(){this.d.remove()};function hb(a,b){var c=a.port.offset();b.K+=c.left+1;b.L+=c.top+2;a.b&&(b.K-=a.b.x,b.L-=a.b.y)}
function Lb(a){if(a.A){a.s=$(document.createElement("div"));a.s.addClass("hscroll");a.s.css("top",a.height-Ea+"px");a.s.css("width",a.width-68+"px");a.s.mousedown(function(){fatal("scroll")});var b=$(document.createElement("div"));b.addClass("leftarrow");b.mousedown(function(){fatal("scroll")});a.s.append(b);a.k=$(document.createElement("div"));a.k.addClass("rightarrow");a.k.css("left",a.width-Fa-32+"px");a.k.mousedown(function(){fatal("scroll")});a.s.append(a.k);a.j=$(document.createElement("div"));
a.j.addClass("slider");a.j.mousedown(function(){fatal("drag")});a.s.append(a.j);a.d.append(a.s)}if(a.B)a.t=$(document.createElement("div")),a.t.addClass("vscroll"),a.t.css("left",a.width-Da+"px"),a.t.css("height",a.height-48+"px"),a.t.mousedown(function(){fatal("scroll")}),b=$(document.createElement("div")),b.addClass("uparrow"),b.mousedown(function(){fatal("scroll")}),a.t.append(b),a.I=$(document.createElement("div")),a.I.addClass("downarrow"),a.I.css("top",a.height-24-24-E+"px"),a.I.mousedown(function(){fatal("scroll")}),
a.t.append(a.I),a.f=$(document.createElement("div")),a.f.addClass("slider"),a.f.mousedown(function(){fatal("drag")}),a.t.append(a.f),a.d.append(a.t);a.G=$(document.createElement("div"));a.G.addClass("grow");a.G.css("top",a.height-24+"px");a.G.css("left",a.width-32+"px");a.G.mousedown(function(){fatal("grow")});a.d.append(a.G)}function V(a){for(var b=0;b<U.length;b++)if(U[b]==a){a.close();U.splice(b,1);break}U.length&&ia(U[0])}
function ia(a){if(U[0]!=a){U[0]!=i&&U[0].d.removeClass("active");for(var b=0;b<U.length;b++)U[b]==a&&U.splice(b,1);U.unshift(a)}a.d.addClass("active")}function Ia(a,b,c,d){a=new ga("alert",!1,!1,!1,!1,a,b,c,d);a.n=2;a.hide();ia(a);return a}var U=[];function F(a,b,c,d){switch(c&255){case 2:return new Mb(a,b,d);case 10:return new Nb(a,b,d);case 15:return new Ob(a,b,d);case 17:return new Pb(a,b,d);case 22:return new Qb(a,b,d);case 23:return new Rb(a,b);case 24:return new Sb(a,b,d);case 25:return new Tb(a,b,d);default:fatal("Unknown control:"+c.toString(16))}}
function Mb(a,b,c){this.a=$(document.createElement("canvas"));this.a.addClass("cbutton");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.attr("width",a[2]);this.a.attr("height",a[3]);this.q=b;this.selected=!1;this.fa=c[0];this.e=c[1];this.ga=c[2];this.a.mousedown(function(){fatal("cbutton")})}Mb.prototype.hide=function(){this.a.hide()};Mb.prototype.show=function(){this.a.show();this.g()};
Mb.prototype.g=function(){var a=this.a.get(0).getContext("2d"),b=a.getImageData(0,0,this.width,this.height),c=this.selected?this.ga:this.e;if(c)for(var d=0;d<this.height;d++)for(var f=(d>>1)*this.fa,e=d*b.width*4,g,h=0;h<this.width;h++)g=c.charCodeAt(f+(h>>2)),g=(g>>(h&2?0:4)&15)*3,b.data[e++]=x[g++],b.data[e++]=x[g++],b.data[e++]=x[g++],b.data[e++]=255;else for(d=0;d<this.height;d++){e=d*b.width*4;for(h=0;h<this.width;h++){g=this.selected?0:255;if(d<2||h<4||d>this.height-3||h>this.width-5)g=0;b.data[e++]=
g;b.data[e++]=g;b.data[e++]=g;b.data[e++]=255}}a.putImageData(b,0,0)};function Nb(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("button");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.a.html(c[0]);this.q=b;this.a.mousedown(function(){fatal("button")})}Nb.prototype.hide=function(){this.a.hide()};Nb.prototype.show=function(){this.a.show()};Nb.prototype.g=m();
function Ob(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("textblock");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.q=b;this.J(c[0])}Ob.prototype.J=function(a){this.a.html(a)};Ob.prototype.hide=function(){this.a.hide()};Ob.prototype.show=function(){this.a.show()};Ob.prototype.g=m();
function Pb(a,b,c){this.a=$(document.createElement("input"));this.a.addClass("textinput");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.a.val(c[0]);this.q=b}Pb.prototype.hide=function(){this.a.hide()};Pb.prototype.show=function(){this.a.show()};Pb.prototype.g=m();
function Qb(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("textblock");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.q=b;this.J(c[0])}Qb.prototype.hide=function(){this.a.hide()};Qb.prototype.show=function(){this.a.show()};Qb.prototype.g=m();
Qb.prototype.J=function(a){for(var b="",c=0;c<a.length;c++)a.charCodeAt(c)==1?(a.charCodeAt(c+1)==74&&this.a.css("text-align","center"),c+=2):b+=a.charCodeAt(c)==13?"<br />":a.charAt(c);this.a.html(b)};function Rb(a,b){this.a=$(document.createElement("div"));this.a.addClass("list");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.q=b}Rb.prototype.hide=function(){this.a.hide()};Rb.prototype.show=function(){this.a.show()};
Rb.prototype.g=m();
function Sb(a,b,c){this.value=parseInt(c[0],10);this.q=b;this.min=parseInt(c[1],10);this.max=parseInt(c[2],10);this.width=a[2];this.a=$(document.createElement("div"));this.a.addClass("hscroll");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.a.mousedown(function(){fatal("mousedown")});this.C=$(document.createElement("div"));this.C.addClass("leftarrow");this.C.css("top","0px");this.C.css("left","0px");this.C.mousedown(function(){fatal("left")});this.a.append(this.C);
this.k=$(document.createElement("div"));this.k.addClass("rightarrow");this.k.css("top","0px");this.k.css("left",a[2]-Fa+"px");this.k.mousedown(function(){fatal("right")});this.a.append(this.k);this.u=$(document.createElement("div"));this.u.addClass("slider");this.u.css("top","0px");this.u.css("left","50px");this.u.css("width","20px");this.u.mousedown(function(){fatal("slider")});this.a.append(this.u)}Sb.prototype.hide=function(){this.a.hide()};Sb.prototype.show=function(){this.a.show();this.g()};
Sb.prototype.g=function(){this.u.css("left",(this.value*(this.width-88)/(this.max-this.min)|0)+32+"px")};function wb(a,b){a.value=b;a.g()}function Tb(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("sbutton");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]-2+"px");this.a.css("height",a[3]-2+"px");this.a.html(c[0]);this.q=b;this.a.mousedown(function(){fatal("button")})}Tb.prototype.hide=function(){this.a.hide()};Tb.prototype.show=function(){this.a.show()};
Tb.prototype.g=m();function mb(a,b){if(b>=J[a].F)return"";var c,d;J[a].Q?(c=J[a].R[b],d=J[a].S[b]):(c=J[a].Y,d=b*c);if(!c)return"";return J[a].data.substring(d,d+c)}var J=[];var Ub=document.createElement("link");Ub.type="text/css";Ub.rel="stylesheet";Ub.href="gs.css";$("head").append(Ub);q=$(document.createElement("img"));q.attr("src","images/gs/start.png");q.css("width","100%");q.css("height","100%");desktop.append(q);
(function(a){$.ajax({url:a,sa:function(a){a.overrideMimeType("text/html; charset=x-user-defined")},complete:function(a){a=new w(a.responseText);var c=a.data.substring(a.c,a.c+4);a.c+=4;c!="2IMG"&&fatal("Not a valid 2mg file");a.seek(12,a.set);ka(a)!=1&&fatal("Not in ProDOS format");a.seek(20,a.set);c=ka(a)*512;var d=ka(a);a.seek(d,a.set);s=new w(v(a,c));delete a}})})(gamename);setTimeout(Qa,10);
