var k=void 0;function aa(){return function(){}}function ba(a){return function(){return a}}var l,ca,da=15,ea=24,fa=2;function ga(a){for(var b="",c=0;c<a.length;c++)switch(a.charCodeAt(c)){case 13:b+="<br />";break;case 63368:b+="&#224;";break;case 63374:b+="&#233;";break;default:b+=a.charAt(c)}return b}
function ha(a,b){var c={top:0,left:0,width:0,height:0},d;if(d=ia(a*2))if(c.width=d.width,c.height=d.height,ja(c,b,c)){a:{for(var e=c.top;e<c.top+c.height;e++)for(var g=(e>>1)*d.r,i,h=c.left;h<c.left+c.width;h++)if(i=d.data[g+(h>>2)],ka&&(i=ka[i]),i=i>>(h&2?0:4)&15){c=!0;break a}c=!1}return c}return!1}function la(){if(!n)return 3E3;return ma[n]}
function oa(a){var b={top:0,left:0,width:0,height:0},c=p(a),d=0;c&&c.a&&(d=pa(c.a.children,a));if(d){d--;if(c.a.children[d].width==0||c.a.children[d].height==0)a=qa(a,c,!0),c.a.children[d].top=a.top,c.a.children[d].left=a.left,c.a.children[d].width=a.width,c.a.children[d].height=a.height;b.top=c.a.children[d].top;b.left=c.a.children[d].left;b.width=c.a.children[d].width;b.height=c.a.children[d].height}else(c=ia(a*2))?(b.top=r(a,2),b.left=r(a,1),b.width=c.width,b.height=c.height):(b.top=0,b.left=0,
b.width=0,b.height=0);return b}function ra(a){a=ia(a*2);var b=a.width,c=a.height,d=$(document.createElement("canvas"));d.addClass("proxy");d.attr("width",b);d.attr("height",c);desktop.append(d);a.j(d,0,0);return d}function sa(a){a=ta(a);return ua(a.Aa,a.left*2,a.top*2,(a.right-a.left)*2,(a.bottom-a.top)*2)};function va(a){a[0]=="3"&&a[1]=="/"&&(a=a.substring(2));return wa(a.toLowerCase(),2)}var s=k;
function wa(a,b){s.seek(b*512+2,s.set);var c=t(s),d=u(s);(d&240)!=240&&(d&240)!=224&&fatal("Corrupt directory");s.seek(30,s.n);var e=u(s),g=u(s),i=u(s),h=1,f=0;d=a.indexOf("/");var j="";d>0&&(j=a.substring(d+1),a=a.substring(0,d));for(;f<i;){s.seek(b*512+e*h+4,s.set);d=u(s);if(d!=0){if(w(s,d&15).toLowerCase()==a){if((d&240)==208)return s.seek(16-(d&15),s.n),c=t(s),wa(j,c);s.seek(b*512+e*h+21,s.set);c=t(s);s.seek(2,s.n);e=xa(s)&16777215;j=c;c=e;e="";switch(d&240){case 16:e=ya(j,c);break;case 32:e=
za(j,c);break;case 48:d=j;j=c;c="";for(e=0;j>0;){s.seek(d*512+e,s.set);i=u(s);s.seek(d*512+e+256,s.set);i|=u(s)<<8;g=j;g>131072&&(g=131072);if(i)c+=za(i,g);else for(i=0;i<g;i++)c+=String.fromCharCode(0);j-=g;e++}e=c}return new Aa(e)}f++}h++;h==g&&(h=0,b=c,s.seek(b*512+2,s.set),c=t(s))}return!1}function ya(a,b){s.seek(a*512,s.set);return w(s,b)}
function za(a,b){for(var c="",d=0;b>0;){s.seek(a*512+d,s.set);var e=u(s);s.seek(a*512+d+256,s.set);e|=u(s)<<8;var g=b;g>512&&(g=512);if(e)c+=ya(e,g);else for(e=0;e<g;e++)c+=String.fromCharCode(0);b-=g;d++}return c};var x,ka,Ba=!0;function Ca(a,b,c){this.width=a>>1;this.height=b*2;this.r=c;this.J=a;this.Q=b;this.data=Array(b*c)}
Ca.prototype.j=function(a,b,c){if(!(this.width==0||this.height==0)){var d=a.get(0).getContext("2d"),e=0,g=0;b<0&&(e=-b,b=0);c<0&&(g=-c,c=0);var i=this.width,h=this.height;i+b>=a.width()&&(i=a.width()-b);h+c>=a.height()&&(h=a.height()-c);if(!(i==0||h==0)){a=d.getImageData(b,c,i,h);for(var f=g;f<h;f++)for(var j=(f>>1)*this.r,q=(f-g)*a.width*4,o,v=e;v<i;v++)o=this.data[j+(v>>2)],ka&&(o=ka[o]),(o=(o>>(v&2?0:4)&15)*3)?(a.data[q++]=x[o++],a.data[q++]=x[o++],a.data[q++]=x[o++],a.data[q++]=255):q+=4;d.putImageData(a,
b,c)}}};Ca.prototype.V=function(a,b){var c=this.data[(b>>1)*this.r+(a>>2)];ka&&(c=ka[c]);return(c>>(a&2?0:4)&15)!=0};function Da(a,b,c,d){this.width=a;this.height=b;this.r=c;this.$=d;this.data=Array(b*c)}
Da.prototype.j=function(a,b,c){if(!(this.width==0||this.height==0)){var d=a.get(0).getContext("2d"),e=this.width,g=this.height*2,i=0,h=0;b<0&&(i=-b,b=0);c<0&&(h=-c,c=0);e+b>=a.width()&&(e=a.width()-b);g+c>=a.height()&&(g=a.height()-c);if(!(e==0||g==0)){a=d.getImageData(b,c,e,g);for(var f=h;f<g;f++)for(var j=(f>>1)*this.r,q=(f-h)*a.width*4,o,v=i;v<e;v++)o=this.data[j+(v>>2)],o=(o>>6-(v&3)*2&3)*3,a.data[q++]=this.$[o++],a.data[q++]=this.$[o++],a.data[q++]=this.$[o++],a.data[q++]=255;d.putImageData(a,
b,c)}}};function Ea(){var a=va(Fa(8)),b=ta(6),c=b.right-b.left;b=b.bottom-b.top;a.seek(8,a.set);for(var d=[],e=0;e<4;e++)y(a),d.push(y(a)&255),d.push(y(a)&255),d.push(y(a)&255);var g=c+7>>2;c=new Da(c,b,g,d);for(e=0;e<g*b;e++)c.data[e]=u(a);return c};function Fa(a){z.seek(368+a*32,z.set);a=u(z);return w(z,a)}function Ga(){z.seek(496,z.set);var a=u(z);return w(z,a)}function ta(a){z.seek(a*10);a={};a.top=t(z);a.left=t(z);a.bottom=t(z);a.right=t(z);a.Aa=t(z);return a}function Ha(){z.seek(1464,z.set);var a=u(z);return w(z,a)}function Ia(){z.seek(1008,z.set);var a=u(z);return ga(w(z,a))}var Ja=[0,80,208];function Ka(a){z.seek(1128+Ja[a],z.set);a=u(z);return w(z,a)}var z;function La(a){for(a={z:a,i:0};Ma(a););}
function Ma(a){var b=!1;if(a.z[a.i]=="."||a.z[a.i+1]==".")return!1;a.z[a.i++]==" "&&(b=!0);a.i++;for(var c="";a.z[a.i]!="\\";)c+=a.z[a.i++];a.i++;for(var d="",e=!0,g=0,i=!1;a.z[a.i]!="\r";)switch(a.z[a.i++]){case "*":d=a.z[a.i++];a.i++;break;case "B":c="<b>"+c+"</b>";break;case "C":a.i++;break;case "D":e=!1;break;case "H":g=a.z.charCodeAt(a.i++)&255;g|=(a.z.charCodeAt(a.i++)&255)<<8;break;case "I":c="<i>"+c+"</i>";break;case "N":break;case "U":break;case "V":i=!0;break;case "X":break;default:fatal("Unknown menu control code")}a.i++;
if(b)return Na(c,g,d,e),i&&Na("-",0,"",!1),!0;A={id:g};A.b=$(document.createElement("div"));c=="@"?A.b.addClass("apple"):A.b.html(c);A.b.data("refCon",A);A.b.mousedown(function(a){if(B)return!1;Oa(a);return!1});A.p=$(document.createElement("table"));A.p.addClass("menu");A.body=$(document.createElement("tbody"));A.p.append(A.body);A.w=[];Pa.append(A.b);Qa.push(A);return!0};var Ra=2,Sa=24,Ta=20,Ua=4,Va=32,Wa=24,Xa=34,Ya;
function Za(){var a=$a(10,36,620,354);a.add(C([240,318,118,20],1,10,["OK"]));a.add(C([10,18,600,146],2,32790,["\u0001J\u0001\0Apple IIGS ^0\r\u0001J\u0001\0Written by:\r\u0001J\u0001\0\u0001S\u0001\0Fred Allen\u0001S\0\0\r\r\u0001J\u0001\0Artwork by:\r^1\r\r\u0001J\u0001\0\u0001S\u0004\0MacVenture Team\u0001S\0\0"]));a.add(C([10,164,300,136],3,32790,["^2"]));a.add(C([310,164,300,136],4,32790,["^3"]));a.add(C([10,294,600,22],5,32790,["\u0001J\u0001\0WebVenture &#169; 2011 Sean Kasun"]));a.param([Ia(),
Ka(0),Ka(1),Ka(2)]);return a}function ab(){var a=$a(80,80,480,200);a.add(C([214,150,50,20],1,10,["OK"]));a.add(C([100,80,280,22],2,24,[0,0,100]));var b=C([20,30,440,30],3,15,["Sound Volume"]);b.b.css("text-align","center");a.add(b);return a}
function bb(a){var b=$a(92,146,456,108);b.add(C([24,68,120,22],1,10,["YES"]));b.add(C([168,68,120,22],3,10,["NO"]));b.add(C([312,68,120,22],2,10,["CANCEL"]));b.add(C([100,10,340,38],4,32790,["Save changes before ^0   "]));switch(a){case 0:b.param(["starting a new game?"]);break;case 1:b.param(["opening another game?"]);break;case 2:b.param(["quitting?"])}return b}
function cb(){var a=$a(50,70,520,228);a.add(C([12,8,298,30],4,22,["Load which game:"]));a.add(C([12,50,298,164],3,23,[]));a.add(C([320,158,190,24],1,10,["Open"]));a.add(C([320,194,190,24],2,10,["Cancel"]));return a}function db(){var a=$a(50,70,540,256);a.add(C([22,50,298,124],4,23,[]));a.add(C([22,182,298,30],5,22,["Save game as:"]));a.add(C([22,200,290,36],3,17,[""]));a.add(C([330,186,200,22],1,10,["Save"]));a.add(C([330,222,200,22],2,10,["Cancel"]));return a}
function eb(){var a;a=D.left;for(var b=D.top,c=0;c<D.S;c++){a+=D.Ba;b+=D.Ca;if(b>=388)b=D.top;if(a>=628)a=D.left}D.S++;a={top:b,left:a,width:D.width,height:D.height};a=ua(D.Aa,a.left,a.top,a.width,a.height);a.l=14;return a}function fb(){var a=$a(10,352,620,40);a.add(C([5,8,30,24],1,10,["Print"]));a.add(C([272,8,32,24],2,10,["Quit"]));a.add(C([42,2,225,36],3,32790,["^0"]));a.param([Ha()]);return a}
function gb(){var a={};z.seek(70,z.set);a.bottom=t(z);a.left=t(z);a.width=t(z);a=C([a.left,a.bottom*2-20,a.width,20],5,17,[""]);a.b.css("text-align","center");return a}function hb(){var a=$a(140,136,430,128);a.add(C([14,56,122,26],1,10,["YES"]));a.add(C([260,56,152,26],2,10,["NO"]));a.add(C([14,92,398,26],3,10,["Yes, I'll use a saved game."]));a.add(C([14,10,398,38],4,15,["You have lost ... Would you\nlike to have another try?"]));return a}
function ib(){var a=$a(20,92,600,140);a.add(C([10,99,50,20],1,10,["OK"]));a.add(C([96,99,120,20],2,10,["CANCEL"]));a.add(C([10,10,580,36],4,22,["^0"]));a.add(C([10,56,580,28],3,17,[""]));return a}function ua(a,b,c,d,e){var g="dbox",i=!1,h=!1;a&32768&&(g="document");a&16&&(g="info");a&8192&&(g="alert");a&4096&&(i=!0);a&2048&&(h=!0);a=new jb(g,a&16384,a&256,i,h,b,c,d,e);a.hide();kb(a);return a};function lb(a){var b=mb(4,a);a=new Aa(b);var c=k;switch(b.charCodeAt(7)){case 0:c=0;var d=y(a);for(b=0;b<d;b++)y(a),c+=y(a),y(a),y(a);a.seek(8,a.set);b=y(a);c=new nb(c,b);var e=0;for(b=0;b<d;b++){a.seek(2+b*8,a.set);var g=y(a),i=y(a);a.seek(g,a.set);for(g=0;g<i;g++)c.data[e++]=u(a)}break;case 2:e=0;b=y(a);for(c=0;c<b;c++)y(a),e+=y(a)*2,y(a),y(a);a.seek(8,a.set);c=y(a);e=new nb(e,c);for(c=i=0;c<b;c++){a.seek(2+c*8,a.set);var h=y(a);g=y(a)*2;a.seek(h,a.set);for(h=0;h<g;h++)h&1?d>>=4:d=u(a),e.data[i++]=
ob[d&15]}c=e}if(c==k)return 0;pb&&!qb&&c.play();return c.C/c.R}var ob=[127,126,124,120,112,96,64,1,128,129,131,135,143,159,191,255];function Aa(a){this.set=0;this.n=1;this.end=2;this.data=a;this.length=a.length;this.q=this.g=0}function u(a){return a.data.charCodeAt(a.g++)&255}function y(a){var b=(a.data.charCodeAt(a.g++)&255)<<8;b|=a.data.charCodeAt(a.g++)&255;return b}function t(a){var b=a.data.charCodeAt(a.g++)&255;b|=(a.data.charCodeAt(a.g++)&255)<<8;return b}function sb(a){var b=(a.data.charCodeAt(a.g++)&255)<<16;b|=(a.data.charCodeAt(a.g++)&255)<<8;b|=a.data.charCodeAt(a.g++)&255;return b}
function tb(a){var b=(a.data.charCodeAt(a.g++)&255)<<24;b|=(a.data.charCodeAt(a.g++)&255)<<16;b|=(a.data.charCodeAt(a.g++)&255)<<8;b|=a.data.charCodeAt(a.g++)&255;return b}function xa(a){var b=a.data.charCodeAt(a.g++)&255;b|=(a.data.charCodeAt(a.g++)&255)<<8;b|=(a.data.charCodeAt(a.g++)&255)<<16;b|=(a.data.charCodeAt(a.g++)&255)<<24;return b}
function ub(a){var b=(a.data.charCodeAt(a.g)&255)<<24;b|=(a.data.charCodeAt(a.g+1)&255)<<16;b|=(a.data.charCodeAt(a.g+2)&255)<<8;b|=a.data.charCodeAt(a.g+3)&255;return b}Aa.prototype.seek=function(a,b){switch(b){case this.n:a+=this.g;break;case this.end:a+=this.length}this.g=a};function w(a,b){var c=a.g;a.g+=b;return a.data.substring(c,a.g)}Aa.prototype.f=function(a){var b=ub(this);b>>>=32-this.q-a;b&=(1<<a)-1;this.q+=a;this.q&16&&(this.q&=15,this.g+=2);return b};function vb(){if(s!=k){E=0;z=va("3/RESOURCE.DAT");ca.remove();delete ca;var a=Fa(6),b=va(a);b.seek(8,b.set);x=[];for(var c=0;c<16;c++)y(b),x.push(y(b)&255),x.push(y(b)&255),x.push(y(b)&255);a=new Ca(1280,200,160);for(c=0;c<32E3;c++)a.data[c]=u(b);b=new jb("plainDBox",!1,!1,!1,!1,0,0,640,400);b.hide();kb(b);wb=b;wb.show();xb(wb.port,0);a.j(wb.port,0,0);a=[3,1,2,0,5];for(b=0;b<5;b++){var d=Fa(a[b]);c=b;d=va(d);var e={Ra:0,ia:!1};d.seek(0,d.set);var g=d.length,i=tb(d),h=k;if(i&2147483648){i&=2147483647;
e.ia=!0;d.seek(i,d.set);e.O=y(d);g=Array(16);h=Array(16);for(var f=0;f<15;f++)g[f]=y(d);for(f=0;f<16;f++)h[f]=u(d);e.ka=Array(e.O);e.ja=Array(e.O);var j=0,q=k;for(f=0;f<e.O;f++){if((f&63)==0){d.seek(i+(f>>6)*6+48,d.set);var o=sb(d);q=sb(d);j=o&7;d.seek(i+(o>>3),d.set)}e.ka[f]=q;o=tb(d)>>>16-j&65535;d.seek(-4,d.n);var v;for(v=0;v<16;v++)if(g[v]>o)break;o=h[v];j+=o&15;j&16&&(j&=15,d.seek(2,d.n));o>>=4;v=0;o&&(v=ub(d),o--,o==0?v=0:v>>>=32-o-j,v&=(1<<o)-1,v|=1<<o,j+=o,j&16&&(j&=15,d.seek(2,d.n)),q+=v);
e.ja[f]=v}h=i-4}else g-=4,h=g,e.Da=i,e.O=g/i|0;d.seek(4,d.set);e.data=w(d,h);yb[c]=e}a={};z.seek(76,z.set);a.Ga=t(z);a.Ea=t(z);a.Pa=t(z);a.Fa=t(z);t(z);a.Qa=t(z);a.oa=[];for(b=0;b<24;b++)a.oa.push(u(z));a.la=[];for(b=0;b<64;b++)a.la.push(u(z));a.ma=[];for(b=0;b<64;b++)a.ma.push(t(z));a.na=[];for(b=0;b<64;b++)a.na.push(u(z));zb=a.Ga;Ab=a.Ea;Bb=a.Fa;Cb=a.la;Db=a.ma;Eb=a.na;ma=a.oa;D=ta(5);D.top*=2;D.left*=2;D.width=D.right*2-D.left;D.height=D.bottom*2-D.top;D.Ca=20;D.Ba=20;D.S=0;Fb=[];Gb();F=[];G=[];
Hb=[];H=[];I=Array(zb*2);var m;if(z.length!=1676){m={};z.seek(1676,z.set);m.length=t(z);m.da=[];z.seek(1680,z.set);for(a=0;a<m.length;a++)m.da.push(t(z));m.ca=[];z.seek(1868,z.set);for(a=0;a<m.length;a++)m.ca.push(u(z));m.ea=[];z.seek(1964,z.set);for(a=0;a<m.length;a++)m.ea.push(u(z))}m!=k&&(Ib=m,Jb=!1);m=[];z.seek(720,z.set);for(a=0;a<16;a++)m.push(t(z));x=[];for(a=0;a<16;a++)b=m[a]>>4&15,c=m[a]&15,x.push((m[a]>>8&15)*17),x.push(b*17),x.push(c*17);m=[];z.seek(752,z.set);for(a=0;a<256;a++)m.push(u(z));
ka=m;z.seek(1092,z.set);Ya=t(z);J=sa(3);J.l=9;J.addClass("commands");m=[{name:"3/SHADOWGATE",start:49390,N:-3272},{name:"3/DEJAVU",start:49390,N:-3272},{name:"3/DEJAVUII",start:4014,N:66},{name:"3/UNINVITED",start:49390,N:-3272}];for(a=0;a<m.length;a++)if(b=va(m[a].name)){for(c=0;c<9;c++)b.seek(m[a].start+c*11,b.set),d=t(b)*2,e=t(b)*2,i=t(b)*2-d,g=t(b)*2-e,h=u(b),f=t(b),f=f&15|f&61440,b.seek(m[a].start+115+c*4,b.set),o=t(b),b.seek(o+m[a].N),j=t(b),q=w(b,j*i),b.seek(m[a].start+151+c*4,b.set),o=t(b),
b.seek(o+m[a].N),t(b),o=w(b,j*i),J.add(C([e,d,g,i],h,f,[j,q,o]));break}K=sa(0);K.l=10;Kb=sa(1);Kb.l=11;L=$(document.createElement("div"));L.addClass("textEdit");m=Kb;a=L;b=m.port.attr("width");c=m.port.attr("height");m.port.remove();a.css("top","0px");a.css("left","0px");a.css("width",b+"px");a.css("height",c+"px");m.port=a;m.c.append(a);Lb=sa(4);Lb.l=12;Lb.a={id:0,x:0,y:0,children:[{id:1,top:0,left:0,width:0,height:0}]};M=sa(2);Mb(M,"Exits");M.l=13;M.addClass("exits");Pa=$(document.createElement("div"));
Pa.addClass("menubar");m=[">L File \\H\u0002\0\r LNew\\V*NnH\0\u0081\r LOpen...\\*OoH\u0002\u0081\r LSave\\*SsH\u0003\u0081\r LSave As...\\VH\u0004\u0081\r LQuit\\*QqH\u0006\u0081\r.",">L Edit \\H\u0003\0\r LUndo\\DV*ZzH\0\u0082\r LCut\\D*XxH\u0002\u0082\r LCopy\\D*CcH\u0003\u0082\r LPaste\\DV*VvH\u0004\u0082\r LClear\\DH\u0005\u0082\r.",">L Special \\H\u0004\0\r LClean Up\\DH\0\u0083\r LMess Up\\DH\u0001\u0083\r."];z.seek(1024);a=w(z,48);La(a);for(a=0;a<m.length;a++)La(m[a]);A=Qa[0];Na("Adjust Volume...",
2304,"",!0);Mb(Kb,"Untitled");if(gameparts.length>1)Nb=gameparts[1],m=window.JSON.parse(window.localStorage.getItem(Nb).toString()),Ob=m.aa,Pb=m.ba,L.html(m.text),Mb(Kb,Nb);else{m=va(Ga());Ob=Array(Bb);Pb=Array(Ab);for(a=0;a<Bb;a++){Ob[a]=Array(zb);for(b=0;b<zb;b++)Ob[a][b]=y(m)}for(a=0;a<Ab;a++)Pb[a]=y(m)}Qb();Nb==""&&(N=!0,n=1,O.push(r(1,0)));setTimeout(Rb,500)}else setTimeout(vb,10)}function Qb(){for(var a,b,c=0;c<zb*2;c++)I[c]=0;for(c=zb-1;c;c--)a=Ob[0][c],(b=I[a*2])&&(I[c*2+1]=b),I[a*2]=c}
function Sb(){for(var a=[],b=0;b<P.length;b++)(P[b].l==10||P[b].l==14)&&a.push(P[b]);for(b in a)Tb(a[b]);D.S=0;G=[];Hb=[];H=[];Fb=[]}var I;function Rb(){Q(wb);delete wb;desktop.append(Pa);J.show();Lb.show();Ub(Lb);M.show();Kb.show();K.show();E=1;Vb=L.get(0).scrollHeight;L.scrollTop(Vb-Vb%da);Wb(r(1,0),6,1);R=!1;S()};var E=0,R=!1,Vb=0,F,O,n=k,N=!1,Xb,Yb,ma,Fb,G,Hb,H,wb,Zb,K,J,Kb,Lb,M,L,zb,Ab,Bb,Eb,Db,Cb,D,Ob,Pb,$b,T,U,Nb="";function ac(){}var bc=!1,cc=!1,dc=!1,B=!1,V=k;function S(){if(E==4)window.location="index.html";else{bc||ec(!1);if(N||bc){bc=!1;if(fc()){B=bc=!0;return}B=!1;if(ec(!0))return;gc()}(E==2||E==3)&&hc()}}
function fc(){if(cc){cc=!1;if(ic(!1))return cc=!0;return!1}if(dc){dc=!1;if(ic(!1))return dc=!0;if(ec(!0))return!0}for(;O.length;){var a=O.shift();if((E==0||E==1)&&jc(a)){if(kc(n,a,T,U))return dc=!0;if(ec(!0))return!0}}if(n==1)R=!1;else if((E==0||E==1)&&kc(3,n,T,U))return cc=!0;return!1}
function jc(a){if(!lc(a))return!1;if(la()>=2&&T>0&&!lc(T))return!1;if(n!=5)return!0;if(!(r(a,3)==0&&r(a,4)==0&&r(a,5)==0))return!1;if(r(1,0)!=T)return!0;var b={top:0,left:0,width:K.port.width(),height:K.port.height()};b.top-=r(a,2)+U.e;b.left-=r(a,1)+U.d;return ha(a,b)}function lc(a){for(var b=r(1,0);a!=0&&a!=1&&a!=b;)a=r(a,0);return a}function ec(a){mc();var b=nc();oc(a)&&(b=!0);return b}
function hc(){if(E==2){pc();var a=Ea();Zb=sa(6);Zb.show();a.j(Zb.port,0,0);qc();E=4}else if(E==3){gc();var b=hb();b.show(function(a){Q(b);switch(a){case 1:rc();break;case 2:E=4;S();break;case 3:sc()}})}}function qc(){var a=document.createElement("link");a.type="text/css";a.rel="stylesheet";a.href="print.css";a.media="print";$("head").append(a);a=fb();B=!0;var b=gb();Zb.add(b);b.b.focus();a.show(function(a){switch(a){case 1:b.b.blur();window.print();break;case 2:S()}})}
function mc(){for(;G.length;){for(var a,b=0,c=0;c<G.length;c++)if(G[c].id>b)b=G[c].id,a=c;b=G.splice(a,1)[0];switch(b.id){case 2:tc(b.val);break;case 3:uc(b.val);break;case 4:vc(b.val);break;case 7:a:{c=b.val;var d=!1;b=c.b;var e=Fb.indexOf(b);e!=-1&&Fb.splice(e,1);if(b==1)c.parent!=r(b,0)&&G.push({id:12}),(c.qa!=r(b,3)||c.pa!=r(b,4))&&Ub(p(b));else if(c.parent!=r(b,0)||c.x!=r(b,1)||c.y!=r(b,2)){if(e=wc(c.parent)){d=e;if(d.a!=k&&(e=pa(d.a.children,b),e!=0))d.a.children.splice(e-1,1),d.a.B=!0,Ub(d);
d=!0}if(e=p(b)){d=e;if(d.a!=k){e=k;for(e=0;e<d.a.children.length&&b>d.a.children[e].id;e++);if(e==d.a.children.length||b!=d.a.children[e].id)d.a.children.splice(e,0,{id:b,top:0,left:0,width:0,height:0}),d.a.B=!0,Ub(d)}d=!0}}else(c.qa!=r(b,3)||c.pa!=r(b,4))&&Ub(p(b));r(b,8)&&(d||c.Ja!=r(b,11)||c.Ha!=r(b,9)||c.Ia!=r(b,10))&&xc(b);c=wc(b);d=b;for(e=r(1,0);d!=e;){if(d==0||!r(d,6))break;d=r(d,0)}if(d==e){if(c)break a;G.push({id:3,val:b})}else{if(!c)break a;G.push({id:4,val:b})}b=yc(b,!0);for(e=0;e<b.length;e++)zc(b[e])}break;
case 8:b=b.val;d=wc(b.T);(c=e=wc(b.K))||(c=d);if(c)d=W(b.K),Mb(c,d),Ac(b.K,c),c.a.B=!0,Ub(c);break;case 12:Wb(K.a.id,6,0);Wb(r(1,0),6,1);break;case 13:for(;F.length;)Bc(F.pop());break;case 14:Cc(b.val)}}}function tc(a){a&&(a=wc(a))&&kb(a)}
function uc(a){if(!wc(a))if(a==r(1,0)){Ac(a,K);Ub(K);Dc();var b=W(a);Mb(K,b.substr(0,1).toUpperCase()+b.substr(1))}else{var c={d:r(a,1),e:r(a,2)};Ec(p(a),c);Fc(c);b=W(a);var d=eb();Mb(d,b);Ac(a,d);d.a.B=!0;var e=$(document.createElement("div"));e.addClass("zoom");desktop.append(e);e.css("top",c.e+"px");e.css("left",c.d+"px");e.css("width","0px");e.css("height","0px");e.animate({top:d.top+"px",left:d.left+"px",width:d.width+"px",height:d.height+"px"},500,"swing",function(){e.remove();d.show();Ub(d)})}}
function vc(a){var b=Tb(wc(a));if(b!=k&&(a=p(b.b),a!=k)){var c=$(document.createElement("div"));c.addClass("zoom");desktop.append(c);c.css("top",b.top+"px");c.css("left",b.left+"px");c.css("width",b.width+"px");c.css("height",b.height+"px");b={d:r(b.b,1),e:r(b.b,2)};Ec(a,b);Fc(b);c.animate({top:b.e+"px",left:b.d+"px",width:"0px",height:"0px"},500,"swing",function(){c.remove();D.S--})}}
function Bc(a){var b=M.find(a);b&&(F.indexOf(a)!=-1?b.select():b.P());a==r(1,0)&&(F.indexOf(a)!=-1?M.addClass("selected"):M.removeClass("selected"));Ub(p(a))}function Cc(a){desktop.append(V);var b={d:r(a,1),e:r(a,2)};Ec(p(a),b);Fc(b);V.animate({top:b.e+"px",left:b.d+"px"},300,"swing",function(){V.remove()})}
function nc(){if(L.get(0).scrollHeight==L.innerHeight()){var a=L.clone();a.css("height","");a.css("visibility","hidden");$("body").append(a);Vb=a.innerHeight();a.remove();delete a}for(;H.length;)switch(a=H.splice(0,1)[0],a.id){case 1:L.append(a.val);R=!0;break;case 2:L.append("<br/>");R=!0;break;case 3:Gc=a.val[1],Hc=a.val[0],L.append(W(a.val[2])),R=!0}return Ic()}
function Ic(){var a=L.get(0).scrollHeight,b=L.innerHeight();L.scrollTop(Vb-Vb%da);Vb=L.scrollTop()+b;Jc(Kb,{left:0,right:0,top:0,bottom:a});if(Vb<a)return Kc(J),Lc(J),B=!0;return!1}function oc(a){for(var b=0;Hb.length;){var c=Hb.splice(0,1)[0];switch(c.id){case 1:lb(c.val);break;case 2:b=lb(c.val)}}if(a&&b)return setTimeout(S,b*1E3),!0;return!1}
function Wb(a,b,c){if(b==1||b==2)c=Math.round(c/fa);if(b==0){var d=c,e=Ob[0][a];if(d!=a){var g=e*2;for(e=I[g];e!=a;)g=e*2+1,e=I[g];I[g]=I[e*2+1];g=d*2;for(e=I[g];e&&e<=a;)g=e*2+1,e=I[g];I[a*2+1]=e;I[g]=a}}b<12&&zc(a);d=Cb[b];c<<=Eb[b];c&=Db[b];Ob[d][a]=c|Ob[d][a]&~Db[b];R=!0}function r(a,b){var c,d=Cb[b];if(d&128){var e=mb(0,a);if(e.length==0)return 0;d&=127;c=(e.charCodeAt(d*2)&255)<<8;c|=e.charCodeAt(d*2+1)&255}else c=Ob[d][a];c&=Db[b];c=X(c>>Eb[b]);if(b==1||b==2)c*=fa;return c}
function Ub(a){if(a!=k&&a.a!=k&&(a==Lb||r(a.a.id,6)==1)){a==K?ia(a.a.id*2).j(K.port,0,0):xb(a.port,Ya);for(var b=0;b<a.a.children.length;b++){var c=qa(a.a.children[b].id,a,0);a.a.children[b].top=c.top;a.a.children[b].left=c.left;a.a.children[b].width=c.width;a.a.children[b].height=c.height}if(a.l==14&&a.a.B){b={top:0,left:0,right:0,bottom:0};a.a.B=!1;for(c=0;c<a.a.children.length;c++){var d=a.a.children[c];b.right==b.left||b.bottom==b.top?(b.top=d.top,b.left=d.left,b.bottom=d.top+d.height,b.right=
d.left+d.width):(b.top=Math.min(b.top,d.top),b.left=Math.min(b.left,d.left),b.bottom=Math.max(b.bottom,d.top+d.height),b.right=Math.max(b.right,d.left+d.width))}if(b.right==b.left||b.bottom==b.top)b.top=a.a.y,b.left=a.a.x,b.bottom=a.a.y,b.right=a.a.x;else{if(b.left>a.a.x)b.left=a.a.x;if(b.right<a.a.x)b.right=a.a.x;if(b.top>a.a.y)b.top=a.a.y;if(b.bottom<a.a.y)b.bottom=a.a.y}Jc(a,b)}}}function Mc(a){a=J.find(a);a!=$b&&($b&&$b.P(),($b=a)&&a.select())}
function Nc(a,b,c){Hc=c;Gc=b;var d=ib();d.param([W(a)]);d.getItem(3).b.keypress(function(a){if(a.which==13)return d.getItem(1).b.mousedown(),!1;return!0});d.show(function(a){Oc=d.getItem(3).b.val();a==1?Y[0].state.push(65535):Y[0].state.push(0);Q(d);S()})}
function Pc(a){switch(a){case 256:Qc();break;case 32768:Qc();break;case 33024:Rc();break;case 33026:Sc();break;case 33027:ac=aa();Tc();break;case 33028:ac=aa();Uc();break;case 33030:Vc();break;case 2304:Wc();break;case 33280:break;case 33282:break;case 33283:break;case 33284:break;case 33285:break;case 33536:break;case 33537:break;default:fatal("Unknown menuitem: "+a.toString(16))}}
function Xc(a,b){var c=a.c;if(c.l==2)c.Na(a.o);else if(c==M)B||Yc(a.o,M,b,!1);else if(a.o==255){c=J;for(var d=0;d<c.h.length;d++)c.h[d].o==255&&c.h[d].hide();Zc(J);Ic()||S()}else if(!B){$b&&a!=$b&&$b.P();n=a.o;Mc(n);switch(la()){case 0:N=!0;break;case 1:N=O.length!=0;break;case 2:T>0&&(N=!0)}S()}}
function Yc(a,b,c,d){b==M&&(b=K);if(c.shiftKey)if(a)O.indexOf(a)!=-1?$c(a):ad(a),S();else if(b.l==14)bd(b,c,d);else{if(O.length==0||b!=p(O[0]))O.indexOf(b.a.id)!=-1?$c(b.a.id):ad(b.a.id);S()}else if(n&&O.length&&la()>1)a?cd(a):cd(b.a.id),S();else{if(!a)dd(),b.l==14?bd(b,c,d):a=b.a.id;if(a){var e;c.timeStamp-Xb<=300&&c.target==Yb?(Xb=0,Yb=k,e=!0):e=!1;e?(O.indexOf(a)==-1&&dd(),ad(a),ed(a,b,c,d)):(O.indexOf(a)==-1&&dd(),ad(a),fd(a,b,c,d))}}}
function bd(a,b,c){var d={},e={d:a.a.x,e:a.a.y};Ec(a,e);Fc(e);d.ta=e.d;d.ua=e.e;d.ra=e.d+a.port.width();d.sa=e.e+a.port.height();var g=$(document.createElement("div"));g.addClass("lasso");desktop.append(g);var i={d:b.pageX,e:b.pageY};Fc(i);g.css("top",i.e+"px");g.css("left",i.d+"px");g.css("width","0px");g.css("height","0px");$(document).mousemove(function(a){var b={d:a.pageX,e:a.pageY};Fc(b);a=Math.max(Math.min(i.d,b.d),d.ta);var c=Math.max(Math.min(i.e,b.e),d.ua),e=Math.min(Math.max(i.d,b.d),d.ra);
b=Math.min(Math.max(i.e,b.e),d.sa);g.css("top",c+"px");g.css("left",a+"px");g.css("width",e-a+"px");g.css("height",b-c+"px")});$(document).mouseup(function(e){$(document).unbind("mousemove");$(document).unbind("mouseup");e={d:e.pageX,e:e.pageY};Fc(e);var f=Math.max(Math.min(i.d,e.d),d.ta),j=Math.max(Math.min(i.e,e.e),d.ua),q=Math.min(Math.max(i.d,e.d),d.ra),o=Math.min(Math.max(i.e,e.e),d.sa);g.remove();e={d:f,e:j};var v=desktop.offset();e.e+=v.top;e.d+=v.left;gd(a,e);j={top:e.e,left:e.d,width:q-f,
height:o-j};f=[];for(q=0;q<a.a.children.length;q++){var m=a.a.children[q].id;if(!r(m,4))j.left=e.d-r(m,1),j.top=e.e-r(m,2),ha(m,j)&&f.push(m)}if(b.shiftKey){if(f.length==0){if(O.length==0||a!=p(O[0]))O.indexOf(a.a.id)!=-1?$c(a.a.id):ad(a.a.id)}else for(;f.length;)m=f.shift(),O.indexOf(m)!=-1?$c(m):ad(m);S()}else{if(f.length==0)m=a.a.id;else for(;f.length;)m=f.shift(),ad(m);Yc(m,a,b,c)}})}
function ed(a,b,c,d){var e=c.pageX,g=c.pageY,i={d:0,e:0},h=!1;V=k;d&&$(document).mousemove(function(c){if(V==k){if(Math.abs(c.pageX-e)+Math.abs(c.pageY-g)<=7)return!1;h=!0;V=ra(a);var d=pa(b.a.children,a);if(d)d--,i.d=b.a.children[d].left,i.e=b.a.children[d].top;Ec(b,i);Fc(i);V.css("top",i.e+"px");V.css("left",i.d+"px")}d=V.position();V.css("top",d.top+(c.pageY-g)+"px");V.css("left",d.left+(c.pageX-e)+"px");e=c.pageX;g=c.pageY;return!1});$(document).mouseup(function(c){var e;d&&($(document).unbind("mousemove"),
V&&(e=V.position(),V.remove()));$(document).unbind("mouseup");if(h)U.d=e.left,U.e=e.top,c=hd(c.pageX,c.pageY),T=c.id,U.d-=i.d,U.e-=i.e,c.c!=b&&(Ec(b,U),c.c&&gd(c.c,U)),n=5,Mc(5),N=!0;N||(cd(a),n||(n=4,Mc(4),N=!0));S()})}
function fd(a,b,c,d){var e=c.pageX,g=c.pageY,i={d:0,e:0},h=!1;V=k;d&&$(document).mousemove(function(c){if(V==k){if(Math.abs(c.pageX-e)+Math.abs(c.pageY-g)<=7)return!1;h=!0;V=ra(a);var d=pa(b.a.children,a);if(d)d--,i.d=b.a.children[d].left,i.e=b.a.children[d].top;Ec(b,i);Fc(i);V.css("top",i.e+"px");V.css("left",i.d+"px")}d=V.position();V.css("top",d.top+(c.pageY-g)+"px");V.css("left",d.left+(c.pageX-e)+"px");e=c.pageX;g=c.pageY;return!1});$(document).mouseup(function(a){Xb=a.timeStamp;Yb=a.target;
var c;d&&($(document).unbind("mousemove"),V&&(c=V.position(),V.remove()));$(document).unbind("mouseup");if(h)U.d=c.left,U.e=c.top,a=hd(a.pageX,a.pageY),T=a.id,U.d-=i.d,U.e-=i.e,a.c!=b&&(Ec(b,U),a.c&&gd(a.c,U)),n=5,Mc(5),N=!0;la()==1&&(N=!0);S()})}function dd(){for(;O.length;)$c(O.shift())}function ad(a){O.length&&p(a)!=p(O[0])&&dd();O.indexOf(a)==-1&&O.push(a);F.indexOf(a)==-1&&(F.push(a),Bc(a))}function $c(a){var b=O.indexOf(a);b!=-1&&O.splice(b,1);if((b=F.indexOf(a))!=-1)F.splice(b,1),Bc(a)}
function cd(a){if(a!=T){var b;if(T>0&&(b=F.indexOf(T))!=-1&&O.indexOf(T)==-1)F.splice(b,1),Bc(T);T=a;F.indexOf(T)==-1&&(F.push(T),Bc(T));N=!0}}
function qa(a,b,c){var d=r(a,1),e=r(a,2),g=r(a,3);if(c||!g||!r(a,4)){var i=1;g||c?i=0:F.indexOf(a)!=-1&&(i=2);c=d-b.a.x;e-=b.a.y;var h=b.port;d=i;i={top:0,left:0,width:0,height:0};if(a=ia(a*2))switch(i={top:e,left:c,width:a.width,height:a.height},d){case 1:a.j(h,c,e);break;case 2:if(!(a.width==0||a.height==0)){d=h.get(0).getContext("2d");var f=g=0;c<0&&(g=-c,c=0);e<0&&(f=-e,e=0);var j=a.width,q=a.height;j+c>=h.width()&&(j=h.width()-c);q+e>=h.height()&&(q=h.height()-e);if(!(j==0||q==0)){h=d.getImageData(c,
e,j,q);for(var o=f;o<q;o++)for(var v=(o>>1)*a.r,m=(o-f)*h.width*4,na,rb=g;rb<j;rb++)na=a.data[v+(rb>>2)],ka&&(na=ka[na]),(na=na>>(rb&2?0:4)&15)?(na^=15,na*=3,h.data[m++]=x[na++],h.data[m++]=x[na++],h.data[m++]=x[na++],h.data[m++]=255):m+=4;d.putImageData(h,c,e)}}}i.top+=b.a.y;i.left+=b.a.x;return i}return{top:0,left:0,width:0,height:0}}function Dc(){for(var a=M,b=0;b<a.h.length;b++)a.h[b].b.remove();a.h=[];a=yc(r(1,0),!0);for(b=0;b<a.length;b++)xc(a[b])}
function xc(a){if(r(a,8)){var b=M.find(a);b&&M.remove(b);!r(a,11)&&r(a,0)==r(1,0)&&M.add(C([r(a,9)*2,r(a,10)*2,14,12],a,2,[]))}}function Qc(){var a=Za();B=!0;a.show(function(){Q(a);B=!1})}function Wc(){var a=ab(),b=id();b==null&&(b=50);jd(a.getItem(2),b);B=!0;a.show(function(){var b=a.getItem(2).value,d=new Date;d.setTime(d.getTime()+31536E6);document.cookie="webventure_volume="+escape(b)+"; expires="+d.toGMTString()+"; path=/";Q(a);B=!1})}
function Rc(){if(R){var a=bb(0);B=!0;a.show(function(b){Q(a);switch(b){case 1:ac=Rc;Tc();break;case 3:rc();break;case 2:B=!1}})}else rc()}function rc(){Nb="";for(var a=va(Ga()),b=0;b<Bb;b++)for(var c=0;c<zb;c++)Ob[b][c]=y(a);for(b=0;b<Ab;b++)Pb[b]=y(a);Sb();Qb();Mb(Kb,"Untitled");L.html("");n=1;O=[r(1,0)];E=1;Wb(r(1,0),6,1);dc=cc=bc=R=!1;Y=[];N=!0;S()}function Sc(){if(R){var a=bb(1);B=!0;a.show(function(b){Q(a);switch(b){case 1:ac=Sc;Tc();break;case 3:sc();break;case 2:B=!1}})}else sc()}
function sc(){var a=cb();B=!0;for(var b=a.getItem(3),c=k,d=0;d<window.localStorage.length;d++){var e=window.localStorage.key(d);if(e!=null&&window.JSON.parse(window.localStorage.getItem(e).toString()).wa==gamename){var g=$(document.createElement("div"));g.addClass("listitem");g.mousedown(ba(!1));g.click(function(a){c&&c.removeClass("active");c=$(a.target);c.addClass("active")});g.dblclick(function(){a.getItem(1).b.mousedown()});g.text(e.toString());b.b.append(g)}}a.show(function(b){switch(b){case 1:if(c==
k)break;Nb=c.text();Q(a);B=!1;b=window.JSON.parse(window.localStorage.getItem(Nb).toString());Ob=b.aa;Pb=b.ba;Sb();Qb();Mb(Kb,Nb);L.html(b.text);Vb=L.get(0).scrollHeight;L.scrollTop(Vb);E=1;dc=cc=bc=!1;O=[];n=0;Y=[];Wb(r(1,0),6,1);R=!1;S();break;case 2:Q(a),B=!1}})}function Tc(){Nb==""?Uc():(window.localStorage.setItem(Nb,window.JSON.stringify({wa:gamename,aa:Ob,ba:Pb,text:L.html()})),Mb(Kb,Nb),R=!1,ac())}
function Uc(){var a=db();B=!0;a.getItem(3).b.keypress(function(b){if(b.which==13)return a.getItem(1).b.mousedown(),!1;return!0});for(var b=a.getItem(4),c=k,d=0;d<window.localStorage.length;d++){var e=window.localStorage.key(d);if(e!=null&&window.JSON.parse(window.localStorage.getItem(e).toString()).wa==gamename){var g=$(document.createElement("div"));g.addClass("listitem");g.mousedown(ba(!1));g.click(function(b){c&&c.removeClass("active");c=$(b.target);c.addClass("active");a.getItem(3).b.val(c.text())});
g.dblclick(function(){a.getItem(1).b.mousedown()});g.text(e.toString());b.b.append(g)}}a.show(function(b){switch(b){case 1:Nb=a.getItem(3).b.val();Q(a);B=!1;Tc();break;case 2:Q(a),B=!1,ac()}})}function Vc(){if(R){var a=bb(2);B=!0;a.show(function(b){Q(a);switch(b){case 1:ac=Vc;Tc();break;case 3:E=4;S();break;case 2:B=!1}})}else E=4,S()}
function id(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var c=a[b];c.charAt(0)==" ";)c=c.substring(1,c.length);if(c.indexOf("webventure_volume=")==0)return unescape(c.substring(18,c.length))}return null}function Gb(){n=0;$b=k;O=[];T=0;U={d:0,e:0};Oc="";N=!1;Xb=0}function zc(a){if(Fb.indexOf(a)==-1){Fb.push(a);var b={b:a};b.parent=r(a,0);b.x=r(a,1);b.y=r(a,2);b.Ha=r(a,9);b.Ia=r(a,10);b.Ja=r(a,11);b.qa=r(a,3);b.pa=r(a,4);G.push({id:7,val:b})}}
function kd(a){a&128&&(a=-((a^255)+1));return a}function X(a){a&32768&&(a=-((a^65535)+1));return a}function wc(a){switch(a){case 65532:return M;case 65533:return Lb;case 65534:return Kb;case 65535:return J}var b;a:for(var c=0;c<P.length;c++)if((P[c].l==10||P[c].l==14)&&P[c].a!=k&&P[c].a.id==a){b=P[c];break a}return b}function yc(a,b){for(var c=[],d=I[a*2];d;)c.push(d),b||(c=c.concat(yc(d,!1))),d=I[d*2+1];return c}
function pa(a,b){var c;for(c=0;c<a.length&&a[c].id!=b;c++);if(c==a.length)return 0;return c+1}function p(a){if(a==1)return Lb;if(a=r(a,0))return wc(a)}function Ac(a,b){var c=yc(a,!0);b.a={id:a,x:0,y:0,B:!1,children:[]};for(var d=32767,e=32767,g=0;g<c.length;g++)if(c[g]!=1){var i={id:c[g],top:0,left:0,width:0,height:0};if(b!=K){var h=r(i,1),f=r(i,2);d>h&&(d=h);e>f&&(e=f)}b.a.children.push(i)}if(d!=32767)b.a.x=d;if(e!=32767)b.a.y=e;if(b!=K)b.a.B=!0}
function gc(){for($b!=k&&$b.P();F.length;)Bc(F.pop());Gb()}
function hd(a,b){var c;a:if(c=desktop.offset(),b>=c.top&&b<c.top+ea&&a>=c.left&&a<c.left+desktop.width())c={id:1,c:k};else{for(c=0;c<P.length;c++){var d=P[c].V(a,b);if(d!=k){c=d;break a}}c={id:0,c:k}}d=0;if(c.c!=k)d=c.c.l;if(c.id==3&&(d==14||d==10))c.id=c.c.a.id;else switch(d){case 9:c.id=-1;break;case 11:c.id=-2;break;case 12:c.id=-3;break;case 13:c.id=-4;break;default:switch(c.id){case 0:c.id=-5;break;case 1:c.id=-6;break;case 2:c.id=-7;break;case 3:c.id=-8;break;case 4:c.id=-9;break;case 5:c.id=
-10;break;case 6:c.id=-11;break;default:c.id=-12}}return c}function Fc(a){var b=desktop.offset();a.e-=b.top;a.d-=b.left};function ia(a){a=mb(3,a);if(!(a.length<2)){if(a.length==2)return ia((a.charCodeAt(0)&255)<<8|a.charCodeAt(1)&255);var b;a=new Aa(a);var c=a.f(3),d,e;Ba&&a.f(2);e=a.f(1)?a.f(10):a.f(6);if((d=a.f(1)?a.f(10):a.f(6))&&e)switch(b=new Ca(d,e,d+15>>3&65534),c){case 0:c=b.J>>4;d=b.J&15;for(var g=0,i=0;i<b.Q;i++){for(var h=0;h<c;h++)e=ub(a),a.seek(2,a.n),e>>>=16-a.q,b.data[g++]=e>>8&255,b.data[g++]=e&255;d&&(e=a.f(d),e<<=16-d,b.data[g++]=e>>8&255,b.data[g++]=e&255)}break;case 1:ld(md,nd,od,b,a);break;case 2:ld(pd,
qd,rd,b,a);break;case 3:c=Array(17);for(g=0;(d=sd[g++])!=255;){for(e=a.f(d);(d=sd[g++])!=255;)c[sd[g++]]=e%d,e=e/d|0;c[sd[g++]]=e}c[16]=0;for(e=16;e>0;e--)for(d=e;d<=16;d++)c[d]>=c[e-1]&&c[d]++;for(e=16;e>=0;e--)if(c[e]==16){c[e]=255;break}g=Array(17);i=Array(17);d=a.f(2)+1;for(e=h=0;e<15;e++){if(e)for(;!a.f(1);)d++;i[e]=d;g[e]=h;h+=1<<16-d}for(g[15]=h;h&1<<16-d;)d++;g[16]=h|1<<16-d;i[15]=d;i[16]=d;ld(g,i,c,b,a)}return b}}
function xb(a,b){for(var c=a.width(),d=a.height(),e=a.get(0).getContext("2d"),g=e.getImageData(0,0,c,d),i=0;i<d;i++)for(var h=i*g.width*4,f=0;f<c;f++){var j=(b>>4*(f&3)&15)*3;g.data[h++]=x[j++];g.data[h++]=x[j++];g.data[h++]=x[j++];g.data[h++]=255}e.putImageData(g,0,0)}
function ja(a,b,c){var d=b.top,e=b.left,g=e+b.width;b=d+b.height;if(d<a.top)d=a.top;if(e<a.left)e=a.left;b>a.top+a.height&&(b=a.top+a.height);g>a.left+a.width&&(g=a.left+a.width);if(g<=e||b<=d)d=b=e=g=0;c.top=d;c.left=e;c.width=g-e;c.height=b-d;return c.height!=0}
var md=[0,8192,16384,20480,24576,28672,32768,36864,40960,45056,49152,53248,55296,57344,59392,61440,63488],nd=[3,3,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5],od=[0,15,3,5,6,7,8,9,10,12,255,1,2,4,11,13,14],pd=[0,16384,32768,49152,51200,53248,55296,57344,59392,61440,62464,62976,63488,64E3,64512,65024,65280],qd=[2,2,2,5,5,5,5,5,5,6,7,7,7,7,7,8,8],rd=[255,0,15,1,3,7,14,12,8,6,2,4,9,13,11,10,5],sd=[8,15,2,255,0,4,255,1,7,9,8,255,3,4,255,4,10,7,10,11,6,255,5,6,6,11,255,7,3,255,9,4,3,14,255,12,2,255,13,1,255,15,255];
function ld(a,b,c,d,e){var g;Z=td=0;g=d.J&3?e.f(5):e.f(4)<<1;var i=0,h=d.J&15;h&&(h>>=2,i=h&1,h=2-(h>>1));for(var f=0,j=0;j<d.Q;j++){for(var q=0;q<d.J>>3;q++){var o=ud(a,b,c,e)<<4;d.data[f++]=ud(a,b,c,e)|o}i&&(d.data[f]=ud(a,b,c,e)<<4);f+=h}if(q=d.J&3){f=d.r-h;var v=0;for(j=h=0;j<d.Q;j++)g&1?(v<q&&(o=ud(a,b,c,e)<<4,h|=o>>>v,v+=4),v-=q,o=h,h<<=q,h&=255):(o=e.f(q),o<<=8-q),i&&(o>>>=4),d.data[f]|=o&255,f+=d.r}if(g&8)for(j=f=0;j<d.Q;j++)if(o=0,g&2)for(q=0;q<d.r;q++)d.data[f]^=o,o=d.data[f++];else for(q=
0;q<d.r;q++)h=d.data[f]^o,h^=h>>>4&15,d.data[f++]=h,o=h<<4&255;if(g&4){a=d.r*4;g&2&&(a*=2);f=0;g=a;for(b=0;b<d.Q*d.r-a;b++)d.data[g++]^=d.data[f++]}}var td=0,Z=0;
function ud(a,b,c,d){if(td)return td--,Z=Z<<8&65280|Z>>8,Z&255;var e=ub(d);e>>>=16-d.q;e&=65535;var g;for(g=0;g<16;g++)if(a[g+1]>e)break;d.q+=b[g];d.q&16&&(d.q&=15,d.seek(2,d.n));a=c[g];if(a==255)return d.f(1)||(Z&=255,Z|=Z<<8),td=d.f(3),td<3&&(td<<=4,td|=d.f(4),td<8&&(td<<=8,td|=d.f(8))),td-=2,Z=Z<<8&65280|Z>>8,Z&255;else Z<<=8,Z|=a,Z&=65535;return a};function Na(a,b,c,d){var e={id:b},g=$(document.createElement("tr"));if(a[0]=="-"){var i=$(document.createElement("td"));i.attr("colspan","2");i.addClass("divider");i.append(document.createElement("hr"))}else g.addClass("menuitem"),i=$(document.createElement("td")),i.html(ga(a)),g.append(i),i=$(document.createElement("td")),c!=""&&(i.addClass("shortcut"),vd.push({key:c,id:b}),i.text(c));g.append(i);e.b=g;e.enabled=d;e.enabled||e.b.addClass("disabled");A.body.append(e.b);A.w.push(e)}
function Oa(a){for(var b=$(a.target);b.data("refCon")==k;)b=b.parent();b.addClass("active");var c=b.data("refCon");desktop.append(c.p);a=b.position();c.p.css("top",a.top+ea+"px");c.p.css("left",a.left+"px");var d=-1;$(document).mousemove(function(a){var g=Pa.offset();if(a.pageX>=g.left&&a.pageY>g.top&&a.pageX<g.left+Pa.width()&&a.pageY<g.top+Pa.height())for(var i=0;i<Qa.length;i++){if(g=Qa[i].b.offset(),a.pageX>=g.left&&a.pageX<g.left+Qa[i].b.outerWidth()){c.p.remove();b.removeClass("active");b=Qa[i].b;
b.addClass("active");c=b.data("refCon");desktop.append(c.p);g=b.position();c.p.css("top",g.top+ea+"px");c.p.css("left",g.left+"px");break}}else if(g=c.p.offset(),a.pageX>=g.left&&a.pageY>=g.top&&a.pageX<g.left+c.p.outerWidth()&&a.pageY<g.top+c.p.outerHeight())for(i=0;i<c.w.length;i++){var h=c.w[i].b;h.hasClass("menuitem")&&c.w[i].enabled&&(g=h.offset(),a.pageY>=g.top&&a.pageY<g.top+h.outerHeight()?(d=i,h.addClass("active")):h.removeClass("active"))}else{for(i=0;i<c.w.length;i++)c.w[i].b.removeClass("active");
d=-1}});$(document).mouseup(function(){$(document).unbind("mousemove");$(document).unbind("mouseup");c.p.remove();b.removeClass("active");d!=-1&&Pc(c.w[d].id)})}var Pa,Qa=[],vd=[],A=k;$("body").keydown(function(a){if(a.target.type=="text")return!0;if(!a.altKey)return!0;if(B)return!0;for(var b=0;b<vd.length;b++)if(vd[b].key.charCodeAt(0)==a.which){a=vd[b].id;for(b=0;b<Qa.length;b++)for(var c=0;c<Qa[b].w.length;c++)Qa[b].w[c].id==a&&Qa[b].w[c].enabled&&wd(Qa[b],a);return!1}return!0});
function wd(a,b){a.b.addClass("active");setTimeout(function(){a.b.removeClass("active");Pc(b)},200)};function jb(a,b,c,d,e,g,i,h,f){var j=this;this.I=k;this.h=[];this.X=c;this.W=b;this.H=d;this.G=e;this.c=$(document.createElement("div"));this.c.addClass(a);if(a=="document"||a=="info"||a=="noGrowDoc"||a=="zoomDoc"||a=="rDoc4")b="<span></span>",this.title=$(document.createElement("div")),this.title.addClass("title"),this.title.mousedown(function(a){B||xd(a.pageX,a.pageY,j);return!1}),this.W&&(b='<div class="close"></div>'+b),this.X&&(b+='<div class="resize"></div>'),this.title.html(b),this.W&&(b=this.title.children("div.close"),
b.mousedown(ba(!1)),b.click(function(a){B||fatal(a);return!1})),this.X&&(b=this.title.children("div.resize"),b.mousedown(ba(!1)),b.click(function(){if(!B){var a=j.c.position();a={x:a.left,y:a.top};a.Ka=j.c.width();a.d=j.c.height();j.I!=k?(j.c.css("left",j.I.x+"px"),j.c.css("top",j.I.y+"px"),j.resize(j.I.Ka,j.I.d)):(j.c.css("left","0px"),j.c.css("top",ea+"px"),j.resize(desktop.width(),desktop.height()-ea));j.I=a}return!1})),this.c.append(this.title);this.port=$(document.createElement("canvas"));this.port.mousedown(function(a){if(!B)switch(kb(j),
j.l){case 9:xd(a.pageX,a.pageY,j);break;case 10:case 14:var b=yd(a.pageX,a.pageY,j),c=!1;b&&!r(b,3)&&(c=!0);Yc(b,j,a,c);break;case 12:b=yd(a.pageX,a.pageY,j);b==1?Yc(b,j,a,!1):xd(a.pageX,a.pageY,j);break;case 13:Yc(r(1,0),j,a,!1)}return!1});this.port.attr("width",h);this.port.attr("height",f);this.c.append(this.port);this.top=i;this.height=f;this.left=g;this.width=h;a=="document"||a=="noGrowDoc"||a=="zoomDoc"||a=="rDoc4"?(this.top-=Sa+Ra,this.height+=Sa,this.left-=Ra):a=="info"?(this.top-=Ta+Ra,this.height+=
Ta,this.left-=Ra):a=="alert"?(this.top-=Ua*2,this.left-=Ua*2,this.width+=Ua,this.height+=Ua):(this.top-=Ra,this.left-=Ra);this.H&&(this.width+=Va);this.G&&(this.height+=Wa);this.c.css("top",this.top+"px");this.c.css("left",this.left+"px");this.c.css("width",this.width+"px");this.c.css("height",this.height+"px");desktop.append(this.c);(this.H||this.G)&&zd(this)}l=jb.prototype;l.show=function(a){this.Na=a;this.c.show();Zc(this)};l.hide=function(){this.c.hide()};
function Mb(a,b){if(a.title!=k){var c=a.title.children("span");c.html("");if(b=="")c.hide();else{var d=a.c.css("display")=="none";a.c.show();c.css({position:"absolute",visibility:"hidden",display:"block"});var e=a.port.width();a.W&&(e-=30);a.X&&(e-=30);for(var g=0;g<b.length;g++)if(c.append(b.substring(g,g+1)),c.width()>e){c.html(b.substring(0,g-1));break}c.css({position:"",visibility:"",display:""});d&&a.c.hide()}}}l.addClass=function(a){this.c.addClass(a)};l.removeClass=function(a){this.c.removeClass(a)};
l.add=function(a){var b=this.port.position().top,c=parseInt(a.b.css("top"),10);a.b.css("top",c+b+"px");this.c.append(a.b);a.c=this;this.h.push(a);this.c.css("display")!="none"&&a.j()};l.remove=function(a){var b=this.h.indexOf(a);b!=-1&&this.h.splice(b,1);a.b.remove()};l.find=function(a){for(var b=0;b<this.h.length;b++)if(this.h[b].o==a)return this.h[b]};function Kc(a){for(var b=0;b<a.h.length;b++)a.h[b].hide()}function Zc(a){for(var b=0;b<a.h.length;b++)a.h[b].o!=255&&a.h[b].show()}
function Lc(a){for(var b=0;b<a.h.length;b++)a.h[b].o==255&&a.h[b].show()}l.close=function(){this.c.remove()};function gd(a,b){var c=a.port.offset();b.d-=c.left+1;b.e-=c.top+2;a.a&&(b.d+=a.a.x,b.e+=a.a.y)}function Ec(a,b){var c=a.port.offset();b.d+=c.left+1;b.e+=c.top+2;a.a&&(b.d-=a.a.x,b.e-=a.a.y)}
function zd(a){if(a.G){a.u=$(document.createElement("div"));a.u.addClass("hscroll");a.u.css("top",a.height-Wa+"px");a.u.css("width",a.width-32+"px");a.u.mousedown(function(){fatal("scroll")});var b=$(document.createElement("div"));b.addClass("leftarrow");b.mousedown(function(){fatal("scroll")});a.u.append(b);a.M=$(document.createElement("div"));a.M.addClass("rightarrow");a.M.css("left",a.width-Xa-32+"px");a.M.mousedown(function(){fatal("scroll")});a.u.append(a.M);a.s=$(document.createElement("div"));
a.s.addClass("slider");a.s.mousedown(function(){fatal("drag")});a.u.append(a.s);a.c.append(a.u)}if(a.H)a.v=$(document.createElement("div")),a.v.addClass("vscroll"),a.v.css("left",a.width-Va+"px"),a.v.css("height",a.height-24-Sa+"px"),a.v.mousedown(function(){fatal("scroll")}),b=$(document.createElement("div")),b.addClass("uparrow"),b.mousedown(function(){fatal("scroll")}),a.v.append(b),a.L=$(document.createElement("div")),a.L.addClass("downarrow"),a.L.css("top",a.height-24-24-Sa+"px"),a.L.mousedown(function(){fatal("scroll")}),
a.v.append(a.L),a.m=$(document.createElement("div")),a.m.addClass("slider"),a.m.mousedown(function(){fatal("drag")}),a.v.append(a.m),a.c.append(a.v);a.D=$(document.createElement("div"));a.D.addClass("grow");a.D.css("top",a.height-24+"px");a.D.css("left",a.width-32+"px");a.D.mousedown(function(b){if(B)return!1;kb(a);var d=$(document.createElement("div"));d.addClass("resizeProxy");desktop.append(d);var e=a.c.position();d.css("top",e.top+"px");d.css("left",e.left+"px");var g=a.c.width(),i=a.c.height();
d.css("width",g+"px");d.css("height",i+"px");var h=b.pageX,f=b.pageY;$(document).mousemove(function(a){var b=g+(a.pageX-h),c=i+(a.pageY-f);if(b>100)g=b,d.css("width",g+"px"),h=a.pageX;if(c>100)i=c,d.css("height",i+"px"),f=a.pageY});$(document).mouseup(function(){$(document).unbind("mousemove");$(document).unbind("mouseup");d.remove();a.resize(g,i)});return!1});a.c.append(a.D)}
l.resize=function(a,b){var c=this.width-this.port.width(),d=this.height-this.port.height();this.width=a;this.height=b;this.c.css("width",a+"px");this.c.css("height",b+"px");this.G&&(this.u.css("top",b-Wa+"px"),this.u.css("width",a-32+"px"),this.M.css("left",a-Xa-32+"px"));this.H&&(this.v.css("left",a-Va+"px"),this.v.css("height",b-24-Sa+"px"),this.L.css("top",b-24-24-Sa+"px"));this.D.css("top",b-24+"px");this.D.css("left",a-32+"px");this.a?(this.port.attr("width",a-c),this.port.attr("height",b-d),
this.a.B=!0,Ub(this)):(this.port.css("width",a-c),this.port.css("height",b-d),Vb=this.port.get(0).scrollHeight,Ic())};
function Jc(a,b){if(a.l==11){a.m.data("min",b.top);a.m.data("max",b.bottom);var c=a.port.scrollTop(),d=a.m.data("min"),e=a.m.data("max");if(d<e){var g=c-d;c+=a.port.height();g=g*(a.height-Sa-24-22-24)/(e-d)|0;d=c*(a.height-Sa-24-22-24-2)/(e-d)|0;a.m.css("top",g+22+"px");a.m.css("height",d-g+"px")}else a.m.css("top","22px"),a.m.css("height",a.height-24-Sa-24+"px")}else{if(b.left>a.a.x)b.left=a.a.x;if(b.right<a.a.x+a.port.width())b.right=a.a.x+a.port.width();if(b.top>a.a.y)b.top=a.a.y;if(b.bottom<a.a.y+
a.port.height())b.bottom=a.a.y+a.port.height();a.G&&(a.s.data("min",b.left),a.s.data("max",b.right));a.H&&(a.m.data("min",b.top),a.m.data("max",b.bottom));a.G&&(d=a.s.data("min"),e=a.s.data("max"),d<e?(c=a.a.x-d,g=a.port.width(),c=c*(a.port.width()-32-Xa)/(e-d)|0,d=g*(a.port.width()-32-Xa-2)/(e-d)|0,a.s.css("left",c+32+"px"),a.s.css("width",d+"px")):(a.s.css("left","32px"),a.s.css("width",a.port.width()-32-Xa+"px")));a.H&&(d=a.m.data("min"),e=a.m.data("max"),d<e?(c=a.a.y-d,g=a.port.height(),c=c*(a.port.height()-
22-24)/(e-d)|0,d=g*(a.port.height()-22-24-2)/(e-d)|0,a.m.css("top",c+22+"px"),a.m.css("height",d+"px")):(a.m.css("top","22px"),a.m.css("height",a.port.height()-22-24+"px")))}}l.V=function(a,b){var c=this.c.offset();if(a>=c.left&&a<c.left+this.c.width()&&b>=c.top&&b<c.top+this.c.height()){c=this.port.offset();if(a>=c.left&&a<c.left+this.port.width()&&b>=c.top&&b<c.top+this.port.height())return{id:3,c:this};return{id:4,c:this}}};
function Ad(a){var b=a.port.get(0).getContext("2d"),c=a.port.width();a=a.port.height();c=b.getImageData(0,0,c,a);for(a=0;a<c.height;a++)for(var d=a*c.width*4,e=0;e<c.width;e++)c.data[d++]^=255,c.data[d++]^=255,c.data[d++]^=255,c.data[d++]=255;b.putImageData(c,0,0)}l.param=function(a){for(var b=0;b<this.h.length;b++)if(this.h[b].Y){var c=this.h[b].Y(),d;do if(d=c.indexOf("^"),d>=0){var e=c.substr(0,d);e+=a[parseInt(c.substr(d+1,1),10)];e+=c.substr(d+2);this.h[b].U(e);c=e}while(d>=0)}};
l.getItem=function(a){for(var b=0;b<this.h.length;b++)if(this.h[b].o==a)return this.h[b]};function pc(){for(var a=[],b=0;b<P.length;b++)P[b].l==14?a.push(P[b]):P[b].hide();for(b in a)Tb(a[b])}function Q(a){for(var b=0;b<P.length;b++)if(P[b]==a){a.close();P.splice(b,1);break}P.length&&kb(P[0])}
function Tb(a){if(a!=k){var b=a.a.id;if(a.l==10)a.a={},Mb(a,"");else{var c={e:0,d:0},d={e:a.port.height(),d:a.port.width()};Ec(a,c);Ec(a,d);a.a={};Q(a);return{b:b,top:c.e,left:c.d,width:d.d-c.d,height:d.e-c.e}}}}function kb(a){if(P[0]!=a){P[0]!=k&&P[0].c.removeClass("active");for(var b=0;b<P.length;b++)P[b]==a&&P.splice(b,1);P.unshift(a)}a.c.addClass("active")}function $a(a,b,c,d){a=new jb("alert",!1,!1,!1,!1,a,b,c,d);a.l=2;a.hide();kb(a);return a}var P=[];
function xd(a,b,c){var d=a,e=b;kb(c);$(document).mousemove(function(a){var b=c.c.position();c.c.css("top",b.top+(a.pageY-e)+"px");c.c.css("left",b.left+(a.pageX-d)+"px");d=a.pageX;e=a.pageY});$(document).mouseup(function(a){$(document).unbind("mousemove");$(document).unbind("mouseup");var b=c.c.position();c.c.css("top",b.top+(a.pageY-e)+"px");c.c.css("left",b.left+(a.pageX-d)+"px")})}
function yd(a,b,c){a={d:a,e:b};var d=0;b=c.a.children.length;for(gd(c,a);b>0&&d==0;){b--;d=a;var e=c.a.children[b],g=0,i;if(i=!r(e.id,4))i=d.d>=e.left&&d.e>=e.top&&d.d<e.left+e.width&d.e<e.top+e.height?!0:!1;if(i)if(i=k,i=ia(e.id*2)){if(i.V(d.d-e.left,d.e-e.top))g=e.id}else g=e.id;d=g}return d};function kc(a,b,c,d){Y.unshift({fa:a,F:b,target:c,ga:d.d,ha:d.e,state:new Bd,k:[],i:[]});return ic(!0)}function ic(a){for(;Y.length;)if(Cd(a))return!0;return!1}var Y=[];function Bd(){this.stack=Array(128);this.A=128}Bd.prototype.push=function(a){this.stack[--this.A]=Dd(a)};Bd.prototype.pop=function(){return this.stack[this.A++]};function Ed(a,b){return a.stack[a.A+b]}Bd.prototype.clear=function(){this.A=128};Bd.prototype.size=function(){return 128-this.A};
function Dd(a){a<0&&(a=(-a^65535)+1);return a&65535}
function Cd(a){var b=!1;if(Y[0].za||a){Y[0].za=!1;if(b=a?Fd(0):Gd())return Y[0].za=!0;b=!0;Y[0].xa=0}if(Y[0].ya||b){Y[0].ya=!1;var c=[r(1,0)].concat(yc(r(1,0),!1));for(a=Y[0].xa;a<c.length;a++){if(b=b?Fd(c[a]):Gd())return Y[0].ya=!0,Y[0].xa=a,!0;b=!0}}var d;if(Y[0].Z&&(Y[0].Z=!1,Gd()))return Y[0].Z=!0;do{for(a=b=0;a<Y[0].k.length;a++)if(b<Y[0].k[a].t)b=Y[0].k[a].t,d=a;if(b&&(Y[0].k[d].t=0,Fd(Y[0].k[d].va)))return Y[0].Z=!0}while(b);Y.shift();return!1}
function Fd(a){if(a=mb(1,a))return Y[0].i[0]=new Aa(a),Hd();return!1}function Gd(){var a=Hd();if(a)return a;Y[0].i.shift();if(Y[0].i.length)return Gd()}var Id;
function Hd(){var a,b,c,d,e,g,i,h;d=Y[0].i[0];for(var f=Y[0].state;!(d.g>=d.length);)if(a=u(d),a&128)switch(a){case 128:b=f.pop();c=f.pop();f.push(r(b,c));break;case 129:b=f.pop();c=f.pop();a=X(f.pop());Wb(b,c,a);break;case 130:b=f.pop();c=f.pop();a=f.pop()!=0;f.push(Jd(b,c,a));break;case 131:f.push(Y[0].fa);break;case 132:f.push(Y[0].F);break;case 133:f.push(Y[0].target);break;case 134:f.push(Y[0].ga);break;case 135:f.push(Y[0].ha);break;case 136:f.push(u(d));break;case 137:f.push(y(d));break;case 138:c=
f.pop();f.push(Pb[c]);break;case 139:c=f.pop();a=X(f.pop());Pb[c]=a;R=!0;break;case 140:a=f.pop();f.push(Math.round((a-1)*Math.random()));break;case 141:a=Ed(f,0);f.push(a);break;case 142:c=f.pop();for(b=c-1;c--;)a=Ed(f,b),f.push(a);break;case 143:b=f.pop();h=f.pop();f.push(b);f.push(h);break;case 144:c=f.pop();h=Ed(f,c);b=Ed(f,0);f.stack[f.A+c]=Dd(b);f.stack[f.A+0]=Dd(h);break;case 145:f.pop();break;case 146:a=Ed(f,1);f.push(a);break;case 147:c=f.pop();a=Ed(f,c);f.push(a);break;case 148:h=f.pop();
b=f.pop();a=f.pop();f.push(h);f.push(a);f.push(b);break;case 149:i=X(f.pop());c=X(f.pop());i%=c;i<0&&(i+=c);e=g=0;for(a=1;a<c;a++)e+=i,e>=c&&(e-=c),e==g?(g++,e=g):(h=Ed(f,g),b=Ed(f,e),f.stack[f.A+g]=Dd(b),f.stack[f.A+e]=Dd(h));break;case 150:f.clear();break;case 151:f.push(f.size());break;case 152:b=f.pop();h=f.pop();f.push(h+b);break;case 153:b=f.pop();h=f.pop();f.push(h-b);break;case 154:b=f.pop();h=f.pop();f.push(h*b);break;case 155:b=f.pop();h=f.pop();f.push(h/b|0);break;case 156:b=f.pop();h=
f.pop();f.push(h%b);break;case 157:b=f.pop();h=f.pop();f.push(h%b);f.push(h/b|0);break;case 158:a=X(f.pop());a<0&&(a=-a);f.push(a);break;case 159:a=-X(f.pop());f.push(a);break;case 160:b=f.pop();h=f.pop();f.push(h&b);break;case 161:b=f.pop();h=f.pop();f.push(h|b);break;case 162:b=f.pop();h=f.pop();f.push(h^b);break;case 163:a=f.pop();f.push(a^65535);break;case 164:b=f.pop();h=f.pop();f.push(h&&b?65535:0);break;case 165:b=f.pop();h=f.pop();f.push(h||b?65535:0);break;case 166:b=f.pop();h=f.pop();f.push(!h!=
!b?65535:0);break;case 167:a=f.pop();f.push(a==0?65535:0);break;case 168:b=f.pop();h=f.pop();f.push(h>b?65535:0);break;case 169:b=f.pop();h=f.pop();f.push(h<b?65535:0);break;case 170:b=X(f.pop());h=X(f.pop());f.push(h>b?65535:0);break;case 171:b=X(f.pop());h=X(f.pop());f.push(h<b?65535:0);break;case 172:b=f.pop();h=f.pop();f.push(h==b?65535:0);break;case 173:b=W(f.pop());h=W(f.pop());f.push(h==b?1:0);break;case 174:b=W(f.pop());a=W(f.pop());f.push(a.toLowerCase().indexOf(b.toLowerCase())!=-1?1:0);
break;case 175:b=W(f.pop());a=W(f.pop());b=RegExp("\\b"+b+"\\b","i");f.push(b.test(a)?65535:0);break;case 176:a=X(y(d));d.seek(a,d.n);break;case 177:a=kd(u(d));d.seek(a,d.n);break;case 178:a=X(y(d));b=f.pop();b!=0&&d.seek(a,d.n);break;case 179:a=kd(u(d));b=f.pop();b!=0&&d.seek(a,d.n);break;case 180:a=X(y(d));b=f.pop();b==0&&d.seek(a,d.n);break;case 181:a=kd(u(d));b=f.pop();b==0&&d.seek(a,d.n);break;case 182:a=f.pop();b=f.pop();Y[0].k.push({t:a,va:b});break;case 183:b=f.pop();for(a=0;a<Y[0].k.length;a++)if(Y[0].k[a].va==
b)Y[0].k[a].t=0;break;case 184:b=f.pop();for(a=0;a<Y[0].k.length;a++)if(Y[0].k[a].t<=b)Y[0].k[a].t=0;break;case 185:c=f.pop();for(a=0;a<Y[0].k.length;a++)if(Y[0].k[a].t>=c)Y[0].k[a].t=0;break;case 186:b=f.pop();c=f.pop();for(a=0;a<Y[0].k.length;a++)if(Y[0].k[a].t>=c&&Y[0].k[a].t<=b)Y[0].k[a].t=0;break;case 187:a={state:new Bd,k:[],i:[k]};a.fa=f.pop();a.F=f.pop();a.target=f.pop();a.ga=f.pop();a.ha=f.pop();Y.unshift(a);if(Cd(!0))return!0;break;case 188:a=f.pop();Y[0].i.unshift(k);if(Fd(a))return!0;
Y[0].i.shift();d=Y[0].i[0];break;case 189:b=f.pop();G.push({id:2,val:b});break;case 190:a={};a.T=f.pop();a.K=f.pop();G.push({id:8,val:a});Wb(a.K,6,r(a.T,6));Wb(a.T,6,0);b=yc(a.T,!0);for(c=0;c<b.length;c++)Wb(b[c],0,a.K);break;case 191:G.push({id:14,val:Y[0].F});break;case 192:G.push({id:13});break;case 193:a=f.pop();H.push({id:3,val:[Y[0].target,Y[0].F,a]});break;case 194:H.push({id:2});break;case 195:a=f.pop();H.push({id:3,val:[Y[0].target,Y[0].F,a]});H.push({id:2});break;case 196:a=f.pop();H.push({id:2});
H.push({id:3,val:[Y[0].target,Y[0].F,a]});H.push({id:2});break;case 197:a=f.pop();H.push({id:1,val:a});break;case 198:f.push(2);break;case 199:b=f.pop();Hb.push({id:1,val:b});break;case 200:b=f.pop();Hb.push({id:2,val:b});break;case 201:Hb.push({id:3});break;case 202:a=new Date;f.push(a.getFullYear());f.push(a.getMonth()+1);f.push(a.getDate());f.push(a.getHours());f.push(a.getMinutes());f.push(a.getSeconds());break;case 203:a=new Date;f.push(a.getDay()+1);break;case 204:a=f.pop()!=0;b=f.pop();b=yc(b,
a);for(a=0;a<b.length;a++)f.push(b[a]);f.push(b.length);break;case 205:a=f.pop()!=0;b=f.pop();b=yc(b,a);f.push(b.length);break;case 206:f.push(86);break;case 207:f.push(3);break;case 208:f.push(1);break;case 209:b=f.pop();a=oa(b);f.push(a.width);f.push(a.height);break;case 210:b=f.pop();h=f.pop();f.push(Kd(b,h));break;case 211:a=b=f.pop();b=[];c=yc(r(a,0),1);for(h=0;h<c.length;h++)a<c[h]&&Kd(c[h],a)>=40&&b.push(c[h]);for(;b.length;)Wb(b.pop(),0,a);break;case 212:b=f.pop();a=yc(b,1);b=r(b,0);for(c=
0;c<a.length;c++)Wb(a[c],0,b);break;case 213:return d=f.pop(),Nc(d,Y[0].F,Y[0].target),!0;case 214:Mc(f.pop());break;case 215:E=3;break;case 216:E=2;break;case 217:return d=f.pop(),setTimeout(S,d/60*1E3),!0;case 218:return ec(!1),Kc(J),Lc(J),B=!0;case 219:mc();break;case 220:if(oc(!0))return!0;break;case 221:if(nc())return!0;break;case 222:if(ec(!0))return!0;break;case 223:return d=f.pop(),Ad(K),setTimeout(Ld,d/60*1E3),!0;case 224:f.pop();break;case 225:f.pop();break;case 226:b=f.pop();h=f.pop();
h*=b;a=f.pop();h/=a;f.push(h|0);break;case 227:b=f.pop();a=k;if(a=r(1,0)==b?K:wc(b))tc(b),mc(),Ub(a);break;case 228:f.push(0);break;case 229:break;case 230:f.push(Id);break;case 231:c=f.pop();b=1;for(a=Id=0;a<c;a++)Id+=b,Id^=b,b^=Id,Id^=b;break;default:fatal("Unknown function:"+a.toString(16))}else f.push(a);return!1}function Ld(){Ad(K);S()}function Jd(a,b,c){var d=0;a=yc(a,c);for(c=0;c<a.length;c++)d+=r(a[c],b);return d}
function Kd(a,b){if(r(a,0)!=r(b,0))return 0;var c=oa(a),d=oa(b);if(ja(d,c,d))return d.width*d.height*100/(c.width*c.height)|0;return 0};function C(a,b,c,d){switch(c&255){case 2:return new Md(a,b,d);case 10:return new Nd(a,b,d);case 15:return new Od(a,b,d);case 17:return new Pd(a,b,d);case 22:return new Qd(a,b,d);case 23:return new Rd(a,b);case 24:return new Sd(a,b,d);case 25:return new Td(a,b,d);default:fatal("Unknown control:"+c.toString(16))}}
function Md(a,b,c){var d=this,e=$(document.createElement("canvas"));e.addClass("cbutton");e.css("left",a[0]+"px");e.css("top",a[1]+"px");e.attr("width",a[2]);e.attr("height",a[3]);e.mousedown(function(a){Xc(d,a);return!1});this.b=e;this.o=b;this.selected=!1;this.La=c[0];this.f=c[1];this.Ma=c[2]}l=Md.prototype;l.hide=function(){this.b.hide()};l.show=function(){this.b.show();this.j()};
l.j=function(){var a=this.b.get(0).getContext("2d"),b=this.b.width(),c=this.b.height(),d=a.getImageData(0,0,b,c),e=this.selected?this.Ma:this.f;if(e)for(var g=0;g<c;g++)for(var i=(g>>1)*this.La,h=g*d.width*4,f,j=0;j<b;j++)f=e.charCodeAt(i+(j>>2)),f=(f>>(j&2?0:4)&15)*3,d.data[h++]=x[f++],d.data[h++]=x[f++],d.data[h++]=x[f++],d.data[h++]=255;else for(g=0;g<c;g++){h=g*d.width*4;for(j=0;j<b;j++){f=this.selected?0:255;if(g<2||j<4||g>c-3||j>b-5)f=0;d.data[h++]=f;d.data[h++]=f;d.data[h++]=f;d.data[h++]=
255}}a.putImageData(d,0,0)};l.select=function(){this.selected=!0;this.j()};l.P=function(){this.selected=!1;this.j()};function Nd(a,b,c){var d=this,e=$(document.createElement("div"));e.addClass("button");e.css("left",a[0]+"px");e.css("top",a[1]+"px");e.css("width",a[2]+"px");e.css("height",a[3]+"px");e.css("line-height",a[3]+"px");e.html(c[0]);e.mousedown(function(a){Xc(d,a);return!1});this.b=e;this.o=b}Nd.prototype.hide=function(){this.b.hide()};Nd.prototype.show=function(){this.b.show()};
Nd.prototype.j=aa();function Od(a,b,c){this.b=$(document.createElement("div"));this.b.addClass("textblock");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.o=b;this.U(c[0])}l=Od.prototype;l.Y=function(){return this.b.html()};l.U=function(a){this.b.html(a)};l.hide=function(){this.b.hide()};l.show=function(){this.b.show()};l.j=aa();
function Pd(a,b,c){var d=$(document.createElement("input"));d.addClass("textinput");d.css("left",a[0]+"px");d.css("top",a[1]+"px");d.css("width",a[2]+"px");d.css("height",a[3]+"px");d.val(c[0]);d.mousedown(function(){d.focus();return!1});this.b=d;this.o=b}Pd.prototype.hide=function(){this.b.hide()};Pd.prototype.show=function(){this.b.show();this.b.focus()};Pd.prototype.j=aa();
function Qd(a,b,c){this.b=$(document.createElement("div"));this.b.addClass("textblock");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.o=b;this.U(c[0])}l=Qd.prototype;l.hide=function(){this.b.hide()};l.show=function(){this.b.show()};l.j=aa();l.Y=function(){return this.b.html()};
l.U=function(a){for(var b="",c=0;c<a.length;c++)a.charCodeAt(c)==1?(a.charCodeAt(c+1)==74&&this.b.css("text-align","center"),c+=2):b+=a.charCodeAt(c)==13?"<br />":a.charAt(c);this.b.html(b)};function Rd(a,b){this.b=$(document.createElement("div"));this.b.addClass("list");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.o=b}Rd.prototype.hide=function(){this.b.hide()};Rd.prototype.show=function(){this.b.show()};
Rd.prototype.j=aa();
function Sd(a,b,c){this.value=parseInt(c[0],10);this.o=b;this.min=parseInt(c[1],10);this.max=parseInt(c[2],10);this.width=a[2];b=$(document.createElement("div"));b.addClass("hscroll");b.css("left",a[0]+"px");b.css("top",a[1]+"px");b.css("width",a[2]+"px");b.css("height",a[3]+"px");this.b=b;c=$(document.createElement("div"));c.addClass("leftarrow");c.css("top","0px");c.css("left","0px");b.append(c);var d=$(document.createElement("div"));d.addClass("rightarrow");d.css("top","0px");d.css("left",a[2]-
Xa+"px");b.append(d);a=$(document.createElement("div"));a.addClass("slider");a.css("top","0px");a.css("left","50px");a.css("width","20px");b.append(a);this.Oa=a;b.mousedown(function(){fatal("mousedown")});c.mousedown(function(){fatal("left")});d.mousedown(function(){fatal("right")});a.mousedown(function(){fatal("slider")})}Sd.prototype.hide=function(){this.b.hide()};Sd.prototype.show=function(){this.b.show();this.j()};
Sd.prototype.j=function(){this.Oa.css("left",(this.value*(this.width-52)/(this.max-this.min)|0)+32+"px")};function jd(a,b){a.value=b;a.j()}function Td(a,b,c){var d=this,e=$(document.createElement("div"));e.addClass("sbutton");e.css("left",a[0]+"px");e.css("top",a[1]+"px");e.css("width",a[2]-2+"px");e.css("height",a[3]-2+"px");e.html(c[0]);e.mousedown(function(a){Xc(d,a);return!1});this.b=e;this.o=b}l=Td.prototype;l.hide=function(){this.b.hide()};l.show=function(){this.b.show()};l.select=function(){this.b.addClass("active")};
l.P=function(){this.b.removeClass("active")};l.j=aa();var Jb=!0,Ib=k,Oc="",Gc=k,Hc=k;
function W(a){if(Jb){if(a&32768)a=Oc;else{a=new Aa(mb(2,a));for(var b=!1,c="",d=y(a);d--;){var e=a.f(5);if(e>0&&e<27)e|=64,b&&(e|=32),b=!0,c+=String.fromCharCode(e);else switch(e){case 0:c+=" ";break;case 27:c+=b?".":",";b=!0;break;case 28:c+=b?"'":'"';b=!0;break;case 29:b=a.f(16);b&32768?(b^=65535,b=Ud(b)):b=W(b);b&&(c+=b);b=!0;break;case 30:c+=String.fromCharCode(a.f(8));b=!0;break;case 31:b=!b}}a=ga(c)}return a}if(a&32768)return Oc;a=new Aa(mb(2,a));d="";for(c=a.f(1)?a.f(15):a.f(7);c--;){b=ub(a);
b>>=16-a.q;b&=65535;for(e=0;e<Ib.length;e++)if(b<Ib.da[e])break;a.q+=Ib.ca[e];a.q&16&&(a.q&=15,a.seek(2,a.n));b=Ib.ea[e];b==1&&(b=a.f(7));b!=2?d+=String.fromCharCode(b):(a.f(1)?(b=a.f(15),b=W(b)):(b=a.f(8),b=Ud(b)),b&&(d+=b))}return ga(d)}function Ud(a){var b,c;b=a&8?Hc:Gc;if((a&3)==1)b=r(b,7),c=["he","she","it"][(b>>4&3)+1-1];else{c=W(b);if(c=="")throw"text failure";switch(a&3){case 2:c=Vd(0,b)+c;break;case 3:c=Vd(2,b)+c}}c.length&&a&4&&(c=c.substr(0,1).toUpperCase()+c.substr(1));return c}
function Vd(a,b){var c=r(b,7)>>a&3;if(c)return["the ","a ","an "][c-1];return""};function mb(a,b){if(b>=yb[a].O)return"";var c,d;yb[a].ia?(c=yb[a].ja[b],d=yb[a].ka[b]):(c=yb[a].Da,d=b*c);if(!c)return"";return yb[a].data.substring(d,d+c)}var yb=[];var pb=!1,qb=!1;try{var Wd=document.createElement("audio").canPlayType("audio/wav");pb=Wd!=""&&Wd!="no"}catch(Xd){}function nb(a,b){this.data=Array(a);this.C=a;this.R=b}nb.prototype.play=function(){var a=$(document.createElement("audio"));$(document.body).append(a);a.attr("src","data:audio/x-wav;base64,"+Yd(this));var b=id();b==null&&(b=50);a.attr("volume",b/100);a.bind("ended",function(){a.remove()});a.get(0).play()};
function Yd(a){var b=Array(44+a.C);b[0]=82;b[1]=73;b[2]=70;b[3]=70;var c=36+a.C;b[4]=c&255;b[5]=c>>8&255;b[6]=c>>16&255;b[7]=c>>24&255;b[8]=87;b[9]=65;b[10]=86;b[11]=69;b[12]=102;b[13]=109;b[14]=116;b[15]=32;b[16]=16;b[17]=0;b[18]=0;b[19]=0;b[20]=1;b[21]=0;b[22]=1;b[23]=0;b[24]=a.R&255;b[25]=a.R>>8&255;b[26]=a.R>>16&255;b[27]=a.R>>24&255;b[28]=b[24];b[29]=b[25];b[30]=b[26];b[31]=b[27];b[32]=1;b[33]=0;b[34]=8;b[35]=0;b[36]=100;b[37]=97;b[38]=116;b[39]=97;b[40]=a.C&255;b[41]=a.C>>8&255;b[42]=a.C>>16&
255;b[43]=a.C>>24&255;for(c=0;c<a.C;c++)b[44+c]=a.data[c];a="";var d,e,g,i=0;do d=b[i++],e=b[i++],g=b[i++],c=d>>2,d=(d&3)<<4,e==k?e=g=64:g==k?(d|=e>>4,e=(e&15)<<2,g=64):(d|=e>>4,e=(e&15)<<2|g>>6,g&=63),a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g);
while(i<b.length);return a};var Zd=document.createElement("link");Zd.type="text/css";Zd.rel="stylesheet";Zd.href="gs.css";$("head").append(Zd);ca=$(document.createElement("img"));ca.attr("src","images/gs/start.png");ca.css("width","100%");ca.css("height","100%");desktop.append(ca);
(function(a){$.ajax({url:a,Sa:function(a){a.overrideMimeType("text/html; charset=x-user-defined")},complete:function(a){a=new Aa(a.responseText);var c=a.data.substring(a.g,a.g+4);a.g+=4;c!="2IMG"&&fatal("Not a valid 2mg file");a.seek(12,a.set);xa(a)!=1&&fatal("Not in ProDOS format");a.seek(20,a.set);c=xa(a)*512;var d=xa(a);a.seek(d,a.set);s=new Aa(w(a,c));delete a}})})(gamename);setTimeout(vb,10);
