var j=void 0;function aa(){return function(){}}function ba(a){return function(){return a}}var m,ca,da=15,ea=24,fa=2;function ga(a){for(var b="",c=0;c<a.length;c++)switch(a.charCodeAt(c)){case 13:b+="<br />";break;case 63368:b+="&#224;";break;case 63374:b+="&#233;";break;default:b+=a.charAt(c)}return b}function ha(a,b){var c={top:0,left:0,width:0,height:0},d;if(d=ia(a*2))return c.width=d.width,c.height=d.height,ja(c,b,c);return!1}function ka(){if(!n)return 3E3;return la[n]}
function ma(a){var b={top:0,left:0,width:0,height:0},c=p(a),d=0;c&&c.a&&(d=oa(c.a.children,a));if(d){d--;if(c.a.children[d].width==0||c.a.children[d].height==0)a=pa(a,c,!0),c.a.children[d].top=a.top,c.a.children[d].left=a.left,c.a.children[d].width=a.width,c.a.children[d].height=a.height;b.top=c.a.children[d].top;b.left=c.a.children[d].left;b.width=c.a.children[d].width;b.height=c.a.children[d].height}else(c=ia(a*2))?(b.top=q(a,2),b.left=q(a,1),b.width=c.width,b.height=c.height):(b.top=0,b.left=0,
b.width=0,b.height=0);return b}function qa(a){a=ia(a*2);var b=a.width,c=a.height,d=$(document.createElement("canvas"));d.addClass("proxy");d.attr("width",b);d.attr("height",c);desktop.append(d);a.i(d,0,0);return d}function ra(a){a=sa(a);return ta(a.ya,a.left*2,a.top*2,(a.right-a.left)*2,(a.bottom-a.top)*2)};function ua(a){a[0]=="3"&&a[1]=="/"&&(a=a.substring(2));return va(a.toLowerCase(),2)}var s=j;
function va(a,b){s.seek(b*512+2,s.set);var c=t(s),d=u(s);(d&240)!=240&&(d&240)!=224&&fatal("Corrupt directory");s.seek(30,s.n);var e=u(s),g=u(s),i=u(s),h=1,f=0;d=a.indexOf("/");var k="";d>0&&(k=a.substring(d+1),a=a.substring(0,d));for(;f<i;){s.seek(b*512+e*h+4,s.set);d=u(s);if(d!=0){if(v(s,d&15).toLowerCase()==a){if((d&240)==208)return s.seek(16-(d&15),s.n),c=t(s),va(k,c);s.seek(b*512+e*h+21,s.set);c=t(s);s.seek(2,s.n);e=wa(s)&16777215;k=c;c=e;e="";switch(d&240){case 16:e=xa(k,c);break;case 32:e=
ya(k,c);break;case 48:d=k;k=c;c="";for(e=0;k>0;){s.seek(d*512+e,s.set);i=u(s);s.seek(d*512+e+256,s.set);i|=u(s)<<8;g=k;g>131072&&(g=131072);if(i)c+=ya(i,g);else for(i=0;i<g;i++)c+=String.fromCharCode(0);k-=g;e++}e=c}return new za(e)}f++}h++;h==g&&(h=0,b=c,s.seek(b*512+2,s.set),c=t(s))}return!1}function xa(a,b){s.seek(a*512,s.set);return v(s,b)}
function ya(a,b){for(var c="",d=0;b>0;){s.seek(a*512+d,s.set);var e=u(s);s.seek(a*512+d+256,s.set);e|=u(s)<<8;var g=b;g>512&&(g=512);if(e)c+=xa(e,g);else for(e=0;e<g;e++)c+=String.fromCharCode(0);b-=g;d++}return c};var x,Aa,Ba=!0;function Ca(a,b,c){this.width=a>>1;this.height=b*2;this.s=c;this.F=a;this.N=b;this.data=Array(b*c)}
Ca.prototype.i=function(a,b,c){if(!(this.width==0||this.height==0)){var d=a.get(0).getContext("2d"),e=0,g=0;b<0&&(e=-b,b=0);c<0&&(g=-c,c=0);var i=this.width,h=this.height;i+b>=a.width()&&(i=a.width()-b);h+c>=a.height()&&(h=a.height()-c);if(!(i==0||h==0)){a=d.getImageData(b,c,i,h);for(var f=g;f<h;f++)for(var k=(f>>1)*this.s,r=(f-g)*a.width*4,l,w=e;w<i;w++)l=this.data[k+(w>>2)],Aa&&(l=Aa[l]),(l=(l>>(w&2?0:4)&15)*3)?(a.data[r++]=x[l++],a.data[r++]=x[l++],a.data[r++]=x[l++],a.data[r++]=255):r+=4;d.putImageData(a,
b,c)}}};Ca.prototype.T=function(a,b){var c=this.data[(b>>1)*this.s+(a>>2)];Aa&&(c=Aa[c]);return(c>>(a&2?0:4)&15)!=0};function Da(a,b,c,d){this.width=a;this.height=b;this.s=c;this.Y=d;this.data=Array(b*c)}
Da.prototype.i=function(a,b,c){if(!(this.width==0||this.height==0)){var d=a.get(0).getContext("2d"),e=this.width,g=this.height*2,i=0,h=0;b<0&&(i=-b,b=0);c<0&&(h=-c,c=0);e+b>=a.width()&&(e=a.width()-b);g+c>=a.height()&&(g=a.height()-c);if(!(e==0||g==0)){a=d.getImageData(b,c,e,g);for(var f=h;f<g;f++)for(var k=(f>>1)*this.s,r=(f-h)*a.width*4,l,w=i;w<e;w++)l=this.data[k+(w>>2)],l=(l>>6-(w&3)*2&3)*3,a.data[r++]=this.Y[l++],a.data[r++]=this.Y[l++],a.data[r++]=this.Y[l++],a.data[r++]=255;d.putImageData(a,
b,c)}}};function Ea(){var a=ua(Fa(8)),b=sa(6),c=b.right-b.left;b=b.bottom-b.top;a.seek(8,a.set);for(var d=[],e=0;e<4;e++)y(a),d.push(y(a)&255),d.push(y(a)&255),d.push(y(a)&255);var g=c+7>>2;c=new Da(c,b,g,d);for(e=0;e<g*b;e++)c.data[e]=u(a);return c};function Fa(a){z.seek(368+a*32,z.set);a=u(z);return v(z,a)}function Ga(){z.seek(496,z.set);var a=u(z);return v(z,a)}function sa(a){z.seek(a*10);a={};a.top=t(z);a.left=t(z);a.bottom=t(z);a.right=t(z);a.ya=t(z);return a}function Ha(){z.seek(1464,z.set);var a=u(z);return v(z,a)}function Ia(){z.seek(1008,z.set);var a=u(z);return ga(v(z,a))}var Ja=[0,80,208];function Ka(a){z.seek(1128+Ja[a],z.set);a=u(z);return v(z,a)}var z;function La(a){for(a={v:a,h:0};Ma(a););}
function Ma(a){var b=!1;if(a.v[a.h]=="."||a.v[a.h+1]==".")return!1;a.v[a.h++]==" "&&(b=!0);a.h++;for(var c="";a.v[a.h]!="\\";)c+=a.v[a.h++];a.h++;for(var d="",e=!0,g=0,i=!1;a.v[a.h]!="\r";)switch(a.v[a.h++]){case "*":d=a.v[a.h++];a.h++;break;case "B":c="<b>"+c+"</b>";break;case "C":a.h++;break;case "D":e=!1;break;case "H":g=a.v.charCodeAt(a.h++)&255;g|=(a.v.charCodeAt(a.h++)&255)<<8;break;case "I":c="<i>"+c+"</i>";break;case "N":break;case "U":break;case "V":i=!0;break;case "X":break;default:fatal("Unknown menu control code")}a.h++;
if(b)return Na(c,g,d,e),i&&Na("-",0,"",!1),!0;A={id:g};A.b=$(document.createElement("div"));c=="@"?A.b.addClass("apple"):A.b.html(c);A.b.data("refCon",A);A.b.mousedown(function(a){if(B)return!1;Oa(a);return!1});A.p=$(document.createElement("table"));A.p.addClass("menu");A.body=$(document.createElement("tbody"));A.p.append(A.body);A.u=[];Pa.append(A.b);Qa.push(A);return!0};var Ra=2,Sa=24,Ta=20,Ua=4,Va=32,Wa=24,Xa=34,Ya;
function Za(){var a=$a(10,36,620,354);a.add(C([240,318,120,22],1,10,["OK"]));a.add(C([10,18,600,146],2,32790,["\u0001J\u0001\0Apple IIGS ^0\r\u0001J\u0001\0Written by:\r\u0001J\u0001\0\u0001S\u0001\0Fred Allen\u0001S\0\0\r\r\u0001J\u0001\0Artwork by:\r^1\r\r\u0001J\u0001\0\u0001S\u0004\0MacVenture Team\u0001S\0\0"]));a.add(C([10,164,300,136],3,32790,["^2"]));a.add(C([310,164,300,136],4,32790,["^3"]));a.add(C([10,294,600,22],5,32790,["\u0001J\u0001\0WebVenture by Sean Kasun"]));a.param([Ia(),Ka(0),
Ka(1),Ka(2)]);return a}function ab(){var a=$a(80,80,480,200);a.add(C([214,150,50,30],1,10,["OK"]));a.add(C([100,80,280,22],2,24,[0,0,100]));a.add(C([20,30,440,30],3,15,["Sound Volume"]));return a}
function bb(a){var b=$a(92,146,456,108);b.add(C([24,68,120,22],1,10,["YES"]));b.add(C([168,68,120,22],2,10,["NO"]));b.add(C([312,68,120,22],3,10,["CANCEL"]));b.add(C([100,10,340,38],4,32790,["Save changes before ^0   "]));switch(a){case 0:b.param(["starting a new game?"]);break;case 1:b.param(["opening another game?"]);break;case 2:b.param(["quitting?"])}return b}
function cb(){var a=$a(50,70,520,228);a.add(C([12,8,298,30],4,22,["Load which game:"]));a.add(C([12,50,298,164],3,23,[]));a.add(C([320,158,190,24],1,10,["Open"]));a.add(C([320,194,190,24],2,10,["Cancel"]));return a}function db(){var a=$a(50,70,540,256);a.add(C([22,50,298,124],4,23,[]));a.add(C([22,182,298,30],5,22,["Save game as:"]));a.add(C([22,200,290,36],3,17,[""]));a.add(C([330,186,200,22],1,10,["Save"]));a.add(C([330,222,200,22],2,10,["Cancel"]));return a}
function eb(){var a;a=D.left;for(var b=D.top,c=0;c<D.P;c++){a+=D.za;b+=D.Aa;if(b>=388)b=D.top;if(a>=628)a=D.left}D.P++;a={top:b,left:a,width:D.width,height:D.height};a=ta(D.ya,a.left,a.top,a.width,a.height);a.l=14;return a}function fb(){var a=$a(10,352,620,40);a.add(C([5,8,30,24],1,10,["Print"]));a.add(C([272,8,32,24],2,10,["Quit"]));a.add(C([42,2,225,36],3,32790,["^0"]));a.param([Ha()]);return a}
function gb(){var a={};z.seek(70,z.set);a.bottom=t(z);a.left=t(z);a.width=t(z);a=C([a.left,a.bottom*2-20,a.width,20],5,17,[""]);a.b.css("text-align","center");return a}function hb(){var a=$a(140,136,430,128);a.add(C([14,56,122,26],1,10,["YES"]));a.add(C([260,56,152,26],2,10,["NO"]));a.add(C([14,92,398,26],3,10,["Yes, I'll use a saved game."]));a.add(C([14,10,398,38],4,15,["You have lost ... Would you\nlike to have another try?"]));return a}
function ib(){var a=$a(20,92,600,140);a.add(C([10,94,50,30],1,10,["OK"]));a.add(C([96,94,120,30],2,10,["CANCEL"]));a.add(C([10,10,580,36],3,22,["^0"]));a.add(C([10,56,580,28],4,17,[""]));return a}function ta(a,b,c,d,e){var g="dbox",i=!1,h=!1;a&32768&&(g="document");a&16&&(g="info");a&8192&&(g="alert");a&4096&&(i=!0);a&2048&&(h=!0);a=new jb(g,a&16384,a&256,i,h,b,c,d,e);a.hide();kb(a);return a};function lb(a){var b=mb(4,a);a=new za(b);var c=j;switch(b.charCodeAt(7)){case 0:c=0;var d=y(a);for(b=0;b<d;b++)y(a),c+=y(a),y(a),y(a);a.seek(8,a.set);b=y(a);c=new nb(c,b);var e=0;for(b=0;b<d;b++){a.seek(2+b*8,a.set);var g=y(a),i=y(a);a.seek(g,a.set);for(g=0;g<i;g++)c.data[e++]=u(a)}break;case 2:e=0;b=y(a);for(c=0;c<b;c++)y(a),e+=y(a)*2,y(a),y(a);a.seek(8,a.set);c=y(a);e=new nb(e,c);for(c=i=0;c<b;c++){a.seek(2+c*8,a.set);var h=y(a);g=y(a)*2;a.seek(h,a.set);for(h=0;h<g;h++)h&1?d>>=4:d=u(a),e.data[i++]=
ob[d&15]}c=e}if(c==j)return 0;pb&&!qb&&c.play();return c.B/c.O}var ob=[127,126,124,120,112,96,64,1,128,129,131,135,143,159,191,255];function za(a){this.set=0;this.n=1;this.end=2;this.data=a;this.length=a.length;this.q=this.g=0}function u(a){return a.data.charCodeAt(a.g++)&255}function y(a){var b=(a.data.charCodeAt(a.g++)&255)<<8;b|=a.data.charCodeAt(a.g++)&255;return b}function t(a){var b=a.data.charCodeAt(a.g++)&255;b|=(a.data.charCodeAt(a.g++)&255)<<8;return b}function sb(a){var b=(a.data.charCodeAt(a.g++)&255)<<16;b|=(a.data.charCodeAt(a.g++)&255)<<8;b|=a.data.charCodeAt(a.g++)&255;return b}
function tb(a){var b=(a.data.charCodeAt(a.g++)&255)<<24;b|=(a.data.charCodeAt(a.g++)&255)<<16;b|=(a.data.charCodeAt(a.g++)&255)<<8;b|=a.data.charCodeAt(a.g++)&255;return b}function wa(a){var b=a.data.charCodeAt(a.g++)&255;b|=(a.data.charCodeAt(a.g++)&255)<<8;b|=(a.data.charCodeAt(a.g++)&255)<<16;b|=(a.data.charCodeAt(a.g++)&255)<<24;return b}
function ub(a){var b=(a.data.charCodeAt(a.g)&255)<<24;b|=(a.data.charCodeAt(a.g+1)&255)<<16;b|=(a.data.charCodeAt(a.g+2)&255)<<8;b|=a.data.charCodeAt(a.g+3)&255;return b}za.prototype.seek=function(a,b){switch(b){case this.n:a+=this.g;break;case this.end:a+=this.length}this.g=a};function v(a,b){var c=a.g;a.g+=b;return a.data.substring(c,a.g)}za.prototype.f=function(a){var b=ub(this);b>>>=32-this.q-a;b&=(1<<a)-1;this.q+=a;this.q&16&&(this.q&=15,this.g+=2);return b};function vb(){if(s!=j){E=0;z=ua("3/RESOURCE.DAT");ca.remove();delete ca;var a=Fa(6),b=ua(a);b.seek(8,b.set);x=[];for(var c=0;c<16;c++)y(b),x.push(y(b)&255),x.push(y(b)&255),x.push(y(b)&255);a=new Ca(1280,200,160);for(c=0;c<32E3;c++)a.data[c]=u(b);b=new jb("plainDBox",!1,!1,!1,!1,0,0,640,400);b.hide();kb(b);wb=b;wb.show();xb(wb.port,0);a.i(wb.port,0,0);a=[3,1,2,0,5];for(b=0;b<5;b++){var d=Fa(a[b]);c=b;d=ua(d);var e={Oa:0,da:!1};d.seek(0,d.set);var g=d.length,i=tb(d),h=j;if(i&2147483648){i&=2147483647;
e.da=!0;d.seek(i,d.set);e.K=y(d);g=Array(16);h=Array(16);for(var f=0;f<15;f++)g[f]=y(d);for(f=0;f<16;f++)h[f]=u(d);e.fa=Array(e.K);e.ea=Array(e.K);var k=0,r=j;for(f=0;f<e.K;f++){if((f&63)==0){d.seek(i+(f>>6)*6+48,d.set);var l=sb(d);r=sb(d);k=l&7;d.seek(i+(l>>3),d.set)}e.fa[f]=r;l=tb(d)>>>16-k&65535;d.seek(-4,d.n);var w;for(w=0;w<16;w++)if(g[w]>l)break;l=h[w];k+=l&15;k&16&&(k&=15,d.seek(2,d.n));l>>=4;w=0;l&&(w=ub(d),l--,l==0?w=0:w>>>=32-l-k,w&=(1<<l)-1,w|=1<<l,k+=l,k&16&&(k&=15,d.seek(2,d.n)),r+=w);
e.ea[f]=w}h=i-4}else g-=4,h=g,e.Ba=i,e.K=g/i|0;d.seek(4,d.set);e.data=v(d,h);yb[c]=e}a={};z.seek(76,z.set);a.Ea=t(z);a.Ca=t(z);a.Ma=t(z);a.Da=t(z);t(z);a.Na=t(z);a.ja=[];for(b=0;b<24;b++)a.ja.push(u(z));a.ga=[];for(b=0;b<64;b++)a.ga.push(u(z));a.ha=[];for(b=0;b<64;b++)a.ha.push(t(z));a.ia=[];for(b=0;b<64;b++)a.ia.push(u(z));zb=a.Ea;Ab=a.Ca;Bb=a.Da;Cb=a.ga;Db=a.ha;Eb=a.ia;la=a.ja;D=sa(5);D.top*=2;D.left*=2;D.width=D.right*2-D.left;D.height=D.bottom*2-D.top;D.Aa=20;D.za=20;D.P=0;Fb=[];Gb();F=[];G=[];
Hb=[];H=[];I=Array(zb*2);var o;if(z.length!=1676){o={};z.seek(1676,z.set);o.length=t(z);o.ba=[];z.seek(1680,z.set);for(a=0;a<o.length;a++)o.ba.push(t(z));o.aa=[];z.seek(1868,z.set);for(a=0;a<o.length;a++)o.aa.push(u(z));o.ca=[];z.seek(1964,z.set);for(a=0;a<o.length;a++)o.ca.push(u(z))}o!=j&&(Ib=o,Jb=!1);o=[];z.seek(720,z.set);for(a=0;a<16;a++)o.push(t(z));x=[];for(a=0;a<16;a++)b=o[a]>>4&15,c=o[a]&15,x.push((o[a]>>8&15)*17),x.push(b*17),x.push(c*17);o=[];z.seek(752,z.set);for(a=0;a<256;a++)o.push(u(z));
Aa=o;z.seek(1092,z.set);Ya=t(z);J=ra(3);J.l=9;J.addClass("commands");o=[{name:"3/SHADOWGATE",start:49390,J:-3272},{name:"3/DEJAVU",start:49390,J:-3272},{name:"3/DEJAVUII",start:4014,J:66},{name:"3/UNINVITED",start:49390,J:-3272}];for(a=0;a<o.length;a++)if(b=ua(o[a].name)){for(c=0;c<9;c++)b.seek(o[a].start+c*11,b.set),d=t(b)*2,e=t(b)*2,i=t(b)*2-d,g=t(b)*2-e,h=u(b),f=t(b),f=f&15|f&61440,b.seek(o[a].start+115+c*4,b.set),l=t(b),b.seek(l+o[a].J),k=t(b),r=v(b,k*i),b.seek(o[a].start+151+c*4,b.set),l=t(b),
b.seek(l+o[a].J),t(b),l=v(b,k*i),J.add(C([e,d,g,i],h,f,[k,r,l]));break}K=ra(0);K.l=10;Kb=ra(1);Kb.l=11;L=$(document.createElement("div"));L.addClass("textEdit");o=Kb;a=L;b=o.port.attr("width");c=o.port.attr("height");o.port.remove();a.css("top","0px");a.css("left","0px");a.css("width",b+"px");a.css("height",c+"px");o.port=a;o.c.append(a);Lb=ra(4);Lb.l=12;Lb.a={id:0,x:0,y:0,children:[{id:1,top:0,left:0,width:0,height:0}]};M=ra(2);Mb(M,"Exits");M.l=13;M.addClass("exits");Pa=$(document.createElement("div"));
Pa.addClass("menubar");o=[">L File \\H\u0002\0\r LNew\\V*NnH\u0001\u0001\r LOpen...\\*OoH\u0002\u0001\r LSave\\*SsH\u0003\u0001\r LSave As...\\VH\u0004\u0001\r LQuit\\*QqH\u0005\u0001\r.",">L Edit \\H\u0003\0\r LUndo\\DV*ZzH\u00fa\0\r LCut\\D*XxH\u00fb\0\r LCopy\\D*CcH\u00fc\0\r LPaste\\DV*VvH\u00fd\0\r LClear\\DH\u00fe\0\r.",">L Special \\H\u0004\0\r LClean Up\\DH\u0006\u0001\r LMess Up\\DH\u0007\u0001\r."];z.seek(1024);a=v(z,48);La(a);for(a=0;a<o.length;a++)La(o[a]);A=Qa[0];Na("Adjust Volume...",
2304,"",!0);Mb(Kb,"Untitled");if(gameparts.length>1)Nb=gameparts[1],o=window.JSON.parse(window.localStorage.getItem(Nb).toString()),Ob=o.Z,Pb=o.$,L.html(o.text),Mb(Kb,Nb);else{o=ua(Ga());Ob=Array(Bb);Pb=Array(Ab);for(a=0;a<Bb;a++){Ob[a]=Array(zb);for(b=0;b<zb;b++)Ob[a][b]=y(o)}for(a=0;a<Ab;a++)Pb[a]=y(o)}Qb();Nb==""&&(N=!0,n=1,O.push(q(1,0)));setTimeout(Rb,500)}else setTimeout(vb,10)}function Qb(){for(var a,b,c=0;c<zb*2;c++)I[c]=0;for(c=zb-1;c;c--)a=Ob[0][c],(b=I[a*2])&&(I[c*2+1]=b),I[a*2]=c}
function Sb(){for(var a=[],b=0;b<P.length;b++)(P[b].l==10||P[b].l==14)&&a.push(P[b]);for(b in a)Tb(a[b]);D.P=0;G=[];Hb=[];H=[];Fb=[]}var I;function Rb(){Q(wb);delete wb;desktop.append(Pa);J.show();Lb.show();Ub(Lb);M.show();Kb.show();K.show();E=1;Vb=L.get(0).scrollHeight;L.scrollTop(Vb-Vb%da);Wb(q(1,0),6,1);R=!1;S()};var E=0,R=!1,Vb=0,F,O,n=j,N=!1,Xb,Yb,la,Fb,G,Hb,H,wb,Zb,K,J,Kb,Lb,M,L,zb,Ab,Bb,Eb,Db,Cb,D,Ob,Pb,$b,T,U,Nb="";function ac(){}var bc=!1,cc=!1,dc=!1,B=!1,V=j;function S(){if(E==4)window.location="index.html";else{bc||ec(!1);if(N||bc){bc=!1;if(fc()){B=bc=!0;return}B=!1;if(ec(!0))return;gc()}(E==2||E==3)&&hc()}}
function fc(){if(cc){cc=!1;if(ic(!1))return cc=!0;return!1}if(dc){dc=!1;if(ic(!1))return dc=!0;if(ec(!0))return!0}for(;O.length;){var a=O.shift();if((E==0||E==1)&&jc(a)){if(kc(n,a,T,U))return dc=!0;if(ec(!0))return!0}}if(n==1)R=!1;else if((E==0||E==1)&&kc(3,n,T,U))return cc=!0;return!1}
function jc(a){if(!lc(a))return!1;if(ka()>=2&&T>0&&!lc(T))return!1;if(n!=5)return!0;if(!(q(a,3)==0&&q(a,4)==0&&q(a,5)==0))return!1;if(q(1,0)!=T)return!0;var b={top:0,left:0,width:K.port.width(),height:K.port.height()};b.top-=q(a,2)+U.e;b.left-=q(a,1)+U.d;return ha(a,b)}function lc(a){for(var b=q(1,0);a!=0&&a!=1&&a!=b;)a=q(a,0);return a}function ec(a){mc();var b=nc();oc(a)&&(b=!0);return b}
function hc(){if(E==2){pc();var a=Ea();Zb=ra(6);Zb.show();a.i(Zb.port,0,0);qc();E=4}else if(E==3){gc();var b=hb();b.show(function(a){Q(b);switch(a){case 1:rc();break;case 2:E=4;S();break;case 3:sc()}})}}function qc(){var a=document.createElement("link");a.type="text/css";a.rel="stylesheet";a.href="print.css";a.media="print";$("head").append(a);a=fb();B=!0;var b=gb();Zb.add(b);b.b.focus();a.show(function(a){switch(a){case 1:b.b.blur();window.print();break;case 2:S()}})}
function mc(){for(;G.length;){for(var a,b=0,c=0;c<G.length;c++)if(G[c].id>b)b=G[c].id,a=c;b=G.splice(a,1)[0];switch(b.id){case 2:tc(b.val);break;case 3:uc(b.val);break;case 4:vc(b.val);break;case 7:a:{c=b.val;var d=!1;b=c.b;var e=Fb.indexOf(b);e!=-1&&Fb.splice(e,1);if(b==1)c.parent!=q(b,0)&&G.push({id:12}),(c.oa!=q(b,3)||c.na!=q(b,4))&&Ub(p(b));else if(c.parent!=q(b,0)||c.x!=q(b,1)||c.y!=q(b,2)){if(e=wc(c.parent)){d=e;if(d.a!=j&&(e=oa(d.a.children,b),e!=0))d.a.children.splice(e-1,1),d.a.C=!0,Ub(d);
d=!0}if(e=p(b)){d=e;if(d.a!=j){e=j;for(e=0;e<d.a.children.length&&b>d.a.children[e].id;e++);if(e==d.a.children.length||b!=d.a.children[e].id)d.a.children.splice(e,0,{id:b,top:0,left:0,width:0,height:0}),d.a.C=!0,Ub(d)}d=!0}}else(c.oa!=q(b,3)||c.na!=q(b,4))&&Ub(p(b));q(b,8)&&(d||c.Ha!=q(b,11)||c.Fa!=q(b,9)||c.Ga!=q(b,10))&&xc(b);c=wc(b);d=b;for(e=q(1,0);d!=e;){if(d==0||!q(d,6))break;d=q(d,0)}if(d==e){if(c)break a;G.push({id:3,val:b})}else{if(!c)break a;G.push({id:4,val:b})}b=yc(b,!0);for(e=0;e<b.length;e++)zc(b[e])}break;
case 8:b=b.val;d=wc(b.Q);(c=e=wc(b.G))||(c=d);if(c)d=W(b.G),Mb(c,d),Ac(b.G,c),c.a.C=!0,Ub(c);break;case 12:Wb(K.a.id,6,0);Wb(q(1,0),6,1);break;case 13:for(;F.length;)Bc(F.pop());break;case 14:Cc(b.val)}}}function tc(a){a&&(a=wc(a))&&kb(a)}
function uc(a){if(!wc(a))if(a==q(1,0)){Ac(a,K);Ub(K);Dc();var b=W(a);Mb(K,b.substr(0,1).toUpperCase()+b.substr(1))}else{var c={d:q(a,1),e:q(a,2)};Ec(p(a),c);b=W(a);var d=eb();Mb(d,b);Ac(a,d);d.a.C=!0;var e=$(document.createElement("div"));e.addClass("zoom");desktop.append(e);e.css("top",c.e+"px");e.css("left",c.d+"px");e.css("width","0px");e.css("height","0px");e.animate({top:d.top+"px",left:d.left+"px",width:d.width+"px",height:d.height+"px"},500,"swing",function(){e.remove();d.show();Ub(d)})}}
function vc(a){var b=Tb(wc(a));if(b!=j&&(a=p(b.b),a!=j)){var c=$(document.createElement("div"));c.addClass("zoom");desktop.append(c);c.css("top",b.top+"px");c.css("left",b.left+"px");c.css("width",b.width+"px");c.css("height",b.height+"px");b={d:q(b.b,1),e:q(b.b,2)};Ec(a,b);c.animate({top:b.e+"px",left:b.d+"px",width:"0px",height:"0px"},500,"swing",function(){c.remove();D.P--})}}
function Bc(a){var b=M.find(a);b&&(F.indexOf(a)!=-1?b.select():b.L());a==q(1,0)&&(F.indexOf(a)!=-1?M.addClass("selected"):M.removeClass("selected"));Ub(p(a))}function Cc(a){desktop.append(V);var b={d:q(a,1),e:q(a,2)};Ec(p(a),b);V.animate({top:b.e+"px",left:b.d+"px"},300,"swing",function(){V.remove()})}
function nc(){if(L.get(0).scrollHeight==L.innerHeight()){var a=L.clone();a.css("height","");a.css("visibility","hidden");$("body").append(a);Vb=a.innerHeight();a.remove();delete a}for(;H.length;)switch(a=H.splice(0,1)[0],a.id){case 1:L.append(a.val);R=!0;break;case 2:L.append("<br/>");R=!0;break;case 3:Fc=a.val[1],Gc=a.val[0],L.append(W(a.val[2])),R=!0}return Hc()}
function Hc(){var a=L.get(0).scrollHeight,b=L.innerHeight();L.scrollTop(Vb-Vb%da);Vb=L.scrollTop()+b;Ic(Kb,{left:0,right:0,top:0,bottom:a});if(Vb<a)return Jc(J),Kc(J),B=!0;return!1}function oc(a){for(var b=0;Hb.length;){var c=Hb.splice(0,1)[0];switch(c.id){case 1:lb(c.val);break;case 2:b=lb(c.val)}}if(a&&b)return setTimeout(S,b*1E3),!0;return!1}
function Wb(a,b,c){if(b==1||b==2)c=Math.round(c/fa);if(b==0){var d=c,e=Ob[0][a];if(d!=a){var g=e*2;for(e=I[g];e!=a;)g=e*2+1,e=I[g];I[g]=I[e*2+1];g=d*2;for(e=I[g];e&&e<=a;)g=e*2+1,e=I[g];I[a*2+1]=e;I[g]=a}}b<12&&zc(a);d=Cb[b];c<<=Eb[b];c&=Db[b];Ob[d][a]=c|Ob[d][a]&~Db[b];R=!0}function q(a,b){var c,d=Cb[b];if(d&128){var e=mb(0,a);if(e.length==0)return 0;d&=127;c=(e.charCodeAt(d*2)&255)<<8;c|=e.charCodeAt(d*2+1)&255}else c=Ob[d][a];c&=Db[b];c=X(c>>Eb[b]);if(b==1||b==2)c*=fa;return c}
function Ub(a){if(a!=j&&a.a!=j&&(a==Lb||q(a.a.id,6)==1)){a==K?ia(a.a.id*2).i(K.port,0,0):xb(a.port,Ya);for(var b=0;b<a.a.children.length;b++){var c=pa(a.a.children[b].id,a,0);a.a.children[b].top=c.top;a.a.children[b].left=c.left;a.a.children[b].width=c.width;a.a.children[b].height=c.height}if(a.l==14&&a.a.C){b={top:0,left:0,right:0,bottom:0};a.a.C=!1;for(c=0;c<a.a.children.length;c++){var d=a.a.children[c];b.right==b.left||b.bottom==b.top?(b.top=d.top,b.left=d.left,b.bottom=d.top+d.height,b.right=
d.left+d.width):(b.top=Math.min(b.top,d.top),b.left=Math.min(b.left,d.left),b.bottom=Math.max(b.bottom,d.top+d.height),b.right=Math.max(b.right,d.left+d.width))}if(b.right==b.left||b.bottom==b.top)b.top=a.a.y,b.left=a.a.x,b.bottom=a.a.y,b.right=a.a.x;else{if(b.left>a.a.x)b.left=a.a.x;if(b.right<a.a.x)b.right=a.a.x;if(b.top>a.a.y)b.top=a.a.y;if(b.bottom<a.a.y)b.bottom=a.a.y}Ic(a,b)}}}function Lc(a){a=J.find(a);a!=$b&&($b&&$b.L(),($b=a)&&a.select())}
function Mc(a,b,c){Gc=c;Fc=b;var d=ib();d.param([W(a)]);a=d.getItem(4);a.b.focus();a.b.keypress(function(a){if(a.which==13)return d.getItem(1).b.click(),!1;return!0});d.show(function(a){Nc=d.getItem(4).b.val();a==1?Y[0].state.push(65535):Y[0].state.push(0);Q(d);S()})}
function Oc(a){switch(a){case 256:Pc();break;case 257:Qc();break;case 258:Rc();break;case 259:ac=aa();Sc();break;case 260:ac=aa();Tc();break;case 261:Uc();break;case 2304:Vc();break;default:fatal("Unknown menuitem: "+a.toString(16))}}
function Wc(a,b){var c=a.c;if(c.l==2)c.Ka(a.o);else if(c==M)B||Xc(a.o,M,b,!1);else if(a.o==255){c=J;for(var d=0;d<c.j.length;d++)c.j[d].o==255&&c.j[d].hide();Yc(J);Hc()||S()}else if(!B){$b&&a!=$b&&$b.L();n=a.o;Lc(n);switch(ka()){case 0:N=!0;break;case 1:N=O.length!=0;break;case 2:T>0&&(N=!0)}S()}}
function Xc(a,b,c,d){b==M&&(b=K);if(c.shiftKey)if(a)O.indexOf(a)!=-1?Zc(a):$c(a),S();else if(b.l==14)ad(b,c,d);else{if(O.length==0||b!=p(O[0]))O.indexOf(b.a.id)!=-1?Zc(b.a.id):$c(b.a.id);S()}else if(n&&O.length&&ka()>1)a?bd(a):bd(b.a.id),S();else{if(!a)cd(),b.l==14?ad(b,c,d):a=b.a.id;if(a){var e;c.timeStamp-Xb<=300&&c.target==Yb?(Xb=0,Yb=j,e=!0):e=!1;e?(O.indexOf(a)==-1&&cd(),$c(a),dd(a,b,c,d)):(O.indexOf(a)==-1&&cd(),$c(a),ed(a,b,c,d))}}}
function ad(a,b,c){var d={},e={d:a.a.x,e:a.a.y};Ec(a,e);d.ra=e.d;d.sa=e.e;d.pa=e.d+a.port.width();d.qa=e.e+a.port.height();var g=$(document.createElement("div"));g.addClass("lasso");desktop.append(g);g.css("top",b.pageY+"px");g.css("left",b.pageX+"px");g.css("width","0px");g.css("height","0px");$(document).mousemove(function(a){var c=Math.max(Math.min(b.pageX,a.pageX),d.ra),e=Math.max(Math.min(b.pageY,a.pageY),d.sa),k=Math.min(Math.max(b.pageX,a.pageX),d.pa);a=Math.min(Math.max(b.pageY,a.pageY),d.qa);
g.css("top",e+"px");g.css("left",c+"px");g.css("width",k-c+"px");g.css("height",a-e+"px")});$(document).mouseup(function(e){$(document).unbind("mousemove");$(document).unbind("mouseup");var h=Math.max(Math.min(b.pageX,e.pageX),d.ra),f=Math.max(Math.min(b.pageY,e.pageY),d.sa),k=Math.min(Math.max(b.pageX,e.pageX),d.pa),r=Math.min(Math.max(b.pageY,e.pageY),d.qa);g.remove();e={d:h,e:f};fd(a,e);f={top:e.e,left:e.d,width:k-h,height:r-f};h=[];for(k=0;k<a.a.children.length;k++){var l=a.a.children[k].id;if(!q(l,
4))f.left=e.d-q(l,1),f.top=e.e-q(l,2),ha(l,f)&&h.push(l)}if(b.shiftKey){if(h.length==0){if(O.length==0||a!=p(O[0]))O.indexOf(a.a.id)!=-1?Zc(a.a.id):$c(a.a.id)}else for(;h.length;)l=h.shift(),O.indexOf(l)!=-1?Zc(l):$c(l);S()}else{if(h.length==0)l=a.a.id;else for(;h.length;)l=h.shift(),$c(l);Xc(l,a,b,c)}})}
function dd(a,b,c,d){var e=c.pageX,g=c.pageY,i={d:0,e:0},h=!1;V=j;d&&$(document).mousemove(function(c){if(V==j){if(Math.abs(c.pageX-e)+Math.abs(c.pageY-g)<=7)return!1;h=!0;V=qa(a);var d=oa(b.a.children,a);if(d)d--,i.d=b.a.children[d].left,i.e=b.a.children[d].top;Ec(b,i);V.css("top",i.e+"px");V.css("left",i.d+"px")}d=V.position();V.css("top",d.top+(c.pageY-g)+"px");V.css("left",d.left+(c.pageX-e)+"px");e=c.pageX;g=c.pageY;return!1});$(document).mouseup(function(c){var e;d&&($(document).unbind("mousemove"),
V&&(e=V.position(),V.remove()));$(document).unbind("mouseup");if(h)U.d=e.left,U.e=e.top,c=gd(c.pageX,c.pageY),T=c.id,U.d-=i.d,U.e-=i.e,c.c!=b&&(Ec(b,U),c.c&&fd(c.c,U)),n=5,Lc(5),N=!0;N||(bd(a),n||(n=4,Lc(4),N=!0));S()})}
function ed(a,b,c,d){var e=c.pageX,g=c.pageY,i={d:0,e:0},h=!1;V=j;d&&$(document).mousemove(function(c){if(V==j){if(Math.abs(c.pageX-e)+Math.abs(c.pageY-g)<=7)return!1;h=!0;V=qa(a);var d=oa(b.a.children,a);if(d)d--,i.d=b.a.children[d].left,i.e=b.a.children[d].top;Ec(b,i);V.css("top",i.e+"px");V.css("left",i.d+"px")}d=V.position();V.css("top",d.top+(c.pageY-g)+"px");V.css("left",d.left+(c.pageX-e)+"px");e=c.pageX;g=c.pageY;return!1});$(document).mouseup(function(a){Xb=a.timeStamp;Yb=a.target;var c;
d&&($(document).unbind("mousemove"),V&&(c=V.position(),V.remove()));$(document).unbind("mouseup");if(h)U.d=c.left,U.e=c.top,a=gd(a.pageX,a.pageY),T=a.id,U.d-=i.d,U.e-=i.e,a.c!=b&&(Ec(b,U),a.c&&fd(a.c,U)),n=5,Lc(5),N=!0;ka()==1&&(N=!0);S()})}function cd(){for(;O.length;)Zc(O.shift())}function $c(a){O.length&&p(a)!=p(O[0])&&cd();O.indexOf(a)==-1&&O.push(a);F.indexOf(a)==-1&&(F.push(a),Bc(a))}function Zc(a){var b=O.indexOf(a);b!=-1&&O.splice(b,1);if((b=F.indexOf(a))!=-1)F.splice(b,1),Bc(a)}
function bd(a){if(a!=T){var b;if(T>0&&(b=F.indexOf(T))!=-1&&O.indexOf(T)==-1)F.splice(b,1),Bc(T);T=a;F.indexOf(T)==-1&&(F.push(T),Bc(T));N=!0}}
function pa(a,b,c){var d=q(a,1),e=q(a,2),g=q(a,3);if(c||!g||!q(a,4)){var i=1;g||c?i=0:F.indexOf(a)!=-1&&(i=2);c=d-b.a.x;e-=b.a.y;var h=b.port;d=i;i={top:0,left:0,width:0,height:0};if(a=ia(a*2))switch(i={top:e,left:c,width:a.width,height:a.height},d){case 1:a.i(h,c,e);break;case 2:if(!(a.width==0||a.height==0)){d=h.get(0).getContext("2d");var f=g=0;c<0&&(g=-c,c=0);e<0&&(f=-e,e=0);var k=a.width,r=a.height;k+c>=h.width()&&(k=h.width()-c);r+e>=h.height()&&(r=h.height()-e);if(!(k==0||r==0)){h=d.getImageData(c,
e,k,r);for(var l=f;l<r;l++)for(var w=(l>>1)*a.s,o=(l-f)*h.width*4,na,rb=g;rb<k;rb++)na=a.data[w+(rb>>2)],Aa&&(na=Aa[na]),(na=na>>(rb&2?0:4)&15)?(na^=15,na*=3,h.data[o++]=x[na++],h.data[o++]=x[na++],h.data[o++]=x[na++],h.data[o++]=255):o+=4;d.putImageData(h,c,e)}}}i.top+=b.a.y;i.left+=b.a.x;return i}return{top:0,left:0,width:0,height:0}}function Dc(){for(var a=M,b=0;b<a.j.length;b++)a.j[b].b.remove();a.j=[];a=yc(q(1,0),!0);for(b=0;b<a.length;b++)xc(a[b])}
function xc(a){if(q(a,8)){var b=M.find(a);b&&M.remove(b);!q(a,11)&&q(a,0)==q(1,0)&&M.add(C([q(a,9)*2,q(a,10)*2,14,12],a,2,[]))}}function Pc(){var a=Za();B=!0;a.show(function(){Q(a);B=!1})}function Vc(){var a=ab(),b=hd();b==null&&(b=50);id(a.getItem(2),b);B=!0;a.show(function(){var b=a.getItem(2).value,d=new Date;d.setTime(d.getTime()+31536E6);document.cookie="webventure_volume="+escape(b)+"; expires="+d.toGMTString()+"; path=/";Q(a);B=!1})}
function Qc(){if(R){var a=bb(0);B=!0;a.show(function(b){Q(a);switch(b){case 1:ac=Qc;Sc();break;case 2:rc();break;case 3:B=!1}})}else rc()}function rc(){Nb="";for(var a=ua(Ga()),b=0;b<Bb;b++)for(var c=0;c<zb;c++)Ob[b][c]=y(a);for(b=0;b<Ab;b++)Pb[b]=y(a);Sb();Qb();Mb(Kb,"Untitled");L.html("");n=1;O=[q(1,0)];E=1;Wb(q(1,0),6,1);dc=cc=bc=R=!1;Y=[];N=!0;S()}function Rc(){if(R){var a=bb(1);B=!0;a.show(function(b){Q(a);switch(b){case 1:ac=Rc;Sc();break;case 2:sc();break;case 3:B=!1}})}else sc()}
function sc(){var a=cb();B=!0;for(var b=a.getItem(3),c=j,d=0;d<window.localStorage.length;d++){var e=window.localStorage.key(d);if(e!=null&&window.JSON.parse(window.localStorage.getItem(e).toString()).ua==gamename){var g=$(document.createElement("div"));g.addClass("listitem");g.mousedown(ba(!1));g.click(function(a){c&&c.removeClass("active");c=$(a.target);c.addClass("active")});g.dblclick(function(){a.getItem(1).b.click()});g.text(e.toString());b.b.append(g)}}a.show(function(b){switch(b){case 1:if(c==
j)break;Nb=c.text();Q(a);B=!1;b=window.JSON.parse(window.localStorage.getItem(Nb).toString());Ob=b.Z;Pb=b.$;Sb();Qb();Mb(Kb,Nb);L.html(b.text);Vb=L.get(0).scrollHeight;L.scrollTop(Vb);E=1;dc=cc=bc=!1;O=[];n=0;Y=[];Wb(q(1,0),6,1);R=!1;S();break;case 2:Q(a),B=!1}})}function Sc(){Nb==""?Tc():(window.localStorage.setItem(Nb,window.JSON.stringify({ua:gamename,Z:Ob,$:Pb,text:L.html()})),Mb(Kb,Nb),R=!1,ac())}
function Tc(){var a=db();B=!0;var b=a.getItem(3);b.b.focus();b.b.keypress(function(b){if(b.which==13)return a.getItem(1).b.click(),!1;return!0});b=a.getItem(4);for(var c=j,d=0;d<window.localStorage.length;d++){var e=window.localStorage.key(d);if(e!=null&&window.JSON.parse(window.localStorage.getItem(e).toString()).ua==gamename){var g=$(document.createElement("div"));g.addClass("listitem");g.mousedown(ba(!1));g.click(function(b){c&&c.removeClass("active");c=$(b.target);c.addClass("active");a.getItem(3).b.val(c.text())});
g.dblclick(function(){a.getItem(1).b.click()});g.text(e.toString());b.b.append(g)}}a.show(function(b){switch(b){case 1:Nb=a.getItem(3).b.val();Q(a);B=!1;Sc();break;case 2:Q(a),B=!1,ac()}})}function Uc(){if(R){var a=bb(2);B=!0;a.show(function(b){Q(a);switch(b){case 1:ac=Uc;Sc();break;case 2:E=4;S();break;case 3:B=!1}})}else E=4,S()}
function hd(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var c=a[b];c.charAt(0)==" ";)c=c.substring(1,c.length);if(c.indexOf("webventure_volume=")==0)return unescape(c.substring(18,c.length))}return null}function Gb(){n=0;$b=j;O=[];T=0;U={d:0,e:0};Nc="";N=!1;Xb=0}function zc(a){if(Fb.indexOf(a)==-1){Fb.push(a);var b={b:a};b.parent=q(a,0);b.x=q(a,1);b.y=q(a,2);b.Fa=q(a,9);b.Ga=q(a,10);b.Ha=q(a,11);b.oa=q(a,3);b.na=q(a,4);G.push({id:7,val:b})}}
function jd(a){a&128&&(a=-((a^255)+1));return a}function X(a){a&32768&&(a=-((a^65535)+1));return a}function wc(a){switch(a){case 65532:return M;case 65533:return Lb;case 65534:return Kb;case 65535:return J}var b;a:for(var c=0;c<P.length;c++)if((P[c].l==10||P[c].l==14)&&P[c].a!=j&&P[c].a.id==a){b=P[c];break a}return b}function yc(a,b){for(var c=[],d=I[a*2];d;)c.push(d),b||(c=c.concat(yc(d,!1))),d=I[d*2+1];return c}
function oa(a,b){var c;for(c=0;c<a.length&&a[c].id!=b;c++);if(c==a.length)return 0;return c+1}function p(a){if(a==1)return Lb;if(a=q(a,0))return wc(a)}function Ac(a,b){var c=yc(a,!0);b.a={id:a,x:0,y:0,C:!1,children:[]};for(var d=32767,e=32767,g=0;g<c.length;g++)if(c[g]!=1){var i={id:c[g],top:0,left:0,width:0,height:0};if(b!=K){var h=q(i,1),f=q(i,2);d>h&&(d=h);e>f&&(e=f)}b.a.children.push(i)}if(d!=32767)b.a.x=d;if(e!=32767)b.a.y=e;if(b!=K)b.a.C=!0}
function gc(){for($b!=j&&$b.L();F.length;)Bc(F.pop());Gb()}
function gd(a,b){var c;a:if(c=desktop.offset(),b>=c.top&&b<c.top+ea&&a>=c.left&&a<c.left+desktop.width())c={id:1,c:j};else{for(c=0;c<P.length;c++){var d=P[c].T(a,b);if(d!=j){c=d;break a}}c={id:0,c:j}}d=0;if(c.c!=j)d=c.c.l;if(c.id==3&&(d==14||d==10))c.id=c.c.a.id;else switch(d){case 9:c.id=-1;break;case 11:c.id=-2;break;case 12:c.id=-3;break;case 13:c.id=-4;break;default:switch(c.id){case 0:c.id=-5;break;case 1:c.id=-6;break;case 2:c.id=-7;break;case 3:c.id=-8;break;case 4:c.id=-9;break;case 5:c.id=
-10;break;case 6:c.id=-11;break;default:c.id=-12}}return c};function ia(a){a=mb(3,a);if(!(a.length<2)){if(a.length==2)return ia((a.charCodeAt(0)&255)<<8|a.charCodeAt(1)&255);var b;a=new za(a);var c=a.f(3),d,e;Ba&&a.f(2);e=a.f(1)?a.f(10):a.f(6);if((d=a.f(1)?a.f(10):a.f(6))&&e)switch(b=new Ca(d,e,d+15>>3&65534),c){case 0:c=b.F>>4;d=b.F&15;for(var g=0,i=0;i<b.N;i++){for(var h=0;h<c;h++)e=ub(a),a.seek(2,a.n),e>>>=16-a.q,b.data[g++]=e>>8&255,b.data[g++]=e&255;d&&(e=a.f(d),e<<=16-d,b.data[g++]=e>>8&255,b.data[g++]=e&255)}break;case 1:kd(ld,md,nd,b,a);break;case 2:kd(od,
pd,qd,b,a);break;case 3:c=Array(17);for(g=0;(d=rd[g++])!=255;){for(e=a.f(d);(d=rd[g++])!=255;)c[rd[g++]]=e%d,e=e/d|0;c[rd[g++]]=e}c[16]=0;for(e=16;e>0;e--)for(d=e;d<=16;d++)c[d]>=c[e-1]&&c[d]++;for(e=16;e>=0;e--)if(c[e]==16){c[e]=255;break}g=Array(17);i=Array(17);d=a.f(2)+1;for(e=h=0;e<15;e++){if(e)for(;!a.f(1);)d++;i[e]=d;g[e]=h;h+=1<<16-d}for(g[15]=h;h&1<<16-d;)d++;g[16]=h|1<<16-d;i[15]=d;i[16]=d;kd(g,i,c,b,a)}return b}}
function xb(a,b){for(var c=a.width(),d=a.height(),e=a.get(0).getContext("2d"),g=e.getImageData(0,0,c,d),i=0;i<d;i++)for(var h=i*g.width*4,f=0;f<c;f++){var k=(b>>4*(f&3)&15)*3;g.data[h++]=x[k++];g.data[h++]=x[k++];g.data[h++]=x[k++];g.data[h++]=255}e.putImageData(g,0,0)}
function ja(a,b,c){var d=b.top,e=b.left,g=e+b.width;b=d+b.height;if(d<a.top)d=a.top;if(e<a.left)e=a.left;b>a.top+a.height&&(b=a.top+a.height);g>a.left+a.width&&(g=a.left+a.width);if(g<=e||b<=d)d=b=e=g=0;c.top=d;c.left=e;c.width=g-e;c.height=b-d;return c.height!=0}
var ld=[0,8192,16384,20480,24576,28672,32768,36864,40960,45056,49152,53248,55296,57344,59392,61440,63488],md=[3,3,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5],nd=[0,15,3,5,6,7,8,9,10,12,255,1,2,4,11,13,14],od=[0,16384,32768,49152,51200,53248,55296,57344,59392,61440,62464,62976,63488,64E3,64512,65024,65280],pd=[2,2,2,5,5,5,5,5,5,6,7,7,7,7,7,8,8],qd=[255,0,15,1,3,7,14,12,8,6,2,4,9,13,11,10,5],rd=[8,15,2,255,0,4,255,1,7,9,8,255,3,4,255,4,10,7,10,11,6,255,5,6,6,11,255,7,3,255,9,4,3,14,255,12,2,255,13,1,255,15,255];
function kd(a,b,c,d,e){var g;Z=sd=0;g=d.F&3?e.f(5):e.f(4)<<1;var i=0,h=d.F&15;h&&(h>>=2,i=h&1,h=2-(h>>1));for(var f=0,k=0;k<d.N;k++){for(var r=0;r<d.F>>3;r++){var l=td(a,b,c,e)<<4;d.data[f++]=td(a,b,c,e)|l}i&&(d.data[f]=td(a,b,c,e)<<4);f+=h}if(r=d.F&3){f=d.s-h;var w=0;for(k=h=0;k<d.N;k++)g&1?(w<r&&(l=td(a,b,c,e)<<4,h|=l>>>w,w+=4),w-=r,l=h,h<<=r,h&=255):(l=e.f(r),l<<=8-r),i&&(l>>>=4),d.data[f]|=l&255,f+=d.s}if(g&8)for(k=f=0;k<d.N;k++)if(l=0,g&2)for(r=0;r<d.s;r++)d.data[f]^=l,l=d.data[f++];else for(r=
0;r<d.s;r++)h=d.data[f]^l,h^=h>>>4&15,d.data[f++]=h,l=h<<4&255;if(g&4){a=d.s*4;g&2&&(a*=2);f=0;g=a;for(b=0;b<d.N*d.s-a;b++)d.data[g++]^=d.data[f++]}}var sd=0,Z=0;
function td(a,b,c,d){if(sd)return sd--,Z=Z<<8&65280|Z>>8,Z&255;var e=ub(d);e>>>=16-d.q;e&=65535;var g;for(g=0;g<16;g++)if(a[g+1]>e)break;d.q+=b[g];d.q&16&&(d.q&=15,d.seek(2,d.n));a=c[g];if(a==255)return d.f(1)||(Z&=255,Z|=Z<<8),sd=d.f(3),sd<3&&(sd<<=4,sd|=d.f(4),sd<8&&(sd<<=8,sd|=d.f(8))),sd-=2,Z=Z<<8&65280|Z>>8,Z&255;else Z<<=8,Z|=a,Z&=65535;return a};function Na(a,b,c,d){var e={id:b},g=$(document.createElement("tr"));if(a[0]=="-"){var i=$(document.createElement("td"));i.attr("colspan","2");i.addClass("divider");i.append(document.createElement("hr"))}else g.addClass("menuitem"),i=$(document.createElement("td")),i.html(ga(a)),g.append(i),i=$(document.createElement("td")),c!=""&&(i.addClass("shortcut"),ud.push({key:c,id:b}),i.text(c));g.append(i);e.b=g;e.enabled=d;e.enabled||e.b.addClass("disabled");A.body.append(e.b);A.u.push(e)}
function Oa(a){for(var b=$(a.target);b.data("refCon")==j;)b=b.parent();b.addClass("active");var c=b.data("refCon");desktop.append(c.p);a=b.position();c.p.css("top",a.top+ea+"px");c.p.css("left",a.left+"px");var d=-1;$(document).mousemove(function(a){var g=Pa.offset();if(a.pageX>=g.left&&a.pageY>g.top&&a.pageX<g.left+Pa.width()&&a.pageY<g.top+Pa.height())for(var i=0;i<Qa.length;i++){if(g=Qa[i].b.offset(),a.pageX>=g.left&&a.pageX<g.left+Qa[i].b.outerWidth()){c.p.remove();b.removeClass("active");b=Qa[i].b;
b.addClass("active");c=b.data("refCon");desktop.append(c.p);g=b.position();c.p.css("top",g.top+ea+"px");c.p.css("left",g.left+"px");break}}else if(g=c.p.offset(),a.pageX>=g.left&&a.pageY>=g.top&&a.pageX<g.left+c.p.outerWidth()&&a.pageY<g.top+c.p.outerHeight())for(i=0;i<c.u.length;i++){var h=c.u[i].b;h.hasClass("menuitem")&&c.u[i].enabled&&(g=h.offset(),a.pageY>=g.top&&a.pageY<g.top+h.outerHeight()?(d=i,h.addClass("active")):h.removeClass("active"))}else{for(i=0;i<c.u.length;i++)c.u[i].b.removeClass("active");
d=-1}});$(document).mouseup(function(){$(document).unbind("mousemove");$(document).unbind("mouseup");c.p.remove();b.removeClass("active");d!=-1&&Oc(c.u[d].id)})}var Pa,Qa=[],ud=[],A=j;$("body").keydown(function(a){if(a.target.type=="text")return!1;if(!a.altKey)return!1;if(B)return!1;for(var b=0;b<ud.length;b++)if(ud[b].key.charCodeAt(0)==a.which)for(var c=ud[b].id,d=0;d<Qa.length;d++)for(var e=0;e<Qa[d].u.length;e++)Qa[d].u[e].id==c&&Qa[d].u[e].enabled&&vd(Qa[d],c)});
function vd(a,b){a.b.addClass("active");setTimeout(function(){a.b.removeClass("active");Oc(b)},200)};function jb(a,b,c,d,e,g,i,h,f){var k=this;this.j=[];this.W=c;this.V=b;this.I=d;this.H=e;this.c=$(document.createElement("div"));this.c.addClass(a);if(a=="document"||a=="info"||a=="noGrowDoc"||a=="zoomDoc"||a=="rDoc4")b="<span></span>",this.title=$(document.createElement("div")),this.title.addClass("title"),this.title.mousedown(function(a){B||wd(a.pageX,a.pageY,k);return!1}),this.V&&(b='<div class="close"></div>'+b),this.W&&(b+='<div class="resize"></div>'),this.title.html(b),this.V&&(b=this.title.children("div.close"),
b.mousedown(ba(!1)),b.click(function(a){B||fatal(a);return!1})),this.W&&(b=this.title.children("div.resize"),b.mousedown(ba(!1)),b.click(function(a){B||fatal(a);return!1})),this.c.append(this.title);this.port=$(document.createElement("canvas"));this.port.mousedown(function(a){if(!B)switch(kb(k),k.l){case 9:wd(a.pageX,a.pageY,k);break;case 10:case 14:var b=xd(a.pageX,a.pageY,k),c=!1;b&&!q(b,3)&&(c=!0);Xc(b,k,a,c);break;case 12:b=xd(a.pageX,a.pageY,k);b==1?Xc(b,k,a,!1):wd(a.pageX,a.pageY,k);break;case 13:Xc(q(1,
0),k,a,!1)}return!1});this.port.attr("width",h);this.port.attr("height",f);this.c.append(this.port);this.top=i;this.height=f;this.left=g;this.width=h;a=="document"||a=="noGrowDoc"||a=="zoomDoc"||a=="rDoc4"?(this.top-=Sa+Ra,this.height+=Sa,this.left-=Ra):a=="info"?(this.top-=Ta+Ra,this.height+=Ta,this.left-=Ra):a=="alert"?(this.top-=Ua*2,this.left-=Ua*2,this.width+=Ua,this.height+=Ua):(this.top-=Ra,this.left-=Ra);this.I&&(this.width+=Va);this.H&&(this.height+=Wa);this.c.css("top",this.top+"px");this.c.css("left",
this.left+"px");this.c.css("width",this.width+"px");this.c.css("height",this.height+"px");desktop.append(this.c);(this.I||this.H)&&yd(this)}m=jb.prototype;m.show=function(a){this.Ka=a;this.c.show();Yc(this)};m.hide=function(){this.c.hide()};
function Mb(a,b){if(a.title!=j){var c=a.title.children("span");c.html("");if(b=="")c.hide();else{var d=a.c.css("display")=="none";a.c.show();c.css({position:"absolute",visibility:"hidden",display:"block"});var e=a.port.width();a.V&&(e-=30);a.W&&(e-=30);for(var g=0;g<b.length;g++)if(c.append(b.substring(g,g+1)),c.width()>e){c.html(b.substring(0,g-1));break}c.css({position:"",visibility:"",display:""});d&&a.c.hide()}}}m.addClass=function(a){this.c.addClass(a)};m.removeClass=function(a){this.c.removeClass(a)};
m.add=function(a){var b=this.port.position().top,c=parseInt(a.b.css("top"),10);a.b.css("top",c+b+"px");this.c.append(a.b);a.c=this;this.j.push(a);this.c.css("display")!="none"&&a.i()};m.remove=function(a){var b=this.j.indexOf(a);b!=-1&&this.j.splice(b,1);a.b.remove()};m.find=function(a){for(var b=0;b<this.j.length;b++)if(this.j[b].o==a)return this.j[b]};function Jc(a){for(var b=0;b<a.j.length;b++)a.j[b].hide()}function Yc(a){for(var b=0;b<a.j.length;b++)a.j[b].o!=255&&a.j[b].show()}
function Kc(a){for(var b=0;b<a.j.length;b++)a.j[b].o==255&&a.j[b].show()}m.close=function(){this.c.remove()};function fd(a,b){var c=a.port.offset();b.d-=c.left+1;b.e-=c.top+2;a.a&&(b.d+=a.a.x,b.e+=a.a.y)}function Ec(a,b){var c=a.port.offset();b.d+=c.left+1;b.e+=c.top+2;a.a&&(b.d-=a.a.x,b.e-=a.a.y)}
function yd(a){if(a.H){a.z=$(document.createElement("div"));a.z.addClass("hscroll");a.z.css("top",a.height-Wa+"px");a.z.css("width",a.width-32+"px");a.z.mousedown(function(){fatal("scroll")});var b=$(document.createElement("div"));b.addClass("leftarrow");b.mousedown(function(){fatal("scroll")});a.z.append(b);a.S=$(document.createElement("div"));a.S.addClass("rightarrow");a.S.css("left",a.width-Xa-32+"px");a.S.mousedown(function(){fatal("scroll")});a.z.append(a.S);a.r=$(document.createElement("div"));
a.r.addClass("slider");a.r.mousedown(function(){fatal("drag")});a.z.append(a.r);a.c.append(a.z)}if(a.I)a.A=$(document.createElement("div")),a.A.addClass("vscroll"),a.A.css("left",a.width-Va+"px"),a.A.css("height",a.height-24-Sa+"px"),a.A.mousedown(function(){fatal("scroll")}),b=$(document.createElement("div")),b.addClass("uparrow"),b.mousedown(function(){fatal("scroll")}),a.A.append(b),a.R=$(document.createElement("div")),a.R.addClass("downarrow"),a.R.css("top",a.height-24-24-Sa+"px"),a.R.mousedown(function(){fatal("scroll")}),
a.A.append(a.R),a.m=$(document.createElement("div")),a.m.addClass("slider"),a.m.mousedown(function(){fatal("drag")}),a.A.append(a.m),a.c.append(a.A);a.M=$(document.createElement("div"));a.M.addClass("grow");a.M.css("top",a.height-24+"px");a.M.css("left",a.width-32+"px");a.M.mousedown(function(){fatal("grow")});a.c.append(a.M)}
function Ic(a,b){if(a.l==11){a.m.data("min",b.top);a.m.data("max",b.bottom);var c=a.port.scrollTop(),d=a.m.data("min"),e=a.m.data("max");if(d<e){var g=c-d;c+=a.port.height();g=g*(a.height-Sa-24-22-24)/(e-d)|0;d=c*(a.height-Sa-24-22-24-2)/(e-d)|0;a.m.css("top",g+22+"px");a.m.css("height",d-g+"px")}else a.m.css("top","22px"),a.m.css("height",a.height-24-Sa-24+"px")}else{if(b.left>a.a.x)b.left=a.a.x;if(b.right<a.a.x+a.port.width())b.right=a.a.x+a.port.width();if(b.top>a.a.y)b.top=a.a.y;if(b.bottom<a.a.y+
a.port.height())b.bottom=a.a.y+a.port.height();a.H&&(a.r.data("min",b.left),a.r.data("max",b.right));a.I&&(a.m.data("min",b.top),a.m.data("max",b.bottom));a.H&&(d=a.r.data("min"),e=a.r.data("max"),d<e?(c=a.a.x-d,g=a.port.width(),c=c*(a.port.width()-32-Xa)/(e-d)|0,d=g*(a.port.width()-32-Xa-2)/(e-d)|0,a.r.css("left",c+32+"px"),a.r.css("width",d+"px")):(a.r.css("left","32px"),a.r.css("width",a.port.width()-32-Xa+"px")));a.I&&(d=a.m.data("min"),e=a.m.data("max"),d<e?(c=a.a.y-d,g=a.port.height(),c=c*(a.port.height()-
22-24)/(e-d)|0,d=g*(a.port.height()-22-24-2)/(e-d)|0,a.m.css("top",c+22+"px"),a.m.css("height",d+"px")):(a.m.css("top","22px"),a.m.css("height",a.port.height()-22-24+"px")))}}m.T=function(a,b){var c=this.c.offset();if(a>=c.left&&a<c.left+this.c.width()&&b>=c.top&&b<c.top+this.c.height()){c=this.port.offset();if(a>=c.left&&a<c.left+this.port.width()&&b>=c.top&&b<c.top+this.port.height())return{id:3,c:this};return{id:4,c:this}}};
function zd(a){var b=a.port.get(0).getContext("2d"),c=a.port.width();a=a.port.height();c=b.getImageData(0,0,c,a);for(a=0;a<c.height;a++)for(var d=a*c.width*4,e=0;e<c.width;e++)c.data[d++]^=255,c.data[d++]^=255,c.data[d++]^=255,c.data[d++]=255;b.putImageData(c,0,0)}function pc(){for(var a=[],b=0;b<P.length;b++)P[b].l==14?a.push(P[b]):P[b].hide();for(b in a)Tb(a[b])}function Q(a){for(var b=0;b<P.length;b++)if(P[b]==a){a.close();P.splice(b,1);break}P.length&&kb(P[0])}
function Tb(a){if(a!=j){var b=a.a.id;if(a.l==10)a.a={},Mb(a,"");else{var c={e:0,d:0},d={e:a.port.height(),d:a.port.width()};Ec(a,c);Ec(a,d);a.a={};Q(a);return{b:b,top:c.e,left:c.d,width:d.d-c.d,height:d.e-c.e}}}}function kb(a){if(P[0]!=a){P[0]!=j&&P[0].c.removeClass("active");for(var b=0;b<P.length;b++)P[b]==a&&P.splice(b,1);P.unshift(a)}a.c.addClass("active")}function $a(a,b,c,d){a=new jb("alert",!1,!1,!1,!1,a,b,c,d);a.l=2;a.hide();kb(a);return a}var P=[];
function wd(a,b,c){var d=a,e=b;kb(c);$(document).mousemove(function(a){var b=c.c.position();c.c.css("top",b.top+(a.pageY-e)+"px");c.c.css("left",b.left+(a.pageX-d)+"px");d=a.pageX;e=a.pageY});$(document).mouseup(function(a){$(document).unbind("mousemove");$(document).unbind("mouseup");var b=c.c.position();c.c.css("top",b.top+(a.pageY-e)+"px");c.c.css("left",b.left+(a.pageX-d)+"px")})}
function xd(a,b,c){a={d:a,e:b};var d=0;b=c.a.children.length;for(fd(c,a);b>0&&d==0;){b--;d=a;var e=c.a.children[b],g=0,i;if(i=!q(e.id,4))i=d.d>=e.left&&d.e>=e.top&&d.d<e.left+e.width&d.e<e.top+e.height?!0:!1;if(i)if(i=j,i=ia(e.id*2)){if(i.T(d.d-e.left,d.e-e.top))g=e.id}else g=e.id;d=g}return d};function kc(a,b,c,d){Y.unshift({ka:a,D:b,target:c,la:d.d,ma:d.e,state:new Ad,k:[],h:[]});return ic(!0)}function ic(a){for(;Y.length;)if(Bd(a))return!0;return!1}var Y=[];function Ad(){this.stack=Array(128);this.w=128}Ad.prototype.push=function(a){this.stack[--this.w]=Cd(a)};Ad.prototype.pop=function(){return this.stack[this.w++]};function Dd(a,b){return a.stack[a.w+b]}Ad.prototype.clear=function(){this.w=128};Ad.prototype.size=function(){return 128-this.w};
function Cd(a){a<0&&(a=(-a^65535)+1);return a&65535}
function Bd(a){var b=!1;if(Y[0].xa||a){Y[0].xa=!1;if(b=a?Ed(0):Fd())return Y[0].xa=!0;b=!0;Y[0].va=0}if(Y[0].wa||b){Y[0].wa=!1;var c=[q(1,0)].concat(yc(q(1,0),!1));for(a=Y[0].va;a<c.length;a++){if(b=b?Ed(c[a]):Fd())return Y[0].wa=!0,Y[0].va=a,!0;b=!0}}var d;if(Y[0].X&&(Y[0].X=!1,Fd()))return Y[0].X=!0;do{for(a=b=0;a<Y[0].k.length;a++)if(b<Y[0].k[a].t)b=Y[0].k[a].t,d=a;if(b&&(Y[0].k[d].t=0,Ed(Y[0].k[d].ta)))return Y[0].X=!0}while(b);Y.shift();return!1}
function Ed(a){if(a=mb(1,a))return Y[0].h[0]=new za(a),Gd();return!1}function Fd(){var a=Gd();if(a)return a;Y[0].h.shift();if(Y[0].h.length)return Fd()}var Hd;
function Gd(){var a,b,c,d,e,g,i,h;d=Y[0].h[0];for(var f=Y[0].state;!(d.g>=d.length);)if(a=u(d),a&128)switch(a){case 128:b=f.pop();c=f.pop();f.push(q(b,c));break;case 129:b=f.pop();c=f.pop();a=X(f.pop());Wb(b,c,a);break;case 130:b=f.pop();c=f.pop();a=f.pop()!=0;f.push(Id(b,c,a));break;case 131:f.push(Y[0].ka);break;case 132:f.push(Y[0].D);break;case 133:f.push(Y[0].target);break;case 134:f.push(Y[0].la);break;case 135:f.push(Y[0].ma);break;case 136:f.push(u(d));break;case 137:f.push(y(d));break;case 138:c=
f.pop();f.push(Pb[c]);break;case 139:c=f.pop();a=X(f.pop());Pb[c]=a;R=!0;break;case 140:a=f.pop();f.push(Math.round((a-1)*Math.random()));break;case 141:a=Dd(f,0);f.push(a);break;case 142:c=f.pop();for(b=c-1;c--;)a=Dd(f,b),f.push(a);break;case 143:b=f.pop();h=f.pop();f.push(b);f.push(h);break;case 144:c=f.pop();h=Dd(f,c);b=Dd(f,0);f.stack[f.w+c]=Cd(b);f.stack[f.w+0]=Cd(h);break;case 145:f.pop();break;case 146:a=Dd(f,1);f.push(a);break;case 147:c=f.pop();a=Dd(f,c);f.push(a);break;case 148:h=f.pop();
b=f.pop();a=f.pop();f.push(h);f.push(a);f.push(b);break;case 149:i=X(f.pop());c=X(f.pop());i%=c;i<0&&(i+=c);e=g=0;for(a=1;a<c;a++)e+=i,e>=c&&(e-=c),e==g?(g++,e=g):(h=Dd(f,g),b=Dd(f,e),f.stack[f.w+g]=Cd(b),f.stack[f.w+e]=Cd(h));break;case 150:f.clear();break;case 151:f.push(f.size());break;case 152:b=f.pop();h=f.pop();f.push(h+b);break;case 153:b=f.pop();h=f.pop();f.push(h-b);break;case 154:b=f.pop();h=f.pop();f.push(h*b);break;case 155:b=f.pop();h=f.pop();f.push(h/b|0);break;case 156:b=f.pop();h=
f.pop();f.push(h%b);break;case 157:b=f.pop();h=f.pop();f.push(h%b);f.push(h/b|0);break;case 158:a=X(f.pop());a<0&&(a=-a);f.push(a);break;case 159:a=-X(f.pop());f.push(a);break;case 160:b=f.pop();h=f.pop();f.push(h&b);break;case 161:b=f.pop();h=f.pop();f.push(h|b);break;case 162:b=f.pop();h=f.pop();f.push(h^b);break;case 163:a=f.pop();f.push(a^65535);break;case 164:b=f.pop();h=f.pop();f.push(h&&b?65535:0);break;case 165:b=f.pop();h=f.pop();f.push(h||b?65535:0);break;case 166:b=f.pop();h=f.pop();f.push(!h!=
!b?65535:0);break;case 167:a=f.pop();f.push(a==0?65535:0);break;case 168:b=f.pop();h=f.pop();f.push(h>b?65535:0);break;case 169:b=f.pop();h=f.pop();f.push(h<b?65535:0);break;case 170:b=X(f.pop());h=X(f.pop());f.push(h>b?65535:0);break;case 171:b=X(f.pop());h=X(f.pop());f.push(h<b?65535:0);break;case 172:b=f.pop();h=f.pop();f.push(h==b?65535:0);break;case 173:b=W(f.pop());h=W(f.pop());f.push(h==b?1:0);break;case 174:b=W(f.pop());a=W(f.pop());f.push(a.toLowerCase().indexOf(b.toLowerCase())!=-1?1:0);
break;case 175:b=W(f.pop());a=W(f.pop());b=RegExp("\\b"+b+"\\b","i");f.push(b.test(a)?65535:0);break;case 176:a=X(y(d));d.seek(a,d.n);break;case 177:a=jd(u(d));d.seek(a,d.n);break;case 178:a=X(y(d));b=f.pop();b!=0&&d.seek(a,d.n);break;case 179:a=jd(u(d));b=f.pop();b!=0&&d.seek(a,d.n);break;case 180:a=X(y(d));b=f.pop();b==0&&d.seek(a,d.n);break;case 181:a=jd(u(d));b=f.pop();b==0&&d.seek(a,d.n);break;case 182:a=f.pop();b=f.pop();Y[0].k.push({t:a,ta:b});break;case 183:b=f.pop();for(a=0;a<Y[0].k.length;a++)if(Y[0].k[a].ta==
b)Y[0].k[a].t=0;break;case 184:b=f.pop();for(a=0;a<Y[0].k.length;a++)if(Y[0].k[a].t<=b)Y[0].k[a].t=0;break;case 185:c=f.pop();for(a=0;a<Y[0].k.length;a++)if(Y[0].k[a].t>=c)Y[0].k[a].t=0;break;case 186:b=f.pop();c=f.pop();for(a=0;a<Y[0].k.length;a++)if(Y[0].k[a].t>=c&&Y[0].k[a].t<=b)Y[0].k[a].t=0;break;case 187:a={state:new Ad,k:[],h:[j]};a.ka=f.pop();a.D=f.pop();a.target=f.pop();a.la=f.pop();a.ma=f.pop();Y.unshift(a);if(Bd(!0))return!0;break;case 188:a=f.pop();Y[0].h.unshift(j);if(Ed(a))return!0;
Y[0].h.shift();d=Y[0].h[0];break;case 189:b=f.pop();G.push({id:2,val:b});break;case 190:a={};a.Q=f.pop();a.G=f.pop();G.push({id:8,val:a});Wb(a.G,6,q(a.Q,6));Wb(a.Q,6,0);b=yc(a.Q,!0);for(c=0;c<b.length;c++)Wb(b[c],0,a.G);break;case 191:G.push({id:14,val:Y[0].D});break;case 192:G.push({id:13});break;case 193:a=f.pop();H.push({id:3,val:[Y[0].target,Y[0].D,a]});break;case 194:H.push({id:2});break;case 195:a=f.pop();H.push({id:3,val:[Y[0].target,Y[0].D,a]});H.push({id:2});break;case 196:a=f.pop();H.push({id:2});
H.push({id:3,val:[Y[0].target,Y[0].D,a]});H.push({id:2});break;case 197:a=f.pop();H.push({id:1,val:a});break;case 198:f.push(2);break;case 199:b=f.pop();Hb.push({id:1,val:b});break;case 200:b=f.pop();Hb.push({id:2,val:b});break;case 201:Hb.push({id:3});break;case 202:a=new Date;f.push(a.getFullYear());f.push(a.getMonth()+1);f.push(a.getDate());f.push(a.getHours());f.push(a.getMinutes());f.push(a.getSeconds());break;case 203:a=new Date;f.push(a.getDay()+1);break;case 204:a=f.pop()!=0;b=f.pop();b=yc(b,
a);for(a=0;a<b.length;a++)f.push(b[a]);f.push(b.length);break;case 205:a=f.pop()!=0;b=f.pop();b=yc(b,a);f.push(b.length);break;case 206:f.push(86);break;case 207:f.push(3);break;case 208:f.push(1);break;case 209:b=f.pop();a=ma(b);f.push(a.width);f.push(a.height);break;case 210:b=f.pop();h=f.pop();f.push(Jd(b,h));break;case 211:a=b=f.pop();b=[];c=yc(q(a,0),1);for(h=0;h<c.length;h++)a<c[h]&&Jd(c[h],a)>=40&&b.push(c[h]);for(;b.length;)Wb(b.pop(),0,a);break;case 212:b=f.pop();a=yc(b,1);b=q(b,0);for(c=
0;c<a.length;c++)Wb(a[c],0,b);break;case 213:return d=f.pop(),Mc(d,Y[0].D,Y[0].target),!0;case 214:Lc(f.pop());break;case 215:E=3;break;case 216:E=2;break;case 217:return d=f.pop(),setTimeout(S,d/60*1E3),!0;case 218:return ec(!1),Jc(J),Kc(J),B=!0;case 219:mc();break;case 220:if(oc(!0))return!0;break;case 221:if(nc())return!0;break;case 222:if(ec(!0))return!0;break;case 223:return d=f.pop(),zd(K),setTimeout(Kd,d/60*1E3),!0;case 224:f.pop();break;case 225:f.pop();break;case 226:b=f.pop();h=f.pop();
h*=b;a=f.pop();h/=a;f.push(h|0);break;case 227:b=f.pop();a=j;if(a=q(1,0)==b?K:wc(b))tc(b),mc(),Ub(a);break;case 228:f.push(0);break;case 229:break;case 230:f.push(Hd);break;case 231:c=f.pop();b=1;for(a=Hd=0;a<c;a++)Hd+=b,Hd^=b,b^=Hd,Hd^=b;break;default:fatal("Unknown function:"+a.toString(16))}else f.push(a);return!1}function Kd(){zd(K);S()}function Id(a,b,c){var d=0;a=yc(a,c);for(c=0;c<a.length;c++)d+=q(a[c],b);return d}
function Jd(a,b){if(q(a,0)!=q(b,0))return 0;var c=ma(a),d=ma(b);if(ja(d,c,d))return d.width*d.height*100/(c.width*c.height)|0;return 0};function C(a,b,c,d){switch(c&255){case 2:return new Ld(a,b,d);case 10:return new Md(a,b,d);case 15:return new Nd(a,b,d);case 17:return new Od(a,b,d);case 22:return new Pd(a,b,d);case 23:return new Qd(a,b);case 24:return new Rd(a,b,d);case 25:return new Sd(a,b,d);default:fatal("Unknown control:"+c.toString(16))}}
function Ld(a,b,c){var d=this,e=$(document.createElement("canvas"));e.addClass("cbutton");e.css("left",a[0]+"px");e.css("top",a[1]+"px");e.attr("width",a[2]);e.attr("height",a[3]);e.mousedown(function(a){Wc(d,a);return!1});this.b=e;this.o=b;this.selected=!1;this.Ia=c[0];this.f=c[1];this.Ja=c[2]}m=Ld.prototype;m.hide=function(){this.b.hide()};m.show=function(){this.b.show();this.i()};
m.i=function(){var a=this.b.get(0).getContext("2d"),b=this.b.width(),c=this.b.height(),d=a.getImageData(0,0,b,c),e=this.selected?this.Ja:this.f;if(e)for(var g=0;g<c;g++)for(var i=(g>>1)*this.Ia,h=g*d.width*4,f,k=0;k<b;k++)f=e.charCodeAt(i+(k>>2)),f=(f>>(k&2?0:4)&15)*3,d.data[h++]=x[f++],d.data[h++]=x[f++],d.data[h++]=x[f++],d.data[h++]=255;else for(g=0;g<c;g++){h=g*d.width*4;for(k=0;k<b;k++){f=this.selected?0:255;if(g<2||k<4||g>c-3||k>b-5)f=0;d.data[h++]=f;d.data[h++]=f;d.data[h++]=f;d.data[h++]=
255}}a.putImageData(d,0,0)};m.select=function(){this.selected=!0;this.i()};m.L=function(){this.selected=!1;this.i()};function Md(a,b,c){var d=this,e=$(document.createElement("div"));e.addClass("button");e.css("left",a[0]+"px");e.css("top",a[1]+"px");e.css("width",a[2]+"px");e.css("height",a[3]+"px");e.html(c[0]);e.mousedown(function(a){Wc(d,a);return!1});this.b=e;this.o=b}Md.prototype.hide=function(){this.b.hide()};Md.prototype.show=function(){this.b.show()};Md.prototype.i=aa();
function Nd(a,b,c){this.b=$(document.createElement("div"));this.b.addClass("textblock");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.o=b;this.U(c[0])}Nd.prototype.U=function(a){this.b.html(a)};Nd.prototype.hide=function(){this.b.hide()};Nd.prototype.show=function(){this.b.show()};Nd.prototype.i=aa();
function Od(a,b,c){this.b=$(document.createElement("input"));this.b.addClass("textinput");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.b.val(c[0]);this.o=b}Od.prototype.hide=function(){this.b.hide()};Od.prototype.show=function(){this.b.show()};Od.prototype.i=aa();
function Pd(a,b,c){this.b=$(document.createElement("div"));this.b.addClass("textblock");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.o=b;this.U(c[0])}Pd.prototype.hide=function(){this.b.hide()};Pd.prototype.show=function(){this.b.show()};Pd.prototype.i=aa();
Pd.prototype.U=function(a){for(var b="",c=0;c<a.length;c++)a.charCodeAt(c)==1?(a.charCodeAt(c+1)==74&&this.b.css("text-align","center"),c+=2):b+=a.charCodeAt(c)==13?"<br />":a.charAt(c);this.b.html(b)};function Qd(a,b){this.b=$(document.createElement("div"));this.b.addClass("list");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.o=b}Qd.prototype.hide=function(){this.b.hide()};Qd.prototype.show=function(){this.b.show()};
Qd.prototype.i=aa();
function Rd(a,b,c){this.value=parseInt(c[0],10);this.o=b;this.min=parseInt(c[1],10);this.max=parseInt(c[2],10);this.width=a[2];b=$(document.createElement("div"));b.addClass("hscroll");b.css("left",a[0]+"px");b.css("top",a[1]+"px");b.css("width",a[2]+"px");b.css("height",a[3]+"px");this.b=b;c=$(document.createElement("div"));c.addClass("leftarrow");c.css("top","0px");c.css("left","0px");b.append(c);var d=$(document.createElement("div"));d.addClass("rightarrow");d.css("top","0px");d.css("left",a[2]-
Xa+"px");b.append(d);a=$(document.createElement("div"));a.addClass("slider");a.css("top","0px");a.css("left","50px");a.css("width","20px");b.append(a);this.La=a;b.mousedown(function(){fatal("mousedown")});c.mousedown(function(){fatal("left")});d.mousedown(function(){fatal("right")});a.mousedown(function(){fatal("slider")})}Rd.prototype.hide=function(){this.b.hide()};Rd.prototype.show=function(){this.b.show();this.i()};
Rd.prototype.i=function(){this.La.css("left",(this.value*(this.width-52)/(this.max-this.min)|0)+32+"px")};function id(a,b){a.value=b;a.i()}function Sd(a,b,c){var d=this,e=$(document.createElement("div"));e.addClass("sbutton");e.css("left",a[0]+"px");e.css("top",a[1]+"px");e.css("width",a[2]-2+"px");e.css("height",a[3]-2+"px");e.html(c[0]);e.mousedown(function(a){Wc(d,a);return!1});this.b=e;this.o=b}m=Sd.prototype;m.hide=function(){this.b.hide()};m.show=function(){this.b.show()};m.select=function(){this.b.addClass("active")};
m.L=function(){this.b.removeClass("active")};m.i=aa();var Jb=!0,Ib=j,Nc="",Fc=j,Gc=j;
function W(a){if(Jb){if(a&32768)a=Nc;else{a=new za(mb(2,a));for(var b=!1,c="",d=y(a);d--;){var e=a.f(5);if(e>0&&e<27)e|=64,b&&(e|=32),b=!0,c+=String.fromCharCode(e);else switch(e){case 0:c+=" ";break;case 27:c+=b?".":",";b=!0;break;case 28:c+=b?"'":'"';b=!0;break;case 29:b=a.f(16);b&32768?(b^=65535,b=Td(b)):b=W(b);b&&(c+=b);b=!0;break;case 30:c+=String.fromCharCode(a.f(8));b=!0;break;case 31:b=!b}}a=ga(c)}return a}if(a&32768)return Nc;a=new za(mb(2,a));d="";for(c=a.f(1)?a.f(15):a.f(7);c--;){b=ub(a);
b>>=16-a.q;b&=65535;for(e=0;e<Ib.length;e++)if(b<Ib.ba[e])break;a.q+=Ib.aa[e];a.q&16&&(a.q&=15,a.seek(2,a.n));b=Ib.ca[e];b==1&&(b=a.f(7));b!=2?d+=String.fromCharCode(b):(a.f(1)?(b=a.f(15),b=W(b)):(b=a.f(8),b=Td(b)),b&&(d+=b))}return ga(d)}function Td(a){var b,c;b=a&8?Gc:Fc;if((a&3)==1)b=q(b,7),c=["he","she","it"][(b>>4&3)+1-1];else{c=W(b);if(c=="")throw"text failure";switch(a&3){case 2:c=Ud(0,b)+c;break;case 3:c=Ud(2,b)+c}}c.length&&a&4&&(c=c.substr(0,1).toUpperCase()+c.substr(1));return c}
function Ud(a,b){var c=q(b,7)>>a&3;if(c)return["the ","a ","an "][c-1];return""};function mb(a,b){if(b>=yb[a].K)return"";var c,d;yb[a].da?(c=yb[a].ea[b],d=yb[a].fa[b]):(c=yb[a].Ba,d=b*c);if(!c)return"";return yb[a].data.substring(d,d+c)}var yb=[];var pb=!1,qb=!1;try{var Vd=document.createElement("audio").canPlayType("audio/wav");pb=Vd!=""&&Vd!="no"}catch(Wd){}function nb(a,b){this.data=Array(a);this.B=a;this.O=b}nb.prototype.play=function(){var a=$(document.createElement("audio"));$(document.body).append(a);a.attr("src","data:audio/x-wav;base64,"+Xd(this));var b=hd();b==null&&(b=50);a.attr("volume",b/100);a.bind("ended",function(){a.remove()});a.get(0).play()};
function Xd(a){var b=Array(44+a.B);b[0]=82;b[1]=73;b[2]=70;b[3]=70;var c=36+a.B;b[4]=c&255;b[5]=c>>8&255;b[6]=c>>16&255;b[7]=c>>24&255;b[8]=87;b[9]=65;b[10]=86;b[11]=69;b[12]=102;b[13]=109;b[14]=116;b[15]=32;b[16]=16;b[17]=0;b[18]=0;b[19]=0;b[20]=1;b[21]=0;b[22]=1;b[23]=0;b[24]=a.O&255;b[25]=a.O>>8&255;b[26]=a.O>>16&255;b[27]=a.O>>24&255;b[28]=b[24];b[29]=b[25];b[30]=b[26];b[31]=b[27];b[32]=1;b[33]=0;b[34]=8;b[35]=0;b[36]=100;b[37]=97;b[38]=116;b[39]=97;b[40]=a.B&255;b[41]=a.B>>8&255;b[42]=a.B>>16&
255;b[43]=a.B>>24&255;for(c=0;c<a.B;c++)b[44+c]=a.data[c];a="";var d,e,g,i=0;do d=b[i++],e=b[i++],g=b[i++],c=d>>2,d=(d&3)<<4,e==j?e=g=64:g==j?(d|=e>>4,e=(e&15)<<2,g=64):(d|=e>>4,e=(e&15)<<2|g>>6,g&=63),a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g);
while(i<b.length);return a};var Yd=document.createElement("link");Yd.type="text/css";Yd.rel="stylesheet";Yd.href="gs.css";$("head").append(Yd);ca=$(document.createElement("img"));ca.attr("src","images/gs/start.png");ca.css("width","100%");ca.css("height","100%");desktop.append(ca);
(function(a){$.ajax({url:a,Pa:function(a){a.overrideMimeType("text/html; charset=x-user-defined")},complete:function(a){a=new za(a.responseText);var c=a.data.substring(a.g,a.g+4);a.g+=4;c!="2IMG"&&fatal("Not a valid 2mg file");a.seek(12,a.set);wa(a)!=1&&fatal("Not in ProDOS format");a.seek(20,a.set);c=wa(a)*512;var d=wa(a);a.seek(d,a.set);s=new za(v(a,c));delete a}})})(gamename);setTimeout(vb,10);
