var m,aa,ba;function ca(){var a=da.port.width(),b=da.port.height();ba=p([4,4,a-8,b-8],255,25,["Click to continue"]);ba.b.addClass("ctc");a=da;for(b=0;b<a.i.length;b++)a.i[b].hide();da.add(ba);q=!0}function ea(a,b,c){var d=fa(s("CNTL",128));d.o=c;c=d.b.position();d.b.css("left",c.left+a+"px");d.b.css("top",c.top+b+"px");return d}
function ga(a){for(var b="",c=0;c<a.length;c++)switch(a.charCodeAt(c)){case 13:b+="<br />";break;case 63368:b+="&#224;";break;case 63374:b+="&#233;";break;case 63401:b+="&#169;";break;case 63433:b+="...";break;case 63441:b+="&#8212;";break;default:b+=a.charAt(c)}return b}function ha(){return t?ia[t-1]:3E3}
function ja(a,b){var c={top:0,left:0,width:0,height:0},d;if(d=ka(2*a+1)){c.width=d.width;c.height=d.height;if(la(c,b,c))a:{for(var e=c.top;e<c.top+c.height;e++)for(var g=e*d.q,k,h=c.left;h<c.left+c.width;h++)if(k=d.data[g+(h>>3)]&1<<7-(h&7)){c=!0;break a}c=!1}else c=!1;return c}return(d=ka(2*a))?(c.width=d.width,c.height=d.height,la(c,b,c)):!1}
function ma(a){var b={top:0,left:0,width:0,height:0},c=na(a),d=0;c&&c.a&&(d=oa(c.a.children,a));if(d){d--;var e=c.a.children[d];if(0==e.width||0==e.height)a=pa(a,c,!0),c.a.children[d].top=a.top,c.a.children[d].left=a.left,c.a.children[d].width=a.width,c.a.children[d].height=a.height;b.top=c.a.children[d].top;b.left=c.a.children[d].left;b.width=c.a.children[d].width;b.height=c.a.children[d].height}else(c=ka(2*a))?(b.top=v(a,2),b.left=v(a,1),b.width=c.width,b.height=c.height):(c=ka(2*a+1))?(b.top=v(a,
2),b.left=v(a,1),b.width=c.width,b.height=c.height):(b.top=0,b.left=0,b.width=0,b.height=0);return b}function qa(a){var b=ka(2*a);a=ka(2*a+1);var c=b.width,d=b.height;a&&(c<a.width&&(c=a.width),d<a.height&&(d=a.height));var e=$(document.createElement("canvas"));e.addClass("proxy");e.attr("width",c);e.attr("height",d);desktop.append(e);a?ra(a,e,0,0):sa(e,0,0,e.width(),e.height(),0);ta(b,e,0,0);return e};function ua(a){for(var b=0,c=0,d=0;4>d;d++)b|="APPL".charCodeAt(d)<<24-8*d,c|=a.charCodeAt(d)<<24-8*d;for(d in w)if(w[d].type==b&&w[d].qa==c)return y.seek((w[d].na+va)*wa,y.set),new xa(z(y,w[d].X))}function ya(a){for(var b in w)if(w[b].name==a){if(0==w[b].Z)break;y.seek((w[b].ra+va)*wa,y.set);return new xa(z(y,w[b].Z))}}function za(a){for(var b in w)if(w[b].name==a){if(0==w[b].X)break;y.seek((w[b].na+va)*wa,y.set);return new xa(z(y,w[b].X))}}var w=[],y=void 0,wa,va,Aa;
function Ba(a,b){var c=a+512*b;y.seek(c+8,y.set);var d=A(y);A(y);var e=B(y);switch(d){case 0:for(d=0;d<e;d++){y.seek(c+512-2*(d+1),y.set);var g=B(y);y.seek(c+g,y.set);var k=A(y);y.seek(c+g+k+1,y.set);g=C(y);Ba(a,g)}break;case 255:for(d=0;d<e;d++)if(y.seek(c+512-2*(d+1),y.set),g=B(y),g=c+g,y.seek(g,y.set),k=A(y),0!=k){k++;k&1&&k++;A(y);var h=C(y),f=A(y),f=z(y,f);y.seek(g+k,y.set);switch(B(y)){case 512:h={parent:h,name:f},y.seek(g+k+4,y.set),h.type=C(y),h.qa=C(y),y.seek(g+k+20,y.set),f=C(y),y.seek(2,
y.j),h.Z=C(y),y.seek(6,y.j),h.X=C(y),y.seek(g+k+74,y.set),h.ra=B(y),y.seek(g+k+86,y.set),h.na=B(y),w[f]=h}}break;default:fatal("Bad HFS Node")}};var Ca=[],Da=!1;function Ea(a,b,c){this.width=a;this.height=b;this.q=c;this.H=a;this.G=b;this.data=Array(b*c)}
Ea.prototype.m=function(a,b,c){if(0!=this.width&&0!=this.height){var d=a.get(0).getContext("2d"),e=this.width,g=this.height,k=0,h=0;0>b&&(k=-b,b=0);0>c&&(h=-c,c=0);e+b>=a.width()&&(e=a.width()-b);g+c>=a.height()&&(g=a.height()-c);if(0!=e&&0!=g){a=d.getImageData(b,c,e,g);for(var f=h;f<g;f++)for(var l=f*this.q,n=(f-h)*a.width*4,r,u=k;u<e;u++)r=(r=this.data[l+(u>>3)]&1<<7-(u&7))?0:255,a.data[n++]=r,a.data[n++]=r,a.data[n++]=r,a.data[n++]=255;d.putImageData(a,b,c)}}};
function ra(a,b,c,d){if(0!=a.width&&0!=a.height){var e=b.get(0).getContext("2d"),g=a.width,k=a.height,h=0,f=0;0>c&&(h=-c,c=0);0>d&&(f=-d,d=0);g+c>=b.width()&&(g=b.width()-c);k+d>=b.height()&&(k=b.height()-d);if(0!=g&&0!=k){b=e.getImageData(c,d,g,k);for(var l=f;l<k;l++)for(var n=l*a.q,r=(l-f)*b.width*4,u,x=h;x<g;x++)(u=a.data[n+(x>>3)]&1<<7-(x&7))?(b.data[r++]=255,b.data[r++]=255,b.data[r++]=255,b.data[r++]=255):r+=4;e.putImageData(b,c,d)}}}
function ta(a,b,c,d){if(0!=a.width&&0!=a.height){var e=b.get(0).getContext("2d"),g=a.width,k=a.height,h=0,f=0;0>c&&(h=-c,c=0);0>d&&(f=-d,d=0);g+c>=b.width()&&(g=b.width()-c);k+d>=b.height()&&(k=b.height()-d);if(0!=g&&0!=k){b=e.getImageData(c,d,g,k);for(var l=f;l<k;l++)for(var n=l*a.q,r=(l-f)*b.width*4,u,x=h;x<g;x++)(u=a.data[n+(x>>3)]&1<<7-(x&7))?(b.data[r++]^=255,b.data[r++]^=255,b.data[r++]^=255,b.data[r++]=255):r+=4;e.putImageData(b,c,d)}}}
Ea.prototype.W=function(a,b){return 0!=(this.data[b*this.q+(a>>3)]&1<<7-(a&7))};function sa(a,b,c,d,e,g){a=a.get(0).getContext("2d");for(var k=a.getImageData(b,c,d,e),h=0;h<e;h++)for(var f=h*k.width*4,l=g?0:255,n=0;n<d;n++)k.data[f++]=l,k.data[f++]=l,k.data[f++]=l,k.data[f++]=255;a.putImageData(k,b,c)}
function Fa(a){var b=new Ea(512,302,64),c=Array(72);a.seek(512,a.set);for(var d=0,e=0;e<b.G;e++){for(var g=0;72>g;){var k=A(a);if(128!=k)if(k&128)for(var k=k^255,k=k+2,h=A(a),f=0;f<k;f++)c[g++]=h;else for(k++,f=0;f<k;f++)c[g++]=A(a)}for(f=0;64>f;f++)b.data[d++]=c[f]}return b}function Ga(){var a=Ha(131),b=za(a),c;if(void 0!=b){var b=Ia(b),d=s("PPIC",0);void 0!=d&&(c=Ja(d));delete Ka[b];Ka.splice(b,1)}void 0==c&&(c=Fa(ya(a)));return c};function Ia(a){Ka.push(a);return Ka.length-1}function s(a,b){for(var c=a.charCodeAt(0)<<24|a.charCodeAt(1)<<16|a.charCodeAt(2)<<8|a.charCodeAt(3),d=Ka.length-1;0<=d;d--){var e=Ka[d];e.seek(0,e.set);var g=C(e),k=C(e);e.seek(k+24,e.set);k+=B(e);e.seek(k,e.set);for(var h=B(e)+1,f=0;f<h;f++){if(C(e)==c){c=B(e)+1;e.seek(k+B(e),e.set);for(f=0;f<c;f++){if(B(e)==b)return e.seek(2,e.j),g+=C(e)&16777215,e.seek(g,e.set),g=C(e),new xa(z(e,g));e.seek(10,e.j)}return}e.seek(4,e.j)}}}
function Ha(a){a=s("STR ",a);if(void 0==a)return"";var b=A(a);return z(a,b)}function La(a,b){if(0==b)return"";var c=s("STR#",a);if(void 0==c)return"";var d=B(c);if(b>d)return"";for(;;){b--;if(0==b)return d=A(c),z(c,d);d=A(c);c.seek(d,c.j)}}function fa(a){var b=B(a),c=B(a),d=B(a)-b,e=B(a)-c;B(a);A(a);A(a);B(a);B(a);var g=B(a),k=C(a),h=A(a),f="";0!=h&&(f=z(a,h));a=[];h=0;switch(g>>4){case 0:h=10;a=[f];break;case 128:h=25,a=[f]}return p([c,b,e,d],k,h,a)}var Ka=[];function Ma(a){var b=B(a);a.seek(12,a.j);var c=A(a),d="";0!=c&&(d=z(a,c));1==c&&(d="");D={id:b};D.b=$(document.createElement("div"));""==d?D.b.addClass("apple"):D.b.html(d);D.b.data("refCon",D);D.b.mousedown(function(a){if(q)return!1;Na(a);return!1});D.p=$(document.createElement("table"));D.p.addClass("menu");D.body=$(document.createElement("tbody"));D.p.append(D.body);D.items=[];d.match(/(Edit)|(Font)/i)||Oa.append(D.b);E.push(D);for(c=0;;){var e=A(a);if(0==e)break;d="";0!=e&&(d=ga(z(a,e)));A(a);
e=A(a);A(a);A(a);e=0!=e?String.fromCharCode(e):"";Pa(d,b<<8|c,e);c++}};var Qa=1,Ra=18,Sa=18,Ta=2,Ua=15,Va=15,Wa=15,Xa=15,Ya=2,Za=0;function $a(){var a=s(La(129,1),0),b=A(a);z(a,b);a=ab(146,96,220,150);a.add(p([75,120,70,18],1,10,["Ok"]));a.add(p([20,10,180,80],3,15,["&#169; 2014 Zojoi LLC.<br />"+fullGameName+" is a registered trademark of Zojoi LLC. All rights reserved.<br />Programming by Sean Kasun"]));a.getItem(3).b.css("text-align","center");return a}
function bb(){var a=ab(146,96,220,120);a.add(p([75,90,70,18],1,10,["Ok"]));a.add(p([55,55,110,14],2,24,[0,0,100]));a.add(p([20,25,180,20],3,15,["Sound Volume"]));a.getItem(3).b.css("text-align","center");return a}function eb(a){a=ga(La(128,[8,9,7][a]));var b=fb(s("ALRT",131));b.param([a]);return b}function gb(){var a=ab(82,71,348,200);a.add(p([256,138,80,18],1,10,["Open"]));a.add(p([256,163,80,18],2,10,["Cancel"]));a.add(p([12,39,218,146],3,23,[]));return a}
function hb(){var a=ab(104,79,304,184);a.add(p([218,132,70,18],1,10,["Save"]));a.add(p([218,158,70,18],2,10,["Cancel"]));a.add(p([14,136,183,16],5,15,["Save as:"]));a.add(p([17,157,177,16],3,17,[""]));a.add(p([14,29,183,98],4,23,[]));return a}function ib(){for(var a=F.left,b=F.top,c=0;c<F.Q;c++)a+=F.ya,b+=F.za,388<=b&&(b=F.top),628<=a&&(a=F.left);F.Q++;a=jb("zoomDoc",!0,!0,!0,!0,a,b,F.width,F.height);a.kind=14;return a}
function kb(){var a=s("GNRL",129);B(a);var b=B(a),c=B(a),d=B(a),e=B(a)-c,a=B(a)-d,c=p([d,c,a,e],5,17,[""]);c.b.css("text-align","center");c.b.css("font-size",b+"px");c.b.css("line-height",e+"px");return c}
function lb(a){var b=B(a),c=B(a),d=B(a)-b,e=B(a)-c,g="",k=!1;switch(B(a)){case 0:g="document";break;case 1:g="dBox";break;case 2:g="plainDBox";break;case 3:g="altDBox";break;case 4:g="noGrowDoc";break;case 5:g="movableDBox";break;case 8:g="zoomDoc";k=!0;break;case 12:g="zoomNoGrow";k=!0;break;case 16:g="rDoc16";break;case 18:g="rDoc4";break;case 20:g="rDoc6";break;case 22:g="rDoc10"}B(a);var h=0!=B(a);C(a);var f=A(a),l="";1!=f&&(l=ga(z(a,f)));a=jb(g,h,k,!1,!1,c,b,e,d);mb(a,l);return a}
function fb(a){var b=B(a),c=B(a),d=B(a)-b,e=B(a)-c,g=B(a);a=ab(c,b,e,d);for(var g=s("DITL",g),k=B(g)+1,h=0;h<k;h++){C(g);var b=B(g),c=B(g),d=B(g)-b,e=B(g)-c,f=A(g),l=A(g),n="";0<l&&(n=ga(z(g,l)));l&1&&A(g);switch(f&127){case 4:a.add(p([c,b,e,d],h+1,10,[n]));break;case 8:a.add(p([c,b,e,d],h+1,15,[n]));break;case 16:a.add(p([c,b,e,d],h+1,17,[n]));break;default:fatal("Unknown DITL:"+(f&127))}}return a}
function nb(a){var b=B(a),c=B(a),d=B(a)-b,e=B(a)-c,g="",k=!1;switch(B(a)){case 0:g="document";break;case 1:g="dBox";break;case 2:g="plainDBox";break;case 3:g="altDBox";break;case 4:g="noGrowDoc";break;case 5:g="movableDBox";break;case 8:g="zoomDoc";k=!0;break;case 12:g="zoomNoGrow";k=!0;break;case 16:g="rDoc16";break;case 18:g="rDoc4";break;case 20:g="rDoc6";break;case 22:g="rDoc10"}A(a);A(a);var h=0!=A(a);A(a);C(a);var f=B(a),l=A(a),n="";1!=l&&(n=ga(z(a,l)));a=s("DITL",f);k=jb(g,h,k,!1,!1,c,b,e,
d);mb(k,n);k.kind=2;h=B(a)+1;for(f=0;f<h;f++)switch(C(a),b=B(a),c=B(a),d=B(a)-b,e=B(a)-c,g=A(a),l=A(a),n="",0<l&&(n=ga(z(a,l))),l&1&&A(a),g&127){case 4:k.add(p([c,b,e,d],f+1,10,[n]));break;case 8:k.add(p([c,b,e,d],f+1,15,[n]));break;case 16:k.add(p([c,b,e,d],f+1,17,[n]));break;default:fatal("Unknown DITL:"+(g&127))}return k};function ob(a){var b=pb(4,a);a=new xa(b);var c=void 0;switch(b.charCodeAt(5)&255){case 16:var d=[];a.seek(408,a.set);for(var e=0;16>e;e++)d[e]=A(a);var g=2*C(a);B(a);for(var e=22100*C(a)/65536|0,k=new qb(g,e),h,e=0;e<g;e++)h=e&1?h>>4:A(a),k.data[e]=d[h&15];c=k;break;case 18:a.seek(12,a.set);d=B(a);a.seek(52,a.set);h=B(a)+52;a.seek(h,a.set);g=C(a)-6;B(a);e=22100*C(a)/65536|0;e=new qb(g*d,e);k=0;b=a.seek(226,a.set)+226;for(c=0;c<d;c++){a.seek(b+2*c,a.set);var f=B(a);a.seek(h+10,a.set);for(var l=0;l<
g;l++){var n=A(a);n&128?(n-=128,n*=f,n=n>>8&255,n&128&&(n=127),n+=128):(n=(n^255)+1,n-=128,n*=f,n=n>>8&255,n&128&&(n=127),n+=128,n=(n^255)+1);e.data[k++]=n}}c=e;break;case 24:d=[];a.seek(594,a.set);for(e=0;16>e;e++)d[e]=A(a);h=2*C(a);B(a);e=22100*C(a)/65536|0;k=new qb(h,e);for(e=0;e<h;e++)g=e&1?g>>4:A(a),k.data[e]=d[g&15];c=k;break;case 26:d=[];a.seek(544,a.set);for(g=0;16>g;g++)d[g]=A(a);h=C(a);B(a);g=22100*C(a)/65536|0;k=new qb(h,g);for(g=0;g<h;g++)e=g&1?e>>4:A(a),k.data[g]=d[e&15];c=k;break;case 68:a.seek(94,
a.set);d=C(a);h=22100*C(a)/65536|0;h=new qb(d,h);for(g=0;g<d;g++)h.data[g]=A(a);c=h;break;case 120:d=[];a.seek(186,a.set);for(g=0;16>g;g++)d[g]=A(a);C(a);h=C(a);g=22100*C(a)/65536|0;e=new qb(h,g);for(g=0;g<h;g++)k=g&1?k<<4:A(a),e.data[g]=d[k>>4&15];c=e;break;case 126:h=[];a.seek(194,a.set);for(e=0;16>e;e++)h[e]=A(a);C(a);g=C(a);e=22100*C(a)/65536|0;k=new qb(g,e);b=128;for(e=0;e<g;e++)d=e&1?d<<4:A(a),b+=h[d>>4&15],k.data[e]=b&255;c=k}if(void 0==c)return 0;rb&&!sb&&c.play();return c.time()};function xa(a){this.set=0;this.j=1;this.end=2;this.data=a;this.length=a.length;this.l=this.h=0}function A(a){return a.data.charCodeAt(a.h++)&255}function B(a){var b=(a.data.charCodeAt(a.h++)&255)<<8;return b|=a.data.charCodeAt(a.h++)&255}function tb(a){var b=(a.data.charCodeAt(a.h++)&255)<<16,b=b|(a.data.charCodeAt(a.h++)&255)<<8;return b|=a.data.charCodeAt(a.h++)&255}
function C(a){var b=(a.data.charCodeAt(a.h++)&255)<<24,b=b|(a.data.charCodeAt(a.h++)&255)<<16,b=b|(a.data.charCodeAt(a.h++)&255)<<8;return b|=a.data.charCodeAt(a.h++)&255}function ub(a){var b=(a.data.charCodeAt(a.h)&255)<<24,b=b|(a.data.charCodeAt(a.h+1)&255)<<16,b=b|(a.data.charCodeAt(a.h+2)&255)<<8;return b|=a.data.charCodeAt(a.h+3)&255}xa.prototype.seek=function(a,b){switch(b){case this.j:a+=this.h;break;case this.end:a+=this.length}this.h=a};
function z(a,b){var c=a.h;a.h+=b;return a.data.substring(c,a.h)}xa.prototype.f=function(a){var b=ub(this),b=b>>>32-this.l-a;this.l+=a;this.l&16&&(this.l&=15,this.h+=2);return b&(1<<a)-1};function vb(){if(void 0!=y){G=0;for(var a,b=1;void 0==a&&5>b;b++)a=ua("MCV"+b);for(b=1;void 0==a&&5>b;b++)a=ua("MCv"+b);Ia(a);aa.remove();delete aa;a=La(129,2);b=za(a);void 0!=b?(b=Ia(b),a=Ja(s("PPIC",0)),delete Ka[b],Ka.splice(b,1)):a=Fa(ya(a));wb=jb("plainDBox",!1,!1,!1,!1,0,0,512,342);wb.show();a.m(wb.port,0,0);for(a=0;5>a;a++){var c=La(129,a+4),b=a,c=ya(c),d={Ba:0,fa:!1};c.seek(0,c.set);var e=c.length,g=C(c),k=void 0;if(g&2147483648){g&=2147483647;d.fa=!0;c.seek(g,c.set);d.M=B(c);for(var e=Array(16),
k=Array(16),h=0;15>h;h++)e[h]=B(c);for(h=0;16>h;h++)k[h]=A(c);d.ka=Array(d.M);d.ga=Array(d.M);for(var f=0,l=void 0,h=0;h<d.M;h++){if(0==(h&63)){c.seek(g+6*(h>>6)+48,c.set);var n=tb(c),l=tb(c),f=n&7;c.seek(g+(n>>3),c.set)}d.ka[h]=l;n=C(c)>>>16-f&65535;c.seek(-4,c.j);var r;for(r=0;16>r&&!(e[r]>n);r++);n=k[r];f+=n&15;f&16&&(f&=15,c.seek(2,c.j));n>>=4;r=0;n&&(r=ub(c),n--,r=0==n?0:r>>>32-n-f,r&=(1<<n)-1,r|=1<<n,f+=n,f&16&&(f&=15,c.seek(2,c.j)),l+=r);d.ga[h]=r}k=g-4}else k=e-=4,d.va=g,d.M=e/g|0;c.seek(4,
c.set);d.data=z(c,k);xb[b]=d}a=s("GNRL",128);yb=B(a);zb=B(a);Ab=B(a);Bb=B(a);Cb=B(a);B(a);F={};F.top=B(a);F.left=B(a);F.height=B(a);F.width=B(a);F.za=B(a);F.ya=B(a);F.Q=0;B(a);B(a);Db=Array(Bb);for(b=0;b<Bb;b++)Db[b]=A(a);Eb=Array(Bb);for(b=0;b<Bb;b++)Eb[b]=B(a);Fb=Array(Bb);for(b=0;b<Bb;b++)Fb[b]=A(a);ia=Array(Ab);for(b=0;b<Ab;b++)ia[b]=A(a);Gb=Array(Ab);for(b=0;b<Ab;b++)Gb[b]=A(a);Hb=[];Jb();H=[];I=[];Mb=[];Nb=[];K=Array(2*yb);b=s("GNRL",131);if(void 0!=b){c={};c.length=B(b);B(b);c.ia=Array(c.length);
for(a=0;a<c.length-1;a++)c.ia[a]=B(b);c.ha=Array(c.length);for(a=0;a<c.length;a++)c.ha[a]=A(b);c.oa=Array(c.length);for(a=0;a<c.length;a++)c.oa[a]=A(b);void 0!=c&&(Ob=c,Pb=!1)}da=lb(s("WIND",128));da.kind=9;da.addClass("commands");for(a=0;a<Ab;a++)Gb[a]&&da.add(fa(s("CNTL",129+a)));L=lb(s("WIND",129));L.kind=10;Qb=lb(s("WIND",130));Qb.kind=11;M=$(document.createElement("div"));M.addClass("textEdit");a=Qb;b=M;c=a.port.attr("width");d=a.port.attr("height");a.port.remove();b.css("top","0px");b.css("left",
"0px");b.css("width",c+"px");b.css("height",d+"px");a.port=b;a.e.append(b);Qb.B=!0;Rb(Qb);Sb=lb(s("WIND",131));Sb.kind=12;Sb.a={id:0,x:0,y:0,children:[{id:1,top:0,left:0,width:0,height:0}]};N=lb(s("WIND",132));N.kind=13;N.addClass("exits");Oa=$(document.createElement("div"));Oa.addClass("menubar");for(a=128;133>=a;a++)Ma(s("MENU",a));D=E[0];Pa("Adjust Volume...",2304,"");D=E[0];Pa("Choose Game...",2305,"");var u;try{u="localStorage"in window&&null!==window.localStorage}catch(x){u=!1}u?(Tb(33026),
Tb(33027),Tb(33028)):(Ub(33026),Ub(33027),Ub(33028));rb?Tb(2304):Ub(2304);mb(Qb,La(128,1));if(1<gameparts.length)Vb=gameparts[1],u=window.JSON.parse(window.localStorage.getItem(Vb).toString()),Wb=u.gamedata,Xb=u.globals,M.html(u.text),mb(Qb,Vb);else{u=ya(Ha(133));Wb=Array(Cb);Xb=Array(zb);for(a=0;a<Cb;a++)for(Wb[a]=Array(yb),b=0;b<yb;b++)Wb[a][b]=B(u);for(a=0;a<zb;a++)Xb[a]=B(u)}Yb();""==Vb&&(O=!0,t=1,P.push(v(1,0)));setTimeout(Zb,500)}else setTimeout(vb,10)}
function Yb(){for(var a,b,c=0;c<2*yb;c++)K[c]=0;for(c=yb-1;c;c--)a=Wb[0][c],(b=K[2*a])&&(K[2*c+1]=b),K[2*a]=c}function $b(){for(var a=[],b=0;b<Q.length;b++)10!=Q[b].kind&&14!=Q[b].kind||a.push(Q[b]);for(b in a)ac(a[b]);F.Q=0;I=[];Mb=[];Nb=[];Hb=[]}var K;function Zb(){bc(wb);delete wb;desktop.append(Oa);da.show();Sb.show();R(Sb);N.show();Qb.show();L.show();G=1;cc=M.get(0).scrollHeight;M.scrollTop(cc-cc%15);dc(v(1,0),6,1);ec=!1;S()};var G=0,ec=!1,cc=0,H,P,t=void 0,O=!1,fc,gc,ia,Gb,Hb,I,Mb,Nb,wb,hc,L,da,Qb,Sb,N,M,yb,zb,Ab,Bb,Cb,Fb,Eb,Db,F,Wb,Xb,ic,T,U,Vb="";function jc(){}var kc=!1,lc=!1,mc=!1,q=!1,V=void 0;function S(){if(4==G)window.cefQuery({request:"quit"});else{kc||nc(!1);if(O||kc){kc=!1;if(oc()){q=kc=!0;return}q=!1;if(nc(!0))return;pc()}2!=G&&3!=G||qc();rc()}}
function oc(){if(lc)return lc=!1,sc(!1)?lc=!0:!1;if(mc){mc=!1;if(sc(!1))return mc=!0;if(nc(!0))return!0}for(;P.length;){var a=P.shift();if((0==G||1==G)&&tc(a)){if(uc(t,a))return mc=!0;if(nc(!0))return!0}}if(1==t)ec=!1;else if((0==G||1==G)&&uc(3,t))return lc=!0;return!1}
function tc(a){if(!vc(a)||2<=ha()&&0<T&&!vc(T))return!1;if(5!=t)return!0;if(0!=v(a,3)||0!=v(a,4)||0!=v(a,5))return!1;if(v(1,0)!=T)return!0;var b={top:0,left:0,width:L.port.width(),height:L.port.height()};b.top-=v(a,2)+U.d;b.left-=v(a,1)+U.c;return ja(a,b)}function vc(a){for(var b=v(1,0);0!=a&&1!=a&&a!=b;)a=v(a,0);return a}function nc(a){wc();var b=xc();yc(a)&&(b=!0);return b}
function qc(){if(2==G){zc();var a=Ga();hc=lb(s("WIND",133));hc.show();a.m(hc.port,0,0);Ac();G=4}else if(3==G){pc();var b=fb(s("ALRT",134));b.show(function(a){bc(b);switch(a){case 1:Bc();break;case 3:G=4;S();break;case 4:Cc()}})}}
function Ac(){var a=document.createElement("link");a.type="text/css";a.rel="stylesheet";a.href="print.css";a.media="print";$("head").append(a);a=nb(s("DLOG",135));q=!0;var b=kb();hc.add(b);b.b.focus();a.show(function(a){switch(a){case 1:b.b.blur();window.print();break;case 2:S()}})}
function wc(){for(;I.length;){for(var a,b=0,c=0;c<I.length;c++)I[c].id>b&&(b=I[c].id,a=c);b=I.splice(a,1)[0];switch(b.id){case 2:Dc(b.val);break;case 3:Ec(b.val);break;case 4:Fc(b.val);break;case 7:a:{var c=b.val,d=!1,b=c.b,e=Hb.indexOf(b);-1!=e&&Hb.splice(e,1);if(1==b)c.parent!=v(b,0)&&I.push({id:12}),c.ja==v(b,3)&&c.ea==v(b,4)||R(na(b));else if(c.parent!=v(b,0)||c.x!=v(b,1)||c.y!=v(b,2)){if(e=Gc(c.parent))d=e,void 0!=d.a&&(e=oa(d.a.children,b),0!=e&&(d.a.children.splice(e-1,1),d.a.s=!0,R(d))),d=
!0;if(e=na(b)){d=e;if(void 0!=d.a){e=void 0;for(e=0;e<d.a.children.length&&b>d.a.children[e].id;e++);if(e==d.a.children.length||b!=d.a.children[e].id)d.a.children.splice(e,0,{id:b,top:0,left:0,width:0,height:0}),d.a.s=!0,R(d)}d=!0}}else c.ja==v(b,3)&&c.ea==v(b,4)||R(na(b));v(b,8)&&(d||c.hidden!=v(b,11)||c.ta!=v(b,9)||c.ua!=v(b,10))&&Hc(b);c=Gc(b);d=b;for(e=v(1,0);d!=e&&0!=d&&v(d,6);)d=v(d,0);if(d==e){if(c)break a;I.push({id:3,val:b})}else{if(!c)break a;I.push({id:4,val:b})}b=Ic(b,!0);for(e=0;e<b.length;e++)Jc(b[e])}break;
case 8:b=b.val;d=Gc(b.P);(c=e=Gc(b.O))||(c=d);c&&(d=W(b.O),mb(c,d),Kc(b.O,c),c.a.s=!0,R(c));break;case 12:dc(L.a.id,6,0);dc(v(1,0),6,1);break;case 13:for(;H.length;)Lc(H.pop());break;case 14:Mc(b.val)}}}function Dc(a){a&&(a=Gc(a))&&Nc(a)}
function Ec(a){if(!Gc(a))if(a==v(1,0)){Kc(a,L);R(L);Oc();var b=W(a);mb(L,b.substr(0,1).toUpperCase()+b.substr(1))}else{var c={c:v(a,1),d:v(a,2)};Pc(na(a),c);Qc(c);var b=W(a),d=ib();mb(d,b);Kc(a,d);d.a.s=!0;var e=$(document.createElement("div"));e.addClass("zoom");desktop.append(e);e.css("top",c.d+"px");e.css("left",c.c+"px");e.css("width","0px");e.css("height","0px");e.animate({top:d.top+"px",left:d.left+"px",width:d.width+"px",height:d.height+"px"},500,"swing",function(){e.remove();d.show();R(d)})}}
function Fc(a){var b=ac(Gc(a));if(void 0!=b&&(a=na(b.b),void 0!=a)){var c=$(document.createElement("div"));c.addClass("zoom");desktop.append(c);c.css("top",b.top+"px");c.css("left",b.left+"px");c.css("width",b.width+"px");c.css("height",b.height+"px");b={c:v(b.b,1),d:v(b.b,2)};Pc(a,b);Qc(b);c.animate({top:b.d+"px",left:b.c+"px",width:"0px",height:"0px"},500,"swing",function(){c.remove();F.Q--})}}
function Lc(a){var b=N.find(a);b&&(-1!=H.indexOf(a)?b.select():b.J());a==v(1,0)&&(-1!=H.indexOf(a)?N.addClass("selected"):N.removeClass("selected"));R(na(a))}function Mc(a){desktop.append(V);var b={c:v(a,1),d:v(a,2)};Pc(na(a),b);Qc(b);V.animate({top:b.d+"px",left:b.c+"px"},300,"swing",function(){V.remove()})}
function xc(){if(M.get(0).scrollHeight==M.innerHeight()){var a=M.clone();a.css("height","");a.css("visibility","hidden");$("body").append(a);cc=a.innerHeight();a.remove();delete a}for(;Nb.length;)switch(a=Nb.splice(0,1)[0],a.id){case 1:M.append(a.val);ec=!0;break;case 2:M.append("<br/>");ec=!0;break;case 3:Rc=a.val[1],Sc=a.val[0],M.append(W(a.val[2])),ec=!0}return Tc()}
function Tc(){var a=M.get(0).scrollHeight,b=M.innerHeight();M.scrollTop(cc-cc%15);cc=M.scrollTop()+b+15;Uc(Qb,{left:0,right:0,top:0,bottom:a});return cc<a?(ca(),!0):!1}function yc(a){for(var b=0;Mb.length;){var c=Mb.splice(0,1)[0];switch(c.id){case 1:ob(c.val);break;case 2:b=ob(c.val)}}return a&&b?(setTimeout(S,1E3*b),!0):!1}
function dc(a,b,c){if(1==b||2==b)c=Math.round(c/1);if(0==b){var d=c,e=Wb[0][a];if(d!=a){for(var g=2*e,e=K[g];e!=a;)g=2*e+1,e=K[g];K[g]=K[2*e+1];g=2*d;for(e=K[g];e&&e<=a;)g=2*e+1,e=K[g];K[2*a+1]=e;K[g]=a}}12>b&&Jc(a);d=Db[b];c<<=Fb[b];c&=Eb[b];Wb[d][a]=c|Wb[d][a]&~Eb[b];ec=!0}function v(a,b){var c,d=Db[b];if(d&128){var e=pb(0,a);if(0==e.length)return 0;d&=127;c=(e.charCodeAt(2*d)&255)<<8;c|=e.charCodeAt(2*d+1)&255}else c=Wb[d][a];c&=Eb[b];c=Vc(c>>Fb[b]);if(1==b||2==b)c*=1;return c}
function R(a){if(void 0!=a&&void 0!=a.a&&(a==Sb||1==v(a.a.id,6))){if(a==L)ka(2*a.a.id).m(L.port,0,0);else{var b=a.port,c=Za;sa(b,0,0,b.width(),b.height(),c)}for(b=0;b<a.a.children.length;b++)c=pa(a.a.children[b].id,a,0),a.a.children[b].top=c.top,a.a.children[b].left=c.left,a.a.children[b].width=c.width,a.a.children[b].height=c.height;if(14==a.kind&&a.a.s){b={top:0,left:0,right:0,bottom:0};a.a.s=!1;for(c=0;c<a.a.children.length;c++){var d=a.a.children[c];b.right==b.left||b.bottom==b.top?(b.top=d.top,
b.left=d.left,b.bottom=d.top+d.height,b.right=d.left+d.width):(b.top=Math.min(b.top,d.top),b.left=Math.min(b.left,d.left),b.bottom=Math.max(b.bottom,d.top+d.height),b.right=Math.max(b.right,d.left+d.width))}b.right==b.left||b.bottom==b.top?(b.top=a.a.y,b.left=a.a.x,b.bottom=a.a.y,b.right=a.a.x):(b.left>a.a.x&&(b.left=a.a.x),b.right<a.a.x&&(b.right=a.a.x),b.top>a.a.y&&(b.top=a.a.y),b.bottom<a.a.y&&(b.bottom=a.a.y));Uc(a,b)}}}function Wc(a){a=da.find(a);a!=ic&&(ic&&ic.J(),(ic=a)&&a.select())}
function Xc(a){var b=X[0].C;Sc=X[0].target;Rc=b;var c=nb(s("DLOG",132));c.param([W(a)]);c.getItem(3).b.keypress(function(a){return 13==a.which?(c.getItem(1).b.mousedown(),!1):!0});c.show(function(a){Yc=c.getItem(3).b.val();1==a?X[0].state.push(65535):X[0].state.push(0);bc(c);S()})}
function Zc(a){switch(a){case 256:$c();break;case 32768:$c();break;case 33024:ad();break;case 33026:bd();break;case 33027:jc=function(){};cd();break;case 33028:jc=function(){};dd();break;case 33030:ed();break;case 2304:fd();break;case 2305:window.location="index.html";break;case 2306:G=2;S();break;case 33280:break;case 33282:break;case 33283:break;case 33284:break;case 33285:break;case 33536:gd();break;case 33537:hd();break;default:fatal("Unknown menuitem: "+a.toString(16))}}window.menuSelect=Zc;
function id(a,b){var c=a.e;if(2==c.kind)c.sa(a.o);else if(c==N)q||jd(a.o,N,b,!1);else if(255==a.o)da.remove(ba),kd(da),delete ba,Tc()||S();else if(!q){ic&&a!=ic&&ic.J();t=a.o;Wc(t);switch(ha()){case 0:O=!0;break;case 1:O=0!=P.length;break;case 2:0<T&&(O=!0)}S()}}
function jd(a,b,c,d){b==N&&(b=L);if(c.shiftKey)if(a)-1!=P.indexOf(a)?ld(a):md(a),S();else if(14==b.kind)nd(b,c,d);else{if(0==P.length||b!=na(P[0]))-1!=P.indexOf(b.a.id)?ld(b.a.id):md(b.a.id);S()}else if(t&&P.length&&1<ha())a?od(a):od(b.a.id),S();else if(a||(pd(),14==b.kind?nd(b,c,d):a=b.a.id),a){var e;300>=c.timeStamp-fc&&c.target==gc?(fc=0,gc=void 0,e=!0):e=!1;e?(-1==P.indexOf(a)&&pd(),md(a),qd(a,b,c,d)):(-1==P.indexOf(a)&&pd(),md(a),rd(a,b,c,d))}}
function nd(a,b,c){var d,e,g,k,h={c:a.a.x,d:a.a.y};Pc(a,h);Qc(h);d=h.c;e=h.d;g=h.c+a.port.width();k=h.d+a.port.height();var f=$(document.createElement("div"));f.addClass("lasso");desktop.append(f);var l={c:Math.floor(b.pageX/pageZoom),d:Math.floor(b.pageY/pageZoom)};Qc(l);f.css("top",l.d+"px");f.css("left",l.c+"px");f.css("width","0px");f.css("height","0px");$(document).mousemove(function(a){var b={c:Math.floor(a.pageX/pageZoom),d:Math.floor(a.pageY/pageZoom)};Qc(b);a=Math.max(Math.min(l.c,b.c),d);
var c=Math.max(Math.min(l.d,b.d),e),h=Math.min(Math.max(l.c,b.c),g),b=Math.min(Math.max(l.d,b.d),k);f.css("top",c+"px");f.css("left",a+"px");f.css("width",h-a+"px");f.css("height",b-c+"px")});$(document).mouseup(function(h){$(document).unbind("mousemove");$(document).unbind("mouseup");h={c:Math.floor(h.pageX/pageZoom),d:Math.floor(h.pageY/pageZoom)};Qc(h);var r=Math.max(Math.min(l.c,h.c),d),u=Math.max(Math.min(l.d,h.d),e),x=Math.min(Math.max(l.c,h.c),g),Ib=Math.min(Math.max(l.d,h.d),k);f.remove();
h={c:r,d:u};var cb=desktop.offset();h.d+=cb.top;h.c+=cb.left;sd(a,h);u={top:h.d,left:h.c,width:x-r,height:Ib-u};r=[];for(x=0;x<a.a.children.length;x++){var J=a.a.children[x].id;v(J,4)||(u.left=h.c-v(J,1),u.top=h.d-v(J,2),ja(J,u)&&r.push(J))}if(b.shiftKey){if(0==r.length){if(0==P.length||a!=na(P[0]))-1!=P.indexOf(a.a.id)?ld(a.a.id):md(a.a.id)}else for(;r.length;)J=r.shift(),-1!=P.indexOf(J)?ld(J):md(J);S()}else{if(0==r.length)J=a.a.id;else for(;r.length;)J=r.shift(),md(J);jd(J,a,b,c)}})}
function qd(a,b,c,d){var e=Math.floor(c.pageX/pageZoom),g=Math.floor(c.pageY/pageZoom),k={c:0,d:0},h=!1;V=void 0;d&&$(document).mousemove(function(c){if(void 0==V){if(7>=Math.abs(Math.floor(c.pageX/pageZoom)-e)+Math.abs(Math.floor(c.pageY/pageZoom)-g))return!1;h=!0;V=qa(a);var d=oa(b.a.children,a);d&&(d--,k.c=b.a.children[d].left,k.d=b.a.children[d].top);Pc(b,k);Qc(k);V.css("top",k.d+"px");V.css("left",k.c+"px")}d=V.position();V.css("top",d.top+(Math.floor(c.pageY/pageZoom)-g)+"px");V.css("left",
d.left+(Math.floor(c.pageX/pageZoom)-e)+"px");e=Math.floor(c.pageX/pageZoom);g=Math.floor(c.pageY/pageZoom);return!1});$(document).mouseup(function(c){var e;d&&($(document).unbind("mousemove"),V&&(e=V.position(),V.remove()));$(document).unbind("mouseup");h&&(U.c=e.left,U.d=e.top,c=td(Math.floor(c.pageX/pageZoom),Math.floor(c.pageY/pageZoom)),T=c.id,U.c-=k.c,U.d-=k.d,c.e!=b&&(Pc(b,U),c.e&&sd(c.e,U)),t=5,Wc(5),O=!0);O||(od(a),t||(t=4,Wc(4),O=!0));S()})}
function rd(a,b,c,d){var e=Math.floor(c.pageX/pageZoom),g=Math.floor(c.pageY/pageZoom),k={c:0,d:0},h=!1;V=void 0;d&&$(document).mousemove(function(c){if(void 0==V){if(7>=Math.abs(Math.floor(c.pageX/pageZoom)-e)+Math.abs(Math.floor(c.pageY/pageZoom)-g))return!1;h=!0;V=qa(a);var d=oa(b.a.children,a);d&&(d--,k.c=b.a.children[d].left,k.d=b.a.children[d].top);Pc(b,k);Qc(k);V.css("top",k.d+"px");V.css("left",k.c+"px")}d=V.position();V.css("top",d.top+(Math.floor(c.pageY/pageZoom)-g)+"px");V.css("left",
d.left+(Math.floor(c.pageX/pageZoom)-e)+"px");e=Math.floor(c.pageX/pageZoom);g=Math.floor(c.pageY/pageZoom);return!1});$(document).mouseup(function(a){fc=a.timeStamp;gc=a.target;var c;d&&($(document).unbind("mousemove"),V&&(c=V.position(),V.remove()));$(document).unbind("mouseup");h&&(U.c=c.left,U.d=c.top,a=td(Math.floor(a.pageX/pageZoom),Math.floor(a.pageY/pageZoom)),T=a.id,U.c-=k.c,U.d-=k.d,a.e!=b&&(Pc(b,U),a.e&&sd(a.e,U)),t=5,Wc(5),O=!0);1==ha()&&(O=!0);S()})}
function pd(){for(;P.length;)ld(P.shift())}function md(a){P.length&&na(a)!=na(P[0])&&pd();-1==P.indexOf(a)&&P.push(a);-1==H.indexOf(a)&&(H.push(a),Lc(a))}function ld(a){var b=P.indexOf(a);-1!=b&&P.splice(b,1);-1!=(b=H.indexOf(a))&&(H.splice(b,1),Lc(a))}function od(a){if(a!=T){var b;0<T&&-1!=(b=H.indexOf(T))&&-1==P.indexOf(T)&&(H.splice(b,1),Lc(T));T=a;-1==H.indexOf(T)&&(H.push(T),Lc(T));O=!0}}
function pa(a,b,c){var d=v(a,1),e=v(a,2),g=v(a,3);if(c||!g||!v(a,4)){var k=1;g||c?k=0:-1!=H.indexOf(a)&&(k=2);c=d-b.a.x;var e=e-b.a.y,d=b.port,g={top:0,left:0,width:0,height:0},h;if(h=ka(2*a+1))switch(g={top:e,left:c,width:h.width,height:h.height},k){case 1:ra(h,d,c,e);break;case 2:var f=h,l=c,n=e;if(0!=f.width&&0!=f.height){var r=d.get(0).getContext("2d"),u=f.width,x=f.height,Ib=0,cb=0;0>l&&(Ib=-l,l=0);0>n&&(cb=-n,n=0);u+l>=d.width()&&(u=d.width()-l);x+n>=d.height()&&(x=d.height()-n);if(0!=u&&0!=
x){for(var J=r.getImageData(l,n,u,x),Kb=cb;Kb<x;Kb++)for(var ie=Kb*f.q,db=(Kb-cb)*J.width*4,je,Lb=Ib;Lb<u;Lb++)(je=f.data[ie+(Lb>>3)]&1<<7-(Lb&7))?(J.data[db++]=0,J.data[db++]=0,J.data[db++]=0,J.data[db++]=255):db+=4;r.putImageData(J,l,n)}}}else if(h=ka(2*a))switch(g={top:e,left:c,width:h.width,height:h.height},k){case 1:sa(d,c,e,h.width,h.height,0);break;case 2:sa(d,c,e,h.width,h.height,1)}0<k&&(h=ka(2*a))&&ta(h,d,c,e);a=g;a.top+=b.a.y;a.left+=b.a.x;return a}return{top:0,left:0,width:0,height:0}}
function Oc(){for(var a=N,b=0;b<a.i.length;b++)a.i[b].b.remove();a.i=[];a=Ic(v(1,0),!0);for(b=0;b<a.length;b++)Hc(a[b])}function Hc(a){if(v(a,8)){var b=N.find(a);b&&N.remove(b);v(a,11)||v(a,0)!=v(1,0)||N.add(ea(v(a,9),v(a,10),a))}}function $c(){var a=$a();q=!0;a.show(function(){bc(a);q=!1})}
function fd(){var a=bb(),b=ud();null==b&&(b=50);vd(a.getItem(2),b);q=!0;a.show(function(){var b=a.getItem(2).value,d=new Date;d.setTime(d.getTime()+31536E6);document.cookie="webventure_volume="+escape(b)+"; expires="+d.toGMTString()+"; path=/";bc(a);q=!1})}function ad(){if(ec){var a=eb(0);q=!0;a.show(function(b){bc(a);switch(b){case 1:jc=ad;cd();break;case 3:Bc();break;case 2:q=!1}})}else Bc()}
function Bc(){Vb="";for(var a=ya(Ha(133)),b=0;b<Cb;b++)for(var c=0;c<yb;c++)Wb[b][c]=B(a);for(b=0;b<zb;b++)Xb[b]=B(a);$b();Yb();mb(Qb,La(128,1));M.html("");t=1;P=[v(1,0)];G=1;dc(v(1,0),6,1);mc=lc=kc=ec=!1;X=[];O=!0;S()}function bd(){if(ec){var a=eb(1);q=!0;a.show(function(b){bc(a);switch(b){case 1:jc=bd;cd();break;case 3:Cc();break;case 2:q=!1}})}else Cc()}
function Cc(){var a=gb();q=!0;for(var b=a.getItem(3),c=void 0,d=0;d<window.localStorage.length;d++){var e=window.localStorage.key(d);if(null!=e&&window.JSON.parse(window.localStorage.getItem(e).toString()).game==gamename){var g=$(document.createElement("div"));g.addClass("listitem");g.mousedown(function(){return!1});g.click(function(a){c&&c.removeClass("active");c=$(a.target);c.addClass("active")});g.dblclick(function(){a.getItem(1).b.mousedown()});g.text(e.toString());b.b.append(g)}}a.show(function(b){switch(b){case 1:if(void 0==
c)break;Vb=c.text();bc(a);q=!1;b=window.JSON.parse(window.localStorage.getItem(Vb).toString());Wb=b.gamedata;Xb=b.globals;$b();Yb();mb(Qb,Vb);M.html(b.text);cc=M.get(0).scrollHeight;M.scrollTop(cc);G=1;mc=lc=kc=!1;P=[];t=0;X=[];dc(v(1,0),6,1);ec=!1;S();break;case 2:bc(a),q=!1}})}function cd(){""==Vb?dd():(window.localStorage.setItem(Vb,window.JSON.stringify({game:gamename,gamedata:Wb,globals:Xb,text:M.html()})),mb(Qb,Vb),ec=!1,jc())}
function dd(){var a=hb();q=!0;a.getItem(3).b.keypress(function(b){return 13==b.which?(a.getItem(1).b.mousedown(),!1):!0});for(var b=a.getItem(4),c=void 0,d=0;d<window.localStorage.length;d++){var e=window.localStorage.key(d);if(null!=e&&window.JSON.parse(window.localStorage.getItem(e).toString()).game==gamename){var g=$(document.createElement("div"));g.addClass("listitem");g.mousedown(function(){return!1});g.click(function(b){c&&c.removeClass("active");c=$(b.target);c.addClass("active");a.getItem(3).b.val(c.text())});
g.dblclick(function(){a.getItem(1).b.mousedown()});g.text(e.toString());b.b.append(g)}}a.show(function(b){switch(b){case 1:Vb=a.getItem(3).b.val();bc(a);q=!1;cd();break;case 2:bc(a),q=!1,jc()}})}function ed(){if(ec){var a=eb(2);q=!0;a.show(function(b){bc(a);switch(b){case 1:jc=ed;cd();break;case 3:G=4;S();break;case 2:q=!1}})}else G=4,S()}
function ud(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var c=a[b];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf("webventure_volume="))return unescape(c.substring(18,c.length))}return null}function Jb(){t=0;ic=void 0;P=[];T=0;U={c:0,d:0};Yc="";O=!1;fc=0}function Jc(a){if(-1==Hb.indexOf(a)){Hb.push(a);var b={b:a};b.parent=v(a,0);b.x=v(a,1);b.y=v(a,2);b.ta=v(a,9);b.ua=v(a,10);b.hidden=v(a,11);b.ja=v(a,3);b.ea=v(a,4);I.push({id:7,val:b})}}
function wd(a){a&128&&(a=-((a^255)+1));return a}function Vc(a){a&32768&&(a=-((a^65535)+1));return a}function Gc(a){switch(a){case 65532:return N;case 65533:return Sb;case 65534:return Qb;case 65535:return da}a:{for(var b=0;b<Q.length;b++)if((10==Q[b].kind||14==Q[b].kind)&&void 0!=Q[b].a&&Q[b].a.id==a){a=Q[b];break a}a=void 0}return a}function Ic(a,b){for(var c=[],d=K[2*a];d;)c.push(d),b||(c=c.concat(Ic(d,!1))),d=K[2*d+1];return c}
function oa(a,b){var c;for(c=0;c<a.length&&a[c].id!=b;c++);return c==a.length?0:c+1}function na(a){return 1==a?Sb:(a=v(a,0))?Gc(a):void 0}function Kc(a,b){var c=Ic(a,!0);b.a={id:a,x:0,y:0,s:!1,children:[]};for(var d=32767,e=32767,g=0;g<c.length;g++)if(1!=c[g]){var k={id:c[g],top:0,left:0,width:0,height:0};if(b!=L){var h=v(k,1),f=v(k,2);d>h&&(d=h);e>f&&(e=f)}b.a.children.push(k)}32767!=d&&(b.a.x=d);32767!=e&&(b.a.y=e);b!=L&&(b.a.s=!0)}
function pc(){for(void 0!=ic&&ic.J();H.length;)Lc(H.pop());Jb()}
function td(a,b){var c;a:if(c=desktop.offset(),b>=c.top&&b<c.top+19&&a>=c.left&&a<c.left+desktop.width())c={id:1,e:void 0};else{for(c=0;c<Q.length;c++){var d=Q[c].W(a,b);if(void 0!=d){c=d;break a}}c={id:0,e:void 0}}d=0;void 0!=c.e&&(d=c.e.kind);if(3!=c.id||14!=d&&10!=d)switch(d){case 9:c.id=-1;break;case 11:c.id=-2;break;case 12:c.id=-3;break;case 13:c.id=-4;break;default:switch(c.id){case 0:c.id=-5;break;case 1:c.id=-6;break;case 2:c.id=-7;break;case 3:c.id=-8;break;case 4:c.id=-9;break;case 5:c.id=
-10;break;case 6:c.id=-11;break;default:c.id=-12}}else c.id=c.e.a.id;return c}function Qc(a){var b=desktop.offset();a.d-=b.top;a.c-=b.left}function rc(){14==Q[0].kind?(Tb(33536),Tb(33537)):(Ub(33536),Ub(33537));Ub(33280);Ub(33282);Ub(33283);Ub(33284);Ub(33285)}function xd(){return{width:8,items:[]}}function yd(a,b,c){a.width+=8+c[b].width;a.items.push(b)}function zd(a,b,c){var d=a.items[b];a.width-=8+c[d].width;a.items.splice(b,1);return d}
function Ad(a,b,c,d){for(var e=b?32767:-32768,g=!0,k=-1,h=0;h<a.items.length;h++){var f=a.items[h],l=c[f].top+c[f].height>d.top+d.height||c[f].top>d.top;b&&(l=!l);g&&l&&(g=!1,e=b?32767:-32768);if(g||l)if(f=c[f].width/2|0,l=!1,l=b?e>=f:e<=f)k=h,e=f}return zd(a,k,c)}
function gd(){var a=Q[0],b={};b.top=a.a.y;b.left=a.a.x;b.width=a.port.width();b.height=a.port.height();for(var c=a.a.children,d=[],e=xd(),g=xd(),k=xd(),h=xd(),f=c.length-1;0<=f;f--){var l=c[f];l.top+l.height>b.top+b.height||l.top<b.top?yd(g,f,c):16+l.width>b.width?yd(g,f,c):yd(e,f,c)}for(var n=b.top+8;e.items.length||g.items.length;){for(var r=32767,u=-1,x=0,f=e.items.length-1;0<=f;f--)l=e.items[f],c[l].top<r&&(r=c[l].top,x=c[l].height,u=f);if(-1!=u){yd(k,zd(e,u,c),c);do for(u=!0,f=e.items.length-
1;0<=f;f--)l=e.items[f],c[l].top<r+x&&(x<c[l].height&&(u=!1,x=c[l].height),yd(k,zd(e,f,c),c));while(!u)}for(;k.items.length&&k.width>b.width;)yd(e,Ad(k,!1,c,b),c);x=0;for(f=k.items.length-1;0<=f;f--)l=k.items[f],x<c[l].height&&(x=c[l].height);for(;g.items.length&&k.width<b.width;)f=Ad(g,!0,c,b),e.items.length&&c[f].height>x?yd(h,f,c):k.width+8+c[f].width<=b.width?(x<c[f].height&&(x=c[f].height),yd(k,f,c)):yd(h,f,c);for(;h.items.length;)yd(g,zd(h,0,c),c);!k.items.length&&g.items.length&&(f=zd(g,0,
c),x<c[f].height&&(x=c[f].height),yd(k,f,c));for(l=b.left+8;k.items.length;)f=Ad(k,!0,c,b),d.push({id:c[f].id,left:l,top:n+(x-c[f].height)/2|0}),l+=c[f].width+8;n+=x+8}Bd(d,a)}function hd(){var a=Q[0],b,c,d,e;b=a.a.y;c=a.a.x;d=a.port.width();e=a.port.height();for(var g=a.a.children,k=[],h=0;h<g.length;h++){var f=e-g[h].height;0>f&&(f=0);var l=(Math.random()*f|0)+b,f=d-g[h].width;0>f&&(f=0);k.push({id:g[h].id,left:(Math.random()*f|0)+c,top:l})}Bd(k,a)}
function Bd(a,b){for(var c=0;c<a.length;c++){var d=ma(a[c].id);if(d.top!=a[c].top||d.left!=a[c].left)dc(a[c].id,1,a[c].left),dc(a[c].id,2,a[c].top)}b.a.s=!0;R(b)};function ka(a){a=pb(3,a);return 2>a.length?void 0:2==a.length?ka((a.charCodeAt(0)&255)<<8|a.charCodeAt(1)&255):Ja(new xa(a))}function la(a,b,c){var d=b.top,e=b.left,g=e+b.width;b=d+b.height;d<a.top&&(d=a.top);e<a.left&&(e=a.left);b>a.top+a.height&&(b=a.top+a.height);g>a.left+a.width&&(g=a.left+a.width);if(g<=e||b<=d)d=b=e=g=0;c.top=d;c.left=e;c.width=g-e;c.height=b-d;return 0!=c.height}
function Ja(a){var b=a.f(3),c,d;Da&&a.f(2);d=a.f(1)?a.f(10):a.f(6);if((c=a.f(1)?a.f(10):a.f(6))&&d){c=new Ea(c,d,c+15>>3&65534);switch(b){case 0:b=c.H>>4;d=c.H&15;for(var e,g=0,k=0;k<c.G;k++){for(var h=0;h<b;h++)e=ub(a),a.seek(2,a.j),e>>>=16-a.l,c.data[g++]=e>>8&255,c.data[g++]=e&255;d&&(e=a.f(d),e<<=16-d,c.data[g++]=e>>8&255,c.data[g++]=e&255)}break;case 1:Cd(Dd,Ed,Fd,c,a);break;case 2:Cd(Gd,Hd,Id,c,a);break;case 3:b=Array(17);for(g=0;255!=(d=Jd[g++]);){for(e=a.f(d);255!=(d=Jd[g++]);)b[Jd[g++]]=
e%d,e=e/d|0;b[Jd[g++]]=e}b[16]=0;for(e=16;0<e;e--)for(d=e;16>=d;d++)b[d]>=b[e-1]&&b[d]++;for(e=16;0<=e;e--)if(16==b[e]){b[e]=255;break}g=Array(17);k=Array(17);d=a.f(2)+1;for(e=h=0;15>e;e++){if(e)for(;!a.f(1);)d++;k[e]=d;g[e]=h;h+=1<<16-d}for(g[15]=h;h&1<<16-d;)d++;g[16]=h|1<<16-d;k[15]=d;k[16]=d;Cd(g,k,b,c,a)}return c}}
var Dd=[0,8192,16384,20480,24576,28672,32768,36864,40960,45056,49152,53248,55296,57344,59392,61440,63488],Ed=[3,3,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5],Fd=[0,15,3,5,6,7,8,9,10,12,255,1,2,4,11,13,14],Gd=[0,16384,32768,49152,51200,53248,55296,57344,59392,61440,62464,62976,63488,64E3,64512,65024,65280],Hd=[2,2,2,5,5,5,5,5,5,6,7,7,7,7,7,8,8],Id=[255,0,15,1,3,7,14,12,8,6,2,4,9,13,11,10,5],Jd=[8,15,2,255,0,4,255,1,7,9,8,255,3,4,255,4,10,7,10,11,6,255,5,6,6,11,255,7,3,255,9,4,3,14,255,12,2,255,13,1,255,15,255];
function Cd(a,b,c,d,e){var g;Y=Z=0;g=d.H&3?e.f(5):e.f(4)<<1;var k=0,h=d.H&15;h&&(h>>=2,k=h&1,h=2-(h>>1));for(var f=0,l=0;l<d.G;l++){for(var n=0;n<d.H>>3;n++){var r=Kd(a,b,c,e)<<4;d.data[f++]=Kd(a,b,c,e)|r}k&&(d.data[f]=Kd(a,b,c,e)<<4);f+=h}if(n=d.H&3)for(var f=d.q-h,u=0,l=h=0;l<d.G;l++)g&1?(u<n&&(r=Kd(a,b,c,e)<<4,h|=r>>>u,u+=4),u-=n,r=h,h<<=n,h&=255):(r=e.f(n),r<<=8-n),k&&(r>>>=4),d.data[f]|=r&255,f+=d.q;if(g&8)for(l=f=0;l<d.G;l++)if(r=0,g&2)for(n=0;n<d.q;n++)d.data[f]^=r,r=d.data[f++];else for(n=
0;n<d.q;n++)h=d.data[f]^r,h^=h>>>4&15,d.data[f++]=h,r=h<<4&255;if(g&4)for(a=4*d.q,g&2&&(a*=2),f=0,g=a,b=0;b<d.G*d.q-a;b++)d.data[g++]^=d.data[f++]}var Z=0,Y=0;function Kd(a,b,c,d){if(Z)return Z--,Y=Y<<8&65280|Y>>8,Y&255;var e=ub(d),e=e>>>16-d.l,e=e&65535,g;for(g=0;16>g&&!(a[g+1]>e);g++);d.l+=b[g];d.l&16&&(d.l&=15,d.seek(2,d.j));a=c[g];if(255==a)return d.f(1)||(Y&=255,Y|=Y<<8),Z=d.f(3),3>Z&&(Z<<=4,Z|=d.f(4),8>Z&&(Z<<=8,Z|=d.f(8))),Z-=2,Y=Y<<8&65280|Y>>8,Y&255;Y<<=8;Y|=a;Y&=65535;return a};function Pa(a,b,c){var d={id:b},e=$(document.createElement("tr"));if("-"==a[0]){var g=$(document.createElement("td"));g.attr("colspan","2");g.addClass("divider");g.append(document.createElement("hr"))}else e.addClass("menuitem"),g=$(document.createElement("td")),g.html(ga(a)),e.append(g),g=$(document.createElement("td")),""!=c&&(g.addClass("shortcut"),Ld.push({key:c,id:b}),g.text(c));e.append(g);d.b=e;d.enabled=!0;d.enabled||d.b.addClass("disabled");D.body.append(d.b);D.items.push(d)}
function Md(a){for(var b=0;b<E.length;b++)for(var c=0;c<E[b].items.length;c++)if(E[b].items[c].id==a)return E[b].items[c]}function Tb(a){if(a=Md(a))a.enabled=!0,a.b.removeClass("disabled")}function Ub(a){if(a=Md(a))a.enabled=!1,a.b.addClass("disabled")}
function Na(a){for(var b=$(a.target);void 0==b.data("refCon");)b=b.parent();b.addClass("active");var c=b.data("refCon");desktop.append(c.p);a=b.position();c.p.css("top",a.top+19+"px");c.p.css("left",a.left+"px");var d=-1;$(document).mousemove(function(a){var g=Oa.offset();if(Math.floor(a.pageX/pageZoom)>=g.left&&Math.floor(a.pageY/pageZoom)>g.top&&Math.floor(a.pageX/pageZoom)<g.left+Oa.width()&&Math.floor(a.pageY/pageZoom)<g.top+Oa.height()){for(var k=0;k<E.length;k++)if(g=E[k].b.offset(),Math.floor(a.pageX/
pageZoom)>=g.left&&Math.floor(a.pageX/pageZoom)<g.left+E[k].b.outerWidth()){c.p.remove();b.removeClass("active");b=E[k].b;b.addClass("active");c=b.data("refCon");desktop.append(c.p);g=b.position();c.p.css("top",g.top+19+"px");c.p.css("left",g.left+"px");break}for(k=0;k<c.items.length;k++)c.items[k].b.removeClass("active");d=-1}else if(g=c.p.offset(),Math.floor(a.pageX/pageZoom)>=g.left&&Math.floor(a.pageY/pageZoom)>=g.top&&Math.floor(a.pageX/pageZoom)<g.left+c.p.outerWidth()&&Math.floor(a.pageY/pageZoom)<
g.top+c.p.outerHeight())for(k=0;k<c.items.length;k++){var h=c.items[k].b;h.hasClass("menuitem")&&c.items[k].enabled&&(g=h.offset(),Math.floor(a.pageY/pageZoom)>=g.top&&Math.floor(a.pageY/pageZoom)<g.top+h.outerHeight()?(d=k,h.addClass("active")):h.removeClass("active"))}else{for(k=0;k<c.items.length;k++)c.items[k].b.removeClass("active");d=-1}});$(document).mouseup(function(){$(document).unbind("mousemove");$(document).unbind("mouseup");c.p.remove();b.removeClass("active");-1!=d&&(c.items[d].b.removeClass("active"),
Zc(c.items[d].id))})}var Oa,E=[],Ld=[],D=void 0;$("body").keydown(function(a){if("text"==a.target.type||!a.altKey||q)return!0;for(var b=0;b<Ld.length;b++)if(Ld[b].key.charCodeAt(0)==a.which){a=Ld[b].id;for(b=0;b<E.length;b++)for(var c=0;c<E[b].items.length;c++)E[b].items[c].id==a&&E[b].items[c].enabled&&Nd(E[b],a);return!1}return!0});function Nd(a,b){a.b.addClass("active");setTimeout(function(){a.b.removeClass("active");Zc(b)},200)};function Od(a,b,c,d,e,g,k,h,f){var l=this;this.I=void 0;this.i=[];this.V=c;this.U=b;this.B=d;this.F=e;this.e=$(document.createElement("div"));this.e.addClass(a);if("document"==a||"info"==a||"noGrowDoc"==a||"zoomDoc"==a||"rDoc4"==a)b="<span></span>",this.title=$(document.createElement("div")),this.title.addClass("title"),this.title.mousedown(function(a){q||Pd(Math.floor(a.pageX/pageZoom),Math.floor(a.pageY/pageZoom),l);return!1}),this.U&&(b='<div class="close"></div>'+b),this.V&&(b+='<div class="resize"></div>'),
this.title.html(b),this.U&&(b=this.title.children("div.close"),b.mousedown(function(){return!1}),b.click(function(){q||(14==l.kind&&(pd(),md(l.a.id),t=2,Wc(2),O=!0),S());return!1})),this.V&&(b=this.title.children("div.resize"),b.mousedown(function(){return!1}),b.click(function(){if(!q){var a=l.e.position(),a={x:a.left,y:a.top};a.Aa=l.e.width();a.c=l.e.height();void 0!=l.I?(l.e.css("left",l.I.x+"px"),l.e.css("top",l.I.y+"px"),l.resize(l.I.Aa,l.I.c)):(l.e.css("left","0px"),l.e.css("top","19px"),l.resize(desktop.width(),
desktop.height()-19));l.I=a}return!1})),this.e.append(this.title);this.port=$(document.createElement("canvas"));this.port.mousedown(function(a){if(!q)switch(Nc(l),l.kind){case 9:Pd(Math.floor(a.pageX/pageZoom),Math.floor(a.pageY/pageZoom),l);break;case 10:case 14:var b=Qd(Math.floor(a.pageX/pageZoom),Math.floor(a.pageY/pageZoom),l),c=!1;b&&!v(b,3)&&(c=!0);jd(b,l,a,c);break;case 12:b=Qd(Math.floor(a.pageX/pageZoom),Math.floor(a.pageY/pageZoom),l);1==b?jd(b,l,a,!1):Pd(Math.floor(a.pageX/pageZoom),Math.floor(a.pageY/
pageZoom),l);break;case 13:jd(v(1,0),l,a,!1)}return!1});this.port.attr("width",h);this.port.attr("height",f);this.e.append(this.port);this.top=k;this.height=f;this.left=g;this.width=h;"document"==a||"noGrowDoc"==a||"zoomDoc"==a||"rDoc4"==a?(this.top-=Ra+Qa,this.height+=Ra,this.left-=Qa):"info"==a?(this.top-=Sa+Qa,this.height+=Sa,this.left-=Qa):"alert"==a?(this.top-=2*Ta,this.left-=2*Ta,this.width+=Ta,this.height+=Ta):(this.top-=Qa,this.left-=Qa);this.B&&(this.width+=Ua);this.F&&(this.height+=Va);
this.e.css("top",this.top+"px");this.e.css("left",this.left+"px");this.e.css("width",this.width+"px");this.e.css("height",this.height+"px");desktop.append(this.e);(this.B||this.F)&&Rb(this)}m=Od.prototype;m.show=function(a){this.sa=a;this.e.show();kd(this)};m.hide=function(){this.e.hide()};
function mb(a,b){if(void 0!=a.title){var c=a.title.children("span");c.html("");if(""==b)c.hide();else{var d="none"==a.e.css("display");a.e.show();c.css({position:"absolute",visibility:"hidden",display:"block"});var e=a.port.width();a.U&&(e-=30);a.V&&(e-=30);for(var g=0;g<b.length;g++)if(c.append(b.substring(g,g+1)),c.width()>e){c.html(b.substring(0,g-1));break}c.css({position:"",visibility:"",display:""});d&&a.e.hide()}}}m.addClass=function(a){this.e.addClass(a)};m.removeClass=function(a){this.e.removeClass(a)};
m.add=function(a){var b=this.port.position().top,c=parseInt(a.b.css("top"),10);a.b.css("top",c+b+"px");this.e.append(a.b);a.e=this;this.i.push(a);"none"!=this.e.css("display")&&a.m()};m.remove=function(a){var b=this.i.indexOf(a);-1!=b&&this.i.splice(b,1);a.b.remove()};m.find=function(a){for(var b=0;b<this.i.length;b++)if(this.i[b].o==a)return this.i[b]};function kd(a){for(var b=0;b<a.i.length;b++)255!=a.i[b].o&&a.i[b].show()}m.close=function(){this.e.remove()};
function sd(a,b){var c=a.port.offset();b.c-=Math.floor(c.left)+1;b.d-=Math.floor(c.top)+2;a.a&&(b.c+=a.a.x,b.d+=a.a.y)}function Pc(a,b){var c=a.port.offset();b.c+=Math.floor(c.left)+1;b.d+=Math.floor(c.top)+2;a.a&&(b.c-=a.a.x,b.d-=a.a.y)}
function Rb(a){if(a.F){a.t=$(document.createElement("div"));a.t.addClass("hscroll");a.t.css("top",a.height-Va+"px");a.t.css("width",a.width-15+"px");a.t.mousedown(function(b){Nc(a);var d=a.n.offset().left;Math.floor(b.pageX/pageZoom)<d?Rd(a,-20,0):Rd(a,20,0);return!1});var b=$(document.createElement("div"));b.addClass("leftarrow");b.mousedown(function(){Rd(a,-5,0);return!1});a.t.append(b);a.N=$(document.createElement("div"));a.N.addClass("rightarrow");a.N.css("left",a.width-Wa-15+"px");a.N.mousedown(function(){Rd(a,
5,0);return!1});a.t.append(a.N);a.n=$(document.createElement("div"));a.n.addClass("slider");a.n.mousedown(function(b){Sd(a,Math.floor(b.pageX/pageZoom),!0);return!1});a.t.append(a.n);a.e.append(a.t)}a.B&&(a.u=$(document.createElement("div")),a.u.addClass("vscroll"),a.u.css("left",a.width-Ua+"px"),a.u.css("height",a.height-15-Ra+"px"),a.u.mousedown(function(b){Nc(a);var d=a.g.offset().top;Math.floor(b.pageY/pageZoom)<d?Rd(a,0,-20):Rd(a,0,20);return!1}),b=$(document.createElement("div")),b.addClass("uparrow"),
b.mousedown(function(){Rd(a,0,-5);return!1}),a.u.append(b),a.K=$(document.createElement("div")),a.K.addClass("downarrow"),a.K.css("top",a.height-15-15-Ra+"px"),a.K.mousedown(function(){Rd(a,0,5);return!1}),a.u.append(a.K),a.g=$(document.createElement("div")),a.g.addClass("slider"),a.g.mousedown(function(b){Sd(a,Math.floor(b.pageY/pageZoom),!1);return!1}),a.u.append(a.g),a.e.append(a.u));a.D=$(document.createElement("div"));a.D.addClass("grow");a.D.css("top",a.height-15+"px");a.D.css("left",a.width-
15+"px");a.D.mousedown(function(b){if(q)return!1;Nc(a);var d=$(document.createElement("div"));d.addClass("resizeProxy");desktop.append(d);var e=a.e.position();d.css("top",e.top+"px");d.css("left",e.left+"px");var g=a.e.width(),k=a.e.height();d.css("width",g+"px");d.css("height",k+"px");var h=Math.floor(b.pageX/pageZoom),f=Math.floor(b.pageY/pageZoom);$(document).mousemove(function(a){var b=g+(Math.floor(a.pageX/pageZoom)-h),c=k+(Math.floor(a.pageY/pageZoom)-f);100<b&&(g=b,d.css("width",g+"px"),h=
Math.floor(a.pageX/pageZoom));100<c&&(k=c,d.css("height",k+"px"),f=Math.floor(a.pageY/pageZoom))});$(document).mouseup(function(){$(document).unbind("mousemove");$(document).unbind("mouseup");d.remove();a.resize(g,k)});return!1});a.e.append(a.D)}
m.resize=function(a,b){var c=this.width-this.port.width(),d=this.height-this.port.height();this.width=a;this.height=b;this.e.css("width",a+"px");this.e.css("height",b+"px");this.F&&(this.t.css("top",b-Va+"px"),this.t.css("width",a-15+"px"),this.N.css("left",a-Wa-15+"px"));this.B&&(this.u.css("left",a-Ua+"px"),this.u.css("height",b-15-Ra+"px"),this.K.css("top",b-15-15-Ra+"px"));this.D.css("top",b-15+"px");this.D.css("left",a-15+"px");this.a?(this.port.attr("width",a-c),this.port.attr("height",b-d),
this.a.s=!0,R(this)):(this.port.css("width",a-c),this.port.css("height",b-d),cc=this.port.get(0).scrollHeight,Tc())};
function Uc(a,b){if(11==a.kind)a.g.data("min",b.top),a.g.data("max",b.bottom),Td(a);else{b.left>a.a.x&&(b.left=a.a.x);b.right<a.a.x+a.port.width()&&(b.right=a.a.x+a.port.width());b.top>a.a.y&&(b.top=a.a.y);b.bottom<a.a.y+a.port.height()&&(b.bottom=a.a.y+a.port.height());a.F&&(a.n.data("min",b.left),a.n.data("max",b.right));a.B&&(a.g.data("min",b.top),a.g.data("max",b.bottom));if(a.F){var c=a.n.data("min"),d=a.n.data("max");if(c<d){var e=a.a.x-c,g=a.port.width(),e=e*(a.port.width()-Xa-Wa)/(d-c)|0,
c=g*(a.port.width()-Xa-Wa-Ya)/(d-c)|0;a.n.css("left",e+Xa+"px");a.n.css("width",c+"px")}else a.n.css("left",Xa+"px"),a.n.css("width",a.port.width()-Xa-Wa+"px")}a.B&&(c=a.g.data("min"),d=a.g.data("max"),c<d?(e=a.a.y-c,g=a.port.height(),e=e*(a.port.height()-15-15)/(d-c)|0,c=g*(a.port.height()-15-15-2)/(d-c)|0,a.g.css("top",e+15+"px"),a.g.css("height",c+"px")):(a.g.css("top","15px"),a.g.css("height",a.port.height()-15-15+"px")))}}
function Td(a){var b=a.port.scrollTop(),c=a.g.data("min"),d=a.g.data("max");if(c<d){var e=b-c,b=b+a.port.height(),e=e*(a.height-Ra-15-15-15)/(d-c)|0,c=b*(a.height-Ra-15-15-15-2)/(d-c)|0;a.g.css("top",e+15+"px");a.g.css("height",c-e+"px")}else a.g.css("top","15px"),a.g.css("height",a.height-15-Ra-15+"px")}
m.W=function(a,b){var c=this.e.offset();if(a>=c.left&&a<c.left+this.e.width()&&b>=c.top&&b<c.top+this.e.height())return c=this.port.offset(),a>=c.left&&a<c.left+this.port.width()&&b>=c.top&&b<c.top+this.port.height()?{id:3,e:this}:{id:4,e:this}};
function Ud(){for(var a=L,b=a.port.get(0).getContext("2d"),c=a.port.width(),a=a.port.height(),c=b.getImageData(0,0,c,a),a=0;a<c.height;a++)for(var d=a*c.width*4,e=0;e<c.width;e++)c.data[d++]^=255,c.data[d++]^=255,c.data[d++]^=255,c.data[d++]=255;b.putImageData(c,0,0)}m.param=function(a){for(var b=0;b<this.i.length;b++)if(this.i[b].S){var c=this.i[b].S(),d;do if(d=c.indexOf("^"),0<=d){var e=c.substr(0,d),e=e+a[parseInt(c.substr(d+1,1),10)],e=e+c.substr(d+2);this.i[b].R(e);c=e}while(0<=d)}};
m.getItem=function(a){for(var b=0;b<this.i.length;b++)if(this.i[b].o==a)return this.i[b]};
function Rd(a,b,c){if(11==a.kind){a.port.scrollTop(a.port.scrollTop()+c);Td(a);var d=setTimeout(function(){Rd(a,b,c)},50)}else{a.a.x+=b;a.a.y+=c;if(a.F){var e=a.n.data("min"),g=a.n.data("max");a.a.x<e&&(a.a.x=e);a.a.x>g-a.port.width()&&(a.a.x=g-a.port.width())}a.B&&(e=a.g.data("min"),g=a.g.data("max"),a.a.y<e&&(a.a.y=e),a.a.y>g-a.port.height()&&(a.a.y=g-a.port.height()));a.a.s=!0;R(a);d=setTimeout(function(){Rd(a,b,c)},50)}$(document).mouseup(function(){$(document).unbind("mouseup");clearTimeout(d)})}
function Sd(a,b,c){if(11==a.kind)Vd(a,b);else{var d=b;$(document).mousemove(function(b){if(c){a.a.x+=Math.floor(b.pageX/pageZoom)-d;d=Math.floor(b.pageX/pageZoom);b=a.n.data("min");var g=a.n.data("max");a.a.x<b&&(a.a.x=b);a.a.x>g-a.port.width()&&(a.a.x=g-a.port.width())}else a.a.y+=Math.floor(b.pageY/pageZoom)-d,d=Math.floor(b.pageY/pageZoom),b=a.g.data("min"),g=a.g.data("max"),a.a.y<b&&(a.a.y=b),a.a.y>g-a.port.height()&&(a.a.y=g-a.port.height());a.a.s=!0;R(a)});$(document).mouseup(function(){$(document).unbind("mouseup");
$(document).unbind("mousemove")})}}function Vd(a,b){var c=b;$(document).mousemove(function(b){var e=a.g.data("min"),g=a.g.data("max"),e=(Math.floor(b.pageY/pageZoom)-c)*(g-e)/(a.height-Ra-15-15-15)|0;c=Math.floor(b.pageY/pageZoom);a.port.scrollTop(a.port.scrollTop()+e);Td(a)});$(document).mouseup(function(){$(document).unbind("mouseup");$(document).unbind("mousemove")})}function zc(){for(var a=[],b=0;b<Q.length;b++)14==Q[b].kind?a.push(Q[b]):Q[b].hide();for(b in a)ac(a[b])}
function bc(a){for(var b=0;b<Q.length;b++)if(Q[b]==a){a.close();Q.splice(b,1);break}Q.length&&Nc(Q[0])}function ac(a){if(void 0!=a){var b=a.a.id;if(10==a.kind)a.a={},mb(a,"");else{var c={d:0,c:0},d={d:a.port.height(),c:a.port.width()};Pc(a,c);Pc(a,d);a.a={};bc(a);return{b:b,top:c.d,left:c.c,width:d.c-c.c,height:d.d-c.d}}}}
function Nc(a){if(Q[0]==a)a.e.addClass("active");else{void 0!=Q[0]&&Q[0].e.removeClass("active");for(var b=0;b<Q.length;b++)Q[b]==a&&Q.splice(b,1);Q.unshift(a);a.e.addClass("active");rc()}}function jb(a,b,c,d,e,g,k,h,f){a=new Od(a,b,c,d,e,g,k,h,f);a.hide();Nc(a);return a}function ab(a,b,c,d){a=new Od("alert",!1,!1,!1,!1,a,b,c,d);a.kind=2;a.hide();Nc(a);return a}var Q=[];
function Pd(a,b,c){var d=a,e=b;Nc(c);$(document).mousemove(function(a){var b=c.e.position();c.e.css("top",b.top+(Math.floor(a.pageY/pageZoom)-e)+"px");c.e.css("left",b.left+(Math.floor(a.pageX/pageZoom)-d)+"px");d=Math.floor(a.pageX/pageZoom);e=Math.floor(a.pageY/pageZoom)});$(document).mouseup(function(a){$(document).unbind("mousemove");$(document).unbind("mouseup");var b=c.e.position();c.e.css("top",b.top+(Math.floor(a.pageY/pageZoom)-e)+"px");c.e.css("left",b.left+(Math.floor(a.pageX/pageZoom)-
d)+"px")})}function Qd(a,b,c){var d={c:a,d:b},e=0,g=c.a.children.length;console.log("x:"+a+" y:"+b);sd(c,d);for(console.log("adjustx:"+d.c+" y:"+d.d);0<g&&0==e;)if(g--,a=d,b=c.a.children[g],e=0,!v(b.id,4)&&a.c>=b.left&&a.d>=b.top&&a.c<b.left+b.width&a.d<b.top+b.height){var k=void 0;(k=ka(2*b.id+1))?k.W(a.c-b.left,a.d-b.top)&&(e=b.id):e=b.id}return e};var Wd=0;function uc(a,b){var c=U;X.unshift({Y:a,C:b,target:T,la:c.c,ma:c.d,state:new Xd,k:[],A:[]});return sc(!0)}function sc(a){for(;X.length;)if(Yd(a))return!0;return!1}var X=[];function Xd(){this.stack=Array(128);this.v=128}Xd.prototype.push=function(a){this.stack[--this.v]=Zd(a)};Xd.prototype.pop=function(){return this.stack[this.v++]};function $d(a,b){return a.stack[a.v+b]}Xd.prototype.clear=function(){this.v=128};Xd.prototype.size=function(){return 128-this.v};
function Zd(a){0>a&&(a=(-a^65535)+1);return a&65535}
function Yd(a){var b=!1;if(X[0].da||a){X[0].da=!1;if(b=a?ae(0):be())return X[0].da=!0;b=!0;X[0].aa=0}if(X[0].ca||b){X[0].ca=!1;var c;a=v(1,0);c=[a].concat(Ic(a,!1));for(a=X[0].aa;a<c.length;a++){if(b=b?ae(c[a]):be())return X[0].ca=!0,X[0].aa=a,!0;b=!0}}var d;if(X[0].T&&(X[0].T=!1,be()))return X[0].T=!0;do{for(a=b=0;a<X[0].k.length;a++)b<X[0].k[a].r&&(b=X[0].k[a].r,d=a);if(b&&(X[0].k[d].r=0,ae(X[0].k[d].ba)))return X[0].T=!0}while(b);X.shift();return!1}
function ae(a){return(a=pb(1,a))?(X[0].A[0]=new xa(a),ce()):!1}function be(){var a=ce();if(a)return a;X[0].A.shift();if(X[0].A.length)return be()}var de;
function ce(){var a,b,c,d,e,g,k,h;d=X[0].A[0];for(var f=X[0].state;!(d.h>=d.length);)if(a=A(d),a&128)switch(a){case 128:b=f.pop();c=f.pop();f.push(v(b,c));break;case 129:b=f.pop();c=f.pop();a=Vc(f.pop());dc(b,c,a);break;case 130:b=f.pop();c=f.pop();a=0!=f.pop();f.push(ee(b,c,a));break;case 131:f.push(X[0].Y);break;case 132:f.push(X[0].C);break;case 133:f.push(X[0].target);break;case 134:f.push(X[0].la);break;case 135:f.push(X[0].ma);break;case 136:f.push(A(d));break;case 137:f.push(B(d));break;case 138:c=
f.pop();f.push(Xb[c]);break;case 139:c=f.pop();a=Vc(f.pop());Xb[c]=a;ec=!0;break;case 140:a=f.pop();f.push(Math.round((a-1)*Math.random()));break;case 141:a=$d(f,0);f.push(a);break;case 142:c=f.pop();for(b=c-1;c--;)a=$d(f,b),f.push(a);break;case 143:b=f.pop();h=f.pop();f.push(b);f.push(h);break;case 144:c=f.pop();h=$d(f,c);b=$d(f,0);f.stack[f.v+c]=Zd(b);f.stack[f.v+0]=Zd(h);break;case 145:f.pop();break;case 146:a=$d(f,1);f.push(a);break;case 147:c=f.pop();a=$d(f,c);f.push(a);break;case 148:h=f.pop();
b=f.pop();a=f.pop();f.push(h);f.push(a);f.push(b);break;case 149:k=Vc(f.pop());c=Vc(f.pop());k%=c;0>k&&(k+=c);e=g=0;for(a=1;a<c;a++)e+=k,e>=c&&(e-=c),e==g?(g++,e=g):(h=$d(f,g),b=$d(f,e),f.stack[f.v+g]=Zd(b),f.stack[f.v+e]=Zd(h));break;case 150:f.clear();break;case 151:f.push(f.size());break;case 152:b=f.pop();h=f.pop();f.push(h+b);break;case 153:b=f.pop();h=f.pop();f.push(h-b);break;case 154:b=f.pop();h=f.pop();f.push(h*b);break;case 155:b=f.pop();h=f.pop();f.push(h/b|0);break;case 156:b=f.pop();
h=f.pop();f.push(h%b);break;case 157:b=f.pop();h=f.pop();f.push(h%b);f.push(h/b|0);break;case 158:a=Vc(f.pop());0>a&&(a=-a);f.push(a);break;case 159:a=-Vc(f.pop());f.push(a);break;case 160:b=f.pop();h=f.pop();f.push(h&b);break;case 161:b=f.pop();h=f.pop();f.push(h|b);break;case 162:b=f.pop();h=f.pop();f.push(h^b);break;case 163:a=f.pop();f.push(a^65535);break;case 164:b=f.pop();h=f.pop();f.push(h&&b?65535:0);break;case 165:b=f.pop();h=f.pop();f.push(h||b?65535:0);break;case 166:b=f.pop();h=f.pop();
f.push(!h!=!b?65535:0);break;case 167:a=f.pop();f.push(0==a?65535:0);break;case 168:b=f.pop();h=f.pop();f.push(h>b?65535:0);break;case 169:b=f.pop();h=f.pop();f.push(h<b?65535:0);break;case 170:b=Vc(f.pop());h=Vc(f.pop());f.push(h>b?65535:0);break;case 171:b=Vc(f.pop());h=Vc(f.pop());f.push(h<b?65535:0);break;case 172:b=f.pop();h=f.pop();f.push(h==b?65535:0);break;case 173:b=W(f.pop());h=W(f.pop());f.push(h==b?1:0);break;case 174:b=W(f.pop());a=W(f.pop());f.push(-1!=a.toLowerCase().indexOf(b.toLowerCase())?
1:0);break;case 175:b=W(f.pop());a=W(f.pop());b=new RegExp("\\b"+b+"\\b","i");f.push(b.test(a)?65535:0);break;case 176:a=Vc(B(d));d.seek(a,d.j);break;case 177:a=wd(A(d));d.seek(a,d.j);break;case 178:a=Vc(B(d));b=f.pop();0!=b&&d.seek(a,d.j);break;case 179:a=wd(A(d));b=f.pop();0!=b&&d.seek(a,d.j);break;case 180:a=Vc(B(d));b=f.pop();0==b&&d.seek(a,d.j);break;case 181:a=wd(A(d));b=f.pop();0==b&&d.seek(a,d.j);break;case 182:a=f.pop();b=f.pop();X[0].k.push({r:a,ba:b});break;case 183:b=f.pop();for(a=0;a<
X[0].k.length;a++)X[0].k[a].ba==b&&(X[0].k[a].r=0);break;case 184:b=f.pop();for(a=0;a<X[0].k.length;a++)X[0].k[a].r<=b&&(X[0].k[a].r=0);break;case 185:c=f.pop();for(a=0;a<X[0].k.length;a++)X[0].k[a].r>=c&&(X[0].k[a].r=0);break;case 186:b=f.pop();c=f.pop();for(a=0;a<X[0].k.length;a++)X[0].k[a].r>=c&&X[0].k[a].r<=b&&(X[0].k[a].r=0);break;case 187:a={state:new Xd,k:[],A:[void 0]};a.Y=f.pop();a.C=f.pop();a.target=f.pop();a.la=f.pop();a.ma=f.pop();X.unshift(a);if(Yd(!0))return!0;break;case 188:a=f.pop();
X[0].A.unshift(void 0);if(ae(a))return!0;X[0].A.shift();d=X[0].A[0];break;case 189:b=f.pop();I.push({id:2,val:b});break;case 190:a={};a.P=f.pop();a.O=f.pop();I.push({id:8,val:a});dc(a.O,6,v(a.P,6));dc(a.P,6,0);b=Ic(a.P,!0);for(c=0;c<b.length;c++)dc(b[c],0,a.O);break;case 191:I.push({id:14,val:X[0].C});break;case 192:I.push({id:13});break;case 193:a=f.pop();Nb.push({id:3,val:[X[0].target,X[0].C,a]});break;case 194:Nb.push({id:2});break;case 195:a=f.pop();Nb.push({id:3,val:[X[0].target,X[0].C,a]});
Nb.push({id:2});break;case 196:a=f.pop();Nb.push({id:2});Nb.push({id:3,val:[X[0].target,X[0].C,a]});Nb.push({id:2});break;case 197:a=f.pop();Nb.push({id:1,val:a});break;case 198:f.push(2);break;case 199:b=f.pop();Mb.push({id:1,val:b});break;case 200:b=f.pop();Mb.push({id:2,val:b});break;case 201:Mb.push({id:3});break;case 202:a=new Date;f.push(a.getFullYear());f.push(a.getMonth()+1);f.push(a.getDate());f.push(a.getHours());f.push(a.getMinutes());f.push(a.getSeconds());break;case 203:a=new Date;f.push(a.getDay()+
1);break;case 204:a=0!=f.pop();b=f.pop();b=Ic(b,a);for(a=0;a<b.length;a++)f.push(b[a]);f.push(b.length);break;case 205:a=0!=f.pop();b=f.pop();b=Ic(b,a);f.push(b.length);break;case 206:f.push(86);break;case 207:f.push(Wd);break;case 208:f.push(1);break;case 209:b=f.pop();a=ma(b);f.push(a.width);f.push(a.height);break;case 210:b=f.pop();h=f.pop();f.push(fe(b,h));break;case 211:a=b=f.pop();b=[];c=Ic(v(a,0),1);for(h=0;h<c.length;h++)a<c[h]&&40<=fe(c[h],a)&&b.push(c[h]);for(;b.length;)dc(b.pop(),0,a);
break;case 212:b=f.pop();a=Ic(b,1);b=v(b,0);for(c=0;c<a.length;c++)dc(a[c],0,b);break;case 213:return d=f.pop(),Xc(d),!0;case 214:Wc(f.pop());break;case 215:G=3;break;case 216:G=2;break;case 217:return d=f.pop(),setTimeout(S,d/60*1E3),!0;case 218:return nc(!1),ca(),!0;case 219:wc();break;case 220:if(yc(!0))return!0;break;case 221:if(xc())return!0;break;case 222:if(nc(!0))return!0;break;case 223:return d=f.pop(),Ud(),setTimeout(ge,d/60*1E3),!0;case 224:f.pop();break;case 225:f.pop();break;case 226:b=
f.pop();h=f.pop();h*=b;a=f.pop();h/=a;f.push(h|0);break;case 227:b=f.pop();a=void 0;if(a=v(1,0)==b?L:Gc(b))Dc(b),wc(),R(a);break;case 228:f.push(0);break;case 229:break;case 230:f.push(de);break;case 231:c=f.pop();b=1;for(a=de=0;a<c;a++)de+=b,de^=b,b^=de,de^=b;break;default:fatal("Unknown function:"+a.toString(16))}else f.push(a);return!1}function ge(){Ud();S()}function ee(a,b,c){var d=0;a=Ic(a,c);for(c=0;c<a.length;c++)d+=v(a[c],b);return d}
function fe(a,b){if(v(a,0)!=v(b,0))return 0;var c=ma(a),d=ma(b);return la(d,c,d)?d.width*d.height*100/(c.width*c.height)|0:0};function p(a,b,c,d){switch(c&255){case 2:return new he(a,b,d);case 10:return new ke(a,b,d);case 15:return new le(a,b,d);case 17:return new me(a,b,d);case 22:return new ne(a,b,d);case 23:return new oe(a,b);case 24:return new pe(a,b,d);case 25:return new qe(a,b,d);default:fatal("Unknown control:"+c.toString(16))}}
function he(a,b,c){var d=this,e=$(document.createElement("canvas"));e.addClass("cbutton");e.css("left",a[0]+"px");e.css("top",a[1]+"px");e.attr("width",a[2]);e.attr("height",a[3]);e.mousedown(function(a){id(d,a);return!1});this.b=e;this.o=b;this.selected=!1;this.pa=c[0];this.f=c[1];this.wa=c[2]}m=he.prototype;m.hide=function(){this.b.hide()};m.show=function(){this.b.show();this.m()};
m.m=function(){var a=this.b.get(0).getContext("2d"),b=this.b.width(),c=this.b.height(),d=a.getImageData(0,0,b,c),e=this.selected?this.wa:this.f;if(e)for(var g=0;g<c;g++)for(var k=(g>>1)*this.pa,h=g*d.width*4,f,l=0;l<b;l++)f=e.charCodeAt(k+(l>>2)),f=3*(f>>(l&2?0:4)&15),d.data[h++]=Ca[f++],d.data[h++]=Ca[f++],d.data[h++]=Ca[f++],d.data[h++]=255;else for(g=0;g<c;g++)for(h=g*d.width*4,l=0;l<b;l++){f=this.selected?0:255;if(2>g||4>l||g>c-3||l>b-5)f=0;d.data[h++]=f;d.data[h++]=f;d.data[h++]=f;d.data[h++]=
255}a.putImageData(d,0,0)};m.select=function(){this.selected=!0;this.m()};m.J=function(){this.selected=!1;this.m()};function ke(a,b,c){var d=this,e=$(document.createElement("div"));e.addClass("button");e.css("left",a[0]+"px");e.css("top",a[1]+"px");e.css("width",a[2]+"px");e.css("height",a[3]+"px");e.css("line-height",a[3]+"px");e.html(c[0]);e.mousedown(function(a){id(d,a);return!1});this.b=e;this.o=b}ke.prototype.hide=function(){this.b.hide()};ke.prototype.show=function(){this.b.show()};
ke.prototype.m=function(){};function le(a,b,c){this.b=$(document.createElement("div"));this.b.addClass("textblock");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.o=b;this.R(c[0])}m=le.prototype;m.S=function(){return this.b.html()};m.R=function(a){this.b.html(a)};m.hide=function(){this.b.hide()};m.show=function(){this.b.show()};m.m=function(){};
function me(a,b,c){var d=$(document.createElement("input"));d.addClass("textinput");d.css("left",a[0]+"px");d.css("top",a[1]+"px");d.css("width",a[2]+"px");d.css("height",a[3]+"px");d.val(c[0]);d.mousedown(function(){d.focus();return!1});this.b=d;this.o=b}me.prototype.hide=function(){this.b.hide()};me.prototype.show=function(){this.b.show();this.b.focus()};me.prototype.m=function(){};
function ne(a,b,c){this.b=$(document.createElement("div"));this.b.addClass("textblock");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.o=b;this.R(c[0])}m=ne.prototype;m.hide=function(){this.b.hide()};m.show=function(){this.b.show()};m.m=function(){};m.S=function(){return this.b.html()};
m.R=function(a){for(var b="",c=0;c<a.length;c++)1==a.charCodeAt(c)?(74==a.charCodeAt(c+1)&&this.b.css("text-align","center"),c+=2):b=13==a.charCodeAt(c)?b+"<br />":b+a.charAt(c);this.b.html(b)};function oe(a,b){this.b=$(document.createElement("div"));this.b.addClass("list");this.b.css("left",a[0]+"px");this.b.css("top",a[1]+"px");this.b.css("width",a[2]+"px");this.b.css("height",a[3]+"px");this.o=b}oe.prototype.hide=function(){this.b.hide()};oe.prototype.show=function(){this.b.show()};
oe.prototype.m=function(){};
function pe(a,b,c){var d=this;this.value=parseInt(c[0],10);this.o=b;this.min=parseInt(c[1],10);this.max=parseInt(c[2],10);this.width=a[2];b=$(document.createElement("div"));b.addClass("hscroll");b.css("left",a[0]+"px");b.css("top",a[1]+"px");b.css("width",a[2]+"px");b.css("height",a[3]+"px");this.b=b;c=$(document.createElement("div"));c.addClass("leftarrow");c.css("top","0px");c.css("left","0px");b.append(c);var e=$(document.createElement("div"));e.addClass("rightarrow");e.css("top","0px");e.css("left",
a[2]-Wa+"px");b.append(e);var g=$(document.createElement("div"));g.addClass("slider");g.css("top","0px");g.css("left","50px");g.css("width","20px");b.append(g);this.xa=g;b.mousedown(function(a){var b=g.offset().left;Math.floor(a.pageX/pageZoom)<b?re(d,-20):re(d,20);return!1});c.mousedown(function(){re(d,-5);return!1});e.mousedown(function(){re(d,5);return!1});g.mousedown(function(a){se(d,Math.floor(a.pageX/pageZoom));return!1})}pe.prototype.hide=function(){this.b.hide()};
pe.prototype.show=function(){this.b.show();this.m()};pe.prototype.m=function(){this.xa.css("left",(this.value*(this.width-Xa-Wa-20-Ya)/(this.max-this.min)|0)+Xa+"px")};function vd(a,b){a.value=parseInt(b,10);a.m()}function re(a,b){a.value+=b;a.value<a.min&&(a.value=a.min);a.value>a.max&&(a.value=a.max);a.m();var c=setTimeout(function(){re(a,b)},50);$(document).mouseup(function(){$(document).unbind("mouseup");clearTimeout(c)})}
function se(a,b){var c=b;$(document).mousemove(function(b){var e=(Math.floor(b.pageX/pageZoom)-c)*(a.max-a.min)/(a.width-Xa-Wa-20-Ya)|0;c=Math.floor(b.pageX/pageZoom);a.value+=e;a.value<a.min&&(a.value=a.min);a.value>a.max&&(a.value=a.max);a.m()});$(document).mouseup(function(){$(document).unbind("mouseup");$(document).unbind("mousemove")})}
function qe(a,b,c){var d=this,e=$(document.createElement("div"));e.addClass("sbutton");e.css("left",a[0]+"px");e.css("top",a[1]+"px");e.css("width",a[2]-2+"px");e.css("height",a[3]-2+"px");e.html(c[0]);e.mousedown(function(a){id(d,a);return!1});this.b=e;this.o=b}m=qe.prototype;m.hide=function(){this.b.hide()};m.show=function(){this.b.show()};m.select=function(){this.b.addClass("active")};m.J=function(){this.b.removeClass("active")};m.m=function(){};var Pb=!0,Ob=void 0,Yc="",Rc=void 0,Sc=void 0;
function W(a){if(Pb){if(a&32768)a=Yc;else{a=new xa(pb(2,a));for(var b=!1,c="",d=B(a);d--;){var e=a.f(5);if(0<e&&27>e)e|=64,b&&(e|=32),b=!0,c+=String.fromCharCode(e);else switch(e){case 0:c+=" ";break;case 27:c+=b?".":",";b=!0;break;case 28:c+=b?"'":'"';b=!0;break;case 29:b=a.f(16);b&32768?(b^=65535,b=te(b)):b=W(b);b&&(c+=b);b=!0;break;case 30:c+=String.fromCharCode(a.f(8));b=!0;break;case 31:b=!b}}a=ga(c)}return a}if(a&32768)return Yc;a=new xa(pb(2,a));d="";for(c=a.f(1)?a.f(15):a.f(7);c--;){b=ub(a);
b>>=16-a.l;b&=65535;for(e=0;e<Ob.length-1&&!(b<Ob.ia[e]);e++);a.l+=Ob.ha[e];a.l&16&&(a.l&=15,a.seek(2,a.j));b=Ob.oa[e];1==b&&(b=a.f(7));2!=b?d+=String.fromCharCode(b):(a.f(1)?(b=a.f(15),b=W(b)):(b=a.f(8),b=te(b)),b&&(d+=b))}return ga(d)}function te(a){var b,c;b=a&8?Sc:Rc;if(1==(a&3))b=v(b,7),c=La(132,(b>>4&3)+1);else switch(c=W(b),a&3){case 2:c=ue(0,b)+c;break;case 3:c=ue(2,b)+c}c.length&&a&4&&(c=c.substr(0,1).toUpperCase()+c.substr(1));return c}
function ue(a,b){var c=v(b,7)>>a&3;return c?La(131,c):""};function pb(a,b){if(b>=xb[a].M)return"";var c,d;xb[a].fa?(c=xb[a].ga[b],d=xb[a].ka[b]):(c=xb[a].va,d=b*c);return c?xb[a].data.substring(d,d+c):""}var xb=[];var rb=!1,sb=!1;try{var ve=document.createElement("audio").canPlayType("audio/wav"),rb=""!=ve&&"no"!=ve}catch(we){}function qb(a,b){this.data=Array(a);this.w=a;this.L=b}qb.prototype.time=function(){return this.w/this.L};qb.prototype.play=function(){var a=$(document.createElement("audio"));$(document.body).append(a);a.attr("src","data:audio/x-wav;base64,"+xe(this));var b=ud();null==b&&(b=50);a.attr("volume",b/100);a.bind("ended",function(){a.remove()});a.get(0).play()};
function xe(a){var b=Array(44+a.w);b[0]=82;b[1]=73;b[2]=70;b[3]=70;var c=36+a.w;b[4]=c&255;b[5]=c>>8&255;b[6]=c>>16&255;b[7]=c>>24&255;b[8]=87;b[9]=65;b[10]=86;b[11]=69;b[12]=102;b[13]=109;b[14]=116;b[15]=32;b[16]=16;b[17]=0;b[18]=0;b[19]=0;b[20]=1;b[21]=0;b[22]=1;b[23]=0;b[24]=a.L&255;b[25]=a.L>>8&255;b[26]=a.L>>16&255;b[27]=a.L>>24&255;b[28]=b[24];b[29]=b[25];b[30]=b[26];b[31]=b[27];b[32]=1;b[33]=0;b[34]=8;b[35]=0;b[36]=100;b[37]=97;b[38]=116;b[39]=97;b[40]=a.w&255;b[41]=a.w>>8&255;b[42]=a.w>>16&
255;b[43]=a.w>>24&255;for(c=0;c<a.w;c++)b[44+c]=a.data[c];a="";var d,e,g,k=0;do d=b[k++],e=b[k++],g=b[k++],c=d>>2,d=(d&3)<<4,void 0==e?e=g=64:void 0==g?(d|=e>>4,e=(e&15)<<2,g=64):(d|=e>>4,e=(e&15)<<2|g>>6,g&=63),a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g);
while(k<b.length);return a};var ye=document.createElement("link");ye.type="text/css";ye.rel="stylesheet";ye.href="mac.css";$("head").append(ye);aa=$(document.createElement("img"));aa.attr("src","images/mac/start.png");aa.css("width","100%");aa.css("height","100%");desktop.append(aa);
$.ajax({url:gamename,beforeSend:function(a){a.overrideMimeType("text/html; charset=x-user-defined")},complete:function(a){y=new xa(a.responseText);y.seek(1044,y.set);wa=C(y);y.seek(1052,y.set);va=B(y);y.seek(1174,y.set);Aa=B(y);a=(Aa+va)*wa;y.seek(a+wa-2,y.set);var b=B(y);y.seek(a+b+2,y.set);b=C(y);Ba(a,b)}});setTimeout(vb,10);
