var j=void 0;function k(){return function(){}}function aa(a){return function(){return a}}var o,q,ba=15,ca=19;function da(a){for(var b="",c=0;c<a.length;c++)switch(a.charCodeAt(c)){case 13:b+="<br />";break;case 63368:b+="&#224;";break;case 63374:b+="&#233;";break;case 63401:b+="&#169;";break;case 63433:b+="...";break;case 63441:b+="&#8212;";break;default:b+=a.charAt(c)}return b};function ea(a){for(var b in r)if(r[b].name==a){if(r[b].S==0)break;s.seek((r[b].Y+fa)*ga,s.set);return new t(u(s,r[b].S))}}var r=[],s=j,ga,fa,ha;
function ia(a,b){var c=a+b*512;s.seek(c+8,s.set);var d=v(s);v(s);var e=x(s);switch(d){case 0:for(d=0;d<e;d++){s.seek(c+512-(d+1)*2,s.set);var f=x(s);s.seek(c+f,s.set);var g=v(s);s.seek(c+f+g+1,s.set);f=y(s);ia(a,f)}break;case 255:for(d=0;d<e;d++)if(s.seek(c+512-(d+1)*2,s.set),f=x(s),f=c+f,s.seek(f,s.set),g=v(s),g!=0){g++;g&1&&g++;v(s);var h=y(s),i=v(s);i=u(s,i);s.seek(f+g,s.set);switch(x(s)){case 512:h={parent:h,name:i},s.seek(f+g+4,s.set),h.type=y(s),h.T=y(s),s.seek(f+g+20,s.set),i=y(s),s.seek(2,
s.h),h.S=y(s),s.seek(6,s.h),h.F=y(s),s.seek(f+g+74,s.set),h.Y=x(s),s.seek(f+g+86,s.set),h.N=x(s),r[i]=h}}break;default:fatal("Bad HFS Node")}};var ka=[],la=!1;function ma(a,b,c){this.width=a;this.height=b;this.n=c;this.v=a;this.t=b;this.data=Array(b*c)}
ma.prototype.g=function(a,b,c){if(!(this.width==0||this.height==0)){var d=a.get(0).getContext("2d"),e=this.width,f=this.height,g=0,h=0;b<0&&(g=-b,b=0);c<0&&(h=-c,c=0);e+b>=a.width()&&(e=a.width()-b);f+c>=a.height()&&(f=a.height()-c);if(!(e==0||f==0)){a=d.getImageData(b,c,e,f);for(var i=h;i<f;i++)for(var n=i*this.n,l=(i-h)*a.width*4,m,p=g;p<e;p++)m=(m=this.data[n+(p>>3)]&1<<7-(p&7))?0:255,a.data[l++]=m,a.data[l++]=m,a.data[l++]=m,a.data[l++]=255;d.putImageData(a,b,c)}}};
function na(a,b,c,d,e,f){a=a.get(0).getContext("2d");for(var g=a.getImageData(b,c,d,e),h=0;h<e;h++)for(var i=h*g.width*4,n=f?0:255,l=0;l<d;l++)g.data[i++]=n,g.data[i++]=n,g.data[i++]=n,g.data[i++]=255;a.putImageData(g,b,c)};function oa(a){pa.push(a);return pa.length-1}function z(a,b){for(var c=a.charCodeAt(0)<<24|a.charCodeAt(1)<<16|a.charCodeAt(2)<<8|a.charCodeAt(3),d=pa.length-1;d>=0;d--){var e=pa[d];e.seek(0,e.set);var f=y(e),g=y(e);e.seek(g+24,e.set);g+=x(e);e.seek(g,e.set);for(var h=x(e)+1,i=0;i<h;i++){if(y(e)==c){c=x(e)+1;e.seek(g+x(e),e.set);for(i=0;i<c;i++){if(x(e)==b)return e.seek(2,e.h),f+=y(e)&16777215,e.seek(f,e.set),f=y(e),new t(u(e,f));e.seek(10,e.h)}return}e.seek(4,e.h)}}}
function qa(){var a=z("STR ",133);if(a==j)return"";var b=v(a);return u(a,b)}function ra(a,b){if(b==0)return"";var c=z("STR#",a);if(c==j)return"";var d=x(c);if(b>d)return"";for(;;){b--;if(b==0)return d=v(c),u(c,d);d=v(c);c.seek(d,c.h)}}function sa(a){var b=x(a),c=x(a),d=x(a)-b,e=x(a)-c;x(a);v(a);v(a);x(a);x(a);var f=x(a),g=y(a),h=v(a),i="";h!=0&&(i=u(a,h));a=[];h=0;switch(f>>4){case 0:h=10;a=[i];break;case 128:h=25,a=[i]}return A([c,b,e,d],g,h,a)}var pa=[];function ta(a){var b=x(a);a.seek(12,a.h);var c=v(a),d="";c!=0&&(d=u(a,c));c==1&&(d="");B={id:b};B.a=$(document.createElement("div"));d==""?B.a.addClass("apple"):B.a.html(d);B.a.data("refCon",B);B.a.mousedown(function(a){if(E)return!1;ua(a);return!1});B.i=$(document.createElement("table"));B.i.addClass("menu");B.body=$(document.createElement("tbody"));B.i.append(B.body);B.l=[];G.append(B.a);H.push(B);for(c=0;;){var e=v(a);if(e==0)break;d="";e!=0&&(d=da(u(a,e)));v(a);e=v(a);v(a);v(a);e=e!=0?String.fromCharCode(e):
"";va(d,b<<8|c,e);c++}};var wa=1,xa=18,ya=18,za=2,Aa=15,Ba=15,Ca=15,Da=0;function Ea(){var a=z(ra(129,1),0),b=v(a);a=da(u(a,b));b=Fa(146,96,220,150);b.add(A([75,120,70,18],1,10,["Ok"]));b.add(A([20,30,180,40],2,15,a));b.add(A([20,80,180,40],3,15,["WebVenture <br/> &#169; 2010 Sean Kasun"]));b.getItem(2).css("text-align","center");b.getItem(3).css("text-align","center");return b}
function Ga(){var a=Fa(146,96,220,120);a.add(A([75,90,70,18],1,10,["Ok"]));a.add(A([55,55,110,13],2,24,[0,0,100]));a.add(A([20,25,180,20],3,15,["Sound Volume"]));a.getItem(3).css("text-align","center");return a}
function Ha(a){a=da(ra(128,[8,9,7][a]));var b=z("ALRT",131),c=x(b),d=x(b),e=x(b)-c,f=x(b)-d,g=x(b);b=Fa(d,c,f,e);g=z("DITL",g);for(var h=x(g)+1,i=0;i<h;i++){y(g);c=x(g);d=x(g);e=x(g)-c;f=x(g)-d;var n=v(g),l=v(g),m="";l>0&&(m=da(u(g,l)));l&1&&v(g);switch(n&127){case 4:b.add(A([d,c,f,e],10,i+1,[m]));break;case 8:b.add(A([d,c,f,e],15,i+1,[m]));break;case 16:b.add(A([d,c,f,e],17,i+1,[m]));break;default:fatal("Unknown DITL:"+(n&127))}}b.param([a]);return b}
function Ia(){var a=Fa(82,71,348,200);a.add(A([256,138,80,18],1,10,["Open"]));a.add(A([256,163,80,18],2,10,["Cancel"]));a.add(A([12,39,218,146],3,23,[]));return a}function Ja(){var a=Fa(104,79,304,184);a.add(A([218,132,70,18],1,10,["Save"]));a.add(A([218,158,70,18],2,10,["Cancel"]));a.add(A([14,136,183,16],5,15,["Save as:"]));a.add(A([17,157,177,16],3,17,[""]));a.add(A([14,29,183,98],4,23,[]));return a}
function Ka(a){var b=x(a),c=x(a),d=x(a)-b,e=x(a)-c,f="",g=!1;switch(x(a)){case 0:f="document";break;case 1:f="dBox";break;case 2:f="plainDBox";break;case 3:f="altDBox";break;case 4:f="noGrowDoc";break;case 5:f="movableDBox";break;case 8:f="zoomDoc";g=!0;break;case 12:f="zoomNoGrow";g=!0;break;case 16:f="rDoc16";break;case 18:f="rDoc4";break;case 20:f="rDoc6";break;case 22:f="rDoc10"}x(a);var h=x(a)!=0;y(a);var i=v(a);i!=1&&u(a,i);a=new La(f,h,g,!1,!1,c,b,e,d);a.hide();Ma(a);return a};function t(a){this.set=0;this.h=1;this.end=2;this.data=a;this.length=a.length;this.o=this.e=0}function v(a){return a.data.charCodeAt(a.e++)&255}function x(a){var b=(a.data.charCodeAt(a.e++)&255)<<8;b|=a.data.charCodeAt(a.e++)&255;return b}function Na(a){var b=(a.data.charCodeAt(a.e++)&255)<<16;b|=(a.data.charCodeAt(a.e++)&255)<<8;b|=a.data.charCodeAt(a.e++)&255;return b}
function y(a){var b=(a.data.charCodeAt(a.e++)&255)<<24;b|=(a.data.charCodeAt(a.e++)&255)<<16;b|=(a.data.charCodeAt(a.e++)&255)<<8;b|=a.data.charCodeAt(a.e++)&255;return b}function Oa(a){var b=(a.data.charCodeAt(a.e)&255)<<24;b|=(a.data.charCodeAt(a.e+1)&255)<<16;b|=(a.data.charCodeAt(a.e+2)&255)<<8;b|=a.data.charCodeAt(a.e+3)&255;return b}t.prototype.seek=function(a,b){switch(b){case this.h:a+=this.e;break;case this.end:a+=this.length}this.e=a};
function u(a,b){var c=a.e;a.e+=b;return a.data.substring(c,a.e)}t.prototype.d=function(a){var b=Oa(this);b>>>=32-this.o-a;b&=(1<<a)-1;this.o+=a;this.o&16&&(this.o&=15,this.e+=2);return b};function Pa(){if(s!=j){for(var a,b=1;a==j&&b<5;b++)a:{for(var c=a=0,d=0;d<4;d++)a|="APPL".charCodeAt(d)<<24-d*8,c|=("MCV"+b).charCodeAt(d)<<24-d*8;for(d in r)if(r[d].type==a&&r[d].T==c){s.seek((r[d].N+fa)*ga,s.set);a=new t(u(s,r[d].F));break a}a=j}oa(a);q.remove();delete q;b=ra(129,2);var e;a:{for(e in r)if(r[e].name==b){if(r[e].F==0)break;s.seek((r[e].N+fa)*ga,s.set);e=new t(u(s,r[e].F));break a}e=j}if(e!=j)b=oa(e),e=Qa(z("PPIC",0)),delete pa[b],pa.splice(b,1);else{e=ea(b);b=new ma(512,302,64);a=
Array(72);e.seek(512,e.set);for(d=c=0;d<b.t;d++){for(var f=0;f<72;){var g=v(e);if(g!=128)if(g&128){g^=255;g+=2;for(var h=v(e),i=0;i<g;i++)a[f++]=h}else{g++;for(i=0;i<g;i++)a[f++]=v(e)}}for(i=0;i<64;i++)b.data[c++]=a[i]}e=b}b=new La("plainDBox",!1,!1,!1,!1,0,0,512,342);b.hide();Ma(b);Ra=b;Ra.show();e.g(Ra.port,0,0);for(e=0;e<5;e++){b=e;a=ra(129,e+4);a=ea(a);c={Z:0,O:!1};a.seek(0,a.set);f=a.length;d=y(a);g=j;if(d&2147483648){d&=2147483647;c.O=!0;a.seek(d,a.set);c.B=x(a);f=Array(16);g=Array(16);for(h=
0;h<15;h++)f[h]=x(a);for(h=0;h<16;h++)g[h]=v(a);c.Q=Array(c.B);c.P=Array(c.B);i=0;var n=j;for(h=0;h<c.B;h++){if((h&63)==0){a.seek(d+(h>>6)*6+48,a.set);var l=Na(a);n=Na(a);i=l&7;a.seek(d+(l>>3),a.set)}c.Q[h]=n;l=y(a)>>>16-i&65535;a.seek(-4,a.h);var m;for(m=0;m<16;m++)if(f[m]>l)break;l=g[m];i+=l&15;i&16&&(i&=15,a.seek(2,a.h));l>>=4;m=0;l&&(m=Oa(a),l--,l==0?m=0:m>>>=32-l-i,m&=(1<<l)-1,m|=1<<l,i+=l,i&16&&(i&=15,a.seek(2,a.h)),n+=m);c.P[h]=m}g=d-4}else f-=4,g=f,c.U=d,c.B=f/d|0;a.seek(4,a.set);c.data=u(a,
g);I[b]=c}e=z("GNRL",128);J=x(e);Sa=x(e);Ta=x(e);L=x(e);Ua=x(e);x(e);x(e);x(e);x(e);x(e);x(e);x(e);x(e);x(e);Va=Array(L);for(b=0;b<L;b++)Va[b]=v(e);Wa=Array(L);for(b=0;b<L;b++)Wa[b]=x(e);Xa=Array(L);for(b=0;b<L;b++)Xa[b]=v(e);Ya=Array(Ta);for(b=0;b<Ta;b++)Ya[b]=v(e);Za=Array(Ta);for(b=0;b<Ta;b++)Za[b]=v(e);$a=[];ab=[];bb=[];db=[];eb=Array(J*2);z("GNRL",131);fb=Ka(z("WIND",128));fb.m=9;fb.addClass("commands");for(e=0;e<Ta;e++)Za[e]&&fb.add(sa(z("CNTL",129+e)));gb=Ka(z("WIND",129));gb.m=10;N=Ka(z("WIND",
130));N.m=11;Q=$(document.createElement("div"));Q.addClass("textEdit");e=N;b=Q;a=e.port.width();c=e.port.height();e.port.remove();b.css("top","0px");b.css("left","0px");b.css("width",a+"px");b.css("height",c+"px");e.port=b;e.c.append(b);hb=Ka(z("WIND",131));hb.m=12;hb.b={id:0,x:0,y:0,children:[{id:1,top:0,left:0,width:0,height:0}]};ib=Ka(z("WIND",132));ib.m=13;ib.addClass("exits");G=$(document.createElement("div"));G.addClass("menubar");for(e=128;e<=133;e++)ta(z("MENU",e));B=H[0];va("Adjust Volume...",
2304,"");jb(N,ra(128,1));if(gameparts.length>1)R=gameparts[1],e=window.JSON.parse(window.localStorage.getItem(R).toString()),S=e.L,kb=e.M,Q.html(e.text),jb(N,R);else{e=ea(qa());S=Array(Ua);kb=Array(Sa);for(b=0;b<Ua;b++){S[b]=Array(J);for(a=0;a<J;a++)S[b][a]=x(e)}for(b=0;b<Sa;b++)kb[b]=x(e)}lb();R==""&&ab.push(T(1,0));setTimeout(mb,500)}else setTimeout(Pa,10)}function lb(){for(var a,b,c=0;c<J*2;c++)eb[c]=0;for(c=J-1;c;c--)a=S[0][c],(b=eb[a*2])&&(eb[c*2+1]=b),eb[a*2]=c}
function nb(){for(var a=[],b=0;b<U.length;b++)(U[b].m==10||U[b].m==14)&&a.push(U[b]);for(b in a){var c=a[b];if(c!=j)if(c.m==10)c.b={},jb(c,"");else{var d={I:c.port.height(),H:c.port.width()};ob(c,{I:0,H:0});ob(c,d);c.b={};V(c)}}db=[];$a=[]}var eb;
function mb(){V(Ra);delete Ra;desktop.append(G);fb.show();hb.show();var a=hb;if(a!=j&&a.b!=j&&(a==hb||T(a.b.id,6)==1)){if(a==gb)pb(a.b.id*2).g(gb.port,0,0);else{var b=a.port,c=Da;na(b,0,0,b.width(),b.height(),c)}for(b=0;b<a.b.children.length;b++){var d=a.b.children[b].id;c=a;var e=T(d,1),f=T(d,2),g=T(d,3);if(!g||!T(d,4)){var h=1;g?h=0:bb.indexOf(d)!=-1&&(h=2);g=j;e-=c.b.x;g=f-c.b.y;f=c.port;var i=h;h={top:0,left:0,width:0,height:0};var n=j;if(n=pb(d*2+1))switch(h={top:g,left:e,width:n.width,height:n.height},
i){case 1:var l=n,m=e,p=g;if(!(l.width==0||l.height==0)){var M=f.get(0).getContext("2d"),C=l.width,w=l.height,ja=0,F=0;m<0&&(ja=-m,m=0);p<0&&(F=-p,p=0);C+m>=f.width()&&(C=f.width()-m);w+p>=f.height()&&(w=f.height()-p);if(!(C==0||w==0)){for(var D=M.getImageData(m,p,C,w),O=F;O<w;O++)for(var cb=O*l.n,K=(O-F)*D.width*4,wb,P=ja;P<C;P++)(wb=l.data[cb+(P>>3)]&1<<7-(P&7))?(D.data[K++]=255,D.data[K++]=255,D.data[K++]=255,D.data[K++]=255):K+=4;M.putImageData(D,m,p)}}break;case 2:if(l=n,m=e,p=g,!(l.width==0||
l.height==0))if(M=f.get(0).getContext("2d"),C=l.width,w=l.height,F=ja=0,m<0&&(ja=-m,m=0),p<0&&(F=-p,p=0),C+m>=f.width()&&(C=f.width()-m),w+p>=f.height()&&(w=f.height()-p),!(C==0||w==0)){D=M.getImageData(m,p,C,w);for(O=F;O<w;O++){cb=O*l.n;K=(O-F)*D.width*4;for(P=ja;P<C;P++)(wb=l.data[cb+(P>>3)]&1<<7-(P&7))?(D.data[K++]=0,D.data[K++]=0,D.data[K++]=0,D.data[K++]=255):K+=4}M.putImageData(D,m,p)}}else if(n=pb(d*2))switch(h={top:g,left:e,width:n.width,height:n.height},i){case 1:na(f,e,g,n.width,n.height,
0);break;case 2:na(f,e,g,n.width,n.height,1)}if(i>0&&(n=pb(d*2)))if(d=n,!(d.width==0||d.height==0))if(i=f.get(0).getContext("2d"),n=d.width,l=d.height,p=m=0,e<0&&(m=-e,e=0),g<0&&(p=-g,g=0),n+e>=f.width()&&(n=f.width()-e),l+g>=f.height()&&(l=f.height()-g),!(n==0||l==0)){f=i.getImageData(e,g,n,l);for(M=p;M<l;M++){C=M*d.n;w=(M-p)*f.width*4;for(F=m;F<n;F++)(ja=d.data[C+(F>>3)]&1<<7-(F&7))?(f.data[w++]^=255,f.data[w++]^=255,f.data[w++]^=255,f.data[w++]=255):w+=4}i.putImageData(f,e,g)}g=h;g.top+=c.b.y;
g.left+=c.b.x;c=g}else c={top:0,left:0,width:0,height:0};a.b.children[b].top=c.top;a.b.children[b].left=c.left;a.b.children[b].width=c.width;a.b.children[b].height=c.height}if(a.m==14&&a.b.X){b={top:0,left:0,right:0,bottom:0};a.b.X=!1;for(c=0;c<a.b.children.length;c++)h=a.b.children[c],b.right==b.left||b.bottom==b.top?(b.top=h.top,b.left=h.left,b.bottom=h.top+h.height,b.right=h.left+h.width):(b.top=Math.min(b.top,h.top),b.left=Math.min(b.left,h.left),b.bottom=Math.max(b.bottom,h.top+h.height),b.right=
Math.max(b.right,h.left+h.width));if(b.right==b.left||b.bottom==b.top)b.top=a.b.y,b.left=a.b.x,b.bottom=a.b.y,b.right=a.b.x;else{if(b.left>a.b.x)b.left=a.b.x;if(b.right<a.b.x)b.right=a.b.x;if(b.top>a.b.y)b.top=a.b.y;if(b.bottom<a.b.y)b.bottom=a.b.y}if(a.m==11)a.f.data("min",b.top),a.f.data("max",b.bottom),f=a.port.scrollTop(),b=a.f.data("min"),c=a.f.data("max"),b<c?(h=f-b,f+=a.port.height(),h=h*(a.height-15-xa-15)/(c-b)|0,b=f*(a.height-15-xa-15)/(c-b)|0,a.f.css("top",h+15+"px"),a.f.css("height",b-
h+"px")):(a.f.css("top","15px"),a.f.css("height",a.height-15-xa-15+"px"));else{if(b.left>a.b.x)b.left=a.b.x;if(b.right<a.b.x+a.port.width())b.right=a.b.x+a.port.width();if(b.top>a.b.y)b.top=a.b.y;if(b.bottom<a.b.y+a.port.height())b.bottom=a.b.y+a.port.height();a.w&&(a.j.data("min",b.left),a.j.data("max",b.right));a.z&&(a.f.data("min",b.top),a.f.data("max",b.bottom));a.w&&(b=a.j.data("min"),c=a.j.data("max"),b<c?(f=a.b.x-b,h=a.port.width(),f=f*(a.port.width()-15)/(c-b)|0,b=h*(a.port.width()-15)/(c-
b)|0,b>a.port.width()-15-f&&(b=a.port.width()-15-f),a.j.css("left",f+15+"px"),a.j.css("width",b+"px")):(a.j.css("left","15px"),a.j.css("width",a.port.width()-15+"px")));a.z&&(b=a.f.data("min"),c=a.f.data("max"),b<c?(f=a.b.y-b,h=a.port.height(),f=f*(a.port.height()-15)/(c-b)|0,b=h*(a.port.height()-15)/(c-b)|0,b>a.port.height()-15-f&&(b=a.port.height()-15-f),a.f.css("top",f+15+"px"),a.f.css("height",b+"px")):(a.f.css("top","15px"),a.f.css("height",a.port.height()-15+"px")))}}}ib.show();N.show();gb.show();
qb=Q.get(0).scrollHeight;Q.scrollTop(qb-qb%ba);rb(T(1,0));W=!1;sb()};var W=!1,qb=0,bb,ab,Ya,Za,$a,db,Ra,gb,fb,N,hb,ib,Q,J,Sa,Ta,L,Ua,Xa,Wa,Va,S,kb,R="";function X(){}var E=!1;function sb(){fatal("runmain")}function rb(a){var b=1;if($a.indexOf(a)==-1){$a.push(a);var c={a:a};c.parent=T(a,0);c.x=T(a,1);c.y=T(a,2);c.$=T(a,9);c.aa=T(a,10);c.ba=T(a,11);c.da=T(a,3);c.ca=T(a,4);db.push({id:7,val:c})}c=Va[6];b<<=Xa[6];b&=Wa[6];S[c][a]=b|S[c][a]&~Wa[6];W=!0}
function T(a,b){var c,d=Va[b];if(d&128){var e=tb(0,a);if(e.length==0)return 0;d&=127;c=(e.charCodeAt(d*2)&255)<<8;c|=e.charCodeAt(d*2+1)&255}else c=S[d][a];c&=Wa[b];c>>=Xa[b];c&32768&&(c=-((c^65535)+1));return c}function ub(a){switch(a){case 256:vb();break;case 257:xb();break;case 258:yb();break;case 259:X=k();zb();break;case 260:X=k();Ab();break;case 261:Bb();break;case 2304:Cb();break;default:fatal("Unknown menuitem: "+a.toString(16))}}
function vb(){var a=Ea();E=!0;a.show(function(){V(a);E=!1})}function Cb(){var a=Ga(),b=Db();b==null&&(b=50);Eb(a.getItem(2),b);E=!0;a.show(function(){var b=a.getItem(2).value,d=new Date;d.setTime(d.getTime()+31536E6);document.cookie="webventure_volume="+escape(b)+"; expires="+d.toGMTString()+"; path=/";V(a);E=!1})}function xb(){if(W){var a=Ha(0);E=!0;a.show(function(b){V(a);switch(b){case 1:X=xb;zb();break;case 2:Fb();break;case 3:E=!1}})}else Fb()}
function Fb(){R="";for(var a=ea(qa()),b=0;b<Ua;b++)for(var c=0;c<J;c++)S[b][c]=x(a);for(b=0;b<Sa;b++)kb[b]=x(a);nb();lb();jb(N,ra(128,1));Q.html("");ab=[T(1,0)];rb(T(1,0));W=!1;sb()}function yb(){if(W){var a=Ha(1);E=!0;a.show(function(b){V(a);switch(b){case 1:X=yb;zb();break;case 2:Gb();break;case 3:E=!1}})}else Gb()}
function Gb(){var a=Ia();E=!0;for(var b=a.getItem(3),c=j,d=0;d<window.localStorage.length;d++){var e=window.localStorage.key(d);if(e!=null&&window.JSON.parse(window.localStorage.getItem(e).toString()).R==gamename){var f=$(document.createElement("div"));f.addClass("listitem");f.mousedown(aa(!1));f.click(function(a){c&&c.removeClass("active");c=$(a.target);c.addClass("active")});f.dblclick(function(){a.getItem(1).a.click()});f.text(e.toString());b.a.append(f)}}a.show(function(b){switch(b){case 1:if(c==
j)break;R=c.text();V(a);E=!1;b=window.JSON.parse(window.localStorage.getItem(R).toString());S=b.L;kb=b.M;nb();lb();jb(N,R);Q.html(b.text);qb=Q.get(0).scrollHeight;Q.scrollTop(qb);ab=[];rb(T(1,0));W=!1;sb();break;case 2:V(a),E=!1}})}function zb(){R==""?Ab():(window.localStorage.setItem(R,window.JSON.stringify({R:gamename,L:S,M:kb,text:Q.html()})),jb(N,R),W=!1,X())}
function Ab(){var a=Ja();E=!0;var b=a.getItem(3);b.a.focus();b.a.keypress(function(b){if(b.which==13)return a.getItem(1).a.click(),!1;return!0});b=a.getItem(4);for(var c=j,d=0;d<window.localStorage.length;d++){var e=window.localStorage.key(d);if(e!=null&&window.JSON.parse(window.localStorage.getItem(e).toString()).R==gamename){var f=$(document.createElement("div"));f.addClass("listitem");f.mousedown(aa(!1));f.click(function(b){c&&c.removeClass("active");c=$(b.target);c.addClass("active");a.getItem(3).a.val(c.text())});
f.dblclick(function(){a.getItem(1).a.click()});f.text(e.toString());b.a.append(f)}}a.show(function(b){switch(b){case 1:R=a.getItem(3).a.val();V(a);E=!1;zb();break;case 2:V(a),E=!1,X()}})}function Bb(){if(W){var a=Ha(2);E=!0;a.show(function(b){V(a);switch(b){case 1:X=Bb;zb();break;case 2:sb();break;case 3:E=!1}})}else sb()}
function Db(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var c=a[b];c.charAt(0)==" ";)c=c.substring(1,c.length);if(c.indexOf("webventure_volume=")==0)return unescape(c.substring(18,c.length))}return null};function pb(a){a=tb(3,a);if(!(a.length<2)){if(a.length==2)return pb((a.charCodeAt(0)&255)<<8|a.charCodeAt(1)&255);return Qa(new t(a))}}
function Qa(a){var b=a.d(3),c,d;la&&a.d(2);d=a.d(1)?a.d(10):a.d(6);if((c=a.d(1)?a.d(10):a.d(6))&&d){c=new ma(c,d,c+15>>3&65534);switch(b){case 0:b=c.v>>4;d=c.v&15;for(var e,f=0,g=0;g<c.t;g++){for(var h=0;h<b;h++)e=Oa(a),a.seek(2,a.h),e>>>=16-a.o,c.data[f++]=e>>8&255,c.data[f++]=e&255;d&&(e=a.d(d),e<<=16-d,c.data[f++]=e>>8&255,c.data[f++]=e&255)}break;case 1:Hb(Ib,Jb,Kb,c,a);break;case 2:Hb(Lb,Mb,Nb,c,a);break;case 3:b=Array(17);for(f=0;(d=Ob[f++])!=255;){for(e=a.d(d);(d=Ob[f++])!=255;)b[Ob[f++]]=
e%d,e=e/d|0;b[Ob[f++]]=e}b[16]=0;for(e=16;e>0;e--)for(d=e;d<=16;d++)b[d]>=b[e-1]&&b[d]++;for(e=16;e>=0;e--)if(b[e]==16){b[e]=255;break}f=Array(17);g=Array(17);d=a.d(2)+1;for(e=h=0;e<15;e++){if(e)for(;!a.d(1);)d++;g[e]=d;f[e]=h;h+=1<<16-d}for(f[15]=h;h&1<<16-d;)d++;f[16]=h|1<<16-d;g[15]=d;g[16]=d;Hb(f,g,b,c,a)}return c}}
var Ib=[0,8192,16384,20480,24576,28672,32768,36864,40960,45056,49152,53248,55296,57344,59392,61440,63488],Jb=[3,3,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5],Kb=[0,15,3,5,6,7,8,9,10,12,255,1,2,4,11,13,14],Lb=[0,16384,32768,49152,51200,53248,55296,57344,59392,61440,62464,62976,63488,64E3,64512,65024,65280],Mb=[2,2,2,5,5,5,5,5,5,6,7,7,7,7,7,8,8],Nb=[255,0,15,1,3,7,14,12,8,6,2,4,9,13,11,10,5],Ob=[8,15,2,255,0,4,255,1,7,9,8,255,3,4,255,4,10,7,10,11,6,255,5,6,6,11,255,7,3,255,9,4,3,14,255,12,2,255,13,1,255,15,255];
function Hb(a,b,c,d,e){var f;Y=Z=0;f=d.v&3?e.d(5):e.d(4)<<1;var g=0,h=d.v&15;h&&(h>>=2,g=h&1,h=2-(h>>1));for(var i=0,n=0;n<d.t;n++){for(var l=0;l<d.v>>3;l++){var m=Pb(a,b,c,e)<<4;d.data[i++]=Pb(a,b,c,e)|m}g&&(d.data[i]=Pb(a,b,c,e)<<4);i+=h}if(l=d.v&3){i=d.n-h;var p=0;for(n=h=0;n<d.t;n++)f&1?(p<l&&(m=Pb(a,b,c,e)<<4,h|=m>>>p,p+=4),p-=l,m=h,h<<=l,h&=255):(m=e.d(l),m<<=8-l),g&&(m>>>=4),d.data[i]|=m&255,i+=d.n}if(f&8)for(n=i=0;n<d.t;n++)if(m=0,f&2)for(l=0;l<d.n;l++)d.data[i]^=m,m=d.data[i++];else for(l=
0;l<d.n;l++)h=d.data[i]^m,h^=h>>>4&15,d.data[i++]=h,m=h<<4&255;if(f&4){a=d.n*4;f&2&&(a*=2);i=0;f=a;for(b=0;b<d.t*d.n-a;b++)d.data[f++]^=d.data[i++]}}var Z=0,Y=0;
function Pb(a,b,c,d){if(Z)return Z--,Y=Y<<8&65280|Y>>8,Y&255;var e=Oa(d);e>>>=16-d.o;e&=65535;var f;for(f=0;f<16;f++)if(a[f+1]>e)break;d.o+=b[f];d.o&16&&(d.o&=15,d.seek(2,d.h));a=c[f];if(a==255)return d.d(1)||(Y&=255,Y|=Y<<8),Z=d.d(3),Z<3&&(Z<<=4,Z|=d.d(4),Z<8&&(Z<<=8,Z|=d.d(8))),Z-=2,Y=Y<<8&65280|Y>>8,Y&255;else Y<<=8,Y|=a,Y&=65535;return a};function va(a,b,c){var d={id:b},e=$(document.createElement("tr"));if(a[0]=="-"){var f=$(document.createElement("td"));f.attr("colspan","2");f.addClass("divider");f.append(document.createElement("hr"))}else e.addClass("menuitem"),f=$(document.createElement("td")),f.html(da(a)),e.append(f),f=$(document.createElement("td")),c!=""&&(f.addClass("shortcut"),Qb.push({key:c,id:b}),f.text(c));e.append(f);d.a=e;d.enabled=!0;d.enabled||d.a.addClass("disabled");B.body.append(d.a);B.l.push(d)}
function ua(a){for(var b=$(a.target);b.data("refCon")==j;)b=b.parent();b.addClass("active");var c=b.data("refCon");desktop.append(c.i);a=b.position();c.i.css("top",a.top+ca+"px");c.i.css("left",a.left+"px");var d=-1;$(document).mousemove(function(a){var f=G.offset();if(a.pageX>=f.left&&a.pageY>f.top&&a.pageX<f.left+G.width()&&a.pageY<f.top+G.height())for(var g=0;g<H.length;g++){if(f=H[g].a.offset(),a.pageX>=f.left&&a.pageX<f.left+H[g].a.outerWidth()){c.i.remove();b.removeClass("active");b=H[g].a;
b.addClass("active");c=b.data("refCon");desktop.append(c.i);f=b.position();c.i.css("top",f.top+ca+"px");c.i.css("left",f.left+"px");break}}else if(f=c.i.offset(),a.pageX>=f.left&&a.pageY>=f.top&&a.pageX<f.left+c.i.outerWidth()&&a.pageY<f.top+c.i.outerHeight())for(g=0;g<c.l.length;g++){var h=c.l[g].a;h.hasClass("menuitem")&&c.l[g].enabled&&(f=h.offset(),a.pageY>=f.top&&a.pageY<f.top+h.outerHeight()?(d=g,h.addClass("active")):h.removeClass("active"))}else{for(g=0;g<c.l.length;g++)c.l[g].a.removeClass("active");
d=-1}});$(document).mouseup(function(){$(document).unbind("mousemove");$(document).unbind("mouseup");c.i.remove();b.removeClass("active");d!=-1&&ub(c.l[d].id)})}var G,H=[],Qb=[],B=j;$("body").keydown(function(a){if(a.target.type=="text")return!1;if(!a.altKey)return!1;if(E)return!1;for(var b=0;b<Qb.length;b++)if(Qb[b].key.charCodeAt(0)==a.which)for(var c=Qb[b].id,d=0;d<H.length;d++)for(var e=0;e<H[d].l.length;e++)H[d].l[e].id==c&&H[d].l[e].enabled&&Rb(H[d],c)});
function Rb(a,b){a.a.addClass("active");setTimeout(function(){a.a.removeClass("active");ub(b)},200)};function La(a,b,c,d,e,f,g,h,i){this.u=[];this.K=c;this.J=b;this.z=d;this.w=e;this.c=$(document.createElement("div"));this.c.addClass(a);if(a=="document"||a=="info")b="<span></span>",this.title=$(document.createElement("div")),this.title.addClass("title"),this.title.mousedown(function(a){E||fatal(a);return!1}),this.J&&(b='<div class="close"></div>'+b),this.K&&(b+='<div class="resize"></div>'),this.title.html(b),this.J&&(b=this.title.children("div.close"),b.mousedown(aa(!1)),b.click(function(a){E||
fatal(a);return!1})),this.K&&(b=this.title.children("div.resize"),b.mousedown(aa(!1)),b.click(function(a){E||fatal(a);return!1})),this.c.append(this.title);this.port=$(document.createElement("canvas"));this.port.mousedown(function(a){E||fatal(a);return!1});this.port.attr("width",h);this.port.attr("height",i);this.c.append(this.port);this.top=g;this.height=i;this.left=f;this.width=h;a=="document"?(this.top-=xa+wa,this.height+=xa,this.left-=wa):a=="info"?(this.top-=ya+wa,this.height+=ya,this.left-=
wa):a=="alert"?(this.top-=za*2,this.left-=za*2,this.width+=za,this.height+=za):(this.top-=wa,this.left-=wa);this.z&&(this.width+=Aa);this.w&&(this.height+=Ba);this.c.css("top",this.top+"px");this.c.css("left",this.left+"px");this.c.css("width",this.width+"px");this.c.css("height",this.height+"px");desktop.append(this.c);(this.z||this.w)&&Sb(this)}o=La.prototype;o.show=function(){this.c.show();for(var a=0;a<this.u.length;a++)this.u[a].p!=255&&this.u[a].show()};o.hide=function(){this.c.hide()};
function jb(a,b){if(a.title!=j){var c=a.title.children("span");c.html("");if(b=="")c.hide();else{var d=a.c.css("display")=="none";a.c.show();c.css({position:"absolute",visibility:"hidden",display:"block"});var e=a.port.width();a.J&&(e-=30);a.K&&(e-=30);for(var f=0;f<b.length;f++)if(c.append(b.substring(f,f+1)),c.width()>e){c.html(b.substring(0,f-1));break}c.css({position:"",visibility:"",display:""});d&&a.c.hide()}}}o.addClass=function(a){this.c.addClass(a)};o.removeClass=function(a){this.c.removeClass(a)};
o.add=function(a){var b=this.port.position().top,c=parseInt(a.a.css("top"),10);a.a.css("top",c+b+"px");this.c.append(a.a);a.c=this;this.u.push(a);this.c.css("display")!="none"&&a.g()};o.remove=function(a){var b=this.u.indexOf(a);b!=-1&&this.u.splice(b,1);a.a.remove()};o.close=function(){this.c.remove()};function ob(a,b){var c=a.port.offset();b.H+=c.left+1;b.I+=c.top+2;a.b&&(b.H-=a.b.x,b.I-=a.b.y)}
function Sb(a){if(a.w){a.q=$(document.createElement("div"));a.q.addClass("hscroll");a.q.css("top",a.height-Ba+"px");a.q.css("width",a.width-15+"px");a.q.mousedown(function(){fatal("scroll")});var b=$(document.createElement("div"));b.addClass("leftarrow");b.mousedown(function(){fatal("scroll")});a.q.append(b);a.k=$(document.createElement("div"));a.k.addClass("rightarrow");a.k.css("left",a.width-Ca-15+"px");a.k.mousedown(function(){fatal("scroll")});a.q.append(a.k);a.j=$(document.createElement("div"));
a.j.addClass("slider");a.j.mousedown(function(){fatal("drag")});a.q.append(a.j);a.c.append(a.q)}if(a.z)a.r=$(document.createElement("div")),a.r.addClass("vscroll"),a.r.css("left",a.width-Aa+"px"),a.r.css("height",a.height-15+"px"),a.r.mousedown(function(){fatal("scroll")}),b=$(document.createElement("div")),b.addClass("uparrow"),b.mousedown(function(){fatal("scroll")}),a.r.append(b),a.D=$(document.createElement("div")),a.D.addClass("downarrow"),a.D.css("top",a.height-15-15-xa+"px"),a.D.mousedown(function(){fatal("scroll")}),
a.r.append(a.D),a.f=$(document.createElement("div")),a.f.addClass("slider"),a.f.mousedown(function(){fatal("drag")}),a.r.append(a.f),a.c.append(a.r);a.C=$(document.createElement("div"));a.C.addClass("grow");a.C.css("top",a.height-15+"px");a.C.css("left",a.width-15+"px");a.C.mousedown(function(){fatal("grow")});a.c.append(a.C)}function V(a){for(var b=0;b<U.length;b++)if(U[b]==a){a.close();U.splice(b,1);break}U.length&&Ma(U[0])}
function Ma(a){if(U[0]!=a){U[0]!=j&&U[0].c.removeClass("active");for(var b=0;b<U.length;b++)U[b]==a&&U.splice(b,1);U.unshift(a)}a.c.addClass("active")}function Fa(a,b,c,d){a=new La("alert",!1,!1,!1,!1,a,b,c,d);a.m=2;a.hide();Ma(a);return a}var U=[];function A(a,b,c,d){switch(c&255){case 2:return new Tb(a,b,d);case 10:return new Ub(a,b,d);case 15:return new Vb(a,b,d);case 17:return new Wb(a,b,d);case 22:return new Xb(a,b,d);case 23:return new Yb(a,b);case 24:return new Zb(a,b,d);case 25:return new $b(a,b,d);default:fatal("Unknown control:"+c.toString(16))}}
function Tb(a,b,c){this.a=$(document.createElement("canvas"));this.a.addClass("cbutton");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.attr("width",a[2]);this.a.attr("height",a[3]);this.p=b;this.selected=!1;this.V=c[0];this.d=c[1];this.W=c[2];this.a.mousedown(function(){fatal("cbutton")})}Tb.prototype.hide=function(){this.a.hide()};Tb.prototype.show=function(){this.a.show();this.g()};
Tb.prototype.g=function(){var a=this.a.get(0).getContext("2d"),b=a.getImageData(0,0,this.width,this.height),c=this.selected?this.W:this.d;if(c)for(var d=0;d<this.height;d++)for(var e=(d>>1)*this.V,f=d*b.width*4,g,h=0;h<this.width;h++)g=c.charCodeAt(e+(h>>2)),g=(g>>(h&2?0:4)&15)*3,b.data[f++]=ka[g++],b.data[f++]=ka[g++],b.data[f++]=ka[g++],b.data[f++]=255;else for(d=0;d<this.height;d++){f=d*b.width*4;for(h=0;h<this.width;h++){g=this.selected?0:255;if(d<2||h<4||d>this.height-3||h>this.width-5)g=0;b.data[f++]=
g;b.data[f++]=g;b.data[f++]=g;b.data[f++]=255}}a.putImageData(b,0,0)};function Ub(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("button");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.a.html(c[0]);this.p=b;this.a.mousedown(function(){fatal("button")})}Ub.prototype.hide=function(){this.a.hide()};Ub.prototype.show=function(){this.a.show()};Ub.prototype.g=k();
function Vb(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("textblock");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.p=b;this.G(c[0])}Vb.prototype.G=function(a){this.a.html(a)};Vb.prototype.hide=function(){this.a.hide()};Vb.prototype.show=function(){this.a.show()};Vb.prototype.g=k();
function Wb(a,b,c){this.a=$(document.createElement("input"));this.a.addClass("textinput");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.a.val(c[0]);this.p=b}Wb.prototype.hide=function(){this.a.hide()};Wb.prototype.show=function(){this.a.show()};Wb.prototype.g=k();
function Xb(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("textblock");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.p=b;this.G(c[0])}Xb.prototype.hide=function(){this.a.hide()};Xb.prototype.show=function(){this.a.show()};Xb.prototype.g=k();
Xb.prototype.G=function(a){for(var b="",c=0;c<a.length;c++)a.charCodeAt(c)==1?(a.charCodeAt(c+1)==74&&this.a.css("text-align","center"),c+=2):b+=a.charCodeAt(c)==13?"<br />":a.charAt(c);this.a.html(b)};function Yb(a,b){this.a=$(document.createElement("div"));this.a.addClass("list");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.p=b}Yb.prototype.hide=function(){this.a.hide()};Yb.prototype.show=function(){this.a.show()};
Yb.prototype.g=k();
function Zb(a,b,c){this.value=parseInt(c[0],10);this.p=b;this.min=parseInt(c[1],10);this.max=parseInt(c[2],10);this.width=a[2];this.a=$(document.createElement("div"));this.a.addClass("hscroll");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.a.mousedown(function(){fatal("mousedown")});this.A=$(document.createElement("div"));this.A.addClass("leftarrow");this.A.css("top","0px");this.A.css("left","0px");this.A.mousedown(function(){fatal("left")});this.a.append(this.A);
this.k=$(document.createElement("div"));this.k.addClass("rightarrow");this.k.css("top","0px");this.k.css("left",a[2]-Ca+"px");this.k.mousedown(function(){fatal("right")});this.a.append(this.k);this.s=$(document.createElement("div"));this.s.addClass("slider");this.s.css("top","0px");this.s.css("left","50px");this.s.css("width","20px");this.s.mousedown(function(){fatal("slider")});this.a.append(this.s)}Zb.prototype.hide=function(){this.a.hide()};Zb.prototype.show=function(){this.a.show();this.g()};
Zb.prototype.g=function(){this.s.css("left",(this.value*(this.width-35)/(this.max-this.min)|0)+15+"px")};function Eb(a,b){a.value=b;a.g()}function $b(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("sbutton");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]-2+"px");this.a.css("height",a[3]-2+"px");this.a.html(c[0]);this.p=b;this.a.mousedown(function(){fatal("button")})}$b.prototype.hide=function(){this.a.hide()};$b.prototype.show=function(){this.a.show()};
$b.prototype.g=k();function tb(a,b){if(b>=I[a].B)return"";var c,d;I[a].O?(c=I[a].P[b],d=I[a].Q[b]):(c=I[a].U,d=b*c);if(!c)return"";return I[a].data.substring(d,d+c)}var I=[];var ac=document.createElement("link");ac.type="text/css";ac.rel="stylesheet";ac.href="mac.css";$("head").append(ac);q=$(document.createElement("img"));q.attr("src","images/mac/start.png");q.css("width","100%");q.css("height","100%");desktop.append(q);
(function(a){$.ajax({url:a,ea:function(a){a.overrideMimeType("text/html; charset=x-user-defined")},complete:function(a){s=new t(a.responseText);s.seek(1044,s.set);ga=y(s);s.seek(1052,s.set);fa=x(s);s.seek(1174,s.set);ha=x(s);a=(ha+fa)*ga;s.seek(a+ga-2,s.set);var c=x(s);s.seek(a+c+2,s.set);c=y(s);ia(a,c)}})})(gamename);setTimeout(Pa,10);
