var l=void 0;function o(){return function(){}}function aa(a){return function(){return a}}var p,q,ba=15,ca=19;function da(a){for(var b="",c=0;c<a.length;c++)switch(a.charCodeAt(c)){case 13:b+="<br />";break;case 63368:b+="&#224;";break;case 63374:b+="&#233;";break;case 63401:b+="&#169;";break;case 63433:b+="...";break;case 63441:b+="&#8212;";break;default:b+=a.charAt(c)}return b};function ea(a){for(var b in r)if(r[b].name==a){if(r[b].U==0)break;s.seek((r[b].X+fa)*ga,s.set);return new u(v(s,r[b].U))}}var r=[],s=l,ga,fa;var ia=[],ja=!1;function ka(a,b,c){this.width=a;this.height=b;this.n=c;this.v=a;this.t=b;this.data=Array(b*c)}
ka.prototype.h=function(a,b,c){if(!(this.width==0||this.height==0)){var e=a.get(0).getContext("2d"),d=this.width,f=this.height,h=0,g=0;b<0&&(h=-b,b=0);c<0&&(g=-c,c=0);d+b>=a.width()&&(d=a.width()-b);f+c>=a.height()&&(f=a.height()-c);if(!(d==0||f==0)){a=e.getImageData(b,c,d,f);for(var i=g;i<f;i++)for(var m=i*this.n,j=(i-g)*a.width*4,k,n=h;n<d;n++)k=(k=this.data[m+(n>>3)]&1<<7-(n&7))?0:255,a.data[j++]=k,a.data[j++]=k,a.data[j++]=k,a.data[j++]=255;e.putImageData(a,b,c)}}};
function la(a,b,c,e,d,f){a=a.get(0).getContext("2d");for(var h=a.getImageData(b,c,e,d),g=0;g<d;g++)for(var i=g*h.width*4,m=f?0:255,j=0;j<e;j++)h.data[i++]=m,h.data[i++]=m,h.data[i++]=m,h.data[i++]=255;a.putImageData(h,b,c)};function ma(a){w.push(a);return w.length-1}function x(a,b){for(var c=a.charCodeAt(0)<<24|a.charCodeAt(1)<<16|a.charCodeAt(2)<<8|a.charCodeAt(3),e=w.length-1;e>=0;e--){var d=w[e];d.seek(0,d.set);var f=y(d),h=y(d);d.seek(h+24,d.set);h+=B(d);d.seek(h,d.set);for(var g=B(d)+1,i=0;i<g;i++){if(y(d)==c){c=B(d)+1;d.seek(h+B(d),d.set);for(i=0;i<c;i++){if(B(d)==b)return d.seek(2,d.i),f+=y(d)&16777215,d.seek(f,d.set),f=y(d),new u(v(d,f));d.seek(10,d.i)}return}d.seek(4,d.i)}}}
function na(){var a=x("STR ",133);if(a==l)return"";var b=D(a);return v(a,b)}function oa(a,b){if(b==0)return"";var c=x("STR#",a);if(c==l)return"";var e=B(c);if(b>e)return"";for(;;){b--;if(b==0)return e=D(c),v(c,e);e=D(c);c.seek(e,c.i)}}function pa(a){var b=B(a),c=B(a),e=B(a)-b,d=B(a)-c;B(a);D(a);D(a);B(a);B(a);var f=B(a),h=y(a),g=D(a),i="";g!=0&&(i=v(a,g));a=[];g=0;switch(f>>4){case 0:g=10;a=[i];break;case 128:g=25,a=[i]}return E([c,b,d,e],h,g,a)}var w=[];function qa(a){var b=B(a);a.seek(12,a.i);var c=D(a),e="";c!=0&&(e=v(a,c));c==1&&(e="");F={id:b};F.a=$(document.createElement("div"));e=="@"?F.a.addClass("apple"):F.a.html(e);F.a.data("refCon",F);F.a.mousedown(function(a){if(H)return!1;ra(a);return!1});F.g=$(document.createElement("table"));F.g.addClass("menu");F.body=$(document.createElement("tbody"));F.g.append(F.body);F.m=[];sa.append(F.a);I.push(F);for(c=0;;){var d=D(a);if(d==0)break;e="";d!=0&&(e=da(v(a,d)));D(a);d=D(a);D(a);D(a);d=d!=0?String.fromCharCode(d):
"";ta(e,b<<8|c,d);c++}};var ua=1,va=18,wa=18,xa=2,ya=15,za=15,Aa=15,Ba=0;function Ca(){var a=x(oa(129,1),0),b=D(a);a=da(v(a,b));b=Da(146,96,220,150);b.add(E([75,120,70,18],1,10,["Ok"]));b.add(E([20,30,180,40],2,15,a));b.add(E([20,80,180,40],3,15,["WebVenture <br/> &#169; 2010 Sean Kasun"]));b.getItem(2).css("text-align","center");b.getItem(3).css("text-align","center");return b}
function Ea(){var a=Da(146,96,220,120);a.add(E([75,90,70,18],1,10,["Ok"]));a.add(E([55,55,110,13],2,24,[0,0,100]));a.add(E([20,25,180,20],3,15,["Sound Volume"]));a.getItem(3).css("text-align","center");return a}
function Fa(a){a=da(oa(128,[8,9,7][a]));var b=x("ALRT",131),c=B(b),e=B(b),d=B(b)-c,f=B(b)-e,h=B(b);b=Da(e,c,f,d);h=x("DITL",h);for(var g=B(h)+1,i=0;i<g;i++){y(h);c=B(h);e=B(h);d=B(h)-c;f=B(h)-e;var m=D(h),j=D(h),k="";j>0&&(k=da(v(h,j)));j&1&&D(h);switch(m&127){case 4:b.add(E([e,c,f,d],10,i+1,[k]));break;case 8:b.add(E([e,c,f,d],15,i+1,[k]));break;case 16:b.add(E([e,c,f,d],17,i+1,[k]));break;default:fatal("Unknown DITL:"+(m&127))}}b.param([a]);return b}
function Ga(){var a=Da(82,71,348,200);a.add(E([256,138,80,18],1,10,["Open"]));a.add(E([256,163,80,18],2,10,["Cancel"]));a.add(E([12,39,218,146],3,23,[]));return a}function Ha(){var a=Da(104,79,304,184);a.add(E([218,132,70,18],1,10,["Save"]));a.add(E([218,158,70,18],2,10,["Cancel"]));a.add(E([14,136,183,16],5,15,["Save as:"]));a.add(E([17,157,177,16],3,17,[""]));a.add(E([14,29,183,98],4,23,[]));return a}
function Ia(a){var b=B(a),c=B(a),e=B(a)-b,d=B(a)-c,f="",h=!1;switch(B(a)){case 0:f="document";break;case 1:f="dBox";break;case 2:f="plainDBox";break;case 3:f="altDBox";break;case 4:f="noGrowDoc";break;case 5:f="movableDBox";break;case 8:f="zoomDoc";h=!0;break;case 12:f="zoomNoGrow";h=!0;break;case 16:f="rDoc16";break;case 18:f="rDoc4";break;case 20:f="rDoc6";break;case 22:f="rDoc10"}B(a);var g=B(a)!=0;y(a);var i=D(a);i!=1&&v(a,i);a=new Ja(f,g,h,!1,!1,c,b,d,e);a.hide();Ka(a);return a};function u(a){this.set=0;this.i=1;this.end=2;this.data=a;this.length=a.length;this.o=this.e=0}function D(a){return a.data.charCodeAt(a.e++)&255}function B(a){var b=(a.data.charCodeAt(a.e++)&255)<<8;b|=a.data.charCodeAt(a.e++)&255;return b}function La(a){var b=(a.data.charCodeAt(a.e++)&255)<<16;b|=(a.data.charCodeAt(a.e++)&255)<<8;b|=a.data.charCodeAt(a.e++)&255;return b}
function y(a){var b=(a.data.charCodeAt(a.e++)&255)<<24;b|=(a.data.charCodeAt(a.e++)&255)<<16;b|=(a.data.charCodeAt(a.e++)&255)<<8;b|=a.data.charCodeAt(a.e++)&255;return b}function Ma(a){var b=(a.data.charCodeAt(a.e)&255)<<24;b|=(a.data.charCodeAt(a.e+1)&255)<<16;b|=(a.data.charCodeAt(a.e+2)&255)<<8;b|=a.data.charCodeAt(a.e+3)&255;return b}u.prototype.seek=function(a,b){switch(b){case this.i:a+=this.e;break;case this.end:a+=this.length}this.e=a};
function v(a,b){var c=a.e;a.e+=b;return a.data.substring(c,a.e)}u.prototype.d=function(a){var b=Ma(this);b>>>=32-this.o-a;b&=(1<<a)-1;this.o+=a;this.o&16&&(this.o&=15,this.e+=2);return b};function Na(){if(s!=l){for(var a,b=1;a==l&&b<5;b++)a:{for(var c=a=0,e=0;e<4;e++)a|="APPL".charCodeAt(e)<<24-e*8,c|=("MCV"+b).charCodeAt(e)<<24-e*8;for(e in r)if(r[e].type==a&&r[e].V==c){s.seek((r[e].Q+fa)*ga,s.set);a=new u(v(s,r[e].N));break a}a=l}ma(a);q.remove();delete q;b=oa(129,2);var d;a:{for(d in r)if(r[d].name==b){if(r[d].N==0)break;s.seek((r[d].Q+fa)*ga,s.set);d=new u(v(s,r[d].N));break a}d=l}if(d!=l)b=ma(d),d=Oa(x("PPIC",0)),delete w[b],w.splice(b,1);else{d=ea(b);b=new ka(512,302,64);a=Array(72);
d.seek(512,d.set);for(e=c=0;e<b.t;e++){for(var f=0;f<72;){var h=D(d);if(h!=128)if(h&128){h^=255;h+=2;for(var g=D(d),i=0;i<h;i++)a[f++]=g}else{h++;for(i=0;i<h;i++)a[f++]=D(d)}}for(i=0;i<64;i++)b.data[c++]=a[i]}d=b}b=new Ja("plainDBox",!1,!1,!1,!1,0,0,512,342);b.hide();Ka(b);Pa=b;Pa.show();d.h(Pa.port,0,0);for(d=0;d<5;d++){b=d;a=oa(129,d+4);a=ea(a);c={W:0,K:!1};a.seek(0,a.set);f=a.length;e=y(a);h=l;if(e&2147483648){e&=2147483647;c.K=!0;a.seek(e,a.set);c.B=B(a);f=Array(16);h=Array(16);for(g=0;g<15;g++)f[g]=
B(a);for(g=0;g<16;g++)h[g]=D(a);c.M=Array(c.B);c.L=Array(c.B);i=0;var m=l;for(g=0;g<c.B;g++){if((g&63)==0){a.seek(e+(g>>6)*6+48,a.set);var j=La(a);m=La(a);i=j&7;a.seek(e+(j>>3),a.set)}c.M[g]=m;j=y(a)>>>16-i&65535;a.seek(-4,a.i);var k;for(k=0;k<16;k++)if(f[k]>j)break;j=h[k];i+=j&15;i&16&&(i&=15,a.seek(2,a.i));j>>=4;k=0;j&&(k=Ma(a),j--,j==0?k=0:k>>>=32-j-i,k&=(1<<j)-1,k|=1<<j,i+=j,i&16&&(i&=15,a.seek(2,a.i)),m+=k);c.L[g]=k}h=e-4}else f-=4,h=f,c.P=e,c.B=f/e|0;a.seek(4,a.set);c.data=v(a,h);J[b]=c}d=x("GNRL",
128);K=B(d);Ra=B(d);Sa=B(d);M=B(d);Ta=B(d);B(d);B(d);B(d);B(d);B(d);B(d);B(d);B(d);B(d);Ua=Array(M);for(b=0;b<M;b++)Ua[b]=D(d);Va=Array(M);for(b=0;b<M;b++)Va[b]=B(d);Wa=Array(M);for(b=0;b<M;b++)Wa[b]=D(d);Xa=Array(Sa);for(b=0;b<Sa;b++)Xa[b]=D(d);Ya=Array(Sa);for(b=0;b<Sa;b++)Ya[b]=D(d);Za=[];$a=[];ab=Array(K*2);x("GNRL",131);bb=Ia(x("WIND",128));bb.l=9;bb.addClass("commands");for(d=0;d<Sa;d++)Ya[d]&&bb.add(pa(x("CNTL",129+d)));cb=Ia(x("WIND",129));cb.l=10;P=Ia(x("WIND",130));P.l=11;Q=$(document.createElement("div"));
Q.addClass("textEdit");d=P;b=Q;a=d.port.width();c=d.port.height();d.port.remove();b.css("top","0px");b.css("left","0px");b.css("width",a+"px");b.css("height",c+"px");d.port=b;d.c.append(b);db=Ia(x("WIND",131));db.l=12;db.b={id:0,x:0,y:0,children:[{id:1,top:0,left:0,width:0,height:0}]};eb=Ia(x("WIND",132));eb.l=13;eb.addClass("exits");for(d=128;d<=133;d++)qa(x("MENU",d));F=I[0];ta("Adjust Volume...",2304,"");fb(P,oa(128,1));if(gameparts.length>1)R=gameparts[1],d=window.JSON.parse(window.localStorage.getItem(R).toString()),
S=d.I,gb=d.J,Q.html(d.text),fb(P,R);else{d=ea(na());S=Array(Ta);gb=Array(Ra);for(b=0;b<Ta;b++){S[b]=Array(K);for(a=0;a<K;a++)S[b][a]=B(d)}for(b=0;b<Ra;b++)gb[b]=B(d)}hb();R==""&&Za.push(T());setTimeout(ib,500)}else setTimeout(Na,10)}function hb(){for(var a,b,c=0;c<K*2;c++)ab[c]=0;for(c=K-1;c;c--)a=S[0][c],(b=ab[a*2])&&(ab[c*2+1]=b),ab[a*2]=c}var ab;
function ib(){U(Pa);delete Pa;desktop.append(sa);bb.show();db.show();var a=db;if(a!=l&&a.b!=l&&(a==db||T()==1)){if(a==cb)kb(a.b.id*2).h(cb.port,0,0);else{var b=a.port,c=Ba;la(b,0,0,b.width(),b.height(),c)}for(b=0;b<a.b.children.length;b++){var e=a.b.children[b].id;c=a;var d=T(),f=T(),h=T();if(!h||!T()){var g=1;h?g=0:$a.indexOf(e)!=-1&&(g=2);h=l;d-=c.b.x;h=f-c.b.y;f=c.port;var i=g;g={top:0,left:0,width:0,height:0};var m=l;if(m=kb(e*2+1))switch(g={top:h,left:d,width:m.width,height:m.height},i){case 1:var j=
m,k=d,n=h;if(!(j.width==0||j.height==0)){var L=f.get(0).getContext("2d"),z=j.width,t=j.height,ha=0,C=0;k<0&&(ha=-k,k=0);n<0&&(C=-n,n=0);z+k>=f.width()&&(z=f.width()-k);t+n>=f.height()&&(t=f.height()-n);if(!(z==0||t==0)){for(var A=L.getImageData(k,n,z,t),N=C;N<t;N++)for(var Qa=N*j.n,G=(N-C)*A.width*4,jb,O=ha;O<z;O++)(jb=j.data[Qa+(O>>3)]&1<<7-(O&7))?(A.data[G++]=255,A.data[G++]=255,A.data[G++]=255,A.data[G++]=255):G+=4;L.putImageData(A,k,n)}}break;case 2:if(j=m,k=d,n=h,!(j.width==0||j.height==0))if(L=
f.get(0).getContext("2d"),z=j.width,t=j.height,C=ha=0,k<0&&(ha=-k,k=0),n<0&&(C=-n,n=0),z+k>=f.width()&&(z=f.width()-k),t+n>=f.height()&&(t=f.height()-n),!(z==0||t==0)){A=L.getImageData(k,n,z,t);for(N=C;N<t;N++){Qa=N*j.n;G=(N-C)*A.width*4;for(O=ha;O<z;O++)(jb=j.data[Qa+(O>>3)]&1<<7-(O&7))?(A.data[G++]=0,A.data[G++]=0,A.data[G++]=0,A.data[G++]=255):G+=4}L.putImageData(A,k,n)}}else if(m=kb(e*2))switch(g={top:h,left:d,width:m.width,height:m.height},i){case 1:la(f,d,h,m.width,m.height,0);break;case 2:la(f,
d,h,m.width,m.height,1)}if(i>0&&(m=kb(e*2)))if(e=m,!(e.width==0||e.height==0))if(i=f.get(0).getContext("2d"),m=e.width,j=e.height,n=k=0,d<0&&(k=-d,d=0),h<0&&(n=-h,h=0),m+d>=f.width()&&(m=f.width()-d),j+h>=f.height()&&(j=f.height()-h),!(m==0||j==0)){f=i.getImageData(d,h,m,j);for(L=n;L<j;L++){z=L*e.n;t=(L-n)*f.width*4;for(C=k;C<m;C++)(ha=e.data[z+(C>>3)]&1<<7-(C&7))?(f.data[t++]^=255,f.data[t++]^=255,f.data[t++]^=255,f.data[t++]=255):t+=4}i.putImageData(f,d,h)}h=g;h.top+=c.b.y;h.left+=c.b.x;c=h}else c=
{top:0,left:0,width:0,height:0};a.b.children[b].top=c.top;a.b.children[b].left=c.left;a.b.children[b].width=c.width;a.b.children[b].height=c.height}if(a.l==14&&a.b.R){b={top:0,left:0,right:0,bottom:0};a.b.R=!1;for(c=0;c<a.b.children.length;c++)g=a.b.children[c],b.right==b.left||b.bottom==b.top?(b.top=g.top,b.left=g.left,b.bottom=g.top+g.height,b.right=g.left+g.width):(b.top=Math.min(b.top,g.top),b.left=Math.min(b.left,g.left),b.bottom=Math.max(b.bottom,g.top+g.height),b.right=Math.max(b.right,g.left+
g.width));if(b.right==b.left||b.bottom==b.top)b.top=a.b.y,b.left=a.b.x,b.bottom=a.b.y,b.right=a.b.x;else{if(b.left>a.b.x)b.left=a.b.x;if(b.right<a.b.x)b.right=a.b.x;if(b.top>a.b.y)b.top=a.b.y;if(b.bottom<a.b.y)b.bottom=a.b.y}if(a.l==11)a.f.data("min",b.top),a.f.data("max",b.bottom),f=a.port.scrollTop(),b=a.f.data("min"),c=a.f.data("max"),b<c?(g=f-b,f+=a.port.height(),g=g*(a.height-15-va-15)/(c-b)|0,b=f*(a.height-15-va-15)/(c-b)|0,a.f.css("top",g+15+"px"),a.f.css("height",b-g+"px")):(a.f.css("top",
"15px"),a.f.css("height",a.height-15-va-15+"px"));else{if(b.left>a.b.x)b.left=a.b.x;if(b.right<a.b.x+a.port.width())b.right=a.b.x+a.port.width();if(b.top>a.b.y)b.top=a.b.y;if(b.bottom<a.b.y+a.port.height())b.bottom=a.b.y+a.port.height();a.w&&(a.j.data("min",b.left),a.j.data("max",b.right));a.z&&(a.f.data("min",b.top),a.f.data("max",b.bottom));a.w&&(b=a.j.data("min"),c=a.j.data("max"),b<c?(f=a.b.x-b,g=a.port.width(),f=f*(a.port.width()-15)/(c-b)|0,b=g*(a.port.width()-15)/(c-b)|0,b>a.port.width()-15-
f&&(b=a.port.width()-15-f),a.j.css("left",f+15+"px"),a.j.css("width",b+"px")):(a.j.css("left","15px"),a.j.css("width",a.port.width()-15+"px")));a.z&&(b=a.f.data("min"),c=a.f.data("max"),b<c?(f=a.b.y-b,g=a.port.height(),f=f*(a.port.height()-15)/(c-b)|0,b=g*(a.port.height()-15)/(c-b)|0,b>a.port.height()-15-f&&(b=a.port.height()-15-f),a.f.css("top",f+15+"px"),a.f.css("height",b+"px")):(a.f.css("top","15px"),a.f.css("height",a.port.height()-15+"px")))}}}eb.show();P.show();cb.show();lb=Q.get(0).scrollHeight;
Q.scrollTop(lb-lb%ba);T();fatal("set");V=!1;mb()};var V=!1,lb=0,$a,Za,Xa,Ya,Pa,cb,bb,P,db,eb,Q,K,Ra,Sa,M,Ta,Wa,Va,Ua,S,gb,R="";function W(){}var H=!1;function mb(){fatal("runmain")}function T(){fatal("get");return 0}function nb(a){switch(a){case 256:ob();break;case 257:pb();break;case 258:qb();break;case 259:W=o();rb();break;case 260:W=o();sb();break;case 261:tb();break;case 2304:ub();break;default:fatal("Unknown menuitem: "+a.toString(16))}}function ob(){var a=Ca();H=!0;a.show(function(){U(a);H=!1})}
function ub(){var a=Ea(),b=vb();b==null&&(b=50);wb(a.getItem(2),b);H=!0;a.show(function(){var b=a.getItem(2).value,e=new Date;e.setTime(e.getTime()+31536E6);document.cookie="webventure_volume="+escape(b)+"; expires="+e.toGMTString()+"; path=/";U(a);H=!1})}function pb(){if(V){var a=Fa(0);H=!0;a.show(function(b){U(a);switch(b){case 1:W=pb;rb();break;case 2:xb();break;case 3:H=!1}})}else xb()}
function xb(){R="";for(var a=ea(na()),b=0;b<Ta;b++)for(var c=0;c<K;c++)S[b][c]=B(a);for(b=0;b<Ra;b++)gb[b]=B(a);yb();hb();fb(P,oa(128,1));Q.html("");Za=[T()];T();fatal("set");V=!1;mb()}function qb(){if(V){var a=Fa(1);H=!0;a.show(function(b){U(a);switch(b){case 1:W=qb;rb();break;case 2:zb();break;case 3:H=!1}})}else zb()}
function zb(){var a=Ga();H=!0;for(var b=a.getItem(3),c=l,e=0;e<window.localStorage.length;e++){var d=window.localStorage.key(e);if(d!=null&&window.JSON.parse(window.localStorage.getItem(d).toString()).O==gamename){var f=$(document.createElement("div"));f.addClass("listitem");f.mousedown(aa(!1));f.click(function(a){c&&c.removeClass("active");c=$(a.target);c.addClass("active")});f.dblclick(function(){a.getItem(1).a.click()});f.text(d.toString());b.a.append(f)}}a.show(function(b){switch(b){case 1:if(c==
l)break;R=c.text();U(a);H=!1;b=window.JSON.parse(window.localStorage.getItem(R).toString());S=b.I;gb=b.J;yb();hb();fb(P,R);Q.html(b.text);lb=Q.get(0).scrollHeight;Q.scrollTop(lb);Za=[];T();fatal("set");V=!1;mb();break;case 2:U(a),H=!1}})}function rb(){R==""?sb():(window.localStorage.setItem(R,window.JSON.stringify({O:gamename,I:S,J:gb,text:Q.html()})),fb(P,R),V=!1,W())}
function sb(){var a=Ha();H=!0;var b=a.getItem(3);b.a.focus();b.a.keypress(function(b){if(b.which==13)return a.getItem(1).a.click(),!1;return!0});b=a.getItem(4);for(var c=l,e=0;e<window.localStorage.length;e++){var d=window.localStorage.key(e);if(d!=null&&window.JSON.parse(window.localStorage.getItem(d).toString()).O==gamename){var f=$(document.createElement("div"));f.addClass("listitem");f.mousedown(aa(!1));f.click(function(b){c&&c.removeClass("active");c=$(b.target);c.addClass("active");a.getItem(3).a.val(c.text())});
f.dblclick(function(){a.getItem(1).a.click()});f.text(d.toString());b.a.append(f)}}a.show(function(b){switch(b){case 1:R=a.getItem(3).a.val();U(a);H=!1;rb();break;case 2:U(a),H=!1,W()}})}function tb(){if(V){var a=Fa(2);H=!0;a.show(function(b){U(a);switch(b){case 1:W=tb;rb();break;case 2:mb();break;case 3:H=!1}})}else mb()}
function vb(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var c=a[b];c.charAt(0)==" ";)c=c.substring(1,c.length);if(c.indexOf("webventure_volume=")==0)return unescape(c.substring(18,c.length))}return null};function kb(a){var b;a>=J[3].B?b="":(J[3].K?(b=J[3].L[a],a=J[3].M[a]):(b=J[3].P,a*=b),b=b?J[3].data.substring(a,a+b):"");if(!(b.length<2)){if(b.length==2)return kb((b.charCodeAt(0)&255)<<8|b.charCodeAt(1)&255);return Oa(new u(b))}}
function Oa(a){var b=a.d(3),c,e;ja&&a.d(2);e=a.d(1)?a.d(10):a.d(6);if((c=a.d(1)?a.d(10):a.d(6))&&e){c=new ka(c,e,c+15>>3&65534);switch(b){case 0:b=c.v>>4;e=c.v&15;for(var d,f=0,h=0;h<c.t;h++){for(var g=0;g<b;g++)d=Ma(a),a.seek(2,a.i),d>>>=16-a.o,c.data[f++]=d>>8&255,c.data[f++]=d&255;e&&(d=a.d(e),d<<=16-e,c.data[f++]=d>>8&255,c.data[f++]=d&255)}break;case 1:Ab(Bb,Cb,Db,c,a);break;case 2:Ab(Eb,Fb,Gb,c,a);break;case 3:b=Array(17);for(f=0;(e=Hb[f++])!=255;){for(d=a.d(e);(e=Hb[f++])!=255;)b[Hb[f++]]=
d%e,d=d/e|0;b[Hb[f++]]=d}b[16]=0;for(d=16;d>0;d--)for(e=d;e<=16;e++)b[e]>=b[d-1]&&b[e]++;for(d=16;d>=0;d--)if(b[d]==16){b[d]=255;break}f=Array(17);h=Array(17);e=a.d(2)+1;for(d=g=0;d<15;d++){if(d)for(;!a.d(1);)e++;h[d]=e;f[d]=g;g+=1<<16-e}for(f[15]=g;g&1<<16-e;)e++;f[16]=g|1<<16-e;h[15]=e;h[16]=e;Ab(f,h,b,c,a)}return c}}
var Bb=[0,8192,16384,20480,24576,28672,32768,36864,40960,45056,49152,53248,55296,57344,59392,61440,63488],Cb=[3,3,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5],Db=[0,15,3,5,6,7,8,9,10,12,255,1,2,4,11,13,14],Eb=[0,16384,32768,49152,51200,53248,55296,57344,59392,61440,62464,62976,63488,64E3,64512,65024,65280],Fb=[2,2,2,5,5,5,5,5,5,6,7,7,7,7,7,8,8],Gb=[255,0,15,1,3,7,14,12,8,6,2,4,9,13,11,10,5],Hb=[8,15,2,255,0,4,255,1,7,9,8,255,3,4,255,4,10,7,10,11,6,255,5,6,6,11,255,7,3,255,9,4,3,14,255,12,2,255,13,1,255,15,255];
function Ab(a,b,c,e,d){var f;X=Y=0;f=e.v&3?d.d(5):d.d(4)<<1;var h=0,g=e.v&15;g&&(g>>=2,h=g&1,g=2-(g>>1));for(var i=0,m=0;m<e.t;m++){for(var j=0;j<e.v>>3;j++){var k=Ib(a,b,c,d)<<4;e.data[i++]=Ib(a,b,c,d)|k}h&&(e.data[i]=Ib(a,b,c,d)<<4);i+=g}if(j=e.v&3){i=e.n-g;var n=0;for(m=g=0;m<e.t;m++)f&1?(n<j&&(k=Ib(a,b,c,d)<<4,g|=k>>>n,n+=4),n-=j,k=g,g<<=j,g&=255):(k=d.d(j),k<<=8-j),h&&(k>>>=4),e.data[i]|=k&255,i+=e.n}if(f&8)for(m=i=0;m<e.t;m++)if(k=0,f&2)for(j=0;j<e.n;j++)e.data[i]^=k,k=e.data[i++];else for(j=
0;j<e.n;j++)g=e.data[i]^k,g^=g>>>4&15,e.data[i++]=g,k=g<<4&255;if(f&4){a=e.n*4;f&2&&(a*=2);i=0;f=a;for(b=0;b<e.t*e.n-a;b++)e.data[f++]^=e.data[i++]}}var Y=0,X=0;
function Ib(a,b,c,e){if(Y)return Y--,X=X<<8&65280|X>>8,X&255;var d=Ma(e);d>>>=16-e.o;d&=65535;var f;for(f=0;f<16;f++)if(a[f+1]>d)break;e.o+=b[f];e.o&16&&(e.o&=15,e.seek(2,e.i));a=c[f];if(a==255)return e.d(1)||(X&=255,X|=X<<8),Y=e.d(3),Y<3&&(Y<<=4,Y|=e.d(4),Y<8&&(Y<<=8,Y|=e.d(8))),Y-=2,X=X<<8&65280|X>>8,X&255;else X<<=8,X|=a,X&=65535;return a};function ta(a,b,c){var e={id:b},d=$(document.createElement("tr"));if(a[0]=="-"){var f=$(document.createElement("td"));f.attr("colspan","2");f.addClass("divider");f.append(document.createElement("hr"))}else d.addClass("menuitem"),f=$(document.createElement("td")),f.html(da(a)),d.append(f),f=$(document.createElement("td")),c!=""&&(f.addClass("shortcut"),Jb.push({key:c,id:b}),f.text(c));d.append(f);e.a=d;e.enabled=!0;e.enabled||e.a.addClass("disabled");F.body.append(e.a);F.m.push(e)}
function ra(a){for(var b=$(a.target);b.data("refCon")==l;)b=b.parent();b.addClass("active");var c=b.data("refCon");desktop.append(c.g);a=b.position();c.g.css("top",a.top+ca+"px");c.g.css("left",a.left+"px");var e=-1;$(document).mousemove(function(a){var f=sa.offset();if(a.pageX>=f.left&&a.pageY>f.top&&a.pageX<f.left+sa.width()&&a.pageY<f.top+sa.height())for(var h=0;h<I.length;h++){if(f=I[h].a.offset(),a.pageX>=f.left&&a.pageX<f.left+I[h].a.outerWidth()){c.g.remove();b.removeClass("active");b=I[h].a;
b.addClass("active");c=b.data("refCon");desktop.append(c.g);f=b.position();c.g.css("top",f.top+ca+"px");c.g.css("left",f.left+"px");break}}else if(f=c.g.offset(),a.pageX>=f.left&&a.pageY>=f.top&&a.pageX<f.left+c.g.outerWidth()&&a.pageY<f.top+c.g.outerHeight())for(h=0;h<c.m.length;h++){var g=c.m[h].a;g.hasClass("menuitem")&&c.m[h].enabled&&(f=g.offset(),a.pageY>=f.top&&a.pageY<f.top+g.outerHeight()?(e=h,g.addClass("active")):g.removeClass("active"))}else{for(h=0;h<c.m.length;h++)c.m[h].a.removeClass("active");
e=-1}});$(document).mouseup(function(){$(document).unbind("mousemove");$(document).unbind("mouseup");c.g.remove();b.removeClass("active");e!=-1&&nb(c.m[e].id)})}var sa,I=[],Jb=[],F=l;$("body").keydown(function(a){if(a.target.type=="text")return!1;if(!a.altKey)return!1;if(H)return!1;for(var b=0;b<Jb.length;b++)if(Jb[b].key.charCodeAt(0)==a.which)for(var c=Jb[b].id,e=0;e<I.length;e++)for(var d=0;d<I[e].m.length;d++)I[e].m[d].id==c&&I[e].m[d].enabled&&Kb(I[e],c)});
function Kb(a,b){a.a.addClass("active");setTimeout(function(){a.a.removeClass("active");nb(b)},200)};function Ja(a,b,c,e,d,f,h,g,i){this.u=[];this.zoom=c;this.close=b;this.z=e;this.w=d;this.c=$(document.createElement("div"));this.c.addClass(a);if(a=="document"||a=="info")b="<span></span>",this.title=$(document.createElement("div")),this.title.addClass("title"),this.title.mousedown(function(a){H||fatal(a);return!1}),this.close&&(b='<div class="close"></div>'+b),this.zoom&&(b+='<div class="resize"></div>'),this.title.html(b),this.close&&(b=this.title.children("div.close"),b.mousedown(aa(!1)),b.click(function(a){H||
fatal(a);return!1})),this.zoom&&(b=this.title.children("div.resize"),b.mousedown(aa(!1)),b.click(function(a){H||fatal(a);return!1})),this.c.append(this.title);this.port=$(document.createElement("canvas"));this.port.mousedown(function(a){H||fatal(a);return!1});this.port.attr("width",g);this.port.attr("height",i);this.c.append(this.port);this.top=h;this.height=i;this.left=f;this.width=g;a=="document"?(this.top-=va+ua,this.height+=va,this.left-=ua):a=="info"?(this.top-=wa+ua,this.height+=wa,this.left-=
ua):a=="alert"?(this.top-=xa*2,this.left-=xa*2,this.width+=xa,this.height+=xa):(this.top-=ua,this.left-=ua);this.z&&(this.width+=ya);this.w&&(this.height+=za);this.c.css("top",this.top+"px");this.c.css("left",this.left+"px");this.c.css("width",this.width+"px");this.c.css("height",this.height+"px");desktop.append(this.c);(this.z||this.w)&&Lb(this)}p=Ja.prototype;p.show=function(){this.c.show();for(var a=0;a<this.u.length;a++)this.u[a].p!=255&&this.u[a].show()};p.hide=function(){this.c.hide()};
function fb(a,b){if(a.title!=l){var c=a.title.children("span");c.html("");if(b=="")c.hide();else{var e=a.c.css("display")=="none";a.c.show();c.css({position:"absolute",visibility:"hidden",display:"block"});var d=a.port.width();a.close&&(d-=30);a.zoom&&(d-=30);for(var f=0;f<b.length;f++)if(c.append(b.substring(f,f+1)),c.width()>d){c.html(b.substring(0,f-1));break}c.css({position:"",visibility:"",display:""});e&&a.c.hide()}}}p.addClass=function(a){this.c.addClass(a)};p.removeClass=function(a){this.c.removeClass(a)};
p.add=function(a){var b=this.port.position().top,c=parseInt(a.a.css("top"),10);a.a.css("top",c+b+"px");this.c.append(a.a);a.c=this;this.u.push(a);this.c.css("display")!="none"&&a.h()};p.remove=function(a){var b=this.u.indexOf(a);b!=-1&&this.u.splice(b,1);a.a.remove()};p.close=function(){this.c.remove()};function Mb(a,b){var c=a.port.offset();b.G+=c.left+1;b.H+=c.top+2;a.b&&(b.G-=a.b.x,b.H-=a.b.y)}
function Lb(a){if(a.w){a.q=$(document.createElement("div"));a.q.addClass("hscroll");a.q.css("top",a.height-za+"px");a.q.css("width",a.width-15+"px");a.q.mousedown(function(){fatal("scroll")});var b=$(document.createElement("div"));b.addClass("leftarrow");b.mousedown(function(){fatal("scroll")});a.q.append(b);a.k=$(document.createElement("div"));a.k.addClass("rightarrow");a.k.css("left",a.width-Aa-15+"px");a.k.mousedown(function(){fatal("scroll")});a.q.append(a.k);a.j=$(document.createElement("div"));
a.j.addClass("slider");a.j.mousedown(function(){fatal("drag")});a.q.append(a.j);a.c.append(a.q)}if(a.z)a.r=$(document.createElement("div")),a.r.addClass("vscroll"),a.r.css("left",a.width-ya+"px"),a.r.css("height",a.height-15+"px"),a.r.mousedown(function(){fatal("scroll")}),b=$(document.createElement("div")),b.addClass("uparrow"),b.mousedown(function(){fatal("scroll")}),a.r.append(b),a.D=$(document.createElement("div")),a.D.addClass("downarrow"),a.D.css("top",a.height-15-15-va+"px"),a.D.mousedown(function(){fatal("scroll")}),
a.r.append(a.D),a.f=$(document.createElement("div")),a.f.addClass("slider"),a.f.mousedown(function(){fatal("drag")}),a.r.append(a.f),a.c.append(a.r);a.C=$(document.createElement("div"));a.C.addClass("grow");a.C.css("top",a.height-15+"px");a.C.css("left",a.width-15+"px");a.C.mousedown(function(){fatal("grow")});a.c.append(a.C)}
function yb(){for(var a=[],b=0;b<Z.length;b++)(Z[b].l==10||Z[b].l==14)&&a.push(Z[b]);for(b in a){var c=a[b];if(c!=l)if(c.l==10)c.b={},fb(c,"");else{var e={H:c.port.height(),G:c.port.width()};Mb(c,{H:0,G:0});Mb(c,e);c.b={};U(c)}}}function U(a){for(var b=0;b<Z.length;b++)if(Z[b]==a){a.close();Z.splice(b,1);break}Z.length&&Ka(Z[0])}function Ka(a){if(Z[0]!=a){Z[0]!=l&&Z[0].a.removeClass("active");for(var b=0;b<Z.length;b++)Z[b]==a&&Z.splice(b,1);Z.unshift(a)}a.a.addClass("active")}
function Da(a,b,c,e){a=new Ja("alert",!1,!1,!1,!1,a,b,c,e);a.l=2;a.hide();Ka(a);return a}var Z=[];function E(a,b,c,e){switch(c&255){case 2:return new Nb(a,b,e);case 10:return new Ob(a,b,e);case 15:return new Pb(a,b,e);case 17:return new Qb(a,b,e);case 22:return new Rb(a,b,e);case 23:return new Sb(a,b);case 24:return new Tb(a,b,e);case 25:return new Ub(a,b,e);default:fatal("Unknown control:"+c.toString(16))}}
function Nb(a,b,c){this.a=$(document.createElement("canvas"));this.a.addClass("cbutton");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.attr("width",a[2]);this.a.attr("height",a[3]);this.p=b;this.selected=!1;this.S=c[0];this.d=c[1];this.T=c[2];this.a.mousedown(function(){fatal("cbutton")})}
Nb.prototype.h=function(){var a=this.a.get(0).getContext("2d"),b=a.getImageData(0,0,this.width,this.height),c=this.selected?this.T:this.d;if(c)for(var e=0;e<this.height;e++)for(var d=(e>>1)*this.S,f=e*b.width*4,h,g=0;g<this.width;g++)h=c.charCodeAt(d+(g>>2)),h=(h>>(g&2?0:4)&15)*3,b.data[f++]=ia[h++],b.data[f++]=ia[h++],b.data[f++]=ia[h++],b.data[f++]=255;else for(e=0;e<this.height;e++){f=e*b.width*4;for(g=0;g<this.width;g++){h=this.selected?0:255;if(e<2||g<4||e>this.height-3||g>this.width-5)h=0;b.data[f++]=
h;b.data[f++]=h;b.data[f++]=h;b.data[f++]=255}}a.putImageData(b,0,0)};function Ob(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("button");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.a.html(c[0]);this.p=b;this.a.mousedown(function(){fatal("button")})}Ob.prototype.h=o();
function Pb(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("textblock");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.p=b;this.F(c[0])}Pb.prototype.F=function(a){this.a.html(a)};Pb.prototype.h=o();
function Qb(a,b,c){this.a=$(document.createElement("input"));this.a.addClass("textinput");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.a.val(c[0]);this.p=b}Qb.prototype.h=o();function Rb(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("textblock");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.p=b;this.F(c[0])}Rb.prototype.h=o();
Rb.prototype.F=function(a){for(var b="",c=0;c<a.length;c++)a.charCodeAt(c)==1?(a.charCodeAt(c+1)==74&&this.a.css("text-align","center"),c+=2):b+=a.charCodeAt(c)==13?"<br />":a.charAt(c);this.a.html(b)};function Sb(a,b){this.a=$(document.createElement("div"));this.a.addClass("list");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.p=b}Sb.prototype.h=o();
function Tb(a,b,c){this.value=parseInt(c[0],10);this.p=b;this.min=parseInt(c[1],10);this.max=parseInt(c[2],10);this.width=a[2];this.a=$(document.createElement("div"));this.a.addClass("hscroll");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]+"px");this.a.css("height",a[3]+"px");this.a.mousedown(function(){fatal("mousedown")});this.A=$(document.createElement("div"));this.A.addClass("leftarrow");this.A.css("top","0px");this.A.css("left","0px");this.A.mousedown(function(){fatal("left")});
this.a.append(this.A);this.k=$(document.createElement("div"));this.k.addClass("rightarrow");this.k.css("top","0px");this.k.css("left",a[2]-Aa+"px");this.k.mousedown(function(){fatal("right")});this.a.append(this.k);this.s=$(document.createElement("div"));this.s.addClass("slider");this.s.css("top","0px");this.s.css("left","50px");this.s.css("width","20px");this.s.mousedown(function(){fatal("slider")});this.a.append(this.s)}
Tb.prototype.h=function(){this.s.css("left",(this.value*(this.width-35)/(this.max-this.min)|0)+15+"px")};function wb(a,b){a.value=b;a.h()}function Ub(a,b,c){this.a=$(document.createElement("div"));this.a.addClass("sbutton");this.a.css("left",a[0]+"px");this.a.css("top",a[1]+"px");this.a.css("width",a[2]-2+"px");this.a.css("height",a[3]-2+"px");this.a.html(c[0]);this.p=b;this.a.mousedown(function(){fatal("button")})}Ub.prototype.h=o();var J=[];var Vb=document.createElement("link");Vb.type="text/css";Vb.rel="stylesheet";Vb.href="mac.css";$("head").append(Vb);q=$(document.createElement("img"));q.attr("src","images/mac/start.png");q.css("width","100%");q.css("height","100%");desktop.append(q);setTimeout(Na,10);
